### PR TITLE
SpinButton: Moving aria-label from outer div to inner input to conform with Keros expectations

### LINKED ISSUE #7345: SpinButton: [keros bug]: aria-label attribute does not exist or is empty, when passing aria label through spinbutton prop
### Environment Information 

- __Package version(s)__: 6.46.0
- __Browser and OS versions__: chrome and windows 10

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/anon/pen/roNQLg
 
#### Actual behavior:
 
we have a keros issue for spin button control: aria-label attribute does not exist or is empty.
By adding aria label to SpinButton, aria label added to outer div of the input, as given in screenshot below:

spinbutton aria label

 
#### Expected behavior:
 
Aria label property should be added on input control instead of outer div. So that keros do not show any error.

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7345
- [x] Include a change request file using `$ npm run change`

#### Description of changes

SpinButton: Moving aria-label from outer div to inner input to conform with Keros expectations.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
This change-set seems odd.. perhaps you branched off a "dirty" branch when creating this one. I'd revert the unrelated files that were modified to simplify the PR and subsequent merge.

**Comment by khmakoto** [comment]
@KevinTCoughlin if you take a look at the changes the only real change is a one-line change in `SpinButton.tsx`, all other files are just prettier messing with the files were a merge conflict occurred, but the logic isn't actually being changed.

**Comment by khmakoto** [comment]
Also, the Travis CI build failed because of a missing change file in `@uifabric/experiments`, will add it tomorrow.

**Comment by KevinTCoughlin** [comment]
I think there might be some implications with this change given the existing `SpinButton` code.

`SpinButton` has a required prop `label` which is _always_ rendered as an element referred to by `aria-labelledby` here:

https://github.com/OfficeDev/office-ui-fabric-react/blob/bd8a9a8d4c1fe42039c00fb4d691da58ac6b8cad/packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx#L171

My understanding is that `aria-labelledby` takes precedence over other ARIA attributes such as `aria-label`.

>Importantly, aria-labelledby overrides all other name sources for an element. So, for example, if an element has both an aria-labelledby and an aria-label, or an aria-labelledby and a native HTML label, the aria-labelledby label always takes precedence.
>
>https://developers.google.com/web/fundamentals/accessibility/semantics-aria/aria-labels-and-relationships"

In https://github.com/OfficeDev/office-ui-fabric-react/issues/7345, the user has an empty string for the `aria-labelledby` DOM node. Perhaps the fix is on the implementation side where they provide a value for `SpinButton`'s _required_ `label` prop.

**Comment by KevinTCoughlin** [comment]
I went down the above rabbit hole once I realized my ARIA extension did not flag the existing `SpinButton` examples... therefore this seems like an implementation issue OR requires additional code changes so that `aria-label` is not overridden by `aria-labelledby` on the same element.

**Comment by khmakoto** [comment]
Closing this for the moment given the conversation above. Will reopen if necessary.

**Pull request closed without merging**
