### PR TITLE
ContextualMenu: fix opening submenus with hrefs

### LINKED ISSUE #7419: Context menu sub-links don't expand on hover if all links have href
Sub menu items don't expand on hover if every node on them has href. Only if at least one node doesn't have href, the ones with submenu items would expand, after you hover on the one without href at least once! like that action triggers something than enables the expansion on hover. 

```
{
    key: "29",
    name: "Operations",
    subMenuProps: {
        items: [{
            key: "30",
            name: "Global Operations",
            canCheck: true,
            href: "/sites/intranet/Operations/GlobalOperations",
            subMenuProps: {
                items: [{
                    key: "31",
                    name: "Project Engineering",
                    href: "/sites/intranet/Operations/Project%20Engineering",
                    subMenuProps: null
                }]
            },
        }, {
            key: "36",
            // onClick: () => {
            //     location.href = "/sites/intranet/Operations/ManufacturingAndLaboratory"
            // },
            name: "Manufacturing and Laboratory",
            href: "/sites/intranet/Operations/ManufacturingAndLaboratory",
            subMenuProps: {
                items: [{
                    key: "37",
                    name: "System Design",
                    href: "/sites/intranet/Operations/System%20Design",
                }
            },
        }]
    },
}
```

So second level items are links themselves but on hover should show a third level menu. But right now you have to click which navigates the page. So I can't access the third level. 

Removing the href makes the expansion on hover work so I thought I use onclick to get rid of the href but onclick doesn't work either. 
Am I missing something here? Spent too much time on this and can't get it to work. 

Thanks for your help in advance :)

### PR DESCRIPTION
**Pull request by ecraig12345**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7419
- [x] Include a change request file using `$ npm run change`

#### Description of changes

In a context menu where all items in a submenu have hrefs (causing them to be rendered as anchor items), and some/all of the submenu items have children, hovering over the submenu item wouldn't open the sub-submenu. 

This was because ContextualMenuAnchor wasn't passing the mouse move handler through to its `<a>` element, preventing the ContextualMenu private member `_gotMouseMove` from being set. That caused the ContextualMenu to ignore other mouse events which were supposed to open the child menus.

### CODE REVIEW

**Comment by cliffkoh** [comment]
It would be great to add a screener test for this.

**Comment by KevinTCoughlin** [comment]
> 
> 
> It would be great to add a screener test for this.

Agreed, I'd be interested in seeing what one looked like. Typically, I've tested this in unit tests using enzyme `simulate`.

**Comment by KevinTCoughlin** [comment]
@aftab-hassan see above for an interesting size-auditor 🤖 result -- https://github.com/OfficeDev/office-ui-fabric-react/pull/7429#issuecomment-448122661

**Comment by JasonGore** [comment]
I think this is a deprecated test file that I had blanket copied over and forgot to remove duplicated tests on. It seems to me that this PR just removes tests that don't cover deprecated props.. is that true @ecraig12345 ?

**Comment by ecraig12345** [comment]
@JasonGore @cliffkoh Yes, I was just removing tests that don't cover deprecated props (to speed things up). Though technically since the `name` prop has been deprecated in favor of `text`, almost all the tests were using a deprecated prop...but I don't think the extra test coverage of using `name` in absolutely all scenarios is really necessary. Can revert if someone disagrees.

**Comment by khmakoto** [comment]
@ecraig12345 is this ready to be merged?

**Comment by ecraig12345** [comment]
@khmakoto I'm working on adding a screener test, it's just been a bit delayed because I've been distracted by other things. Should be done by EOD.

**Comment by khmakoto** [comment]
All good, just asking. Good luck with the screener test!

**Comment by ecraig12345** [comment]
Went ahead and merged this so users get the fix, but I still plan to work on expanding the tests to better cover this scenario.

**Comment by khmakoto** [comment]
@ecraig12345 maybe it would be a good idea to create an issue asking for the tests so that we have a way to track that work to completion.

**Pull request merged**
