### PR TITLE
Add tool tip for text of Persona

### LINKED ISSUE #2723: Persona should be able to show tool tip for primaryText, secondaryText and tertiaryText
### Bug Report

- __Package version(s)__: 4.x
- __Browser and OS versions__: Any

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal 

Products/sites affected: SharePoint online, People web part

#### Describe the issue:

When Persona can't show the entire primaryText, secondaryText and tertiaryText, there's no way for user to see the full text.

#### Actual behavior:

Hover on the text, no tool tip showing the full text.

#### Expected behavior:

Hover on the text, show tool tip showing the full text.

### If applicable, please provide a codepen repro:

https://codepen.io/luhu/pen/qXvMyN

### PR DESCRIPTION
**Pull request by luhu**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2723
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Add tool tip for text of Persona.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
This PR is simply adding a title field to Personas. For other components we are using the tooltip component to provide a more rich, unified experience. Is there a reason for not using the tooltip component here?

**Comment by luhu** [comment]
Yes, persona on SPO/O365 don't use fabric tooltip component yet. This is to align with them. @micahgodbolt

**Comment by betrue-final-final** [comment]
@cschlechty, do we know what this will do to screen readers?

**Comment by micahgodbolt** [comment]
Here's the new behavior visually. 

persona

**Comment by betrue-final-final** [comment]
This is the thing that we don't want tooltips to do. It's very redundant and devalues tooltips. I wouldn't recommend going forward with this. Also this is going to make screen readers read the name twice, which is extremely bothersome.

**Comment by cschlechty** [comment]
It'll read the same thing twice, the visible text and then title. Not
ideal. Do we anticipate lots of truncation?

**Comment by micahgodbolt** [comment]
We can certainly consider adding Fabric tooltips that only show up on truncation. That's pretty easy actually.

**Comment by luhu** [comment]
Thank you @micahgodbolt. I replaced title with Fabric tooltips.
persona

**Comment by micahgodbolt** [comment]
awesome :D Love how simple that is to apply here.

**Pull request merged**
