### PR TITLE
Reversing the order of :focus and :active selectors in a comboBox.

### PR DESCRIPTION
**Pull request by whykushal93**
The current order causes an option button to take the styles of the focused state when it is pressed.

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes
The current order causes an option button to take the styles of the focused state when it is pressed.

### CODE REVIEW

**Comment by christiango** [comment]
@whykushal93 can you merge the upstream repo again and try again. Not sure why the CI is still pending.

**Comment by lynamemi** [comment]
Does this PR fix this issue? https://github.com/OfficeDev/office-ui-fabric-react/issues/3472

**Comment by whykushal93** [comment]
@lynamemi this does not fix that unfortunately. This change is to fix, the order in which :focus and :active styles get cascaded for each option. Without the current change, we you keep an option pressed, it takes :focus styles override :active styles, when usually it is the other way around.

For #3472, I do not think that options get true keyboard focus ever in a comboBox. The true focus always stays in the input field, and we just see the background color change for hovered/selected option.

**Comment by lynamemi** [comment]
@whykushal93 Ah gotcha, makes sense now. Thank you for clarifying!

**Pull request merged**
