### PR TITLE
Use typeof check on process before checking process.env.NODE_ENV

### PR DESCRIPTION
**Pull request by ThomasMichon**
Some downstream application bundlers are currently not yet set up to polyfill the `process.env.NODE_ENV` variable universally, so Fabric code should first check if the global `process` variable is defined before trying to read it.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8234)

### CODE REVIEW

**Comment by ThomasMichon** [comment]
No way this added 1 KB g-zipped.

**Comment by JasonGore** [comment]
@aftab-hassan These numbers don't seem right...

**Comment by ecraig12345** [comment]
I thought @dzearing mentioned webpack does some magic to strip out process.env.NODE_ENV checks in production? Maybe this messed that up?

**Comment by dzearing** [comment]
@ThomasMichon no change files causing build to fail;

**Comment by dzearing** [comment]
@leddie24 any PRs on your plate that are still sitting around, can you prod them along? :)

**Comment by dzearing** [comment]
@ecraig12345 that is true for partners using webpack, but odsp doesn't.

**Comment by leddie24** [comment]
@aftab-hassan is taking a look at the size auditor exceeding tolerance levels to unblock currently.

**Comment by dzearing** [comment]
feels weird to me.

**Comment by aftab-hassan** [comment]
> @aftab-hassan is taking a look at the size auditor exceeding tolerance levels to unblock currently.

> feels weird to me but I can't see how this could actually affect bundlesize like this.

I am taking a look, comparing the stats files between baseline and PR using https://microsoft.github.io/sizeAuditor-website/

**Comment by aftab-hassan** [comment]
@dzearing @leddie24 

Compared stats files individually for a few bundles now that we have separate stats files for each bundle, as of yesterday. However, the modules are concatenated together, and doesn't provide anything actionable.
Icons-size-auditor

**Pull request merged**
