### PR TITLE
ComboBox: Fix clearing the comboBox on escape

### LINKED ISSUE #3061: ComboBox newly created freeform item is cleared with escape key
### Bug Report

- __Package version(s)__: 5.5.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Perhaps, if pointed in the right direction.

Requested priority: Normal

#### Describe the issue:

I am having some difficulties with freeform-entered options in uncontrolled ComboBoxes.  Specifically, after creating an option by typing it in and pressing enter, if I open the dropdown and press the escape key to close the dropdown/blur, the selection disappears.  I've made a codepen to illustrate the issue.

#### Actual behavior:

Freeform-entered options can be cleared, leaving a blank field.  `onChanged` does not fire, but the field remains blank.

#### Expected behavior:

Pressing escape would not clear out the selection, and would behave just as it does when choosing an option from the dropdown, opening the dropdown, and pressing escape.

### If applicable, please provide a codepen repro:

https://codepen.io/IanVS/pen/YrexLg?editors=0011

### PR DESCRIPTION
**Pull request by jspurlin**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #3061 
- [X] Include a change request file using `$ npm run change`

#### Description of changes
When entering a new value, pressing ENTER, and then pressing ESC the value gets cleared. The issue stemmed from the fact that the comboBox was calling clear on the input when resetting the value so while it was being reset to the correct value, it was subsequently cleared...

Another thing that I did as part of this change is select the text when ETNER is pressed, without that it's not clear that the new value was submitted/accepted

#### Focus areas to test
Verified that the comboBox does not clear for the previously described repro steps, submitting the value works as expected, cancelling the value works as expected (even if the value was initially empty in the comboBox). I also verified that with https://github.com/OfficeDev/office-ui-fabric-react/pull/6142 the expand then click away issue no longer happens

### CODE REVIEW

**Comment by micahgodbolt** [comment]
accepting screener. created #6155 to track that combobox bug. it's unrelated to this PR

**Comment by jspurlin** [comment]
@micahgodbolt I pulled the lastest changes from master and now screener is showing 25 "new" screenshots for datepicker

**Comment by micahgodbolt** [comment]
There is a screener bug where master isn't automatically being updated with the newest snapshots once code has been merged in. #6162 should hopefully fix that, though i'm having to upgrade screener, which needs new lockfile, which seems to be failing....

ie. working on that. As for now, I can approve your screener tests

**Comment by jspurlin** [comment]
@micahgodbolt, @JasonGore, and/or @michaelangotti ...PING... Looking to get this merged

**Comment by micahgodbolt** [comment]
merged! 💃

**Pull request merged**
