### PR TITLE
Revert "BaseFloatingItem: fix tests + remove redundant state  (#9500)"

### PR DESCRIPTION
**Pull request by MLoughry**
This reverts commit 89e67c9561a224fab01157b5aa33f5c50992f296.

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

#9500 broke the contract of expected behavior with the BaseExtendedPicker. Rather than stashing the `props.defaultSelectedItems` and/or `props.selectedItems` into the `state` object and using that, the code now references a public `React.ref` object hanging off the component. As a result, code that is not changed to account for this pattern ends up throwing a TypeError in `canAddItems()`, where the code attempts to dereference `this.items`, which is `null`.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9663)

### CODE REVIEW

**Comment by joschect** [comment]
@MLoughry why revert the entire change rather than fix canAddItems?

**Comment by joschect** [comment]
Also @MLoughry thanks for taking this on!

**Comment by MLoughry** [comment]
Because the code as it currently is breaks backwards-compatibility, since it ignored defaultSelectedItems and selectedItems.

- Michael
________________________________

**Comment by Adjective-Object** [comment]
FYI @MLoughry, that state object is not maintained by the component, so anything referencing that object state is either working *entirely* based on custom logic consumer-side, or is now invisibly broken.

also, why revert the tests?

**Comment by Adjective-Object** [comment]
Either way, looks like I'll need to be fixing up some of the legacy picker logic in outlook when I'm back in office :roll_eyes:

**Pull request merged**
