### PR TITLE
Stack: Re-exporting component from experiments package.

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This PR re-exports the `Stack` component from the `experiments` package so that people that might have been using it don't encounter the breaking change. A `@deprecated` tag is also put in place so that we have visibility on the fact that we're taking this out in the future.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8023)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
I agree, this is handy (i just saw a broken codepen due to this), but I don't want to export it forever. Do we have a timeframe on how long this will be there?

**Comment by JasonGore** [comment]
I agree with Micah's concerns. We should codify promotion policy here. Experiments is experiments, so we should be able to make API breaking changes. What is driving this change?

**Comment by micahgodbolt** [comment]
there are a bunch of codepen demos that are broken due to this change....though that should really just be on us to fix. Codepen makes it pretty easy to search and find 'stack' or 'experiments'. 

Yeah, I think let's just pull off the bandaid, otherwise we'll have to keep supporting this in experiments forever.

**Comment by khmakoto** [comment]
That sounds good to me.

However, since this was a request from @dzearing, I'll ask for his take before closing this PR.

**Pull request merged**
