### PR TITLE
Update persona initial colors to be aligned with those in Fabric 6 branch

### LINKED ISSUE #9691: PersonaCoin initial colors are inconsistent due to differences between versions 6 and 7
This is an issue observed in OwaReact SDF.

There are persona coins shown on the page, eg. email senders.
Hovering or clicking on them opens a profile card.
Profile card code comes from a separate package (LPC).

Until recently, both LPC and OWA were on Fabric React 6.
Then OWA upgraded to version 7. Due to changes in [#8905](https://github.com/OfficeDev/office-ui-fabric-react/pull/8905) that resulted in a color difference which breaks our coherence principles.

### PR DESCRIPTION
**Pull request by idijan**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9691 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Update persona initial colors to be aligned with those in Fabric 6 branch

Having a different set here while some O365 apps still use Fabric React 6 leads to color inconsistencies. For example, persona card is using FR6, while OWA is using FR7. Coin for same person on the page ends up having different background.

This change is aimed at mitigating the current color incoherence.
Later on, we want to apply the update in a controlled manner across all consumers, including the persona card which appears inside other applications.

#### Focus areas to test

Persona component
PersonaCoin component

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9692)

### CODE REVIEW

**Comment by idijan** [comment]
Thanks for catching that @Vitalius1.
I'll address it in the next commit.

**Comment by KevinTCoughlin** [comment]
cc: @micahgodbolt as per discussion with @Vitalius1 offline

**Comment by micahgodbolt** [comment]
When will the extended palette get used? If the new ramp has more colors, will those new colors ever get used? And if they do get used, won't we still have a alignment issue?

i.e. someone with initials AB might be fine, but if PT picks up the extended palette in Fabric 7, won't that be different than Fabric 6?

**Comment by idijan** [comment]
The palette update in v7 was intentional and moving towards fabric design goals.

Inconsistency which we encountered within some apps can be solved in other ways, so I'm closing this PR.
Thanks for reviewing.

**Pull request closed without merging**
