### PR TITLE
ComboBox button should have data-is-focusable="false"

### LINKED ISSUE #4051: ComboBox: Allow users to set the button's data-is-focusable value
Currently the button on a ComboBox defaults to data-is-focusable="true". There is [a mechanism](https://github.com/OfficeDev/office-ui-fabric-react/blob/d2edbbc6c069f8cb8d2936a8d982aa50be0613e1/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L166) for setting that value to false. The ComboBox just needs an interface to allow its consumer to do so.

This button is redundant for keyboard navigation (users can just arrow down to get to the options), so being able to set that value to false when using a FocusZone would be ideal.

I'm happy to submit a PR if approved.

### PR DESCRIPTION
**Pull request by paterasMSFT**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4051
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Added a property to ComboBox to specify the value for its button's data-is-focusable attribute. This is useful when the ComboBox is part of a FocusZone, as setting the value to false allows the button to be skipped with keyboard navigation.

I defaulted it to true, to avoid making a silent, subtle change for existing users. However, I believe the most frequent use case would be to set it to false, as that button doesn't make much sense in a keyboard navigation context. Any advice on what the appropriate default setting should be would be appreciated.

### CODE REVIEW

**Comment by jspurlin** [comment]
Yep. this holds true for spitButtons and spinButtons as well

**Comment by jspurlin** [comment]
@paterasMSFT The button should always be data-is-focusable={false}... it should never be focusable

**Comment by paterasMSFT** [comment]
It occurs to me that if the button is no longer keyboard navigatable, should we also remove aria-hidden=true and tabindex=-1? Do those still serve a purpose?

I know tabindex=-1 means it's not keyboard navigatable (something I surmise the FocusZone works around), but _is_ still focusable (presumably by mouse?).

**Comment by jspurlin** [comment]
just got your comment. Yes, the tabindex can be removed, but we should hold off on removing the aria-hidden, there's still some unresolved issues around how the comboBox gets build for accessibility where it currently doesn't correctly represent the control correctly if the button is visible

**Comment by paterasMSFT** [comment]
Now that the PR is closed, how should I make that change?

**Comment by jspurlin** [comment]
No, we can make that update when we deal with the unresolved issues that exist on the browser/screen reader side of things

**Pull request merged**
