### PR TITLE
Add contextual menu for documentation version switching

### PR DESCRIPTION
**Pull request by leddie24**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

- Move `getParameterByName` to location utility
- Add a `ContextualMenu` to `HomePage.tsx` to control version switching of documentation between Fabric 5 and 6.  This simply appends a URL param of `fabricVer=6` or `fabricVer=5`.  The logic for pulling the correct manifest file was created in PR #8343 

Screenshots:
**HomePage**
image

**Menu Open**
image

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by Jahnp** [comment]
Thanks @leddie24 ! Will take a look at this soon. One thing to note is that we need to update the server's `homepage.htm` with the changes from #8343 in order for this to work--we shouldn't merge this until thta work is done. I'll get started on that asap and update here when done.

**Comment by KevinTCoughlin** [comment]
Should we list the exact version in the dropdown or `6.x`? Not sure I have an opinion right now.

cc: @natalieethell as this may relate to her documentation work

**Comment by KevinTCoughlin** [comment]
I'm unsure of the status of this PR. Is it ready for review @leddie24?

**Comment by Jahnp** [comment]
Hey @KevinTCoughlin , sorry for the delay. Yes, this PR should be ready to go. We're close to finishing the backend work on the site required to test this functionality and are waiting to verify before merging this. I'd imagine this would be ready to merge in a few days.

In the meantime, if we want to keep the PR list clean, we can close this out for now. It just won't change much or at all between now and then.

**Comment by Jahnp** [comment]
Also, good question re: version string to show. I think showing the specific version would be better, but the way the site is setup today, the latest `5.x` version won't be available from the `6.x` site. Later, when we do the work to enable minor & patch version switching, we should be able to account for that behavior in the site.

Thanks for reviewing!

**Pull request merged**
