### PR TITLE
Stack: Consolidating vr-tests into single Stack.stories file

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Include a change request file using `$ npm run change`

#### Description of changes

Consolidating vr-tests into single Stack.stories file instead of separate VerticalStack.stories and HorizontalStack.stories files.

**Note:** I renamed the tests to include if they were referencing Vertical or Horizontal Stacks as many of the names were shared between the two. Please let me know if the current approach is alright or if you want it changed to some other way.

### CODE REVIEW

**Comment by khmakoto** [comment]
Screener is failing due to the fact that it's finding new vr-tests. Is this expected or is there anything else I'm that needs updating so that this doesn't happen.

**Comment by micahgodbolt** [comment]
new screener tests just need to be approved. introducing snapshots that aren't design approved means we're testing against something already broken.

**Comment by micahgodbolt** [comment]
great test coverage! Love it.

**Comment by cliffkoh** [comment]
@micahgodbolt who can do design approval while @betrue-final-final is out?

**Pull request merged**
