### PR TITLE
Button Slots Pre-Fluent Colors

### PR DESCRIPTION
**Pull request by bennettclark**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Updates button slots with correct palette values and scss fallbacks with pre-Fluent colors

### CODE REVIEW

**Comment by bennettclark** [comment]
@betrue-final-final - could you please review the screener results on this PR?

**Comment by betrue-final-final** [comment]
I'm getting colors that are all too dark.

**Comment by phkuo** [comment]
@betrue-final-final can you be more specific? Is it too dark and failing accessibility, or darker than the fluent styles, or darker than the original button styles we had before? These should be according to the redlines that the designer gave. @bennettclark who was the designer for this? Can you have them talk to Ben?

**Comment by betrue-final-final** [comment]
These backgrounds are darker than the prefluent specs for standard button. The “current” colors in the screener test are correct if you look at them.

**Comment by bennettclark** [comment]
@betrue-final-final I've pushed Sirena's updates so these should be the correct values now. Please check the screener when it's ready!

@joschect - I'm guessing I need your review on this because some of the snapshots that updated for this belong to you?

**Comment by betrue-final-final** [comment]
Will do!

**Pull request merged**
