### PR TITLE
MessageBar: fixed incorrect use of setTimeout

### PR DESCRIPTION
**Pull request by fantua**
#### Pull request checklist

- [x] Addresses an existing issue: #1014
- [ ] Include a change request file if publishing 
- [x] bugfix
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes

Fixed incorrect use of setTimeout at componentDidMount.

### CODE REVIEW

**Comment by mdahamiwal** [comment]
This is already in review with #1058. I don't think we should add another level of class heriarchy (BaseComponent) due to one setTimeout.

**Comment by fantua** [comment]
@mdahamiwal for `setTimeout` we need to use `this._async.setTimeout`, that defined at `BaseComponent ` and will be auto canceled on unmount. In your PR you just duplicated this logic. Take a look at @dzearing [comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/1014#issuecomment-280424813). 

So please, repoen my PR.

**Comment by mdahamiwal** [comment]
I am aware of BaseComponent but avoided adding another class hierarchy to handle one setimeout call. I would prefer BaseComponent for something more complex like throttle, debounce. I would still leave final call to @dzearing.

**Comment by fantua** [comment]
But anyway you duplicate `this._async.setTimeout` existing logic, that is not good.

**Comment by mdahamiwal** [comment]
@fantua, `setTimeout` and `clearTimeout` is JS native function and it would be overkill to introduce new dependencies on other files (basecomponent, Async) to reuse few lines of code. We do this at other places as well to minimize the dependency and avoid unnecessary redirection in the code. Hope that explains :)

**Comment by dzearing** [comment]
@mdahamiwal there are other reasons why we use BaseComponent, and it likely isn't going to add bits.

**Pull request closed without merging**
