### PR TITLE
Add Pivot item container className

### PR DESCRIPTION
**Pull request by kelseyyoung**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Add a className to the div surrounding the Pivot item to be able to be styled by a developer. Made optional so by default does not have any styles

This is in response to [this teams post](https://teams.microsoft.com/l/message/19:86b094239256467da9dfa96ba0897ca2@thread.skype/1550713063398?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=ffe264f2-14d0-48b5-9384-64f808b81294&parentMessageId=1550713063398&teamName=Microsoft%20UI%20Fabric&channelName=Fabric%20React&createdTime=1550713063398) (hopefully the link works)

#### Focus areas to test

Tested by adding that style in the Pivot demo pages and styles get applied as expected

### CODE REVIEW

**Comment by kelseyyoung** [comment]
Seems my build failed because of a long line in ProgressIndicator? I should have just pulled from master but I can try again

**Comment by leddie24** [comment]
@kelseyyoung, I think @dzearing made a commit to ProgressIndicator earlier today that is breaking that ts lint rule.

**Comment by JasonGore** [comment]
@dzearing Should be fixing it

**Comment by JasonGore** [comment]
Actually it was fixed with the merge of #8045 so another merge should fix this PR.

**Comment by dzearing** [comment]
I closed and reopened to retrigger a merge master

**Comment by cliffkoh** [comment]
Letting the bot take over the merging :) Looks good to go.

**Pull request merged**
