### PR TITLE
updating getFileTypeIconProps to make reference to correct sharepoint  list icon

### PR DESCRIPTION
**Pull request by bigbadcapers**
#### Pull request checklist

- [ ] Fixes an issue with sharepoint list item filetype icon

#### Description of changes

updated the method that handles special "non-file" items

#### Focus areas to test

doclibs that render files

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8162)

### CODE REVIEW

**Comment by betrue-final-final** [comment]
Looks like your PR has resulted in a regression to PeoplePicker. Not sure why, but it might be a mistake. Talk to an engineer
image

**Comment by bigbadcapers** [comment]
@betrue-final-final that is fascinating! how did you even find that out?

I stumbled through 11 commits to make this PR but the actual file changes boil down to 1 line of code related to how to represent an SPList in file views.

let me know how I can help resolve this

**Comment by bigbadcapers** [comment]
@ThomasMichon would you know what might be causing that regression Ben pointed out above? If this PR looks good, could you approve? I confirmed the new icon names have made it into prod for both odsp-media and fabric-cdn.

**Comment by bigbadcapers** [comment]
@Jahnp any idea what happened in Screener here given the file I actually changed? <bug eyed emoji>

**Comment by Jahnp** [comment]
The Screener failure seems completely unrelated to these changes. We should look into the test if it keeps failing and maybe update it to be more resilient--but for now I'm going to go ahead and bypass it since this PR otherwise looks good.

**Pull request merged**
