### PR TITLE
Button: fix size mismatch between primary and default buttons

### LINKED ISSUE #11355: Primary buttons are smaller normal buttons because they have no border
### Environment Information

- **Package version(s)**: latest commit 34c2785efba9f52609bc80cca77a6d37d1d43ae3
- **Browser and OS versions**: -

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/johannes-z/pen/QWwWXeE

#### Actual behavior:

Even though both compound buttons have the same content, their size is different, because the primary button has `border: none`, instead of setting the `borderColor` to `primaryButtonBackground`.

This is the line where this issues occurs: https://github.com/OfficeDev/office-ui-fabric-react/blob/34c2785efba9f52609bc80cca77a6d37d1d43ae3/packages/office-ui-fabric-react/src/components/Button/ButtonThemes.ts#L156

#### Expected behavior:

Both buttons should be the same size.

The line should read:

```ts
border: `1px solid ${s.primaryButtonBackground}`
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes - *I think this applies to all normal/primary button styles though*.

Requested priority: Low

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by xugao**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #11355
- [X] Include a change request file using `$ yarn change`

#### Description of changes
Fix bug where primary & default buttons with same child have different sizes due to primary one has no border but default one does.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11366)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
this is causing a small change with high contrast mode

before

image

after

image

Can you make sure that borders are picking up the high contrast background as well

**Comment by micahgodbolt** [comment]
Also, the change in border is affecting the appearance of the focus state

before: 

image

after

image

Not 100% sure the 'after' there is wrong. but it's a change. @betrue-final-final what's your take on the focus styles with that extra pixel border?

**Comment by betrue-final-final** [comment]
It actually makes it a little clearer. I'm good with this. Would Default also look like this with the extra padding?

**Comment by micahgodbolt** [comment]
better view of side by side 
image

**Comment by micahgodbolt** [comment]
Ben is good with the new focus rec......i'd say just clean up high contrast and we're good

**Comment by betrue-final-final** [comment]
Forgot to hit send. Yes this is great.

**Comment by khmakoto** [comment]
@xugao I think we also need to adjust the border of primary buttons in High Contrast when the buttons are hovered and pressed.

**Comment by micahgodbolt** [comment]
high contrast is looking great now 

image

**Pull request merged**
