### PR TITLE
Cheery-pick #6518 into 5.x

### PR DESCRIPTION
**Pull request by qianghuang94**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes https://github.com/OfficeDev/office-ui-fabric-react/issues/5308
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Cherry-pick fixes into 5.x Original PR https://github.com/OfficeDev/office-ui-fabric-react/pull/6518

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by qianghuang94** [comment]
@mikewheaton and @yiminwu  please help to merge this PR.

**Comment by aneeshack4** [comment]
@qianghuang94 It looks like there's a travis failure due to npm install not working - have you looked into this? Some things that have worked for me with install failures is syncing to latest and/or "rush install --purge"

**Comment by qianghuang94** [comment]
> @qianghuang94 It looks like there's a travis failure due to npm install not working - have you looked into this? Some things that have worked for me with install failures is syncing to latest and/or "rush install --purge"

Thank you so much, i will try!

**Comment by aneeshack4** [comment]
Thank you for fixing the travis failure @qianghuang94. It looks like it's ready to merge but I don't have authorization @mikewheaton do you?

**Comment by qianghuang94** [comment]
@dzearing Hi David, can you help to merge this PR?

**Pull request merged**
