### PR TITLE
Huaxi/no suggestions

### PR DESCRIPTION
**Pull request by yumikohey**
#### Pull request checklist

- [x ] Addresses an existing issue: Fixes #0000
- [x ] Include a change request file using `$ npm run change`

#### Description of changes
Luminosity contrast ratio is less than 4.5:1 for "No results" text in suggestion container

#### Focus areas to test
Suggestion

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9168)

### CODE REVIEW

**Comment by joschect** [comment]
@yumikohey thanks for making this change! It looks like we don't have a screener test for this scenario, would you mind adding one? And @betrue-final-final do you know if this is the right color for the no results text in the picker?

**Comment by yumikohey** [comment]
> @yumikohey thanks for making this change! It looks like we don't have a screener test for this scenario, would you mind adding one? And @betrue-final-final do you know if this is the right color for the no results text in the picker?
I will add a screener test for this scenario.

**Comment by Vitalius1** [comment]
@msft-github-bot make sure @betrue-final-final approves the PR

**Comment by betrue-final-final** [comment]
Not sure how someone thought neutralSecondary was less than 4.5:1, but that is incorrect. Where did this PR originate from?
image

**Pull request closed without merging**
