### PR TITLE
Dubunin/beta mdl2/218302 pivot focus

### PR DESCRIPTION
**Pull request by dubunin**
Updated keyboard focus styles for pivot links and pivot tabs. Since the pivot links already use the :before for the selected underline I could not use the focus-border mixin and had to use the outline. 

Focus-border does work on the pivot-tabs with a little bit of overriding. 

pivot-focused
pivot-tab-focused
pivot-selected-focused

### CODE REVIEW

**Comment by dzearing** [comment]
this seems like a gigantic PR. is there something off with the diffing? Maybe a messed up merge or something.

**Comment by dzearing** [comment]
BTW love the focus rects! looks great.

**Comment by atneik** [comment]
I think this one is meant to be merged in beta/mdl2 branch instead of master

**Comment by dubunin** [comment]
Ok. I meant to move this over to the mdl2 branch but I musthave picked the wrong one when pushing. Really not quire sure what happened. Gonna close this out and open a new PR on the correct branch.

**Pull request closed without merging**
