### PR TITLE
Revert "Reducing the build time (#4714)"

### PR DESCRIPTION
**Pull request by cliffkoh**
This reverts commit e7fa69974b3615f3522b3f09388f1eeb390c56e6, which introduced a bug under certain scenarios that cause builds to fail. The plan is in re-introduce this with a forward fix tomorrow (this revert prioritizes minimizing the disruption to the community while a fix is being developed).

### CODE REVIEW

**Comment by bworline** [comment]
See my comment in https://github.com/OfficeDev/office-ui-fabric-react/pull/4714 about how to improve the parallel build algo before reintroducing.

**Comment by cliffkoh** [comment]
Merging because the build has passed and it is just waiting for screener (which has passed in a previous run). Also until this is merged, master is broken.

**Comment by Markionium** [comment]
@cliffkoh the reason you reverted is because of the misding function error message reported on? https://github.com/OfficeDev/office-ui-fabric-react/pull/4896

@bworline Good suggestions! I'll have a look at them when i find some time.

**Comment by Markionium** [comment]
Will do! It's a national holiday here so didn't check work email ;)

**Pull request merged**
