### PR TITLE
Add selectedOptions to ComboBox and Dropdown

### LINKED ISSUE #8882: Multi-select ComboBox options
There's currently no good way of getting the selected values/indices of a multi-select `ComboBox`. Right now, the ways to do it involve listening to `onChange` (which seems really hacky) or get the selected indices directly out of the state (also hacky).

Having talked about this with @ecraig12345 we think that the best way to do this would be adding a `selectedOptions` prop to `IComboBox` of type `IComboBoxOption[]` that returns an array with the list of selected options in a multi-select `ComboBox`.

### PR DESCRIPTION
**Pull request by atneik**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8882
- [x] Include a change request file using `$ npm run change`

#### Description of changes

There is currently no straight way to get multiple selected options in a Dropdown or a ComboBox. This PR adds `selectedOptions` to `onChange` event of both the components.

Dropdown already had a `getAllSelectedOptions`, this PR also moves it to Utilities so that it can used by both the components.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8992)

### CODE REVIEW

**Comment by atneik** [comment]
@ecraig12345 to provide getter for `selectedOptions` I had to move a few things around. I found that we are calling `onChange` callbacks without waiting for `setState` to finish. So if users were to access `selectedOptions` in their provided onChange handlers they would have got a stale state. I also had to persist the events in order to successfully pass them after waiting for `setState`. 

Right now I'm stuck at two TS issues and wonder whats going wrong:

---

image

Argument of type '(props: IDropdownProps) => Element' is not assignable to parameter of type '(props?: ISelectableDroppableTextProps<IDropdown, IDropdown> | undefined) => Element | null'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'ISelectableDroppableTextProps<IDropdown, IDropdown> | undefined' is not assignable to type 'IDropdownProps'.
      Type 'undefined' is not assignable to type 'IDropdownProps'.

---
image

Argument of type 'IDropdownProps' is not assignable to parameter of type 'ISelectableDroppableTextProps<IDropdown, IDropdown> & IDropdownProps'.
  Type 'IDropdownProps' is not assignable to type 'ISelectableDroppableTextProps<IDropdown, IDropdown>'.
    Types of property 'onCopy' are incompatible.
      Type '((event: ClipboardEvent<HTMLDivElement>) => void) | undefined' is not assignable to type '((event: ClipboardEvent<IDropdown>) => void) | undefined'.
        Type '(event: ClipboardEvent<HTMLDivElement>) => void' is not assignable to type '(event: ClipboardEvent<IDropdown>) => void'.
          Types of parameters 'event' and 'event' are incompatible.
            Type 'ClipboardEvent<IDropdown>' is not assignable to type 'ClipboardEvent<HTMLDivElement>'.
              Type 'IDropdown' is missing the following properties from type 'HTMLDivElement': align, addEventListener, removeEventListener, accessKey, and 237 more.

**Comment by ecraig12345** [comment]
@atneik Wow, didn't realize this would be so complicated when I made the suggestion 😟 but thank you for all the hard work! I'll check out the branch and see if I can help figure out the TS errors.

**Comment by ecraig12345** [comment]
I was able to work around the compiler errors by removing the `props` param from a couple different render functions (and using `this.props` instead):
```
  /** Render Callout or Panel container and pass in list */
  private _onRenderContainer = (): JSX.Element => {
    const { responsiveMode, calloutProps, panelProps, dropdownWidth } = this.props;

    const isSmall = responsiveMode! <= ResponsiveMode.medium;

    const panelStyles = this._classNames.subComponentStyles
      ? (this._classNames.subComponentStyles.panel as IStyleFunctionOrObject<IPanelStyleProps, IPanelStyles>)
      : undefined;

    return isSmall ? (
      <Panel isOpen={true} isLightDismiss={true} onDismissed={this._onDismiss} hasCloseButton={false} styles={panelStyles} {...panelProps}>
        {this._renderFocusableList()}
      </Panel>
    ) : (
      <Callout
        isBeakVisible={false}
        gapSpace={0}
        doNotLayer={false}
        directionalHintFixed={false}
        directionalHint={DirectionalHint.bottomLeftEdge}
        {...calloutProps}
        className={this._classNames.callout}
        target={this._dropDown.current}
        onDismiss={this._onDismiss}
        onScroll={this._onScroll}
        onPositioned={this._onPositioned}
        calloutWidth={dropdownWidth || (this._dropDown.current ? this._dropDown.current.clientWidth : 0)}
      >
        {this._renderFocusableList()}
      </Callout>
    );
  };

  /** Render Caret Down Icon */
  private _onRenderCaretDown = (props: IDropdownProps): JSX.Element => {
    return <Icon className={this._classNames.caretDown} iconName="ChevronDown" />;
  };

  /** Wrap item list in a FocusZone */
  private _renderFocusableList(): JSX.Element {
    const { onRenderList = this._onRenderList, label } = this.props;
    const id = this._id;

    return (
      <div
        className={this._classNames.dropdownItemsWrapper}
        onKeyDown={this._onZoneKeyDown}
        onKeyUp={this._onZoneKeyUp}
        ref={this._host}
        tabIndex={0}
      >
        <FocusZone
          ref={this._focusZone}
          direction={FocusZoneDirection.vertical}
          id={id + '-list'}
          className={this._classNames.dropdownItems}
          aria-labelledby={label ? id + '-label' : undefined}
          role="listbox"
        >
          {onRenderList(this.props, this._onRenderList)}
        </FocusZone>
      </div>
    );
  }

  /** Render List of items */
  private _onRenderList = (): JSX.Element => {
    const { onRenderItem = this._onRenderItem } = this.props;

    return <>{this.props.options.map((item: any, index: number) => onRenderItem({ ...item, index }, this._onRenderItem))}</>;
  };
```

**Comment by atneik** [comment]
@ecraig12345 Upon digging more this time, I realized that both the render functions (`onRenderContainer` & `onRenderList`) are extended from `ISelectableDroppableTextProps`, so their props need to appropriately typed. That fixed it! 

Also had to make `_onRenderContainer` defining variables from both `props` and `this.props` as `responsiveMode` & `dropdownWidth` are from `IDropdown` not `ISelectableDroppableTextProps`. Alongside made the `_onRenderList` private method a pure function dependent upon `props` rather than `this.props`.

**Comment by basovic88** [comment]
Great work. I stumbled on exactly the same issue today. Looking forward to this feature.

**Comment by basovic88** [comment]
@ecraig12345 @atneik : I believe there is something wrong with this change. `onResolveOptions?: (options: IComboBoxOption[]) => IComboBoxOption[] | PromiseLike<IComboBoxOption[]>` is NOT receiving an Array of IComboBoxOption, but rather an Object of IComboBoxOption. For example: `{ "0": {key:"foo", text: "bar", selected: true}, "1": ...}`.

**Comment by ecraig12345** [comment]
@basovic88 Thanks for reporting this--would you mind opening an issue (and linking to this PR)?

**Pull request merged**
