### PR TITLE
Pickers: Make suggestions dismiss properly in dialog.

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [x] Addresses an existing issue: #931 
- [x] Include a change request file if publishing 
- [x] New feature, bugfix, or enhancement
- [x] Documentation update

#### Description of changes
Fixed it so that suggestions would properly dismiss in dialog rather than dismiss the entire dialog. Also changed popup to no longer use native eventing.

### CODE REVIEW

**Comment by joschect** [comment]
@dzearing I don't know why this is failing, all of the tests succeed locally.

**Comment by mdahamiwal** [comment]
@joschect, @dzearing, I see we are using `preventDefault`, `stopPropagation` a lot which solves the immediate goal but may not be the correct approach. As discussed in #836, this breaks the cases where other elements on the page need to react to click at another locations and `stopPropagation` makes it impossible. I guess we need to come up with a plan to fix this across fabric. I can take up some of them if needed.

**Comment by micahgodbolt** [comment]
Ran tests again via Travis and got the same error. Running them locally I get a DIFFERENT error. 

```
1) Fabric components GroupedList can render in a server environment:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```
Trying tests on master to see if my issue repros there as well.

**Comment by joschect** [comment]
@mdahamiwal I'm still uncertain about this. This might be something to take offline and talk more about.

**Comment by joschect** [comment]
@dzearing apparently this does break tests, but only in travis. I'll keep investigating.

**Pull request merged**
