### PR TITLE
ComboBox: Set Callout MaxWidth to be the width of the menu when useComboBoxAsMenuWidth when enabled

### LINKED ISSUE #5173: ComboBox: ellipsis needed for text that is too long for dropdown items AND/OR width should automatically increase.
### Bug Report

- __Package version(s)__: 5.106.1002
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: VSTS Analytics Views

#### Describe the issue:

There is a similar issue here #1589 that was fixed recently for Dropdown. The text in the dropdown should include ellipsis when the "useComboBoxAsMenuWidth" prop is set to true and the text is long, but it doesn't:

image

**The statement above is the main bug that we wanted to point out, but my team also has a feature request:**

_TL;DR: What we are looking for is the dropdown taking the width of the ComboBox as the minimum width, and the width of the dropdown increasing in size when the dropdown items have longer text._

**Feedback/Scenario:**
Having a dropdown shorter than its ComboBox looks odd, and the dropdown should automatically have the same width as the ComboBox:

image

I see that there are existing props that we can pass that address the issue I just stated above (dropdownWidth & useComboBoxAsMenuWidth); however, this becomes very limiting when we have dropdowns items with short and very long text values - using "dropdownWidth" without knowing the full width of the dropdown values or using "useComboBoxAsMenuWidth" with the proper ellipsis would not be the best way to portray this information:

image

**vs.**

image

If there were multiple instances of "zzzz..." with unique information at the end of the text, choosing a value would become confusing.

### PR DESCRIPTION
**Pull request by chang47**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #5173
- [X] Include a change request file using `$ npm run change`

#### Description of changes

We currently have a maxWidth where we set by adding a prop, however we don't set the max width when we have the prop useComboBoxAsMenuWidth set to be true.

I made it so that we use the menu width to be max width of the combo box so we'll overflow and show ellipses if combo box options are longer than the width

#### Focus areas to test

ComboBoxes with useComboBoxAsMenuWidth set to be true. I made a new component in the example page to validate that we indeed overflow if the options are too long we'll overflow with ellipsis.

### CODE REVIEW

**Comment by jspurlin** [comment]
@chang47 Does this address both concerns in #5173 ?

**Comment by chang47** [comment]
@jspurlin this solves the useComboBoxAsMenuWidth problem. Regarding their other requests, it sounds like to me that they want to specifiy the maxWidth of the comboBox, that's a behavior that I introduced in a previous PR: maxComboBoxWidth

**Comment by chang47** [comment]
Correction, in retrospect, the component itself should do that already. 

The fix here just makes the useComboboxAsMenuWidth overflow correctly.

**Comment by jspurlin** [comment]
@chang47 your build is failing because snapshots need to be updated

**Pull request merged**
