### PR TITLE
Add es2015.promise to experiments build

### PR DESCRIPTION
**Pull request by Adjective-Object**
#### Pull request checklist

- ~~[ ] Addresses an existing issue: Fixes #0000~~
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This is in office-ui-fabric-react build but not experiments.

Without it you can't construct promises or refer to promise as a concrete class in experiments

Some of the Extended Picker work I'm doing depends on this

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8667)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
Perhaps we can support this for `>= 7.x` depending on the resolution of https://github.com/OfficeDev/office-ui-fabric-react/issues/7077?

**Comment by Adjective-Object** [comment]
Ah, is that why ExtendedPeoplePicker uses PromiseLike in implementation?

On April 9, 2019 17:40:36 Elizabeth Craig <notifications@github.com> wrote:
> @ecraig12345 requested changes on this pull request.
> I'm not sure this is a good idea--we don't have official requirements that 
> consumers of our projects provide any polyfills, and without a polyfill, 
> anything using Promise will fail in IE 11.
> I think the only reason I included es2015.promise in OUFR is because 
> currently some tests use it (and the tests run in Node 8+, which has 
> Promise), but not any components. Including it was arguably a mistake since 
> that could allow it to sneak into component code.
> If there's no way to achieve what you need without constructing promises, I 
> can talk to some people and figure out a recommended approach.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by ecraig12345** [comment]
> Ah, is that why ExtendedPeoplePicker uses PromiseLike in implementation?

Yeah, that way we're relying on the external code to create the promise (not assuming a polyfill or directly settling for more limited browser support). If there's some scenario that you really can't handle without creating a promise yourself, we can talk about possible ways to handle that.

**Comment by Adjective-Object** [comment]
Alrighty. 

I'm going to be adding some tests that require a `Promise` implementation to experiments soon as part of the Pickers work that I'm doing, but I'll make it part of that PR. I had assumed that `experiments` just wasn't updated when the main oufr package was.

**Comment by ecraig12345** [comment]
If you want to use a promise in tests, what I *might* recommend is depending on es6-promise and importing from there (though don't include es6-promise in tsconfig.json typings to prevent it from being available everywhere). It's ugly and unnecessary since the tests actually have native Promise available due to running in a more up-to-date environment, but without adding a separate tsconfig just for tests, I'm not sure how to express that.

**Pull request closed without merging**
