### PR TITLE
MessageBarButton: Remove Fixed Width Styling

### LINKED ISSUE #10134: MessageBarButton does not render button text correctly
### Environment Information

- **Package version(s)**:  **7.9.0**
- **Browser and OS versions**: Google Chrome 

### Please provide a reproduction of the bug in a codepen: 
https://codepen.io/sshenoy291988/pen/oNvXJxO?&editable=true

#### Actual behavior:
The messageBarButtom has a hard-coded width value because of which any longer button text does not render correctly . Eg - Changing the text from 'Yes' to'Reload' shows how the text overflows from the button boundary and breaks the text 
Issue is probably here : https://github.com/OfficeDev/office-ui-fabric-react/blob/6ff7873e60436513ce7c3e4f39982a461fa5c86f/packages/office-ui-fabric-react/src/components/Button/MessageBarButton/MessageBarButton.styles.ts#L12

#### Expected behavior:
The messageBarButton text should be able to render any text without breaking the text into multiple lines

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Blocking 

Products/sites affected: (if applicable) Yammer

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #10134
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Remove the fixed width added in #8779 to allow `MessageBarButton` to adapt to user content by default.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10149)

### CODE REVIEW

**Comment by Vitalius1** [comment]
@betrue-final-final FYI

**Comment by khmakoto** [comment]
Would we want a `minWidth` instead of a `width` at least? I'll wait for @betrue-final-final's approval.

**Comment by JasonGore** [comment]
It has inherited `minWidth` of `80px`. You can see it in the snapshot output.

**Comment by khmakoto** [comment]
Yeah, I'm just wondering if we should specify `minWidth: 84px` for this variant. I basically just want to know if that width is something specified by the redlines.

**Pull request merged**
