### PR TITLE
Adjustments for focusing items in People Picker

### PR DESCRIPTION
**Pull request by ThomasMichon**
This change addresses some minor focus handling issues in the People Picker, notably:

- You cannot tab to the X button on a persona item that has been selected in the picker.
- Clicking on the X button in a persona to deleted loses the focus.

With this change, the following become possible:

- When a persona has focus, hitting Enter will tab within the persona, focusing the X button. Arrow keys still skip over the X unless you hit Enter.
- Deleting a persona using the X sets focus to the item which replaced it at its index.

### CODE REVIEW

**Comment by betrue-final-final** [comment]
It works as described, but the delete X just says "button". It should say "delete button". Also, when you delete a persona, it should say "deleted".

**Comment by ThomasMichon** [comment]
Right now, there isn't much of a story for how strings are plumbed into the `PeoplePicker` component. So without significant work I can't add the `aria-label` for now.

**Comment by ThomasMichon** [comment]
Looks like someone did the string plumbing work. Huzzah!

**Comment by dzearing** [comment]
@joschect you good here? (also @martellaj )

**Pull request merged**
