### PR TITLE
Snapshots: fixed snapshots while the checkins came through when tests weren't being run

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9240)

### CODE REVIEW

**Comment by ecraig12345** [comment]
Looks like you need to merge with master and run update-snapshots again.

**Comment by ecraig12345** [comment]
Actually the issue is that you need to update snapshots in the date-time package

**Comment by ecraig12345** [comment]
@msft-github-bot merge this pr in 30 minutes

**Comment by kenotron** [comment]
merging since perf-test isn't stable and the build step passes here.

**Comment by kenotron** [comment]
https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=15925

**Pull request merged**
