### PR TITLE
Add CDN configuration and Flight data to root.tsx of fabric-website (5.0) to allow website versioning

### PR DESCRIPTION
**Pull request by leddie24**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Adds Flight and CDN configuration feature to 5.0 branch of fabric-website to support website versioning.  This is a part 1 of 2 PR to introduce website versioning for 5.0 users of Fabric and allow users to toggle viewing documentation between 6.0 and 5.0.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8140)

### CODE REVIEW

**Comment by Jahnp** [comment]
Looks good Eddie!

For anyone else who's curious, this PR address part of #7269. Most of the infra work for that project is done—now we just need to add the capability to support dynamic public paths (this PR) and the actual version switching UI.

**Comment by leddie24** [comment]
Closing and reopening PR to see if build/screener test will succeed.

**Comment by KevinTCoughlin** [comment]
Screener is reporting a `DocumentCard` style change at https://screener.io/v2/states/ryQqxfIYZ.OfficeDev-office-ui-fabric-react/edwl%2F2019-02%2FaddFlightCDNConfig/1024x768/Chrome/documentcard-root-default-0

Could be a loose selector or outdated branch... unsure.

**Comment by Jahnp** [comment]
@KevinTCoughlin right--we noticed that last week and weren't sure what to make of it. Wondering if it's a race condition, outdated baseline, or something else--this PR didn't touch anything related to `DocumentCard`. @Vitalius1 mentioned he'd seen this exact error in other PRs that *also* didn't touch `DocumentCard`. It really looks like a false positive.

Would there be any opposition to merging this as-is?

**Comment by KevinTCoughlin** [comment]
> Would there be any opposition to merging this as-is?

As long as the author is OK with being on the hook for a potential build break ;). I've only ever seen this myself when my branch was out-of-date with `master` so I'm wondering if that is what's at play here.

**Pull request merged**
