### PR TITLE
FI from FUI 2020-02-10

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

First FI test - reruns the script & added an exception to prettierignore for all the .github/*.md files

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11913)

### CODE REVIEW

**Comment by JasonGore** [comment]
If the script was rerun, shouldn't the .md files show up as "modified" from Fabric repo's perspective?

**Comment by khmakoto** [comment]
@JasonGore not really, right? Since what's being added is an exception then the .md files should not have actually been modified.

**Comment by JasonGore** [comment]
Hmm, now I see [the md files that have previously been committed](https://github.com/OfficeDev/office-ui-fabric-react/pull/11897/files) were the unmodified commits. Now I'm curious why prettier didn't affect them on commit as part of that PR and curious why the change in this PR is needed.

In any case, I guess there would be no other md changes for this PR.

**Comment by aneeshack4** [comment]
So .github/*.md files should not be added as an exception?

**Comment by kenotron** [comment]
This might not needed - but i saw formatting changes as i import them before prettier is run locally.

**Comment by ecraig12345** [comment]
@kenotron Should we close this?

**Pull request closed without merging**
