### PR TITLE
ChoiceGroup: Flex layout for image and icon options

### PR DESCRIPTION
**Pull request by lynamemi**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [X] Include a change request file using `$ npm run change`

#### Description of changes

- Giving icon and image ChoiceGroups a flex layout with a new flex container - partners were adding this feature on their own for property pain and dialogs.
- Fixed an edge case bug for image where it was rendering correctly locally but no on the website. Switching to` box-sizing: content-box` seemed to fix this. See bug:
image

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
it's really hard to see what changed. is it possible to create a PR for only the lines you've changed?

**Comment by lynamemi** [comment]
Not sure why the diff went crazy. Where it's showing a large chunk of addition and subtraction, I just added a wrapper so changed the indentation. I'll see if I can fix that.

**Comment by micahgodbolt** [comment]
you can always do git add -p instead of git add .

that'll let you pick which things to add to staging.

**Comment by lynamemi** [comment]
@micahgodbolt I pushed the new lines and ignored the indentation.

**Comment by dzearing** [comment]
@micahgodbolt @lynamemi HINT: add ?w=1 to the PR url to avoid whitespace in diffs:

https://github.com/OfficeDev/office-ui-fabric-react/pull/4137/files?w=1

**Pull request merged**
