### PR TITLE
Drop shadows on menus should match spec

### PR DESCRIPTION
**Pull request by eliblock12**
#### Pull request checklist

- [X] Addresses an existing issue: VSO Bug #190766
- [X] Include a change request file if publishing 
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes
Shadows are smaller, offset differently, and lighter than they should be.

image

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
@eliblock12 can you drop in a screenshot of what it looks like now (assuming that  spec example is actually from our redlines)

**Comment by micahgodbolt** [comment]
@dzearing what's your concern?

**Comment by betrue-final-final** [comment]
Yeah, I'm not sure about this PR. Our spec has been CSS values
box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.4);

And hasn't changed, so it would only be ok if it matched this.

**Comment by betrue-final-final** [comment]
Confirmation that this is correct. Spec is on the right:
image

**Pull request merged**
