### PR TITLE
Integrating Jest in merge-styles

### PR DESCRIPTION
**Pull request by dzearing**
I experimented with jest and have integrated it in `merge-styles`. It has some great features like:

* smaller dependencies list and faster startup
* better errors that are on the actual typescript line number instead of from "tests.js"
* an amazing watch mode

We should dive in deeper into integrating it into experiments so that we can take advantage of snapshot testing.

I've added a `npm run start-test` command in merge-styles to do a test watch mode where you can auto run tests after you save code. @micahgodbolt you should try it out. :)

Also @christiango when i spawn jest, notice that i'm redirecting stderr to stdout which makes rush happy. Still haven't figured out how to preserve ansi color when running through execSync.

### CODE REVIEW

**Comment by christiango** [comment]
Did you try a custom test reporter instead of redirecting stderr?

**Comment by christiango** [comment]
Do you have debugging in vscode working?

**Comment by micahgodbolt** [comment]
Oh this is cool 
image

**Comment by micahgodbolt** [comment]
Though this error message is a bit noisy image

**Comment by dzearing** [comment]
if a test fails, it should have failed the build

**Pull request merged**
