### PR TITLE
BasePicker: prevents the multiline picker case to put the textfield in a new line

### LINKED ISSUE #7910: Picker input is pushed to next line when tag picker goes multiline
### Environment Information 
 
- __Package version(s)__: 6.124.2
- __Browser and OS versions__: Not relevant i believe, but windows 10, chrome 

### Please provide a reproduction of the bug in a codepen:

The codepen is below and note that i was testing on a 1920x1080 screen, and the second row of items was about half way into the input. 
https://codepen.io/sumboxcar182/pen/KJXOqj  

 
#### Actual behavior:
 
The tag picker is rendering the cursor always at the next line, even when there is a lot of space present on the current line. 
 
#### Expected behavior:
 
Previous versions of the Tag Picker (tested @ 6.25.1) always kept the cursor next to the last tag.  Here's a codepen of what it was doing previously https://codepen.io/sumboxcar182/pen/qgVWNY 

Looking at the code itself, it looks like there is a new span that wraps the selected items, and it does not have the input inside of it, so it ends up causing the input to be pushed to the next line when you get to the next row of tags. 

When i placed the input into that span it was fixed and brought back the previous functionality, but i'm not sure if this is something that fabric wants.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? If my suggested fix sounds ok i can look at getting a pr up. 
 
Requested priority: (Blocking, High, Normal, Low) : Low
 
Products/sites affected: (if applicable): My company's website (unsure if i'm allowed to say, my apologies).

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7910
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This places the autofill inside the span to keep all the picker inputs to be on the same line

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/7928)

### CODE REVIEW

**Comment by joschect** [comment]
@kenotron This is not the correct fix for this. The reason they are separate is to help with accessibility. Since the items are really a list of items, they must be contained within a span/div that has role="list" but the input has a different role so it shouldn't get contained within that list.

Instead could this be accomplished by adding a min-width the input? Or by changing some of the flex attributes?

**Comment by kenotron** [comment]
The problem here is that the span is acting NOT like a span. Somehow we ended up with a span that has a different display than inline. Not sure if that's required...

**Comment by kenotron** [comment]
What's even more odd is that the "list" isn't a UL/LI standard list but a span of items. I'm gonna try getting rid of that display weirdness first.

**Comment by kenotron** [comment]
What I'd like to know is how this affects accessibility if the role="list" is already paired with role="list-item. It seems like adding the input there inside the span would be okay since it doesn't contain role="list-item".

**Comment by kenotron** [comment]
@joschect - is there a specific issue in the past that pointed out this?

**Comment by joschect** [comment]
@kenotron per the https://www.w3.org/TR/wai-aria-1.1/#list a list can only contain things with either role="group" or role="listitem" so the list of items cannot contain the input. This is definitely by design. However, I see the problem that you've pointed out and I think it might make sense to make some css changes. I'll block this pr for now.

Thanks for taking the time to look into it!

**Pull request closed without merging**
