### PR TITLE
Coachmark: FIX color beacon prop not passed to styles

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Include a change request file using `$ npm run change`

#### Description of changes

Discovered this issue while was answering a stackoverflow question.
Most of the changes in the `Coachmark.base.tsx` file are caused by prettier... cc: @ecraig12345 Kevin had a similar formatting issue with the PR fixing the create package script. Did anything changed with the prettier config?

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9505)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
> cc: @ecraig12345 Kevin had a similar formatting issue with the PR fixing the create package script. Did anything changed with the prettier config?

FWIW mine were due to a Code extension which I was able to disable and undo.

**Comment by ecraig12345** [comment]
> cc: @ecraig12345 Kevin had a similar formatting issue with the PR fixing the create package script. Did anything changed with the prettier config?

The formatting in Kevin's PR didn't look like something Prettier would do, so I'm wondering if in that case there was a different formatter involved. 

In this case, I didn't see changes like the ones in your PR when I made a minor edit to Coachmark and saved it (with Prettier extension + format on save), but I *do* see the extra changes on commit. I'm not sure why this would happen (but can look into it later today)... It could be related to updating Prettier from 1.15.2 to 1.18.2 as part of Fabric 7, but if that was the case we would have been seeing changes like this before now.

In the meantime, to prevent pre-commit scripts from running and adding unwanted formatting, you can commit with the `-n` option.

**Comment by ecraig12345** [comment]
I think the Prettier changes in this PR are due to updating Prettier from 1.17 to 1.18 as part of the Fabric 7 updates. Specifically the issue is probably the linked change. I can either pin Prettier back to 1.17 or run the script to update everywhere and make a PR.
https://prettier.io/blog/2019/06/06/1.18.0.html#don-t-breakup-call-expressions-when-the-last-argument-is-an-arrow-function-with-a-simple-return-type-6106-by-brainkim

**Comment by Vitalius1** [comment]
Let me know what you decided so I can pull the changes when they are in. I don't have a strong opinion  about it. I feel like another run will just cause lots of conflicts on the already open PRs so devs will get not happy 😄

**Comment by natalieethell** [comment]
@Vitalius1 Elizabeth merged those changes: https://github.com/OfficeDev/office-ui-fabric-react/pull/9532. Want to try merging with master and saving the file again?

**Comment by Vitalius1** [comment]
@leddie24 would appreciate your approval or @ecraig12345 if you could override 😄 . Thanks!

**Pull request merged**
