### PR TITLE
Temporarily disable a11y-tests

### PR DESCRIPTION
**Pull request by statm**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Generated (unstable) CSS class names are included as snippets in a11y-tests' snapshots, causing failures in CI. Temporarily disable it until we correctly scrub/stabilize them.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8767)

### CODE REVIEW

**Comment by statm** [comment]
@msft-github-bot merge in 1 minute

**Comment by cliffkoh** [comment]
@msft-github-bot merge after 30 mins

**Comment by cliffkoh** [comment]
Oops

**Comment by cliffkoh** [comment]
@msft-github-bot merge in 2 mins

**Pull request merged**
