### PR TITLE
Dropdown: remove aria-activedescendant when disabled

### LINKED ISSUE #6605: Disabled Dropdown has no aria-label on screen reader
### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)
 
#### Actual behavior: When it gets to a disabled dropdown, the screen reader (Narrator) will just read "1 of 2, selected: can view". It will not read that the dropdown is disabled.

image

### PR DESCRIPTION
**Pull request by natalieethell**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6605 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Currently, Narrator is not reading out `disabled` for all disabled dropdowns. I noticed that it's working properly for multi-select dropdowns, and I found that (I think) it's because we set `aria-activedescendant` to `undefined` for all multi-select dropdowns. 

https://github.com/OfficeDev/office-ui-fabric-react/blob/fc5a1f4620c93499a41abe8377ff61161cf5bd76/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx#L172-L180

For single select dropdowns, even those that are disabled, we still set an `aria-activedescendant`. By setting this to undefined when the dropdown is disabled, you can see that Narrator now reads out "disabled" on focus. My reasoning is that it doesn't really make sense to have an `aria-activedescendant` if the dropdown is disabled, because that attribute is "used [...] to inform the assistive technology about the active child which has focus" [[developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-activedescendant_attribute)]. However, you aren't really focusing on the child when you focus on the disabled dropdown. 

#### Some more justification
In [Microsoft's documentation](https://docs.microsoft.com/en-us/windows/desktop/winauto/aria-container--no-active-descendants--keyboard-events), it mentions that the ARIA Container Role (without active descendant) Keyboard Accessibility Error does not apply to containers that are disabled.

> This error applies to elements that have a container role, do not have an aria-activedescendant attribute, and are not disabled.

For reference, here's the [W3C spec on aria-activedescendant](https://www.w3.org/TR/wai-aria-1.0/states_and_properties#aria-activedescendant).

#### Before:

image

#### After:

image

Note: One thing I'd like to bring up for discussion is whether we'd like to keep all the other information stored in the aria attributes about the selected key, such as the `aria-setsize` read out by Narrator. It seems okay as is, but just wanted to double check with you all.

#### Focus areas to test

Navigate to the Dropdown demo page and turn on Narrator. Focus on the single-select, disabled dropdown (you can click on it) and ensure that Narrator says "disabled".

### CODE REVIEW

**Comment by natalieethell** [comment]
Thanks for the thorough feedback Kevin! Regarding your question about the _slight_ difference with Narrator readout regarding the selection change, @cschlechty what do you think? Before the change, for a disabled dropdown, the screen reader would read out the position of the selection in the set. With the change, for a disabled dropdown, the screen reader reads out the number of items in the set.

**Comment by cliffkoh** [comment]
Actually it seems to be reading the number of items in *selection* (or so it would read this way to me)...

**Comment by cschlechty** [comment]
I'd expect it to not read position since it technically doesn't have one at that point. It should still read whatever the value is, if there is one set, but immutable.

**Comment by natalieethell** [comment]
With the change in the last commit, the screen reader now reads out the following for disabled, single-select dropdowns:

Disabled uncontrolled example with defaultSelectedKey:, group, collapsed, disabled,
Option d, 

This is now the same behavior as disabled, multi-select dropdowns.

**Comment by KevinTCoughlin** [comment]
> 
> 
> With the change in the last commit, the screen reader now reads out the following for disabled, single-select dropdowns:
> 
> Disabled uncontrolled example with defaultSelectedKey:, group, collapsed, disabled,
> Option d,
> 
> This is now the same behavior as disabled, multi-select dropdowns.

Nice!!

**Pull request merged**
