### PR TITLE
Fix Image not shown in RTL language.

### PR DESCRIPTION
**Pull request by callmedhh**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by callmedhh** [comment]
SharePoint OnPrem is using office-ui-fabric-react at version@5.79.1, and Image in RTL does not show, it is now fixed in [https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Image/Image.styles.ts](url). 
Here is a targeted fix for version@5.79.1.

**Comment by KevinTCoughlin** [comment]
Seeing if I need to wake up CLA 🤖

**Comment by callmedhh** [comment]
> @callmedhh is your Github account linked? I'm asking since the CLA PR gate step is stalled. Reach out to me on teams or mail if you need assistance with linking.

**Comment by callmedhh** [comment]
> @callmedhh is your Github account linked? I'm asking since the CLA PR gate step is stalled. Reach out to me on teams or mail if you need assistance with linking.

Thanks, I just link the account and now it meets CLA requirements.

**Comment by callmedhh** [comment]
@KevinTCoughlin Thanks a lot, I just link Github account.

**Pull request merged**
