### PR TITLE
Added optional month change callback property to Calendar and DatePicker

### LINKED ISSUE #10322: DatePicker/Calendar: ability to inform when month was changed
#### Describe the feature that you would like added

Callback function to execute when changing months like 'onMonthChanged' or similar

#### What component or utility would this be added to

DatePicker/Calendar

#### Have you discussed this feature with our team, and if so, who

Not yet, asked on stackOverflow but no responses yet. https://stackoverflow.com/questions/57711454/fabricui-datepicker-calendar-days-highlighting-and-navigation-callback

#### Additional context/screenshots

Need to get information if user navigated through months and what is the current one.

### PR DESCRIPTION
**Pull request by matprzybyla**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #10322
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Added onChangeMonth optional callback property to Calendar and DatePicker components along with some tests.

#### Focus areas to test
Was not able to get change file. Tries `yarn change` and `npm run change` with following result
```
Target branch is "upstream/master"
Checking for changes against "upstream/master"
fetching latest from remotes
No change files are needed
```

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10329)

### CODE REVIEW

**Comment by matprzybyla** [comment]
As commented here: https://github.com/OfficeDev/office-ui-fabric-react/issues/10322
I have some trouble getting this change file to work. 
Don't want to make duplicated conversation and I know you're busy but I would appreciate some help :)

Is there any other/manual way to make change file for this PR or make something else to push it further?

**Comment by lorejoh12** [comment]
Two suggestions I would add here:

First, I'd suggest putting this in the date-time package instead of the office-ui-fabric-react package (so in office-ui-fabric-react/packages/date-time/src/components/Calendar), because this one is getting deprecated soon, and it should be much easier to work with.

Second, the naming here is a little confusing. The Calendar can show two things side-by-side, the day picker and the month/year picker, or they can be overlapping. "onChangeMonth" doesn't really specify which change you're listening to. (right now, your change listens to the day picker changing, but not to the month/year picker changing).
So if that's what we want, I'd suggest renaming to onNavigateDayPicker. This gets a little weird when you consider the "monthPickerOnly" prop though- if we're only showing the month picker, do we need to have the callback work for that too? Probably, so maybe we should add a second prop, onNavigateMonthPicker as well.

**Comment by matprzybyla** [comment]
O, I'll prepare change to match your suggestions with 2 separate methods

**Comment by matprzybyla** [comment]
@lorejoh12 
Just checked that change I made originally and have some questions.
 
Currently the callback is executed when using arrow icons on day picker or navigating on day picker to next/prev month after clicking on a day. 
Additionally when month picker is visible and selecting different months, the callback is also called, also for month picker only like in example `Inline Calendar with month picker, no day picker`.
I can change the naming to `onNavigateDayPicker` - no problem there, but it also involves Month picker.

Just for clarification - how should then `onNavigateMonthPicker` work? You ment that is should be callback to changing years?

**Comment by maxwellred** [comment]
> @lorejoh12 John Lorenz FTE
> Just checked that change I made originally and have some questions.
> 
> Currently the callback is executed when using arrow icons on day picker or navigating on day picker to next/prev month after clicking on a day.
> Additionally when month picker is visible and selecting different months, the callback is also called, also for month picker only like in example `Inline Calendar with month picker, no day picker`.
> I can change the naming to `onNavigateDayPicker` - no problem there, but it also involves Month picker.
> 
> Just for clarification - how should then `onNavigateMonthPicker` work? You ment that is should be callback to changing years?

**Comment by maxwellred** [comment]
Accidentally closed, my bad.

**Comment by BrandoIsNotASword** [comment]
Any updates on this?

**Comment by lorejoh12** [comment]
> @lorejoh12
> Just checked that change I made originally and have some questions.
> Currently the callback is executed when using arrow icons on day picker or navigating on day picker to next/prev month after clicking on a day.
> Additionally when month picker is visible and selecting different months, the callback is also called, also for month picker only like in example Inline Calendar with month picker, no day picker.
> I can change the naming to onNavigateDayPicker - no problem there, but it also involves Month picker.
> Just for clarification - how should then onNavigateMonthPicker work? You ment that is should be callback to changing years?

I think we're referencing two different things here.

When you click the arrow on the left hand day picker:
image
The left part navigates to the next month. This is the callback you'd like to hook up to, yes?
When you click on a month in the right hand month picker:
image
The left part also navigates to the next month. This should still be announced, I think. :) so same callback.

However, when you click on the arrow in the right hand side:
image
only the right hand side navigates (to the next year).

You probably do not want this one to be announced as part of your callback, right? I guess that's changing the year, not the month, but better to be explicit about these things. :)

**Comment by maxwellred** [comment]
@matprzybyla, please have a look at John comments when you have a chance, thanks!

**Comment by maxwellred** [comment]
@matprzybyla ping

**Comment by matprzybyla** [comment]
Sorry guys, didn't had time to sit with this and got little confused. 
Not sure if able to finish it right now. Maybe we just leave this one out.

**Comment by micahgodbolt** [comment]
As per @matprzybyla, I'll close this PR for now. Feel free to re-open if you want to tackle this feature addition again.

**Pull request closed without merging**
