### PR TITLE
Fix scrollbar appearing in ActivityItem

### PR DESCRIPTION
**Pull request by ThomasMichon**
# Overview

This change fixes an issue in Edge and IE 11 where the `ActivityItem` component would show a scroll bar when rendered in a box exactly equal to the `line-height`. The `overflow-x: hidden` rule causes a vertical scrollbar to appear due to the presence of descenders which extend below the box.
Removing the `line-height` enforcement removes the artificial height enforcement while preserving the visuals, which get the correct line height from the current font size.

### CODE REVIEW

**Comment by ThomasMichon** [comment]
@phkuo It's a little difficult to do the 'before'. But Screener does show the tightening up of the line heights for the smaller fonts.

**Comment by phkuo** [comment]
You mean @cliffkoh right? =)

**Comment by cliffkoh** [comment]
:+1:

**Comment by ThomasMichon** [comment]
@phkuo Yes, sorry! Cross-wired from various Fabric-related correspondence.

**Pull request merged**
