### PR TITLE
add empty alt attribute to the image with presentation role in DocumentCard. 

### PR DESCRIPTION
**Pull request by yiminwu**
add empty alt attribute to the image with presentation role in DocumentCard. Otherwise the accessibility checker will show warning. These images only for presentation and they don't really need alt text but accessibility checker doesn't check the role, it will always complain for image without alt attribution. To workaround it, just add empty alt text.

### CODE REVIEW

**Comment by mikewheaton** [comment]
Maybe we could include descriptive text like "Profile photo of Yimin Wu"? I'm not sure what the best practice is here. What are your thoughts on this, @cschlechty?

**Comment by betrue-final-final** [comment]
Pictures should have captions. I’m not looking at the code, but I’m guessing that this is the circle picture in a card? If so, that seems appropriate.

**Comment by yiminwu** [comment]
@mikewheaton We already set role='presentation', with that reader will not read the alt text. That's why we don't need to add the description.

**Comment by mikewheaton** [comment]
But are these definitely presentation-only images, or do they carry information that we need to have read? For the avatar it seems reasonable, since we have the person's name right there. But for the file type, are we only communicating this via the file name otherwise?

**Comment by yiminwu** [comment]
Melissa told me that all the images are presentation only in the documentCard. for file type, yes, file name is good enough. Since we actually get the file type information from the file name. If we read file type, that is duplicate information.

**Comment by mikewheaton** [comment]
Approved

Oh okay, just didn't realize that Melissa had already reviewed this. 😄

**Pull request merged**
