### PR TITLE
git U/jehell/calendar griditem

### PR DESCRIPTION
**Pull request by jhellesen**
#### Description of changes

The row and column accessibly properties are not being populated (currently set to 0) for the table cells (td) causing screen readers to not read the row and column numbers.  This is due to an edge bug when the "inline-flex" is used as a display value.  

This change removes the display value causing the row and column properties to be set properly.

#### Focus areas to test

- Narrator row and column info should now be read by narrator
- No other changes are expected.

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
> This is due to an edge bug when the "inline-flex" is used as a display value.

Wow! That's surprising if true. Is there any externally available documentation of this bug by chance?

**Comment by lorejoh12** [comment]
> > This is due to an edge bug when the "inline-flex" is used as a display value.
> 
> Wow! That's surprising if true. Is there any externally available documentation of this bug by chance?

I'm not able to find any external documentation for it, it's a pretty specific bug that I'm sure has been noticed but I'm having a hard time finding it.

We did reach out to the Edge team and they acknowledged that it is a bug on their end, but we did not get a bug number or an ETA on when/whether it was planned to be fixed. Apparently dealing with table CSS layout is hard, so it certainly wouldn't be anytime soon. It was mostly shocking to us when we found it because it was extremely easy to repro the bug in a JSFiddle, literally just making a table with gridcells in it and adding/removing this property caused the bug.

**Comment by jhellesen** [comment]
> > This is due to an edge bug when the "inline-flex" is used as a display value.
> 
> Wow! That's surprising if true. Is there any externally available documentation of this bug by chance?

Sorry - not that I'm aware of.  I can confirm that it's at least on the radar of the Edge team.

**Comment by micahgodbolt** [comment]
@lorejoh12 another item to make note of for date-time

**Pull request merged**
