### PR TITLE
bug fix: check for input is exist

### LINKED ISSUE #3457: resolveNewValue picker error
There is code in components/pickers/BasePicker.tsx in resolveNewValue :
```
  this.setState({
      suggestionsLoading: false,
      suggestedDisplayValue: itemValue,
      suggestionsVisible: this.input.value !== '' && this.input.inputElement === document.activeElement
});
```

If u limit picker with itemLimit, when u select last item input is removed, so this code throughs error (TypeError: this.input is null). Easy fix is 
```
  this.setState({
      suggestionsLoading: false,
      suggestedDisplayValue: itemValue,
      suggestionsVisible: this.input && this.input.value !== '' && this.input.inputElement === document.activeElement
});
```

### PR DESCRIPTION
**Pull request by Ridlsan**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3457
- [x] Include a change request file using `$ npm run change`

#### Description of changes

If u set itemLimit for picker, when u pick last item input is removed. So we need this check

### CODE REVIEW

**Comment by Ridlsan** [comment]
My first ever pull request, dont beat me pls ) If i made something bad, i'll try to fix.

**Comment by ohritz** [comment]
I think you need to run the ```npm run change``` in the root of the repo and answer the questions. then commit the change file XXXXX_DATE.json thats generated and push.
I guess for type you would put 'patch'
Comment will show up in the changelog, so a good description...

**Comment by Ridlsan** [comment]
Added more checks and changes file

**Comment by micahgodbolt** [comment]
Nice work. Merging away.

**Pull request merged**
