### PR TITLE
Utilities: Add setVirtualizedParent export.

### PR DESCRIPTION
**Pull request by dzearing**
Missed an export.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8168)

### CODE REVIEW

**Comment by adam1658** [comment]
Hi @dzearing,

I'm getting a `Cannot redefine property: setVirtualParent` error now - I think it's because setVirtualParent is imported twice:
- https://github.com/dzearing/office-ui-fabric-react/blob/5a83881fc91bb3b9fea55b41eee9ab3e852f9415/packages/utilities/src/index.ts#L38
- https://github.com/dzearing/office-ui-fabric-react/blob/5a83881fc91bb3b9fea55b41eee9ab3e852f9415/packages/utilities/src/dom.ts#L14

If I comment out the offending line in `node_modules/@uifabric/utilities/lib/index.js` it works again, so I think that confirms the double import is to blame.

Sorry for reaching out here instead of in a new issue - I tried to create an issue before ibut I had a lot of trouble reproducing it in codesandbox (I'm using parcel to build my app on my machine). I believe this is because the codesandbox is using a UMD build, but in Parcel I'm using es6 builds.

Thanks,
Adam

**Comment by dzearing** [comment]
@adam1658 all good, let me try right now.

**Comment by dzearing** [comment]
@adam1658 this is being published right now, should be ready in 30 minutes. I'm not really sure how everything built with the double export.

**Comment by adam1658** [comment]
Fantastic! Thanks for a super-quick turnaround @dzearing 👍

**Pull request merged**
