### PR TITLE
Change the office-ui-fabric-react imports to be from root

### LINKED ISSUE #9150: Fluent Theme conflicts with Jest
### Environment Information 
 
- __Package version(s)__:
- "@uifabric/fluent-theme": "0.16.9"
- "jest": "24.7.1",
- "react": "16.8.6"
- "create-react-app": "3.0.1"
- "typescript": "3.4.5"

### Please provide a reproduction of the bug in a codepen:

Using a standard setup from Create React App, without building or importing anything else, the Fluent Theme import fails on compilation for running the test suite.

`npx create-react-app my-app --typescript`

`cd my-app`

`npm install @uifabric/fluent-theme`

Add `Theme.test.tsx` to `src`

```
import React from 'react'
import { FluentCustomizations } from '@uifabric/fluent-theme'

describe('Fluent Theme', () => {
    it('should pass', () => {
        console.log(FluentCustomizations)

        expect(true).toEqual(true)
    })
})
``` 

Run `jest Theme`

#### Actual behavior:

 ```
 FAIL  src/Theme.test.tsx
  ● Test suite failed to run

    C:\Users\ArrayKnight\Git\my-app\node_modules\office-ui-fabric-react\lib\Styling.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import './version';
                                                                                                    ^^^^^^^^^^^

    SyntaxError: Unexpected string

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/@uifabric/fluent-theme/lib-commonjs/fluent/src/fluent/styles/Breadcrumb.styles.ts:2:1)
```
 
#### Expected behavior:
 
Test should pass.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9150
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This removes the extra deps - everything should come in through oufr and variants. The import specifiers are changed to point to root so that it's consistent and can work with commonjs environments. 

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9158)

### CODE REVIEW

**Comment by ecraig12345** [comment]
If this version breaks ODSP, `office-ui-fabric-react/lib/index` should work instead.

**Comment by Vitalius1** [comment]
cc: @dzearing

**Comment by ThomasMichon** [comment]
At the moment, changing things to import components directly from the root of `office-ui-fabric-react` will severely impact the bundling of the OneDrive and SharePoint apps. So once this goes in we won't be able to consume drops from here for some time, and will probably have to fork a hotfix branch for sustained fixes.

**Comment by ArrayKnight** [comment]
Would switching to the commonjs version work for Jest and ODSP?

Change `office-ui-fabric-react/lib/Pickers` to `'office-ui-fabric-react/lib-commonjs/Pickers`

Not sure of the detailed requirements of ODSP (tree shaking?) but I believe this would fix the issue with Jest since it would no longer require building anything in node_modules.

**Comment by ecraig12345** [comment]
> Would switching to the commonjs version work for Jest and ODSP?
> 
> Change `office-ui-fabric-react/lib/Pickers` to `'office-ui-fabric-react/lib-commonjs/Pickers`

That would be a pretty major change of conventions. Though if the issue is that we need Jest to point to commonjs modules, there's probably some way to remap `lib` to `lib-commonjs` in Jest config.

**Comment by ArrayKnight** [comment]
Yea, the main issue (#9150) trying to be solved is that Jest shouldn't need to compile anything in node_modules and the current setup seems to be referencing modules that are not compiled to ES5/commonjs.

**Comment by kenotron** [comment]
So, if we move to lib-commonjs, that breaks all of our treeshaking from webpack since it's no longer ESM. 

@ThomasMichon - there already are fluent-theme files that import from root. Is that not already a problem? I seriously doubt that this would tack on more bytes if you were already using some of those packages...

**Comment by ThomasMichon** [comment]
@kenotron Currenty the only import from `'office-ui-fabric-react'` directly is in `FluentCustomizations.ts`, and the import is for an interface only, which is safe. The challenge is that any non-type-only imports from all of `'office-ui-fabric-react'` (or `'office-ui-fabric-react/lib/index'` will negatively impact bundlers which cannot tree-shake.

**Comment by kenotron** [comment]
I'm closing this PR until we can have all of our biggest partners move to non-AMD consumption.

**Pull request closed without merging**
