### PR TITLE
Expose aria label prop in dropdown option.

### PR DESCRIPTION
**Pull request by lijunle**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

- Dropdown: Expose aria label prop for the dropdown options.

#### Focus areas to test

Accessibility on dropdown component.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Minor nit. Can you form the form the change file like <Component Affected>: <Change Performed>

**Comment by lijunle** [comment]
Sorry, I don’t get your words. How do you want to look like?


发件人: Micah Godbolt [mailto:notifications@github.com]
发送时间: Thursday, June 1, 2017 11:19 PM
收件人: OfficeDev/office-ui-fabric-react <office-ui-fabric-react@noreply.github.com>
抄送: Junle Li <junlel@microsoft.com>; Mention <mention@noreply.github.com>
主题: Re: [OfficeDev/office-ui-fabric-react] Expose aria label prop in dropdown option. (#1910)


Minor nit. Can you form the form the change file like :

**Comment by micahgodbolt** [comment]
Sorry @lijunle totally mangled that, didn't escape it properly.

 \<Component Affected\>: \<Change Performed\>

such as

Button: Made it more awesome

**Comment by lijunle** [comment]
Sure! Update it in the PR description and rush change generated file.

**Comment by micahgodbolt** [comment]
Perfect :)

**Pull request merged**
