### PR TITLE
Fix typo in Persona color swatches declaration

### PR DESCRIPTION
**Pull request by c-w**
#### Pull request checklist

- [ ] Addresses an existing issue: #0000
- [x] Include a change request file if publishing 
- [x] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes

Previously, there were two entries for lightPink and no entry for pink meaning that we're disproportionately more likely to create lightPink Persona bubbles and it's impossible to create pink Persona bubbles.

#### Focus areas to test

Just a constant change, no need for in-depth testing.

### CODE REVIEW

**Comment by c-w** [comment]
Putting this onto your radar, @cliffkoh, since you reviewed changes to the Persona component previously.

**Comment by c-w** [comment]
Pinging @micahgodbolt to hit the merge button before master advances again.

**Comment by cliffkoh** [comment]
@c-w @micahgodbolt This change is actually a breaking change, not a patch unfortunately. We may need to revert this change before the next publish goes out.

@dzearing for fyi.

**Comment by cliffkoh** [comment]
@c-w This is great, thanks for the patch.

**Pull request merged**
