### PR TITLE
Fixed label for drop downs

### PR DESCRIPTION
**Pull request by rickyp-ms**
#### Pull request checklist

- [x] Addresses an existing issue: #1194
- [ ] Include a change request file if publishing 
- [x] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [x] Documentation update

#### Description of changes

Changed a <label> to a <Fabric.Label>

#### Focus areas to test

Drop down labels

### CODE REVIEW

**Comment by rickyp-ms** [comment]
A few things I noticed while doing this:
 - Checkbox is still using label, not Fabric.Label
 - It maybe a smart idea to separate the label portion and the contents that the label references in a later change. That way the two wont diverge again. First priority is to fix the layout issue though so I'd rather not block this change on that work.

**Comment by rickyp-ms** [comment]
I'm not sure how to add tests for this... soo I'm not going to and I'm going to put that in the things I noted in the comment above.

**Comment by fantua** [comment]
This on review with #1189.

**Comment by micahgodbolt** [comment]
Good catch here. This would have caused problems once we moved to CSS modules, so best to convert this to use the Label component.

**Comment by fantua** [comment]
@micahgodbolt this PR duplicate #1189.

**Comment by micahgodbolt** [comment]
@fantua Does one PR need to be closed then?

**Comment by rickyp-ms** [comment]
Considering that #1189 is very similar to this I'm going to close this one out without merging. I'll make comments on #1189 to have @fantua merge the two changes and get the best of both worlds.

Don't forget to add bugs for the Checkbox element along with a possible bug for extracting a Labelify element so the css doesn't drift between textfield and dropdown. I won't open them as I'm not sure how you plan to tackle that and will leave it to you.

**Pull request closed without merging**
