### PR TITLE
SpinButton: Add aria-valuenow and aria-valuetext for controller spin buttons

### PR DESCRIPTION
**Pull request by chang47**
#### Pull request checklist

- [X] Include a change request file using `$ npm run change`

#### Description of changes

According to the [aria-spec for spin buttons](https://www.w3.org/TR/wai-aria-1.1/#spinbutton). Spin buttons now need to have an aria-valuenow field.

In the current state of the spin button, we only set it based off of the values that the user sends it. This can be a complication if the user sets the value to be a non-number value, which will cause us not to set an aria-valuenow.

As a result in our code, we can only have aria-valuetext if the value isn't a number or a aria-valuenow if the value the creator pass in is a valid number.

Since aria-valuenow requires a number, we created a new prop where the user can specifically set the aria-valuenow field that they want to use if the value includes non-numeric characters.

#### Focus areas to test

Validate in the local instance of my app where the values of the spin buttons are being controlled externally and not via the spin button that we now have the ability to always have aria-valuenow.

### CODE REVIEW

**Comment by chang47** [comment]
Closing and re-opening PR again to run screener. There is no way my SpinButton changes should affect ComboBoxes!!

**Comment by jspurlin** [comment]
@chang47 Do you have the latest bits? I fixed that this morning with https://github.com/OfficeDev/office-ui-fabric-react/pull/6157

**Comment by chang47** [comment]
Gotcha I did not. I'll update it now

**Comment by jspurlin** [comment]
@micahgodbolt  as an fyi since screener seems to be having some issues (in case it continues to cause issues for this PR)

**Pull request merged**
