### PR TITLE
Fabric 7.0: fluent styles for Link, Label, ChoiceGroup, Slider, Breadcrumb, Callout, ContextualMenu

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Description of changes
This PR fluentizes Link, Label, ChoiceGroup, Slider, Breadcrumb (Had to add Callout and ContextualMenu in order to have the Breadcrumb screener test to pass).

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8402)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
this PR still has customizer wrapped around the controls, so screener tests are going to be a little odd

**Comment by Vitalius1** [comment]
DO NOT MERGE... need to sort out an issue with breadcrumb

**Comment by KevinTCoughlin** [comment]
> DO NOT MERGE... need to sort out an issue with breadcrumb

Ping me when ready for review

**Comment by Vitalius1** [comment]
@KevinTCoughlin ready for review 😄

**Comment by Vitalius1** [comment]
Requesting a review from code owners. Thanks in advance 😄 
@jdhuntington on `Breadcrumb`
@joschect on `Callout` and `ContextualMenu`
@cliffkoh on `Label`
@khmakoto  on `Link`
@aneeshack4  on `Slider`
@srideshpande on `ChoiceGroup`

**Pull request merged**
