### PR TITLE
Folder And Filetype Updates (brought to Fabric7)

### PR DESCRIPTION
**Pull request by bigbadcapers**
- [x] Replaces the filetype icon salt to ensure new Fluid icon is visible
- [x] Makes the signal icon and the itemcount in the folder tile view accessible and better laid out
- [x] Adds bigbadcapers to codeowners for the foldercover because masochism
- [x] Include a change request file using `$ yarn change`
- [x] Fabric 7 version of PR https://github.com/OfficeDev/office-ui-fabric-react/pull/11125

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11434)

### CODE REVIEW

**Comment by bigbadcapers** [comment]
@maxwellred the same screener changes showed in this one (intentional). what's your recommendation on how to get them approved / marked as deliberate?

**Comment by maxwellred** [comment]
@bigbadcapers Looks like Ben already approved, yay! I had the same license/cla issue on one of my  PRs and fixed it with closing and re-opening so I'll do that now

**Comment by bigbadcapers** [comment]
just confirmed this looks equally adorbs in Fabric7. @ThomasMichon lmk if there's anything else required here

image

**Comment by bigbadcapers** [comment]
@Jahnp can you help us merge this? i dont have write access to the repo

**Comment by dzearing** [comment]
@bigbadcapers i gotcha

Looks nice!

**Comment by bigbadcapers** [comment]
Thank you!!! I personally fiddled with the CSS units. #unreasonablyProud


Sent from my iPhone

On Dec 16, 2019, at 12:22 PM, David Zearing <notifications@github.com> wrote:

﻿

@bigbadcapers<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbigbadcapers&data=02%7C01%7Ccaperez%40microsoft.com%7Caea92a493a65429e931608d78265a7ac%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637121245423753541&sdata=pRhrFTdaf1fdIjVvHP3uXPPdYbnJqyUT32W74alzBaE%3D&reserved=0> i gotcha

Looks nice!

**Pull request merged**
