### PR TITLE
ComboBox: when clicking on scrollbar do not call onBlur

### LINKED ISSUE #6392: ComboBox invokes onBlur handler unexpectedly when the user clicks the scroll bar of the dropdown menu
### Bug Report 

For a ComboBox that is configured with "allowFreeForm" being true, if the user clicks on the scroll bar of the dropdown menu in order to scroll to an option to select, it invokes onBlur handler unexpectedly (technically the user's focus is still on the ComboBox as a whole).  In comparison, Fabric Dropdown component doesn't have this issue.
 
 
- __Package version(s)__: 6.61.2 
- __Browser and OS versions__: Chrome on Windows 10/2018 Server
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: SPO
 
#### Describe the issue:
 
Add a ComboBox that is configured with "allowFreeForm" to be true and large number of options so that a scroll bar is shown in the dropdown menu.  The user clicks on the arrow to open the dropdown menu.  Then the user clicks on the scroll bar in the dropdown and try to drag it down or up.

 
#### Actual behavior:
 
Actual: onBlur handler is invoked unexpectedly.
 
#### Expected behavior:
 
Expected: onBlur handler is not invoked because technically the interaction is still on the ComboBox. (Drowdown control doesn't invoke onBlur in this situation)

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6392
- [X] Include a change request file using `$ npm run change`

#### Description of changes
Adds additional logic to stop the `onBlur` handler to be invoked when clicking on the scrollbar of the `Callout` holding the `ComboBox` items

### CODE REVIEW

**Comment by Vitalius1** [comment]
@chang47 It looks like it always existed... but nobody ever checked the clicking on the scrollbar of the Callout holding the list menu.

**Comment by chang47** [comment]
Good to know. Thank you!

**Comment by Vitalius1** [comment]
@stanleyymsft I am trying to repro the issue you described when running locally and I don't see the behavior you mentioned. I am able to click on the scrollbar's thumb, on the scrollbar and I can drag the thumb with the mouse and then move the mouse over the items list and select.

**Comment by dzearing** [comment]
@stanleyymsft did you debug in there to understand the bug? Can you provide as much information as possible? Do you see an obvious fix? @jspurlin wrote the ComboBox so if you need more background you can ask him. :)

**Pull request merged**
