### PR TITLE
Correct typo in PivotDonts.md

### PR DESCRIPTION
**Pull request by matei-oltean**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Yeah, i'd like to know the reasoning behind it.....Are we just saying 'don't use pivots if you have enough room to display all the content on the page'? If you have a SPA with fixed viewport, can we not use pivots?

**Comment by micahgodbolt** [comment]
to the OPs credit....this was a grammar fix, and thanks for that :D But it does make me question if this line is really meaningful.

**Comment by Jahnp** [comment]
First, I'd echo @kkjeer in thanking @matei-oltean for making the change--we appreciate contributions and fixes like this :) Clearly we have a lot to work on!

Second, I'd echo @micahgodbolt 's question around if this guidance should be here at all. To be honest it doesn't make sense to me why one couldn't use a Pivot in a case where there isn't scrolling. But I might be missing something. @betrue-final-final , any thoughts here? I know you were looking at Pivots recently.

**Comment by matei-oltean** [comment]
Sorry, I just edited that fast while reading the docs, I will update that!

**Comment by KevinTCoughlin** [comment]
Should be good to merge pending successful CI cc: @kkjeer

**Comment by khmakoto** [comment]
Will close and reopen so that size auditor kicks in again.

**Comment by KevinTCoughlin** [comment]
I think we simply need to _dismiss_ @kkjeer's review as it is likely what is blocking merge. I believe @kkjeer is OOF. Given the scope of this change, I think its safe to dismiss that review as it was only requesting a change file be added. Which was done in https://github.com/OfficeDev/office-ui-fabric-react/pull/7398/commits/f911e6961652f3b256a29ab57c8b116fc564fc5f.

**Comment by khmakoto** [comment]
@KevinTCoughlin I don't have admin privileges to merge the changes without the approving review. Is there anyone else who can help with this?

**Comment by KevinTCoughlin** [comment]
> 
> 
> @KevinTCoughlin I don't have admin privileges to merge the changes without the approving review. Is there anyone else who can help with this?

Done.

**Pull request merged**
