### PR TITLE
Panel headertext aria

### LINKED ISSUE #1982: Accessibility: Panel aria-labelledby is broken
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes, but I'd like guidance.

Requested priority: High

Products/sites affected: All panels

#### Describe the issue:

Panels are currently unlabeled. I dug into this issue and determined that the onRenderHeader function takes in an untyped props and expects headerTextId to exist, but the props passed in are IPanelProps and headerTextId is not a property of IPanelProps. The onRenderHeader function sets the id of the header to headerTextId, which is undefined, and the dialog sets aria-labelledby to headerTextId. The end result is that there is no label for the panel.

#### Actual behavior:

Opening a panel in Narrator reads "dialog, focus on _____"

#### Expected behavior:

Opening a panel in Narrator should read "'My title' dialog, focus on _______"

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1982
- [x] Include a change request file using `$ npm run change`

#### Description of changes

headerTextId was being passed around as a prop, but it wasn't. So moved the suffix to global const, and recreated ID in header. Also cleaned up types and lets > const.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by marenar** [comment]
This wouldn't work if someone was using a custom onRenderHeader function though right? They wouldn't have the id and the panel would once again be unlabeled. I suppose they could add their own aria-label in that case.

**Comment by micahgodbolt** [comment]
@marenar ok, was able to get a quick change done. Tell me what you think. This creates an interface specifically for the header. Are there going to be any other props than those 3 that a custom render would need?

**Comment by marenar** [comment]
I don't think this is a bad thought, but I worry that this is a breaking change. This would break compatibility for anyone currently using onRenderHeader and expecting IPanelProps. What if instead we added headerTextId  to IPanelProps and then we passed it like { ...this.props, headerTextId: headerTextId}

**Comment by micahgodbolt** [comment]
@marenar yeah, that was my other thought. certainly safer in case others area already using the onRenderHeader. let me revise

**Comment by micahgodbolt** [comment]
@marenar there we go. added a componentId prop which is controlled internally, so that all onRender functions will have access to it.

**Comment by marenar** [comment]
This looks great to me, thanks Micah!

**Pull request merged**
