### PR TITLE
Primary variant for IconButton

### LINKED ISSUE #3933: Icon button: Need primary button
### Bug Report

- __Package version(s)__: N/A
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Any workload that wants a simple primary button
#### Describe the issue:

Right now there is only 1 icon button. It starts as neutral then goes to a darker theme and then lighter theme (not sure why it goes lighter on press....). Anyways, we would like a "Primary"version of this button.

#### Actual behavior:

Button does not exist

#### Expected behavior:

To have a primary icon button that starts as the "theme" color and has proper interactive color states.

### If applicable, please provide a codepen repro:

Icon button today: 

image

New button requested: Ben Truelove to provide pure spec

image

### LINKED ISSUE #4688: How to apply the primary style to an iconButton?
The iconButton default style is "Standard" with gray background color and black text color. what i wanna do is change the iconButton style to "Primary" and how? 
i tried to change the className but doesn't work, below is the react codes.

```
import React, {Component} from 'react';
import {
    ColorClassNames,FontClassNames
} from '@uifabric/styling';
import { IconButton, IButtonProps } from 'office-ui-fabric-react/lib/Button';
var classNames = require('classnames');

export default class extends React.Component<IButtonProps> {
    render() {
        return (
            <div >
                <IconButton
                    iconProps={ { iconName: 'Add'}}
                    className={classNames(ColorClassNames.white,ColorClassNames.themePrimaryBackground,ColorClassNames.themePrimaryBackgroundHover) }
                    title='Add'
                    ariaLabel='Add'
                />
            </div>
        );
    }
}
```

### PR DESCRIPTION
**Pull request by Markionium**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4688, Fixes #3933 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This PR adds a primary variant for the IconButton

image

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by lynamemi** [comment]
Could you add some screener / storybook tests to this, too, since it's a new variant?

**Comment by Markionium** [comment]
I was considering it but it seems the original IconButton doesn't have them either. So perhaps add those too.

**Comment by dzearing** [comment]
Webpack version: 4.5.0
(undefined) ../office-ui-fabric-react/lib/components/Button/IconButton/IconButton.styles.js
Module not found: Error: Can't resolve 'office-ui-fabric-react/lib/components/Button/ButtonThemes' in '/home/travis/build/OfficeDev/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Button/IconButton'
 @ ../office-ui-fabric-react/lib/components/Button/IconButton/IconButton.styles.js 7:21-89
 @ ../office-ui-fabric-react/lib/components/Button/IconButton/IconButton.js
 @ ../office-ui-fabric-react/lib/components/Button/index.js
 @ ../office-ui-fabric-react/lib/Button.js
 @ ./lib/components/SelectedItemsList/SelectedPeopleList/Items/ExtendedSelectedItem.js
 @ ./lib/components/SelectedItemsList/index.js
 @ ./lib/SelectedItemsList.js
 @ ./lib/index.js
[@uifabric/experiments 20:01:10] Error: webpack (4.949s): Webpack failed with 1 error(s).

**Comment by jordandrako** [comment]
Fixes #3933 too.

**Comment by suztocco** [comment]
Just a note that my intent when filing this issue was to have a primary icon style. So replacing the grey icon with the theme color. My intent was not to add a background square around the icon. This "may" be a need but isn't what I originally filed this issue against.

**Comment by betrue-final-final** [comment]
Good to know @suztocco . Sounds like this is all wrong then. So with the standard icon button, the original design changes the icon from neutral to theme color on hover. What would this do? Do we have a comprehensive design solution for icon buttons here? It would be great if there was one so it could be done correctly. @jordandrako so he knows as he was working on icon buttons as well.

**Comment by Markionium** [comment]
I'm currently travelling, so i probably won't have a lot of time to update this. Perhaps in the meantime we can come up with a design solution ;)

**Comment by suztocco** [comment]
Ben- You had mentioned I believe that you would draw one up (month ago of course so memory may mislead).

The thought was that this would start with “theme” and follow the same type of interaction pattern for color we use elsewhere.
So, the icon would become a darker theme color on hover/press or hover and press states (whichever pattern the button inherits).

**Comment by micahgodbolt** [comment]
can we get a reference of what the XD version looks like?

**Comment by suztocco** [comment]
@betrue-final-final  had mentioned drawing it up.

**Comment by betrue-final-final** [comment]
Apologies. Yes, we have that.
image

**Comment by betrue-final-final** [comment]
Icon goes to themeDark, backgrounds follow the same as standard icon button.

**Comment by suztocco** [comment]
@Ben Truelove<mailto:betrue@microsoft.com> Is there an option to “not” have the background colored square?

**Comment by micahgodbolt** [comment]
I'm okay with "fixing" the icon button's background colors. If we aren't lined up with our design specs, it really should be addressed. We just need to make sure doing so doesn't break anything else in Fabric where we expected the icon button to not have backgrounds (like teaching bubble).

Then we'll need to make sure to CLEARLY communicate with everyone the change. In this case, it would be beneficial to add a prop to remove the background (in the case that the icon is sitting on a primary colored background). This'll also help downstream users easily get the old functionality.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by suztocco** [comment]
Not sure if I am following what “fixing” the background means. You mean to have that as the default, but an endpoint can “remove” the background if desired?
I definitely feel that there are cases where the background is not desired.


Thanks

**Comment by betrue-final-final** [comment]
The background doesn't appear on rest, just hover, selected, selected hover etc.

**Comment by micahgodbolt** [comment]
Yes, but adding those styles ends up breaking a number of designs when the icon was never expected to have a background.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by suztocco** [comment]
Right. We are seeing the same issue today in builds where the bg is now showing up (wasn’t a few weeks ago) for some actions and this wasn’t expected.



[cid:image001.png@01D3EEA0.43D29A90]  [cid:image002.png@01D3EEA0.43D29A90]

**Comment by suztocco** [comment]
Ok, thank you Ben.
I’ll follow up with some of the Mail people.  I think they were mostly questioning the bg color on some of the “close” buttons.
It seems to be a mix in the builds now. But it sounds like your guidance is to always have a bg or some really obvious state shift (Like the Like button filling in versus being an outline).

**Comment by betrue-final-final** [comment]
Yes, outline for focus

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by micahgodbolt** [comment]
@Markionium is this PR still close to ready, or can we close it up until you're able to work out some of the above concerns.

**Comment by Markionium** [comment]
I think we haven't really reached a conclusion on this discussion yet? :)

@suztocco any new info? I'm ok to fix up the pr in line with @betrue-final-final's suggestions design from above, but if thats not final then perhaps we can close it for now?

**Comment by betrue-final-final** [comment]
Thanks @suztocco!

**Comment by dzearing** [comment]
I'm confused here.

**Comment by Markionium** [comment]
Closing this. Will reopen when i have an updated version ready.

**Pull request closed without merging**
