### PR TITLE
Image: Add ImageFit.centerContain

### PR DESCRIPTION
**Pull request by swese44**
#### Pull request checklist

- [x] Include a change request file using `$ npm run change`

#### Description of changes

`ImageFit.centerContain` renders as `ImageFit.center` unless the image's height or width is greater than the container's height or width, at which point it renders as `ImageFit.contain`.

Similar to `ImageFit.centerCover`, introduced in #6662.

#### Focus areas to test

Images

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8865)

### CODE REVIEW

**Comment by dzearing** [comment]
Re-opening to re-trigger build. it seems like screener timed out.

**Comment by swese44** [comment]
looks like i duplicated 2 stories in `Image.stories.tsx`, this might have caused Screener to fail. i just pushed a new commit to remove them

**Comment by dzearing** [comment]
@msft-github-bot merge it when it passes

**Comment by dzearing** [comment]
@msft-github-bot merge it in 1 minute

**Comment by swese44** [comment]
needs a manual review of the 4 new Screener diffs before msft-github-bot can merge it

**Comment by dzearing** [comment]
Yep excellent change, agree that the screener tests could use a bounding box to make sure they look right.

**Comment by cliffkoh** [comment]
master branch was broken so re-building. thanks for making the change!

**Pull request merged**
