### PR TITLE
add BlockedSiteSolid12 icon

### PR DESCRIPTION
**Pull request by ahackettms**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by Jahnp** [comment]
Please don't merge this. There are more steps required to update the icons like this. We're following up offline soon--but if possible I'd ask that you close this for now until we can make sure we're covering all the bases.

**Comment by dzearing** [comment]
@ahackettms can you work with @lynamemi on this update?

**Comment by dzearing** [comment]
I'm going to close this, please feel free to reopen once you've followed the steps in syncing with @lynamemi .

**Comment by lynamemi** [comment]
Sounds good! We've started syncing.

**Pull request closed without merging**
