### PR TITLE
Update icons to v3.46

### PR DESCRIPTION
**Pull request by Jahnp**
#### Pull request checklist

- [ ] Addresses an existing issue: N/A
- [x] Include a change request file using `$ yarn change`

#### Description of changes
Updating @uifabric/icon's icon set to the latest version in the [Fabric icons tool](https://aka.ms/uifabric-icons), v3.46. This PR adds new icons from that version while not adding any to the default set (aka the set of icons loaded initially) 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10296)

### CODE REVIEW

**Comment by kenotron** [comment]
@Jahnp - snapshots...

**Comment by Jahnp** [comment]
@kenotron ack—thanks for the reminder, my bad.

**Comment by kenotron** [comment]
Needs a change file note with the snapshot changes 🙈

**Comment by kenotron** [comment]
Shoot, `yarn update-snapshots` doesn't update all... try running this to ensure:

```
lerna run update-snapshots --stream
``` 

This will run update-snapshots on all projects that have an update-snapshots

**Comment by Jahnp** [comment]
Thanks @kenotron , been juggling a few projects between this and wasn't sure what the action was from the build log. I'll give that a try—appreciate the help.

**Comment by Jahnp** [comment]
@aftab-hassan , for the Size Auditor check, is there a way to update the baseline? Should this simply be accepted to proceed?

**Pull request merged**
