### PR TITLE
Updates to Fabric 6 website

### PR DESCRIPTION
**Pull request by ecraig12345**
#### Pull request checklist

- [x] Include a change request file using `$ npm run change`

#### Description of changes

Add Fabric 7 to the homepage dropdown in the Fabric 6 website version.

Export to codepen in the Fabric 6 website should use `office-ui-fabric-react@6`.

Fabric 6 manifests should be generated with `v6-` in the name now.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9454)

### CODE REVIEW

**Comment by ecraig12345** [comment]
Closing for now to ensure we have the right approach

**Comment by Jahnp** [comment]
What's the reason for deleting `homepage.htm` here? Because it's not relevant to actual site versioning?

**Comment by ecraig12345** [comment]
> What's the reason for deleting `homepage.htm` here? Because it's not relevant to actual site versioning?

Yes

**Comment by ecraig12345** [comment]
Marking as do not merge for now because the Fabric 5/6/7 website update PRs need to go in at the same time

**Pull request merged**
