### PR TITLE
Made input border semantic slot accessible

### PR DESCRIPTION
**Pull request by betrue-final-final**
- [x] Include a change request file using `$ yarn change`

Updated input rest states to have an accessible border by changing the inputborder semantic slot from neutralSecondaryAlt to neutralSecondary.

image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11361)

### CODE REVIEW

**Comment by ecraig12345** [comment]
Looks like you need to run `yarn change` again for datetime and experiments (you can use change type `none` if it's just snapshot changes).

**Comment by betrue-final-final** [comment]
I ran yarn change again on the root, which said was unnecessary, and it won't let me run it on date-time or experiments.
image

**Comment by betrue-final-final** [comment]
Hey @aneeshack4, can you take a look at this? Very simple.

**Comment by betrue-final-final** [comment]
Hey @lorejoh12, can you approve this?

**Pull request merged**
