### PR TITLE
Ensure headerClassName is processed properly within DetailsList

### LINKED ISSUE #7555: headerClassName isn't applied properly when using mergeStyles
### Environment Information 
current

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/WLyGwP
 
#### Actual behavior:
 The column header on DetailsList doesn't respect styles passed through the headerClassName property when the class was created with mergeStyles
 
#### Expected behavior:
Styles applied through mergeStyles to the headerClassName property work as expected and aren't overrun by default values.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: M365 Admin Center

### PR DESCRIPTION
**Pull request by brandonthomas**
#### Pull request checklist
- [x] Addresses an existing issue: Fixes #7555
- [x] Include a change request file using `$ npm run change`

#### Description of changes
- Moved headerClassName to the end of the styles array so it's processed properly when using mergeStyles
- Added example page showing custom column headers work with mergeStyles

### CODE REVIEW

**Comment by brandonthomas** [comment]
@dzearing or @KevinTCoughlin , any idea why the build is failing? I ran npm run buildci, rush rebuild --verbose --lint, and npm run bundlesize all successfully locally. Is there a way to rerun the checks? Seems odd it would fail here but not on my box.

**Comment by KevinTCoughlin** [comment]
> 
> 
> @dzearing or @KevinTCoughlin , any idea why the build is failing? I ran npm run buildci, rush rebuild --verbose --lint, and npm run bundlesize all successfully locally. Is there a way to rerun the checks? Seems odd it would fail here but not on my box.

Unsure about this right now, but let's make sure that this change is valid before spending more time there. See below.

---

Tagging @kenotron who has more experience with `mergeStyles` than I.

I tested applying a `headerClassName` in `master` by supplying a custom `className` as follows:

```diff
diff --git a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
index b046dc4f9..650bfad89 100644
--- a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
@@ -23,7 +23,8 @@ const _columns: IColumn[] = [
     minWidth: 100,
     maxWidth: 200,
     isResizable: true,
-    ariaLabel: 'Operations for value'
+    ariaLabel: 'Operations for value',
+    headerClassName: 'foobar'
   }
 ];
```

And saw that the `className` is rendered in the DOM.

```shell
document.querySelectorAll('.foobar').length
1
```

Ken / mergeStyle experts, is it intentional that a `mergeStyles` selector (ex: `css-48`) is omitted when later merged in another JS styles calculation?

It seems like this is by design and that we should recommend using `styles` directly. Otherwise, other components must also exhibit this same behavior.

**Comment by kenotron** [comment]
@brandonthomas The build fails because snapshots needs to be updated I think?

**Comment by KevinTCoughlin** [comment]
@kenotron @cliffkoh do you think this is something we should test for, perhaps as part of conformance tests? See https://github.com/OfficeDev/office-ui-fabric-react/issues/7555#issuecomment-452910076

**Comment by KevinTCoughlin** [comment]
@brandonthomas looks like most other components have the `className` at the end of the list, so your change LGTM.

Do you mind adding a unit test for this component to avoid potential regression? All that should be required is to render the component and test for the presence of the generated `className`. You can run that same test against `master` to ensure that it fails.

Thank you for this fix!

**Comment by dzearing** [comment]
agree with what @cliffkoh said above.

**Pull request merged**
