### PR TITLE
onRenderDivider's implementation in an example (DetailsList)

### PR DESCRIPTION
**Pull request by s-vaibhav**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Example updated with the implementation of onRenderDivider's callback implementation for DetailsList
Preview:
image

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
The icon used as the divider makes it seem like a rendering glitch to me. Can we render something that fits the table better? Perhaps a divider with a custom color that doesn't overlay text? cc: @Jahnp for thoughts on showing this capability in the Advanced DetailsList demo page.

I'd also consider dropping the Callout if we pursue this unless you feel that users looking for custom divider rendering will likely attach Callouts to them. I'm honestly not sure given how overloaded the advanced List demo is today.

**Comment by s-vaibhav** [comment]
@KevinTCoughlin  As suggested, I have removed the **Icon** and **Callout** from the example. The current implementation will simply render a primary theme coloured divider as shown in the (updated)picture above.

**Comment by micahgodbolt** [comment]
@KevinTCoughlin are you good with this now?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin are you good with this now?

Yes! It looks great. Thanks @s-vaibhav.

**Pull request merged**
