### PR TITLE
Changed commandBar cacheKey creation logic for farItems to include th…

### PR DESCRIPTION
**Pull request by mohanmaheshwari1**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes
Changed commandBar cacheKey creation logic for farItems to include the Name along with the key while creating the cacheKey

REpro steps:
Create a modern page;
Add a section with 3 columns or one-third left column;
Add a Document library webpart;
Publish the page.

Root cause of this issue is that the cacheKey stays same before "All Documents" text is added in "Switch View Options" and enve after it update the name to "All Documents"

Because of this second shrink call takes the width from cache which is not changed and because of this primary items do not shrink.

#### Focus areas to test
CommandBar
(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9363)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Is it not possible to change the key if the content changes? that would invalidate the cache without those extra steps

**Comment by mohanmaheshwari1** [comment]
> 
> 
> Is it not possible to change the key if the content changes? that would invalidate the cache without those extra steps

CommandBar takes the list of Menu Items to be shown as part of its props and these items has multiple properties. 
is it fine to every time change items key for an update of its internal props for operation like adding new sub menu ?

**Comment by micahgodbolt** [comment]
> Root cause of this issue is that the cacheKey stays same before "All Documents" text is added in "Switch View Options" and enve after it update the name to "All Documents"

If a button on the command bar changes (styles update, text changes etc), that change should be accompanied by a chance to the item key. It's more expensive to have the command bar checking key AND text. Also, this change is only affecting far items, but it seems the same problem would hold true for near items as well.

I'd like to see if you can use the key to invalidate the cache. And if there is a valid reason why this doesn't work, and we should be watching the text as well, then we should change both near and far items.

**Comment by ThomasMichon** [comment]
@micahgodbolt It doesn't make sense to me to have the `key` change for a given command. `key` should be used like the React `key` prop; it's what lets React maintain the lifetime of component even if moved or re-ordered when props update, which is exactly what can happen with commands.
A calling component may elect to override `commandBarButtonAs` on a command item, in which case we rely on `key` to be persistent even if the text changes, because React needs to be able to maintain the component instance for the button override.
Perhaps we should add a `contentKey` or something to indicate that the content of a command has changed, but not its identity?

**Comment by mohanmaheshwari1** [comment]
> I'd like to see if this can be solved by changing the item key at the same time the text is updated. This should be the approach used for both near AND far items. If there is a valid reason this doesn't work, we should look to adjust both near and far item cache keys.

As suggested by @ThomasMichon changing the items key may not be suitable for our use case. I think the purpose of  "_computeCacheKey" method is to create a unique key for a unique combination of near and far items and indeed its dependent on the key of individual item but we missed out the factors affecting the width should also be part of computation logic. This will solve our core purpose to not recalculate the width if the factors affecting the width are same.

**Comment by micahgodbolt** [comment]
Sorry, to clarify. I'm not talking about changing the 'key' value (used by react to track items), I'm talking about changing the cacheKey is the content changes. Simply set the cacheKey to the same value as your text if you need to invalidate the cache if the text changes. 

We already have a mechanism for invalidating cache. I don't see why we'd need to add additional checks, which only work in the overflow, not in the main items. 

image

**Comment by leddie24** [comment]
@mohanmaheshwari1 @micahgodbolt , what's the status on this PR?  It's been a few days since it's received attention; just checking before it goes stale.

**Comment by micahgodbolt** [comment]
Can you try my solution of modifying the cacheKey prop at the same time you modify the text?

**Comment by leddie24** [comment]
@mohanmaheshwari1 , is this PR still in progress?  Just want to check before it goes stale, thanks.

**Comment by mohanmaheshwari1** [comment]
I have raised the PR in odsp-common with cachekey modification as suggested by @micahgobolt . I think we can revert this PR now.

**Comment by micahgodbolt** [comment]
Great to hear @mohanmaheshwari1 ! If you're having any issues please feel free to reach out to me directly.

**Pull request closed without merging**
