### PR TITLE
ResizeGroup: Optimize performance when onGrowData is provided

### PR DESCRIPTION
**Pull request by christiango**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes
Performance profiles show that there is a wasted state update when onGrowData is provided to a resize group and the controls do not fit. The following example demonstrates the current behavior. For simplicity, let's assume the scaling data is just an object containing the width of the object.

Initial Scaling Data:
```typescript
{ width: 120}
```
Width of the container: 100px.

The initial scaling data would take up 120 pixels when rendered, so it does not fit in the container. The current logic kicks off a new state update with the shrink resize direction and the same data to measure. However, this is wasteful since w already measured this object and we know it does not fit. 

After this change, the new behavior is to also update the data to measure by calling onReduce data to get the next data to measure. 

This change also updates a unit test and replaces one to capture and validate the new behavior.

### CODE REVIEW

**Comment by christiango** [comment]
@micahgodbolt can you take a look at this? There are a few more optimizations I want to explore, but they build on top of this PR.

**Comment by micahgodbolt** [comment]
@christiango i'm trying to figure out how onGrowData is relevant to when the render is too large for the container. Am I just not reading this correctly?

**Comment by christiango** [comment]
So the initial data passed into the ResizeGroup isn't necessarily the largest state (though it is typically the largest state). We set the initial resize direction to grow. In the event that the user does not provide an onGrowData, we run the "shrink contents until everything fits" codepath and this bug is never hit. If an onGrowData is provided, we run the "grow contents until everything doesn't fit, then shrink" to make sure that we account for the case that we could fit more content than the initial data state. This bug only exists in the latter codepath, since the switch from grow to shrink should switch the data to measure to be the result of calling onReduceData, since we already know the data we just measured in the grow pass, does not fit.

**Comment by micahgodbolt** [comment]
Ah, that makes sense. Solving for the case where initial data is smaller than the space and you need to call 'grow' to fill it up.

**Comment by micahgodbolt** [comment]
restarting build. screener had some downtime earlier today.

**Pull request merged**
