### PR TITLE
Fix dropdown misalignment

### PR DESCRIPTION
**Pull request by betrue-final-final**
#### Pull request checklist

- [ ] Addresses an issue found by @dzearing 
- [X] Include a change request file using `$ yarn change`

Added focus rectangle as an after element to fix shifting control up and left by 1px.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11258)

### CODE REVIEW

**Comment by jdhuntington** [comment]
Looks like this is missing a change file (and potentially snapshots); will push those momentarily.

**Comment by joschect** [comment]
@betrue-final-final or @dzearing do we know what happened to the focus mixin? Are we no longer using it?

**Comment by kenotron** [comment]
Is that screener diff a click on a disabled item? I don't think we would be doing a outline on a disabled item?

**Comment by ecraig12345** [comment]
Is this waiting on anything or is it ready to go? (I just triggered a new build.)

**Pull request merged**
