### PR TITLE
 Button: Adding ariaHidden prop

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This PR adds the `ariaHidden` prop in order to achieve better API compatibility with the old `Button`.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9017)

### CODE REVIEW

**Comment by JasonGore** [comment]
Hmm I find this is valid and works fine too. I wonder what the context is behind adding such props.. type safety? (I'm wondering if we should mark `ariaHidden` as @deprecated.)

image

**Comment by khmakoto** [comment]
Maybe we could deprecate it. It was more for backwards compatibility with the old button right now. However, we could get away with not needing it if we wrote a code mod for this.

**Comment by micahgodbolt** [comment]
Agreed. No reason to specify a prop that has already been included by extending unless we need to specify additional docs, or describe special handling etc. I think things like href on a link make sense, but not every single random Aria value

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KevinTCoughlin** [comment]
> In this case, since `aria-hidden` is already usable and has no other special processing for it, we should expect users to use `aria-hidden` and not provide a separate `ariaHidden` prop. For this reason, I think we should actually deprecate `ariaHidden`.

This would be amazing.

**Comment by khmakoto** [comment]
Thanks for your input, I'll close this and work on deprecation.

**Pull request closed without merging**
