### PR TITLE
Pickers: adjust PeoplePicker suggestion item styles to follow toolkit

### LINKED ISSUE #7556: Pickers do not conform to Fabric toolkit spec
### Environment Information 
 
N/A

### Please provide a reproduction of the bug in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/6.120.0/#/examples/pickers

#### Actual behavior:
 
screen shot 2019-01-07 at 2 53 54 pm
 
#### Expected behavior:
 
screen shot 2019-01-07 at 2 50 19 pm

Related: https://github.com/OfficeDev/office-ui-fabric-react/pull/7538#issuecomment-452112114

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #7556 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

1. Set the border to `none` of the buttons wrapping the `PeoplePickerSuggestionItem` to mitigate the coming changes in #7538 
2. Adjust padding on the suggestion item to bring the overall height to the one in the toolkit. @amyngu introduced this padding in #5561 by moving it from `Suggestions.scss`. #1843 introduced in `Suggestions.scss`. The title of that PR says it's updating to match OWA and Fabric toolkit. Obviously, the current toolkit differs from the one followed in the PR. Are we breaking anything by reducing the `padding` on top and bottom? @joschect @betrue-final-final @kristoferbrown  FYI. Let me know and I can revert this change.
3. ~~@betrue-final-final should we reduce the padding for `TagPicker` suggestions also? Here is a comparison on how would that look. If we decide not to touch the `padding` in point 2 of this description I can leave it as it is.~~ **Edit:** Adjust by 1px `padding-top` to bring the overall height to 32px.

|Original                                      |  Reduced                               |
|:-----------------------------:|:---------------------------:|
| ![screen shot before][before] |  ![screen shot after][after]  | 

[before]: https://user-images.githubusercontent.com/29514833/51010523-87475a00-1509-11e9-9f05-f5a4d3cdf2a4.png
[after]: https://user-images.githubusercontent.com/29514833/51010527-8adae100-1509-11e9-8c74-48a7cfa55d83.png

### CODE REVIEW

**Comment by cliffkoh** [comment]
Don't you need to update snapshots?

**Comment by Vitalius1** [comment]
I did run the script but nothing updated 😢

**Comment by cliffkoh** [comment]
No worries :) at least we have screener for this!

**Comment by betrue-final-final** [comment]
I'm not sure what it is now, but the height of menu items should be 32px, until Fluent, where they will be 36px and have a compact mode of 32px.

**Comment by Vitalius1** [comment]
@betrue-final-final will need your screener review. Thanks!

**Comment by ecraig12345** [comment]
@Vitalius1 When trying to update the snapshots, what command did you use and where? The build is definitely failing due to missing snapshot updates. (I'm also seeing other PRs' builds appearing to fail because of the snapshot changes from this PR....???)

**Comment by Vitalius1** [comment]
Wait... other builds failing because of this PR? It's not even merged in 🤔

**Comment by Vitalius1** [comment]
`npm run update-snapshots` from the root of the repo...

**Comment by Vitalius1** [comment]
I have no idea why locally my snapshots are committed in my branch but were never pushed through to the PR... ❓

**Comment by Vitalius1** [comment]
Merged the master into the branch and it finally went through.

**Comment by Vitalius1** [comment]
@ecraig12345 now it's failing on a test I did not touch in this PR 😢 I am guessing there will more of these errors that slipped through...

**Comment by betrue-final-final** [comment]
I OK'd screener. Looks good

**Pull request merged**
