### PR TITLE
Changing breadcrumb items to links

### PR DESCRIPTION
**Pull request by caiomontei**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes breadcrumb items being rendered as buttons instead of links.
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Set prop to render breadcrumb item links as anchor tags instead of buttons.

#### Focus areas to test

Breadcrumb navigation

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10113)

### CODE REVIEW

**Comment by ecraig12345** [comment]
@caiomontei Can you please explain what scenario this was meant to fix? This change entirely broke "clicking" `href`-less breadcrumb items with the keyboard (by pressing enter), which is a severe accessibility issue.

Due to the accessibility issue, I'll probably need to revert this change. If there's some specific scenario you have where you need to force rendering all breadcrumb items as links, you can set `as: 'a'` on each `IBreadcrumbItem`.

**Comment by ecraig12345** [comment]
Looked at this a bit more and apparently the `as` prop was added after your change and currently only allows rendering as a heading. However, I can modify it to allow forcing rendering as an `a` as well, if that's truly something you need.

**Comment by ecraig12345** [comment]
Thanks for the background. Even before this change, any breadcrumb with a `href` should automatically have been rendered as an `a` rather than a `button` (`Link` handles this, and Breadcrumb uses `Link` internally). Was there some case where that behavior wasn't working?

**Comment by caiomontei** [comment]
This is the original issue I logged to fabric, [#10098 ](https://github.com/OfficeDev/office-ui-fabric-react/issues/10098).

I don't remember now if the place consuming it was setting href or not.

**Pull request merged**
