### PR TITLE
Add two icons: streamLogo and powerBILogo

### PR DESCRIPTION
**Pull request by qqli1209**
#### Pull request checklist

- [ ] Include a change request file using `$ npm run change`

Add `streamLogo` and rename `powerBiLogo` to `powerBILogo` to stay the same with office-ui-fabric-core.
IconNames in fabric-core is here:

https://github.com/OfficeDev/office-ui-fabric-core/blob/5385fe26a7d301975b35002559db4633407c0bfb/src/data/icons.json

### CODE REVIEW

**Comment by micahgodbolt** [comment]
How long has 'powerBiLogo' been in? This would be a breaking change for anyone using the original icon name. It might be best to deprecate the old one then add the new. @mikewheaton thoughts?

**Comment by mikewheaton** [comment]
It is technically a breaking change, so I suppose we should support both `powerBiLogo` and `powerBILogo`. There are going to be more of these coming up as developers switch from using the Fabric Core class names to Fabric React – I really wish we'd kept these consistent.

**Comment by dzearing** [comment]
This doesn't really matter when used in `Icon` via `iconName` which is case insensitive.

**Comment by betrue-final-final** [comment]
What is the difference between these two assets?

**Comment by qqli1209** [comment]
@dzearing 
As far as I know, `IconName` is case sensitive respect to this file:      https://github.com/OfficeDev/office-ui-fabric-react/blob/c4bb4fb265f4c40620110700b78186311e8b8063/packages/office-ui-fabric-react/src/components/Icon/Icon.tsx

In line 44, the `Icon` component gets the `iconMemberName` by conveting the first letter of `IconName` to lowercase and then uses `iconMemberName` to specify an icon. 

I'm working on clientSide web parts and when I try to change from using fabric-core to create icons to fabric-react, I find the `powerBiLogo` doesn't work because of the misspelling. This makes one web part icon in toolbox disappear. The other missing icon `streamLogo` also makes another web part icon disappear in toolbox. So I send the PR to fix the issue.

**Comment by qqli1209** [comment]
@mikewheaton 
It's a good idea to support both `powerBiLogo` and `powerBILogo`. I will add it in the PR.

**Comment by qqli1209** [comment]
@betrue-final-final 
As far as I know, this file includes all the icons in fabric-react:  https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Icon/IconName.ts

And this file includes all the icons in fabric-core: https://github.com/OfficeDev/office-ui-fabric-core/blob/5385fe26a7d301975b35002559db4633407c0bfb/src/data/icons.json

Fabric-react seems to have less icons in fabric-core， less than about 200 icons.

**Pull request merged**
