### PR TITLE
Resume size auditor check for master branch

### PR DESCRIPTION
**Pull request by aftab-hassan**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes
Add Size Auditor support back to `master`. The new updates to Size auditor require a field that takes in the source URL of the repository. This has been tested and verified against the `6.0` branch.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10307)

### CODE REVIEW

**Comment by aftab-hassan** [comment]
@kenotron, I had a question on how you discovered these variable names, `connectedServiceName`, `connectedServiceName` and `sizeTolerance` from the original `yaml`.

Did you look at the `task.json` file from the backend changes? It's only there I can find these names. I have added a new variable, and used the same name as in the `task.json`. Can share a link on IM if you'd like to take a look at the `task.json` I am referring to.

**Comment by aftab-hassan** [comment]
Marking this as `Do not merge`. I'd like to look over the numbers that are reported here.

**Comment by aftab-hassan** [comment]
> Does the url need a .git at the end like for cloning?

@kenotron, this URL is good enough; Size auditor does generate the report. Could we hold off on merging this PR until the morning? I have a `LightRail` fix that needs to go in.

**Comment by kenotron** [comment]
> > Does the url need a .git at the end like for cloning?
> 
> @kenotron Ken Chau FTE, this URL is good enough; Size auditor does generate the report. Could we hold off on merging this PR until the morning? I have a `LightRail` fix that needs to go in.

Yes this is fine to hold off - especially because of that label "do not merge" :)

**Comment by kenotron** [comment]
> @kenotron Ken Chau FTE, I had a question on how you discovered these variable names, `connectedServiceName`, `sourceVersionMessage` and `sizeTolerance` from the original `yaml`.
> 
> Did you look at the `task.json` file from the backend changes? It's only there I can find these names. I have added a new variable, and used the same name as in the `task.json`. Can share a link on IM if you'd like to take a look at the `task.json` I am referring to.

I dug pretty deep into your task.json code in SizeAuditor / LightRail src to find these :)

**Comment by aftab-hassan** [comment]
> I dug pretty deep into your task.json code in SizeAuditor / LightRail src to find these :)

ha, thanks @kenotron :)

ETA for this PR: < an hour. Waiting for deployment
image

**Comment by aftab-hassan** [comment]
@kenotron, @KevinTCoughlin, results look valid. I am going to go ahead and merge this PR.

**Pull request merged**
