### PR TITLE
Fabric 7.0: exporting fluent colors from the styling package.

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue:  Part of #8038 
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Exporting the fluent colors from the styling package. This goes against the `fabric-7` branch as part of making Fluent default in Fabric 7.0

@jdhuntington @dzearing  if I run `npm run change` it generates a rush change log for all the packages in our repo (15 logs). Do we need to include them here? If yes, what type they should be? Or we are just going to combine all the changes in one Major version release note?

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8171)

### CODE REVIEW

**Comment by phkuo** [comment]
What's the use case for these?

**Comment by Vitalius1** [comment]
@phkuo Not sure what are the use cases... it was a part of the plan to move the fluent to Fabric and maybe @Jahnp can comment on this.

**Comment by Vitalius1** [comment]
@dzearing @micahgodbolt @jdhuntington 
I get this error in both my outstanding PRs against the `fabric-7` branch. 

screen shot 2019-03-05 at 2 46 02 pm

Do we even need to run screener for this branch? Wouldn't running screener and accepting this new changes conflict with the PR we have against `master`?

**Comment by Jahnp** [comment]
@phkuo these are some of the new "static" colors from Fluent. They're not likely to be used in components or themes, but rather, consumed downstream for more specific cases. See the "colors" section of the Fabric preview site for reference: https://fluentfabric.azurewebsites.net/#/color/neutrals

**Comment by leddie24** [comment]
Just pinged @Vitalius1 on this PR; he's waiting for PR to get merged before updating this one.

**Comment by Vitalius1** [comment]
@phkuo @Jahnp are any objections in merging this PR?

**Comment by Vitalius1** [comment]
@dzearing can you take a look please as being the package owner? Thanks!

**Comment by Vitalius1** [comment]
@phkuo @dzearing I would prefer merging this PR with approval from the code owners of this package.
@Jahnp should we merge without the approval from the code owners?

**Comment by Vitalius1** [comment]
Thank you @dzearing for raising for correct questions in the Team chat regarding this addition. We discussed it briefly with @Jahnp and until further investigation will be done on the proper story behind these colors I am going to close the PR and return to it when a clearer picture.

**Pull request closed without merging**
