### PR TITLE
FocusTrapZone: Fixed FocusTrapZone to use the relatedTarget

### LINKED ISSUE #7891: Unable to check a checkbox within a Panel with scrollable content
Not sure if a bug or "works as intended", but I've noticed an issue with FocusTrapZone with Panel component when I upgraded to the latest version. Could not reproduce issue with 6.37.1, which was the version I was upgrading from. You need to explicitly set focusTrapZoneProps.forceFocusInsideTrap to false to be able to check a Checkbox within a scrollable panel. Is this a bug or an intended feature?

### Environment Information 
 
- __Package version(s)__: (6.133.0, latest) 
- __Browser and OS versions__: (Chrome 71.0.3578.98, FireFox 67.0a1 Nightly, Windows 10 1809)

### Please provide a reproduction of the bug in a codepen:

Create a Panel with enough content to make content scrollable. Add a Checkbox that you need to scroll down to be able to check. Try to check the checkbox with your mouse. You can check it via keyboard.

Example with reproduction guide in textfields:
https://codepen.io/anon/pen/wNeZbM
 
#### Actual behavior:
 
Trying to check the checkbox with a mouse will scroll the pane content back up and force focus to the first element. You are unable to check the checkbox with a mouse with Panel default focustrapzone properties.
 
#### Expected behavior:
 
You should be able to check the checkbox with a mouse.

#### Priorities and help requested:
 
Requested priority: (Low)

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7891
- [x] Include a change request file using `$ npm run change`

#### Description of changes

FocusTrapZone: Fixed FocusTrapZone to use the relatedTarget instead of document.activeElement to find what is losing focus. document.activeElement wasn't accurate in the case inside a popup + with scrolling and tabindex=-1 from a recent change

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/7906)

### CODE REVIEW

**Comment by dzearing** [comment]
just test on edge to make sure we're good

**Comment by kenotron** [comment]
Yup, works okay on edge!

**Comment by cliffkoh** [comment]
2 hours 40 mins to go :) (as long as it does its thing, it will definitely make it before next publish)

**Comment by JasonGore** [comment]
This PR was released in v6.135.0 and appears to be causing the regressions described by #7992 and #8011. I have [a CodePen](https://codepen.io/jasongore/pen/OdaJVR) that shows both of these issues occurring starting as of v6.135.0 but work fine in v6.134.0. (You can fork and modify the  Fabric version used in the CodePen to see.)

**Pull request merged**
