### PR TITLE
ContextualMenu: Implements onRenderMenuList for custom rendering of menu list (e.g. with header, footer or search)

### PR DESCRIPTION
**Pull request by basovic88**
PR following discussion with @micahgodbolt 

#### Pull request checklist

- [x] Addresses an existing issue: #6041 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

…react/issues/6041#issuecomment-415452796

* Added onRenderMenuList prop to ContextualMenu
* Added default _onRenderMenuList renderer with IContextualMenuListProps
* Updated docs with an example of onRenderMenuList implementation that adds a search bar

#### Demo of example implementation
Demo of custom onRenderMenuList

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
This looks awesome. The only thing missing is a change file. run `npm run change` and fill out the prompts. This will create a change file that you can commit into this PR. 

If you can drop in a quick screenshot of the demo you created that'd be great too.

**Comment by basovic88** [comment]
@micahgodbolt 

Done. Here is a demo of onRenderMenuList with the addition of a SearchBox:
Demo of custom onRenderMenuList

**Comment by micahgodbolt** [comment]
waiting for a passing build here.

**Comment by micahgodbolt** [comment]
@joschect while wait for a build, can you take a quick peak at this code.

**Comment by micahgodbolt** [comment]
Seeing as he already did the work to split out the interface into 'IContextualMenuListProps', splitting the MenuList into a component wouldn't be difficult. The main question is would it provide value? Would that menu list be used again somewhere else? How easy would it be to swap in a different component to render the entire list?

**Comment by basovic88** [comment]
@joschect @micahgodbolt . So what's the way forward here? Let me know if I need to do something. Naturally, I would like to see this approved as soon as possible -- it is of great value in our own application.

**Comment by joschect** [comment]
@basovic88 I think that this is probably good to go. I was more wondering why you chose this approach vs another. 

After thinking about Micah's response I don't think that this mini list would get used anywhere else so the iRenderFunction probably makes the most sense. I went ahead and approved but it looks like you have some build errors.

**Comment by micahgodbolt** [comment]
Yeah, lets stick with the onRender. the 'as' approach really helps when components need to be used 'in place' to maintain context with the rest of the component. I don't think thats an issue here. It's just a window into a renderable region of the component.

**Comment by micahgodbolt** [comment]
I'm not quite sure what's causing the build errors.  I'll kick off a new build

**Comment by micahgodbolt** [comment]
@basovic88 you might need to run a fresh build locally to track down this bug. `npm run build` Travis isn't helping us out there.

**Comment by basovic88** [comment]
Ok, this is weird, since I didn't change anything in the area where the error is coming from...

In `@uifabric/utilities` the build log shows the following Enzyme error multiple times:

```
 FAIL  src/initials.test.ts
  ● Test suite failed to run

    Enzyme Internal Error: configured enzyme adapter did not inherit from the EnzymeAdapter base class

      at validateAdapter (../../common/temp/node_modules/enzyme/build/validateAdapter.js:25:11)
      at merge (../../common/temp/node_modules/enzyme/build/configuration.js:27:38)
      at Object.<anonymous> (config/tests.js:125:1)
```

Enzyme seems to be configured okay. That is, cf. http://airbnb.io/enzyme/docs/installation/react-16.html.

Any help is appreciated.

**Comment by JasonGore** [comment]
I pulled your branch and was able to build. Maybe try another clone and see if you still have problems?

In any case the `packages/office-ui-fabric-react` package build is failing for two reasons:
- A test case doesn't have a matching snapshot. Running `npm run build` from `office-ui-fabric-react` or `npm run update-snapshots` from root will resolve. 
   - `src/components/__snapshots__/ContextualMenu.CustomMenuList.Example.tsx.shot`
- TS error:
```
src/components/ContextualMenu/examples/ContextualMenu.CustomMenuList.Example.tsx:3:1 - error TS6133: 'ContextualMenuItemType' is declared but its value is never read.

3 import { ContextualMenuItemType } from 'office-ui-fabric-react/lib/ContextualMenu';
```

**Comment by basovic88** [comment]
@JasonGore Thanks for checking. I fixed the unused import. But I can't get it to build. Still getting a ton of enzyme errors: via both `npm run build` and `npm run update-snapshots`.

I'm at a dead end here.

**Comment by JasonGore** [comment]
Have you been able to build before? Does master build? Did you try a new clone of your branch? Which version of Node do you have? (We've had most luck with LTS v8.11.1.)

**Comment by basovic88** [comment]
I did a fresh clone. Now, `npm install` gives the following error:

```
25321 verbose node v8.11.4
25322 verbose npm  v5.4.0
25323 error code E404
25324 error 404 Not Found: react-dev-utils@https://registry.npmjs.org/react-dev-utils/-/react-dev-utils-5.0.1.tgz
25325 verbose exit [ 1, true ]
```

**Comment by micahgodbolt** [comment]
Looks like tests are currently failing on missing snapshots. Since you added an example, we snapshot it. `npm run update-snapshots`

**Comment by basovic88** [comment]
@micahgodbolt @JasonGore  It worked! I was able to build and create the snapshot file. See my last commit. Should all be fine now.

(React-dev-utils had an issue today -- 5.0.1 was missing on npm -- fixed now -- that's why I couldn't build)

**Comment by micahgodbolt** [comment]
Ok, sorted out some screener issues. All set! Thanks for sticking this out and getting it across the line.

**Pull request merged**
