### PR TITLE
Allow focus on calendar month header button

### PR DESCRIPTION
**Pull request by phtucker**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

CalendarMonth header was not accepting focus. The conditional for TabIndex of the CalendarMonth header is no longer appropriate now that the year picker is fully implemented. This change has already been applied to office-ui-fabric-react Calendar component.

https://github.com/OfficeDev/office-ui-fabric-react/blob/0ce8390605a92ecb4ea748a7c70413b0df988d81/packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx#L145

#### Focus areas to test

date-time package DatePicker Calendar.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11278)

### CODE REVIEW

**Comment by evlevy** [comment]
Can you link to the fix in OUFR Calendar?

**Comment by jdhuntington** [comment]
Need a change file, generate by running `yarn change` in the root of the project on your branch locally.

**Comment by phtucker** [comment]
> Can you link to the fix in OUFR Calendar?

https://github.com/OfficeDev/office-ui-fabric-react/blob/0ce8390605a92ecb4ea748a7c70413b0df988d81/packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx#L145

**Comment by ecraig12345** [comment]
@lorejoh12 Does this change look okay to you?

**Comment by lorejoh12** [comment]
This is not the correct fix.

If you do this, and have the parameter `yearPickerHidden: true` (in CalendarMonthProps), the header button is going to be a tab stop even though there's no click functionality.

A better fix might be changing the check to what we have here: https://github.com/OfficeDev/office-ui-fabric-react/blob/46cb46c0e89d66e93db1989a8f29fbdad1451fa0/packages/date-time/src/components/Calendar/CalendarMonth/CalendarMonth.base.tsx#L117

`tabIndex: !!onHeaderSelect || !yearPickerHidden`,
for both the data-is-focusable and the tabIndex attributes.

**Pull request merged**
