### PR TITLE
CommandBar: Remove margin from command bar items

### LINKED ISSUE #2096: Remove margin between buttons in command bar
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by leddie24**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2096 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Remove the "0 4px" margin from command bar items

**BEFORE**:
screen shot 2017-06-29 at 1 56 51 pm

**AFTER**:
screen shot 2017-06-29 at 1 57 10 pm

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Can you drop in a before and after screenshot?

**Comment by leddie24** [comment]
Added screenshots to description

**Comment by annikanami** [comment]
@micahgodbolt I'm just getting my eyes on the screenshots here -- it seems like there's quite a bit of padding to the left of +New, is that in addition to the buttons?

**Comment by micahgodbolt** [comment]
This is the old command bar, if it isn't quite to spec, I have a new PR for the updated command bar  that I was sure to get to design's spec.

#2108

**Pull request merged**
