### PR TITLE
Expose dataIsFocusable prop to customize Focus for Details list rows 

### PR DESCRIPTION
**Pull request by RajeshGoriga**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Exposing dataIsFocusable prop to customize focus for Details list rows

(give an overview)

#### Focus areas to test

- Details list
- Details Row used components 

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10619)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
@RajeshGoriga, can you expand on what issue this PR is addressing to help with review?

**Comment by RajeshGoriga** [comment]
@KevinTCoughlin, 
The rows are getting focused through keyboard when we don't have checkbox's or any other input elements. 
To restrict the focus on non-accessible rows we are sending false through props, we have default value as true for this.
Work item id: https://office.visualstudio.com/OC/_workitems/edit/3502508

**Comment by KevinTCoughlin** [comment]
I'm thinking the attribute would be overridden ideally like this: https://codepen.io/kevintcoughlin/pen/jjjXap if we need to override it.

**Comment by aneeshack4** [comment]
@RajeshGoriga Pinging this hasn't been active for a couple days now - are you planning to responding to the alternative approach Kevin suggested?

**Comment by RajeshGoriga** [comment]
@KevinTCoughlin I have tried the solution which is provided by you. but no luck. The attribute is not overridden, why because it is assigned to true by hard coding.

**Comment by aneeshack4** [comment]
@KevinTCoughlin gentle ping to follow up with @RajeshGoriga so he can close out this PR

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin gentle ping to follow up with @RajeshGoriga so he can close out this PR

I've raised a PR containing an alternative approach.

**Comment by aneeshack4** [comment]
Thanks @KevinTCoughlin! I'll go ahead and close this one.

**Pull request closed without merging**
