### PR TITLE
Styling: Deprecate getFocusStyle, introduce getFocusStyles

### LINKED ISSUE #5525: Refactor getFocusStyle() arguments into a options object.
**Describe the feature that you would like added**

The function `getFocusStyle()` now has 7 arguments/options. 
https://github.com/OfficeDev/office-ui-fabric-react/blob/8afb6dcede9f9056357ce1d23e06197f458730c3/packages/styling/src/styles/getFocusStyle.ts#L20-L28
In order to change the last option, you need to put a lot of `undefined`s in, which starts turning into really ugly and hard to read code.
```js
getFocusStyle(theme, undefined, undefined, undefined, undefined, undefined, false)
```

Turning this into an options object would make it clearer to read and write, but would be a *breaking change*. I propose it be changed like so:

```js
export interface IGetFocusStyleOptions {
  theme: ITheme;
  inset?: number;
  position?: 'relative' | 'absolute';
  highContrastStyle?: IRawStyle;
  borderColor?: string;
  outlineColor?: string;
  isFocusedOnly?: boolean;
}

export function getFocusStyle( options: IGetFocusStyleOptions ): IRawStyle {
  const {
    theme,
    inset = 0,
    position = 'relative',
    highContrastStyle,
    borderColor = theme.palette.white,
    outlineColor = theme.palette.neutralSecondary,
    isFocusedOnly = true
  } = options;

  return {...}
}
```

This would turn the above example into:

```js
getFocusStyle({ theme: theme, isFocusedOnly: false })
```

**What component or utility would this be added to**

`getFocusStyle()`

**Have you discussed this feature with our team, and if so, who**

@phkuo 

**Additional context/screenshots**

https://github.com/OfficeDev/office-ui-fabric-react/pull/5399#issuecomment-403619784

### PR DESCRIPTION
**Pull request by jordandrako**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5525
- [ ] Include a change request file using `$ npm run change`
- [x] Replace all occurences of `getFocusStyle` with `getFocusStyles`

#### Description of changes

- Deprecate `getFocusStyle`
- Create `getFocusStyles`. **I'm open to ideas for a better name!** It functions the same but instead of all the options being arguments, they're moved to an options object.
- Make old `getFocusStyle` a wrapper for `getFocusStyles`

#### Focus areas to test

It should output the same styles regardless of which function is used as it did before, but there could be visual regressions hiding.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8096)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
CI seems to still be complaining about an outdated API file...

```shell
You have changed the public API signature for this project. Please overwrite etc/styling.api.ts with a copy of temp/styling.api.ts and then request an API review. See the Git repository README.md for more info.
```

**Comment by KevinTCoughlin** [comment]
This is interesting.. CI is complaining about the public API change, but this is targeted to Fabric v7, hrmm...

**Comment by dzearing** [comment]
I like it! Will come back once the build passes

**Comment by jordandrako** [comment]
I don't understand why the build is failing. Running `rush build` says the API is out of date, but when I run `npm run update-api` and it gets nothing new.

```
FAILURE (1)
================================
@uifabric/styling (18.61 seconds)
ts-jest[config] (WARN) Unable to find the root of the project where ts-jest has been installed.
ts-jest[config] (WARN) Unable to find the root of the project where ts-jest has been installed.
ts-jest[config] (WARN) Unable to find the root of the project where ts-jest has been installed.
ts-jest[config] (WARN) Unable to find the root of the project where ts-jest has been installed.
ts-jest[config] (WARN) Unable to find the root of the project where ts-jest has been installed.
You have changed the public API signature for this project. Please overwrite etc/styling.api.ts with a copy of temp/st
yling.api.ts and then request an API review. See the Git repository README.md for more info.
[14:02:00] x Error detected while running 'verify-api-extractor'
[14:02:00] x ------------------------------------
[14:02:00] x The public API file is out of date. Please run "npm run update-api" and commit the updated API file.     
[14:02:00] x ------------------------------------
[14:02:00] x finished 'build' in 16.01s with errors
[14:02:00] x Error previously detected. See above for error messages.
================================

[@uifabric/styling] Returned error code: 1

Error: Project(s) failed to build
rush build - Errors! (1 minute 49.6 seconds)
```

**Comment by ecraig12345** [comment]
@jdhuntington Any ideas about the build error in the comment above?

**Comment by KevinTCoughlin** [comment]
@jordandrako what's the status of this PR? Does `fabric-7` branch have the required changes for CI to pass or is this branch still blocked?

**Comment by dzearing** [comment]
@jordandrako closing this as it's become very outdated. Please re-open when you have the time.

**Pull request closed without merging**
