### PR TITLE
Make new news icon available

### PR DESCRIPTION
**Pull request by hjonasson**
#### Description of changes

Gives access to a news icon that exists on the CDN already.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11528)

### CODE REVIEW

**Comment by ecraig12345** [comment]
Thanks for the contribution! Two things:

1. If you're a Microsoft employee, please link your account at https://repos.opensource.microsoft.com/people (wish the CLA bot would make that option more obvious)

2. You'll need to add a change file by running `yarn change` (that's why the build is failing)

**Comment by hjonasson** [comment]
Thanks Elizabeth. I have done the account linking now.

 I ran yarn change but I get
[image: image.png]
what am I missing?

Cheers,

Hjortur

**Comment by ecraig12345** [comment]
You need to run `yarn change` in your local copy of your branch.

**Comment by ecraig12345** [comment]
The image didn't come through from email. Can you add it in a comment directly? (GitHub comments support drag/drop or copy/paste to upload images.)

**Comment by hjonasson** [comment]
Sorry for the late response. 

I think I made a mistake as I made my changes on the master of my fork, which yarn change then didn't take into account. I made a new PR from that branch.

https://github.com/OfficeDev/office-ui-fabric-react/pull/11611

**Comment by khmakoto** [comment]
Hi @hjonasson, if you made a new PR can you close this one? Thanks!

**Pull request closed without merging**
