### PR TITLE
Panel non modal

### PR DESCRIPTION
**Pull request by mattlind**
Added isModal switch for the Panel control.  Turns off the usage of the Overlay control (which effectively also disables lightDismiss).

Not sure if a the team wants a non-modal dialog example but I added that as well.

### CODE REVIEW

**Comment by Jahnp** [comment]
Approved

Sorry for the delay here. This change makes sense to me. Once you've addressed the conflicts, happy to merge this in.

**Comment by mattlind** [comment]
Thanks, almost gave up on this one. I will get it up to date.

**Comment by Jahnp** [comment]
Awesome, thanks for fixing the conflicts! I'll go ahead and merge once CI has finished.

**Comment by LarsLiden** [comment]
I just filed #3333.  Buttons outside the non-modal panel respond to hover events but not button clicks.  Without this, I'm not really sure what the purpose of a non-modal panel is.

**Pull request merged**
