### PR TITLE
Removed maximum Node version from rush.json

### LINKED ISSUE #3778: Type compilation failures on TypeScript 2.7 RC
### Bug Report

- __Package version(s)__: 5.29.2, 5.41.2
- __TypeScript version__: 2.7.0-dev.20180122

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking

Products/sites affected: Sway

#### Describe the issue:

When compiling with TypeScript 2.7's RC, we get:

```typescript
node_modules/office-ui-fabric-react/lib/components/Callout/Callout.types.d.ts:6:10 - error TS2305: Module '"C:/Code/My-Repo/node_modules/office-ui-fabric-react/lib/utilities/positioning"' has no exported member 'ICalloutPositionedInfo'.

6 import { ICalloutPositionedInfo } from '../../utilities/positioning';
           ~~~~~~~~~~~~~~~~~~~~~~


node_modules/office-ui-fabric-react/lib/components/Callout/CalloutContent.d.ts:6:10 - error TS2305: Module '"C:/Code/My-Repo/node_modules/office-ui-fabric-react/lib/utilities/positioning"' has no exported member 'ICalloutPositionedInfo'.

6 import { ICalloutPositionedInfo } from '../../utilities/positioning';
           ~~~~~~~~~~~~~~~~~~~~~~


node_modules/office-ui-fabric-react/lib/components/SpinButton/SpinButton.types.d.ts:3:10 - error TS2305: Module '"C:/Code/My-Repo/node_modules/office-ui-fabric-react/lib/utilities/positioning"' has no exported member 'Position'.

3 import { Position } from '../../utilities/positioning';
           ~~~~~~~~
```

Here's the corresponding `tsconfig.json`:

```typescript
{
  "compilerOptions": {
    "allowJs": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": [
      "es2015"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "outDir": "build/dist",
    "rootDir": "src",
    "strict": true,
    "strictFunctionTypes": false,
    "sourceMap": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es5",
    "pretty": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest"
  ],
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ]
}
```

### LINKED ISSUE #3825: Allow development with Node >= 9
```typescript
> office-ui-fabric-react-repo@1.0.0 _rushInstall C:\Code\office-ui-fabric-react
> node node_modules/@microsoft/rush/bin/rush install -c



Rush Multi-Package Build Tool 4.1.0 - http://aka.ms/rush



ERROR: Your dev environment is running Node.js version v9.4.0 which does not meet the requirements for building this
       repository.  (The rush.json configuration requires nodeSupportedVersionRange=">=6.9.0 <9.0.0")
```

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #3825

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3778

### CODE REVIEW

**Comment by Jahnp** [comment]
@nickpape-msft @dzearing thoughts on this? I'm not a rush expert, but my sense is we probably want to keep this restriction in place.

**Comment by JoshuaKGoldberg** [comment]
Why is it there? I tried building from scratch on node 9 and had no issues.

**Comment by pgonzal** [comment]
> I tried building from scratch on node 9 and had no issues.

The rush.json file specifies the range of NodeJS versions that are supported.  "Supported" means that people will get involved and help someone when they encounter a build failure.  Using a range implies that support will be offered for any NodeJS version in the range.

I have personally been involved in multiple costly investigations of mysterious errors, which turned out to be simply a buggy NodeJS release.  The "[Long Term Stable (LTS)](https://nodejs.org/en/download/releases/)" releases are pretty reliable, but in my experience the non-LTS releases frequently have serious issues.  When you support an ecosystem with many developers who are casually trying to build your repo, this support cost adds up quickly.

If people want to experiment with non-LTS NodeJS for their personal work, they should certainly be free to do that.  (Just comment out the line from rush.json.)  But I wouldn't recommend to commit that change to the master branch.

@nickpape-msft @Jahnp

**Comment by pgonzal** [comment]
That said, if you've decided to work in an unsupported state, it seems a little inelegant to have to keep editing rush.json every time you pull from master.  Maybe there should be a setting that allows you to permanently override the policy (and see a disclaimer reminding you that you're in an unsupported state).

If you feel strongly about it, you could [open a GitHub issue](https://github.com/Microsoft/web-build-tools/issues) to improve the Rush tool.

**Pull request closed without merging**
