### PR TITLE
Dismiss panel when clicking outside of the Panel component.

### PR DESCRIPTION
**Pull request by tacambridge**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Dismiss panel when clicking outside of the Panel component, when it does not take up the whole page (ex. when it has a top offset to not cover any top nav). In this case, we do not stop propagation.

#### Focus areas to test

Panel

### CODE REVIEW

**Comment by micahgodbolt** [comment]
@tacambridge is this an opt in behavior, or should this happen all the time?

**Comment by tacambridge** [comment]
I modified the behavior so that it is no longer opt-in, but by default, and will be enabled with isBlocking is true.

**Comment by micahgodbolt** [comment]
Going to run this again...The screener change has nothing to do with your changes

**Comment by Vitalius1** [comment]
@tacambridge why are you leveraging `isBlocking` prop when all it's doing is decide if we render a semi-translucent overlay next to the panel which has an `onClick` event listener for dismissing the panel if the `isLightDismiss` prop is set to `true`.

I believe a better way to go is just to do what you did now but without the check for the `isBlocking` inside the `componentWillReceiveProps`. Then have an optional new prop called `onOuterClick` which gives the host application the control on the decision what to do when clicking outside than just bluntly using `this.dismiss`. Instead you check `if` user provided a callback through this new prop than execute `else` dismiss it. And because `this.dismiss` is a public method of the Panel instance the host application could invoke it only if it passes it's conditionals.

@dzearing would like to hear your opinion...

**Comment by tacambridge** [comment]
@Vitalius1 my earlier iterations included the option to opt into dismissing the panel, but @micahgodbolt wanted to avoid the extra prop so I removed it. I'll discuss with him your proposition on adding an onOuterClick to override the dismiss.

If `isBlocking` is false, and the panel is shifted down, clicks on some parts of the page will be dismissable, and some won't without any visual cue (ie: the modal layer) leading to confusing inconsistencies.

**Pull request merged**
