### PR TITLE
Updating build

### PR DESCRIPTION
**Pull request by atneik**
Replacing old location of `fabric.min.css` in gulpfile with updated location of sass and css files. 

With core sass files in `/dist` of office-ui-fabric-react itself, consumers will not need to be dependent on office-ui-fabric for sass mixins and variables. This will be important for consistency in case a consumer and office-ui-fabric-react are on two different versions of [office-ui-fabric/office-ui-fabric-core](https://github.com/OfficeDev/office-ui-fabric).

### CODE REVIEW

**Comment by Jahnp** [comment]
Approved :minibus: 

Makes sense to me. Curious what @dzearing's thoughts are on this since it feels like it streamlines safe consumption of Fabric based on Fabric-React's dependency.

**Comment by dzearing** [comment]
Approved

I think i'm ok with this.

**Comment by dzearing** [comment]
Actually a few issues:

Affects build speed... Maybe we can fix the build to do diffing, but really this one is more like a new build task that should be something like "production only xcopy" that only happens on --production builds.

Affects deploy size. we'll be copying every time. Wonder if we can avoid that.

**Comment by atneik** [comment]
@dzearing updated to run postCopy only on --production. This should address the above issues.

**Comment by dzearing** [comment]
nice!

**Pull request merged**
