### PR TITLE
Fix typo in Shimmer Overview

### PR DESCRIPTION
**Pull request by adem**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Fixed a minor typo.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8635)

### CODE REVIEW

**Comment by atneik** [comment]
@adem you'll have to add the change file for `office-ui-fabric-react - PR` check to pass. This will help: [Change Files](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Change-Files)

**Comment by Vitalius1** [comment]
@adem can you enable run `npm run change` at the root of the repo so it generates a change log. We are blocked on this to be able to merge the PR. Or as an alternative, you can check this flag to allow us to push the change for you into your branch.
Screen Shot 2019-04-12 at 7 25 57 PM
Thanks for the fix!

**Comment by adem** [comment]
Apologies for the incomplete pull request - I just used the edit functionality on the website and wasn't aware of further necessary steps. Will take a look now...

**Comment by adem** [comment]
> can you enable run `npm run change` at the root of the repo so it generates a change log
I ran `npm run change` which yielded a JSON with the following contents:
```json
{
  "changes": [
    {
      "packageName": "office-ui-fabric-react",
      "comment": "Fix typo in Shimmer Overview",
      "type": "patch"
    }
  ],
  "packageName": "office-ui-fabric-react",
  "email": "adem.aydin@protonmail.com"
}
```
> Or as an alternative, you can check this flag to allow us to push the change for you into your branch.
The flag is already checked.

I hope this helps. I will make sure to open a proper pull request next time.

**Comment by Vitalius1** [comment]
@adem the json file generated will need to be committed and pushed to your branch so that the build can restart. This need to be a part of your PR. Sorry for not mentioning in my last message. 😊

**Comment by adem** [comment]
> @adem the json file generated will need to be committed and pushed to your branch so that the build can restart. This need to be a part of your PR. Sorry for not mentioning in my last message.

Got it!

**Comment by adem** [comment]
Is there anything I can do about the failed check "default"?

**Comment by Vitalius1** [comment]
I am sure it's because your branch is behind by a lot from the current master. You can pull a fresh master and merge it to your branch or rebase your branch of a fresh master. Then don't forget to push. I will meanwhile restart the build to see if it's just a bug.

**Comment by aftab-hassan** [comment]
> Is there anything I can do about the failed check "default"?

@adem please merge with master as @Vitalius1 says, and the new baseline should give updated bundle size numbers on this PR.

**Comment by Vitalius1** [comment]
@adem I see a master merge made by you 3 days ago but coincidentally that master was missing some baseline information that was caused by some other factors and another merge with the latest master should resolve this issue. Thanks for your cooperation so far 👍

**Comment by dzearing** [comment]
It looks like the conflicts above are because the edited section has been replaced with:

>If a smooth transition from Shimmer to content is desired, wrap the content node with a Shimmer element and use the `isDataLoaded` prop to trigger the transition. In cases where the content node is not wrapped in a Shimmer, use the `shimmerElements` or `customElementsGroup` props, and once data arrives, manually replace the Shimmer UI with the intended content. See the examples below for reference.

Which reads a bit better than the original. Closing this one, thanks though!

**Comment by adem** [comment]
Apologies for the delayed response. Though it was quite a hassle for a minor change, I learned about the process which will come in handy as I'll be using the docs a lot in the coming months.

**Pull request closed without merging**
