### PR TITLE
Combo box

### LINKED ISSUE #3613: ComboBox: useComboBoxAsMenuWidth should default to true
### Bug Report

- __Package version(s)__: latest

Are you willing to submit a PR to fix? (Yes, No) Yes 

Requested priority: (Blocking, High, Normal, Low)  Normal

Products/sites affected: (if applicable)

#### Describe the issue:

ComboBox recently gained the `useComboBoxAsMenuWidth` prop, which defaults to false. This regressed the ComboBox because anyone who does not provide this property has the Callout appear incorrectly sized.
This property should default to true

### PR DESCRIPTION
**Pull request by natalieethell**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #3613 
- [X] Include a change request file using `$ npm run change`
- [X] Microsoft Alias (if you have one): naethell

#### Description of changes

In ComboBox, useComboBoxAsMenuWidth should default to true, in case "dropdownWidth" is not provided.

### CODE REVIEW

**Comment by natalieethell** [comment]
Hey @jspurlin , I noticed you made the original changes to include useComboBoxAsMenuWidth. Could you take a look at this fix and let me know if it looks okay?

**Comment by jspurlin** [comment]
Why are we wanting to change the default behavior?

**Comment by natalieethell** [comment]
Hey @jspurlin the concern expressed in issue #3613 was that since dropdownWidth and useComboBoxAsMenu are both optional props, if neither of them are provided the calloutWidth would be undefined, leaving the Callout to appear incorrectly sized. 

Here is how the Callout looks currently:
image

Here is how the Callout looks with this fix:
image

**Comment by jspurlin** [comment]
I'm pretty sure there are consumers that expect the menu to not be the width of the comboBox. Can you just pass true for useComboBoxAsMenuWidth?

**Comment by natalieethell** [comment]
Ah, interesting. I'm curious, in what scenarios? For context, before useComboBoxAsMenuWidth was added, the default behavior for when dropdownWidth was not specified was to set calloutWidth to `this._comboBoxWrapper.clientWidth + 2`.
See line 824 of [this version](https://github.com/OfficeDev/office-ui-fabric-react/blame/d2d2548b5e4f03d1df2ec2e0fcafb20358ab1ad7/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx).

**Comment by natalieethell** [comment]
Discussed with @jspurlin offline. If we decided to make this change one day, it's a breaking change so it'd have to be in a major release. The current behavior seems fine, because users can get either behavior by passing in the right props.

**Comment by jspurlin** [comment]
and just a note, this would be a styling break from changing the default API value, not a build break change

**Pull request closed without merging**
