### PR TITLE
Upgrade prettier to latest 1.19.1

### PR DESCRIPTION
**Pull request by xugao**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes
- Upgrade prettier which includes [fix for optional chaining error](https://github.com/prettier/prettier/issues/6595)
- Fixed minor console log mistake in `prettier.js`
- Run `prettier --all` to fix all files in the repo

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11841)

### CODE REVIEW

**Comment by ecraig12345** [comment]
There will probably be some formatting updates with this new version, so it might be good to run prettier on all the files and check in any changes as part of this PR, to reduce noise in other PRs. (IIRC the command is `yarn prettier`.)

**Comment by JasonGore** [comment]
@ecraig12345 Doesn't prettier only run against files actually changed instead of against the whole repo? I'm not sure if it's worthwhile adding all of that noise to this PR.

**Comment by xugao** [comment]
@JasonGore @ecraig12345 - I kinda agree with Jason here. we can let people fix the error as we touch the files later. But honestly this change is not tooo bad/large. I am okay either way

**Comment by JasonGore** [comment]
I'm pretty sure most of these changes would have occurred regardless of the prettier bump. And some people just don't seem to have pre-commit hooks working for one reason or another, so the issue of files not being prettiered consistently will persist either way.

**Pull request merged**
