### PR TITLE
Color: Changing themePrimary / Communication Blue

### LINKED ISSUE #4025: Accessibility: Fix Contrast Ratio
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: NA

#### Describe the issue:
During the Keros testing of our page for accessibility, it was found that the "ms-link"s do not meet the contrast ratio required for accessibility.

#### Actual behavior:

Foreground: #0078d7 
Background: #ffffff 
Contrast ratio: 4.49 
Text size: 9.8pt (regular)

#### Expected behavior:

Regular text must have a contrast ratio of at least 4.5:1.

image
image

### PR DESCRIPTION
**Pull request by lynamemi**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #4025 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Our accessibility tool, Keros, was updated and themePrimary (aka Communication Blue) started failing accessibility tests due to the extra decimal (4.495:1). In response, the Microsoft corporate color palette medium blue a.k.a. Communication Blue has been updated from 0078D7 to 0078D4 to meet accessibility requirements.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by Jahnp** [comment]
Wow--I didn't realize how pervasive this specific HEX value was in this codebase. Very comprehensive PR--thank you! Looks great.

**Comment by betrue-final-final** [comment]
There seems to be some places with hardcoded hex values that need to be changed in another PR.

**Comment by Jahnp** [comment]
@betrue-final-final did you look at the diff? @lynamemi changed a ton of hard-coded values that showed up in specs, tests, and JSON files. Were there others in addition to what was changed here?

**Comment by betrue-final-final** [comment]
Just what I saw here. I was surprised. 
Yeah, when I have time or someone else does, we should look to see if that can be changed and where.

**Pull request merged**
