### PR TITLE
Leddie24/remove placekitten

### PR DESCRIPTION
**Pull request by leddie24**
Missed this in my past PR; removing placekitten from DetailsList marquee selection examples

### CODE REVIEW

**Comment by dzearing** [comment]
I don't really understand the motivation

**Comment by mikewheaton** [comment]
Approved 🐱 😸 😹

**Comment by ericthompson** [comment]
Usage of these assets requires attribution to the good folks who original shot the photos or provided their likeness. This PR helps us update to assets that are more acceptable for use by the project.

**Comment by dzearing** [comment]
Approved

**Pull request merged**
