### PR TITLE
Panel: update styles

### PR DESCRIPTION
**Pull request by maxwellred**
#### Pull request checklist

- [ ] Addresses a style update provided through a toolkit from Chris Wymer
- [x] Include a change request file using `$ yarn change`

#### Description of changes

This incorporates some of the changes proposed in #9578

The main change was allowing for the header to be on the same level as the close button (and the flex styles that went with it). To accomplish this I simply placed the header inside the classname "commands" container found in Panel.base.tsx. 

I converted a lot of the padding to margin since, to my understanding, it's more of a convention to use margin for the spacing of elements from other elements. I understand this might be breaking for some users so I can change it back if needed.

I removed breakpoints as since in a previous PR it was recommended that I don't add breakpoint determined style changes since it introduces an extra level of specificity for the user to overcome when custom styling.

Changed close IconButton  back to its native 32x32 height/width.

Changed the top border color of the footer to neutralLighter.

#### Header next to close button (BEFORE)
Screen Shot 2019-11-25 at 4 42 22 PM

#### Header next to close button (AFTER)
Screen Shot 2019-11-25 at 3 41 43 PM

#### Fixed close button styling (BEFORE)
Screen Shot 2019-11-25 at 4 41 46 PM

#### Fixed close button styling (AFTER)
Screen Shot 2019-11-25 at 3 41 19 PM

#### Footer top border color changed (was originally transparent)
Screen Shot 2019-11-25 at 3 42 24 PM

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11309)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
I'm concerned of how much of a breaking change this will be for some partners who have customized the Panel. 

1. Please communicate this change out as much as possible to all partners (Fabric alias, teams etc)
2. Please add a pre-deprecated prop like "legacyHeader" to support the original design with header content above the scrollable content. This will give users a way to support their existing designs.

**Comment by maxwellred** [comment]
@micahgodbolt Great, I'll get on that!

**Comment by maxwellred** [comment]
@micahgodbolt I've pushed in an update to the Panel component following what we discussed about moving the new header styles over to a separate component. I had to keep the content and footer styles in the Panel component which, unfortunately, meant keeping the useLegacyHeader prop on IPanelStyleProps. Lastly, I made the original header the default so there shouldn't be any breaking changes for partners/users.

**Comment by micahgodbolt** [comment]
@maxwellred can you schedule a 30 minute walkthrough of this change, how it affects existing panels, and how consumers will adopt these new changes?

**Comment by aneeshack4** [comment]
Great idea @micahgodbolt @maxwellred I think that's the quickest way to go over these changes & get them reviewed/merged

**Comment by micahgodbolt** [comment]
Max is working on a new approach here after our talk yesterday. I'll close this up for now. @maximus12793  please feel free to re-open when you're ready for review.

**Comment by maxwellred** [comment]
Closing in favor of #11391

**Pull request closed without merging**
