### PR TITLE
Experiments: reorganize folder structure of Fluent project

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Include a change request file using `$ npm run change`

#### Description of changes
Reorganize folder structure of the Fluent project inside the experiments package as the the styles file starts growing.

### CODE REVIEW

**Comment by Vitalius1** [comment]
@mikewheaton this one needs to be reviewed and merged quick so we can start working on the rest of the components without having to resolve conflicts.

**Comment by Vitalius1** [comment]
@cliffkoh @kenotron 
Question to you to confirm this split into separate files. If `FluentStyles.ts` file imports `ComponentA.styles.ts` and `ComponentB.styles.ts` which are both importing `FluentColor.ts`, will webpack tree-shaking make sure we end up with using it once or we end up with an increased size of the bundle?

**Comment by kenotron** [comment]
the require cache would take care of this.

**Comment by Vitalius1** [comment]
Thanks Ken. So we should not worry about the bundle size then!

**Comment by mikewheaton** [comment]
As discussed on Teams, @JasonGore is working on a PR that will move all of the styles into a separate package. I don't think we should merge this PR or we'll risk having all kinds of merge conflicts. Once Jason's PR goes through, could you split apart the styles as you've done here in the new package?

**Comment by Vitalius1** [comment]
Closing this one as there is a PR moving these to a separate package and would cause lots of conflicts to resolve.

**Pull request closed without merging**
