### PR TITLE
Remove suggestion item button padding

### PR DESCRIPTION
**Pull request by amyngu**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ x] Include a change request file using `$ npm run change`

#### Description of changes

Remove padding, so consumers have full control of suggestion item render

### CODE REVIEW

**Comment by micahgodbolt** [comment]
can you give some before and after screenshots. it doesn't appear we have visual tests on this component.

**Comment by amyngu** [comment]
@micahgodbolt for consumers of this component that want to render their component with certain hover states, we see something that could look like the following:
image
This change would make it so that the render for suggestedItems can be fully customized by the consumer to fill the whole row:
image

**Comment by amyngu** [comment]
@micahgodbolt can you take another look at this?

**Comment by micahgodbolt** [comment]
yeah, it's all in experiments anyway. no problem.

**Pull request merged**
