### PR TITLE
Slider: Support scenario where min and max are the same value

### LINKED ISSUE #6639: Slider misbehaves when min equals max
### Bug Report 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)- Yes
 
Requested priority: (Blocking, High, Normal, Low) - Normal
 
Products/sites affected: (if applicable) - Vsts
 
#### Describe the issue:
 
We are using slider where our max is a dynamic value and min is set to 1. The issue occurs when max = 1 as well. The slider bar becomes invisible.
 
#### Actual behavior:
 The slider bar becomes invisible.
image

 
#### Expected behavior:
 The slider handle should stay at extreme left and movement should not be allowed

### PR DESCRIPTION
**Pull request by SumiranAgg**
fixes #6639

### CODE REVIEW

**Comment by gregdardis** [comment]
Hey SumiranAgg,

Could you please fill out the [pull request template](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/.github/PULL_REQUEST_TEMPLATE.md#pull-request-checklist) and make sure you include a changefile with `npm run change`? This makes things much easier for the maintainers, who I imagine are very busy.

Thank you for the contribution!

**Comment by micahgodbolt** [comment]
@SumiranAgg as greg said, this PR is missing a change file. You can create one by running `npm run change` and committing the created file.

Secondly, can you please add a visual regression test for this situation. You can do that by going into slider.stories.tsx and using addStory with a slider with min and max of 1.

**Comment by SumiranAgg** [comment]
Made changes as suggested.

**Comment by mikewheaton** [comment]
@betrue-final-final, could you review the Screener changes here? The Slider position matches what you showed in the issue, but should it also be disabled? Right now it's enabled but I don't think it could be moved.

**Comment by betrue-final-final** [comment]
@micahgodbolt and @mikewheaton, that's the peculiarity of this particular situation. The slider is actually not disabled, but has a dynamic value for the points. In this state, it only has one point, but could dynamically grow to 2 or 3 points with a refresh, or server push. That is why I keep the thumb "enabled". I can ask for other designer thoughts as well, but the control isn't disabled, just stymied.

**Comment by micahgodbolt** [comment]
@betrue-final-final I actually agree with 'enabled'. So I'm good to keep it as is.

**Comment by mikewheaton** [comment]
Sounds good! @betrue-final-final, I'll merge this PR as soon as you've approved the Screener tests.

**Pull request merged**
