### PR TITLE
Choicegroup: Improved states for focus, HC focus, HC hover

### LINKED ISSUE #3621: [ChoiceGroup][Accessibilty] Difference b/w focused and non foucsed element is not distinguishable
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) : Normal

Products/sites affected: (if applicable): VSTS 

#### Describe the issue:

Difference b/w focused and non focused choice group item is not easily distinguishable.  See Image below
image
Although the  border width is increased by 1px but it is very hard to distinguish.

#### Actual behavior:

Not able to distinguish focused and non focused items

#### Expected behavior:

Focused and Non focused choice group item should be easily distinguishable. We make make the border dotted in high contrast. That should work 

### If applicable, please provide a codepen repro:

https://developer.microsoft.com/en-us/fabric#/components/choicegroup

### PR DESCRIPTION
**Pull request by lynamemi**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #3621 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Focus + Hover (with image / icon):
cg-nonhc-focus-hover

Focus:
cg-nonhc-focus

Hover:
cg-hover-default

HC Focus + Hover:
cg-focus-hover

HC Focus:
cg-focus

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by betrue-final-final** [comment]
What's the one with the simple radio buttons? Which has hover?

**Comment by lynamemi** [comment]
@betrue-final-final, the top one has hover. Yellow is the resting state.

**Comment by manishgarg1** [comment]
Looks good to me. @betrue-final-final ?

**Comment by betrue-final-final** [comment]
The top choice is a hover, or is hover over the dropdown? If it's the radio, I'm confused. Let's chat quick tomorrow AM.

**Pull request merged**
