### PR TITLE
make global class names for base button optional

### LINKED ISSUE #6276: Buttons don't respect the disableGlobalClassNames flag
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/VincentBailly/pen/KxyVZX

### Bug Report 
 
When using the customization with a theme that has { disableGlobalClassNames: true }, I expect the Action to not get all the global class names (like .ms-button)
- __Package version(s)__: 6.7.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High
 
Products/sites affected: LPC
 
#### Describe the issue:
 
Action button does not respect the option to not inject global class names
 
#### Actual behavior:
 
ActionButton has the class names .ms-button, .ms-label...
 
#### Expected behavior:
 
ActionButton does not have global class names

### PR DESCRIPTION
**Pull request by VincentBailly**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6276 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This PR makes the Base button respect the option to opt-out of using global class names

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
This will need a change file, but otherwise (assume tests pass) this looks fine.

**Comment by micahgodbolt** [comment]
looks like a tiny regression in the icon pressed state

image

the icon color isn't the darker blue

**Comment by micahgodbolt** [comment]
trying to determine why the $reference isn't working for the icon, but is for things like description

**Comment by micahgodbolt** [comment]
Options are:
1. find a fix (might be in mergeStyles somewhere)
2. leave those selectors using the global classNames. This won't break current users but you'd lose out on those styles if you suppressed those classnames
3. use some other selector for targeting those styles (data attribute maybe?) so lack global classnames won't affect them

**Comment by micahgodbolt** [comment]
Happy with this @cliffkoh ?

**Comment by VincentBailly** [comment]
The reformating from prettier adds some noise to the PR.
I had to change this snapshot, the updated version seems correct, I am not sure why this change happens.
image

**Pull request merged**
