### PR TITLE
Icon: add ability to show overlays

### PR DESCRIPTION
**Pull request by KatherineThayerMicrosoft**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

We would like to be able to place overlays on icons. For example, an overlay on top of a file type icon could indicate a checked out file. I have added the optional overlayName property to Icon and also added four possible overlays to the file-type-icons package.

#### Focus areas to test

(optional)

#### Screenshot of examples
overlays

### CODE REVIEW

**Comment by micahgodbolt** [comment]
can you add some screenshot examples in this PR?

**Comment by micahgodbolt** [comment]
Also, can you go to `apps/vr-tests/src/stories/icon` and update this file with examples of these new styles. This will create baselines that we can visually test against in future updates.

**Comment by micahgodbolt** [comment]
what was the decision with this PR? Are we going to close this and come up with a different approach?

**Comment by micahgodbolt** [comment]
I'll close it for now. Open it back up if needed, once conflicts are resolved.

**Comment by KatherineThayerMicrosoft** [comment]
Hi Micah, thanks for closing the PR. Design is moving away from using overlays on file type icons, so we are not going to add this ability after all.

**Pull request closed without merging**
