### PR TITLE
Fix DetailsList width given nested groups (#5857)

### LINKED ISSUE #5857: DetailsList header and rows exceeds DetailsList
### Bug Report 
 
- __Package version(s)__: (fill this out) 6.41.1
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) If I have time 
Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) 
 
#### Describe the issue:
The width of DetailsList header and rows  exceeds the width of the entire DetailsList

#### Actual behavior:
 The width of DetailsList header and rows  exceeds the width of the entire DetailsList

#### Expected behavior:
 The width of header and rows should be the same as the width of the DetailsList
 
### If applicable, please provide a codepen repro:
https://codepen.io/anon/pen/rrQMOx?editors=1111
It doesn't clearly reproduce on codepen. Please check the screenshot attached here.
I did some triage and I found the width GroupSpacer in the header and rows might be the root cause. 
If I decrease the width of the GroupSpacer the issue get fixed. We calculate the width of GroupSpacer by groupNestingDepth. I think this part causes the issue.

issue

### PR DESCRIPTION
**Pull request by jeffersonking**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5857
- [x] Include a change request file using `$ npm run change`
  ERROR: Command failed: git diff upstream/master... --dirstat=files,0
       fatal: ambiguous argument 'upstream/master...': unknown revision or path not in the working tree.

#### Description of changes

DetailsList width calculation is not currently taking into account grouping depth >1. This fixes that.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by JasonGore** [comment]
Needs a change file.

**Comment by jeffersonking** [comment]
Anyone have a tip on how to get `npm run change` working? Is there a way to point it to a commit? Thanks!

**Comment by JasonGore** [comment]
If you run it from root directory on this PR's branch, it should automatically detect the changes for you... if it doesn't run correctly, you may have to run `npm install` to get the proper dependencies. If you still have trouble, I can generate it for you as well.

**Comment by jeffersonking** [comment]
I got `npm run change` to work and attached is the output JSON. It doesn't seem to contain information that isn't available already. Is this correct? Thanks.

[issue5857_2018-08-17-18-09.json.txt](https://github.com/OfficeDev/office-ui-fabric-react/files/2298267/issue5857_2018-08-17-18-09.json.txt)

**Comment by JasonGore** [comment]
Yep! It's just a delta regarding your change that's used for publishing. Just add and commit from the location where it was originally created (should be in a subdirectory under `common`.)

**Comment by jeffersonking** [comment]
@JasonGore or @KevinTCoughlin. Looks like this just needs a reviewer stamp and the "default" check to get approved? Any chance you guys could help? Thanks!

**Comment by KevinTCoughlin** [comment]
@jeffersonking what's the best way to see a GroupedList with the width calculation issue? The change makes sense, but I'm trying to better understand why the nested example we have in the docs isn't affected by it since it is nested three levels deep. This Codepen seems the same between `master` and this branch -- https://codepen.io/kevintcoughlin/pen/pOoLJK?editors=1111

**Comment by jeffersonking** [comment]
@KevinTCoughlin You need two things simultaneously: 1) 2+ levels of grouping depth, 2) header columns. The DetailsList docs don't have #1. The GroupedList docs don't have #2.

I can't speak for the Codepen but here is my repro:

```
import * as React from 'react'
import {DetailsList, DetailsListBase, ConstrainMode} from 'office-ui-fabric-react/lib/DetailsList'
import {SelectionMode} from 'office-ui-fabric-react/lib/utilities/selection/index'

export class Repro extends React.Component<any> {
	render() {
		const items = [{ },{ },]
		const groups = [
			{ key: 'a', name: 'Aaa', level: 0, startIndex: 0, count: 2, children: [
				{ key: 'b', name: 'Baa', level: 1, startIndex: 0, count: 2 }
			] }
		]
		const columns = [
			{ minWidth: 300, key: 'snippet',  name: 'Details' },
			{ minWidth: 120, key: 'build',    name: 'First discovered'},
			{ minWidth: 80,  key: 'bug',      name: 'Bug'},
			{ minWidth: 60,  key: 'hitcount', name: 'Hit Count'},
		].map((col: any) => ({
			...col,
			onRender: (item => 'Lorem ipsum dolor sit amet'),
		}))

		return <DetailsList
			items={items}
			groups={groups}
			groupProps={{ showEmptyGroups: true, }}
			constrainMode={ConstrainMode.unconstrained}
			compact={true}
			columns={columns}
			selectionMode={SelectionMode.multiple}
			/>
	}
}
```

**Pull request merged**
