### PR TITLE
Button: Support expanded styles for contextual buttons

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by betrue-final-final** [comment]
Looks great! Just one update. The split button arrow part needs the pressed state. It currently shows hover, but not pressed.
image

**Comment by betrue-final-final** [comment]
Just spoke with Micah. The split button is out of scope for his fix, so should be handled in a different bug.

**Comment by micahgodbolt** [comment]
@betrue-final-final i took a crack at the split button and it wasn't too hard.

Check it out

image

**Comment by betrue-final-final** [comment]
SOOO close! So awesome. We're just using the hover color for the pressed state. Just need to change that to the pressed state.
Also we have some colors that don't quite match. Pressed and Pressed hover don't match with the spec.

image

**Comment by micahgodbolt** [comment]
We don't support just a single dropdown button, but rather all buttons support being a dropdown. Unfortunately there is a difference between default button (pressed color C8C8C8) and the pressed color of the dropdown button example (DADADA) which makes it difficult to reconcile. 

There's also the question of how expanded and expanded/hover would look with a primary button, as that is not specified either. 

I'd like to get this current branch in, as it gets us closer to expected design. Then we need to sit down and reconcile buttons in XD with the approach we use for building them.

**Pull request merged**
