### PR TITLE
Tayoun/commandbar items onrender

### PR DESCRIPTION
**Pull request by RegexEmpire**
#### Pull request checklist

- [ ] Addresses an existing issue: #0000
- [ ] Include a change request file if publishing 
- [ X ] New feature, bugfix, or enhancement
- [ ] Includes tests
- [ ] Documentation update

#### Description of changes
Adding support for IContextualMenuItem onRender in CommadBar. This will enable support for a menu item to render items other than a div or button, such as a SearchBox. This is necessary with the deprecation of the built in SearchBox.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
@RegexEmpire `tslint - src/components/CommandBar/CommandBar.tsx(178,9): error one-line: misplaced 'else'`

**Comment by micahgodbolt** [comment]
```
if () {
} else if () {
}
```

**Comment by RegexEmpire** [comment]
@micahgodbolt 
Hey Micah, updated the tslint issues. Let me know if there is anything else you would like updated.

Thanks,
Taylor

**Comment by micahgodbolt** [comment]
@RegexEmpire how desperate are you for this change. I'm actually in the middle of updating our BaseButton to support using it inside of the command bar. I'm hesitant to expose a larger API surface not knowing what changes need to be made. For instance, renderItemInCommandbar currently takes an item of type IContextMenuItem. This will probably be changing to button, so supporting your need to add search might need to happen elsewhere (possibly a level up).

**Comment by RegexEmpire** [comment]
@micahgodbolt I was creating an extension for another app that I work on. In this app we have a very common experience of having (our version of) a command bar with add and then search in the farItems side. 

I've already worked around the issue by not using command bar and just having a button and search box with styling. I'm fine abandoning the request. While investigating why the searchBox wasn't working, I found a fix and submitted it since it was low effort on my part. Waiting for refactoring makes sense if this is all changing.

Thanks,
Taylor

**Pull request closed without merging**
