### PR TITLE
CommandBar: a11y remove role = presentation

### LINKED ISSUE #11039: OverflowSet inside of CommandBar uses aria-orientation, even though role is set to 'presentation'
### Environment Information

- **Package version(s)**: office-ui-fabric-react v7.42.0
- **Browser and OS versions**: Microsoft Edge v79.0.305.0

### Describe the issue:

CommandBar currently creates an OverflowSet and passes in the role of "presentation", you can see this [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx#L108).

OverflowSet though will set a aria-orientation tag of either vertical or horizontal, you can see this [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/OverflowSet/OverflowSet.base.tsx#L59).

Using aria-orientation with an element who's role is "presentation" is incorrect, as per this W3 document: https://www.w3.org/TR/wai-aria-1.1/#aria-orientation

aria-orientation should only be used with the following roles:

- scrollbar
- select
- separator
- slider
- tablist
- toolbar
- combobox
- listbox
- menu
- menubar
- radiogroup
- tree
- treegrid

This error get's flagged by axe-core, as breaking the aria-allowed-attr rule (https://dequeuniversity.com/rules/axe/3.3/aria-allowed-attr).

#### Actual behavior:

aria-orientation is used with role="presentation".

#### Expected behavior:

role should probably be the default role for an OverflowSet, i.e. "menubar".

### Documentation describing expected behavior

https://www.w3.org/TR/wai-aria-1.1/#aria-orientation

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #11039
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Removal of role={'presentation'} in CommandBar implementation of Overflow 

#### Focus areas to test

Tested with Windows + Narrator and showed no adverse effects

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11224)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
created this PR to see if I had the same snapshot issues as #11107

**Comment by micahgodbolt** [comment]
snaps sadly look the same. will keep an eye on the build

**Comment by maxwellred** [comment]
Interesting and thanks for trying this as I was about to close my PR and see if opening a fresh branch would've done the trick....guess not

**Comment by micahgodbolt** [comment]
so frustrating. this builds just fine locally

**Comment by khmakoto** [comment]
Can we close #11107 if this goes in?

**Comment by micahgodbolt** [comment]
turning off a bunch of experiment tests, and seeing if this will go thorugh

**Comment by micahgodbolt** [comment]
@maximus12793 it's passing, it's passing!

**Comment by micahgodbolt** [comment]
@khmakoto do you think we need to keep those experimental button tests around? I can just remove them vs commenting them out. they were causing flickers

**Comment by khmakoto** [comment]
@micahgodbolt since we're not planning on shipping the experimental Button anymore I guess it's fine if we remove them. Worst case scenario we can look at the history and bring them back.

**Comment by maxwellred** [comment]
@khmakoto I'll close mine and let this one handle it. Woooo!

**Pull request merged**
