### PR TITLE
Firefox: HighContrast fixes: Pivot, Checkbox and choicegroup

### LINKED ISSUE #1944: Pivot: underline not visible in High Contrast mode + firefox
### Bug Report

- __Package version(s)__: 2.34.2
- __Browser and OS versions__: Windows 10 + FireFox

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: VSTS (CI/CD)

#### Describe the issue:

Many high contrast styles are not visible in FireFox, 
1. Underline does not appear for pivot.
Same issue got fixed for other browsers - https://github.com/OfficeDev/office-ui-fabric-react/issues/1183.
2. Selection of choice group not visible.
3. Check-box styles are different.

#### Actual behavior:
In High-Contrast + FireFox:
Pivot Tab does not have underline.
Choice group selection is not visible
Check box style is different

#### Expected behavior:

Underline should appear on selected pivot tab. Styles should be similar to edge/IE in high contrast.

### If applicable, please provide a codepen repro:

Open https://dev.office.com/fabric#/components/pivot in high contrast + FireFox.

### PR DESCRIPTION
**Pull request by mdahamiwal**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1944, #1955, #1946 
- [x] Include a change request file using `$ npm run change`

#### Description of changes
**Issues**:
1. Firefox doesn't understand `-ms-high-contrast` attributes and doesn't support various high contrast colors like IE11 and Edge. Instead it only translates colors in normal mode to two high contrast mode colors, (white/black, yellow/black, black/white). Due to the color palette limitation there is no way to convey "disabled, selected" colors like available in Edge and IE11.
 
2. There is limitation that backgrounds will not be mapped to any high contrast mode due to which components like choicegroup and pivot that make use of background color will not be rendered properly in firefox.

While we can't do anything about `#1`, this changes fixes `#2` for three components on firefox:

1. Checkbox (before/after fix)

image

image

2. Choicegroup
image

image

3. Pivots
image
image

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by betrue-final-final** [comment]
Have you tested this in Edge to make sure you didn't break that? Can we see screenshots?

**Comment by mdahamiwal** [comment]
Yes, I have tested on Edge as well. following are the screenshots:

1. Checkbox (before/after fix)
image


2. 
image

3. Pivots
image

**Comment by betrue-final-final** [comment]
Great. Thanks!

**Comment by mdahamiwal** [comment]
@dzearing, @micahgodbolt  can we get this merged? Thanks

**Pull request merged**
