### PR TITLE
Do not update unmounted BaseFloatingPicker

### PR DESCRIPTION
**Pull request by Adjective-Object**
#### Pull request checklist

- ~~[ ] Addresses an existing issue: Fixes #0000~~
- [x] Include a change request file using `$ npm run change`

#### Description of changes

If a base floating picker is unmounted before its promise resolves, it will throw an error in the console (repros on demo)

This PR tracks the mounted / unmounted state of the component and does not update the state if it is no longer mounted

#### Focus areas to test

FloatingPeoplePicker

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8399)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
@Adjective-Object is it possible to infer state of the component without a boolean?

What about canceling the promise on `componentWillUnmount`?

**Comment by Adjective-Object** [comment]
@KevinTCoughlin Do we have cancellable promises set up in Fabric? I've not seen them used anywhere. I didn't feel comfortable making the call to add the dependency since es6 promises aren't cancellable by default.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin Do we have cancellable promises set up in Fabric? I've not seen them used anywhere. I didn't feel comfortable making the call to add the dependency since es6 promises aren't cancellable by default.

I'm unsure. If you haven't seen them then they are likely not available. If there's no alternative to the `boolean` it seems OK to me. I was mostly asking if there are patterns for this within React for my own knowledge.

**Comment by Adjective-Object** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/blob/bd191a3964734c6619fa49fcdb1d6127e2834522/packages/utilities/src/Async.ts
supports setTimeout / requestAnimationFrame against a component's lifecycle, but I don't see anything for promises bound to a component's lifecycle. Maybe it would make sense to add some `this._async.promise(somePromise)` that returns a new promise that only completes if a component is still mounted when the inner promise resolves. @dzearing thoughts?

**Comment by KevinTCoughlin** [comment]
@Adjective-Object I think you need to run and commit the output of `npm run update-api` for CI to pass. Then we can merge.

```shell
You have changed the public API signature for this project. Please overwrite etc/office-ui-fabric-react.api.ts with a copy of temp/office-ui-fabric-react.api.ts and then request an API review. See the Git repository README.md for more info.
```

**Comment by KevinTCoughlin** [comment]
@Adjective-Object can you merge latest `master` and run `npm run update-api` for CI to pass so we can merge this fix?

**Pull request merged**
