### PR TITLE
[MDL2]: ContextualMenu

### PR DESCRIPTION
**Pull request by atneik**
- Updating example Icons
- Aligning new Icons
- Changing expanded item background

screen shot 2016-08-03 at 7 34 29 pm

### CODE REVIEW

**Comment by dzearing** [comment]
This looks good. However just a MASSIVE HEADS UP: when we merge this change into other products that don't use the fabric icon fonts and have their custom built ones, we will need to update those things just to consume this. We probably want to link OneDrive and scrub the font there before we merge this back into master.

**Comment by dzearing** [comment]
Approved

**Comment by dzearing** [comment]
Honestly I would soooo much prefer not renaming the icons. Or having a shim solution to have 2 names. It isn't really scalable to rename without a friendly transition workflow.

e.g.
if ms-Icon--plus is renamed to ms-Icon--Plus, we should define the css as:

.ms-Icon--plus,
.ms-Icon--Plus {
...
}

Then all of this work you're doing to scrub icon names would only be cleanup and not mandatory.

**Comment by atneik** [comment]
@dzearing We might not need to scrub the font names in our all of our products. I'm not sure about OneDrive @Jahnp might know better. But for sp-client as most of the Icons being used are already using MDL2 font icon names, the transition should be seamless. 

I think for a easy transition for all consumers we could have both icon fonts available in fabric-core (MDL2 and Office365). Eg: .ms-Icon--plus using a glyph from Office365 font, while .ms-Icon--Plus using it from MDL2.

**Comment by mikewheaton** [comment]
Unfortunately there's not always a direct one-to-one mapping between icons from the Office365 set to the MDL2 set. So while we could support the old class names in many cases, some apps will still break. This is why we've made the icon change in a major version (3.0.0) of Fabric Core. Even where the icons are similar, the difference in line weight means we often have to adjust their size. It's not a clean swap.

**Comment by atneik** [comment]
@mikewheaton Agree there is no clean swap. Different name protects us in a way.

But, think about a consumer who is still using Office365 set and wants to use the MDL2 version of Fabric-react. That will be a breaking change for them as Office365 set won't be available; they would first need to swap and adjust all icons to MDL2 and then only they would be able to consume Fabric-react MDL2. 

While, if both icon sets are available (at least for some time), this won't limit them to have Fabric-react MDL2. And they will have time to switch and adjust MDL2 icon set.

**Pull request merged**
