### PR TITLE
fix typo in CommandBar example

### PR DESCRIPTION
**Pull request by danmarshall**
Hello, this is just a fix for a small typo in an example.

### CODE REVIEW

**Comment by Vitalius1** [comment]
@danmarshall you would need to `npm run change` from the root of the repo and follow the prompts to create a rush change file. Then commit and push. Otherwise, the build is failing. Thanks for the typo fix!

**Comment by micahgodbolt** [comment]
Docs update looks fine. Really doesn't need a change file as it isn't triggering a new release. I'll push it through.

**Comment by Vitalius1** [comment]
@micahgodbolt 
I believe this needed a patch type change file. @Jahnp mentioned that the fabric website ties into OUFR releases. And the example is something we show on the website. Although, don't know if we are updating the website right now and there will be other changes that will patch the OUFR before we update it.

**Comment by danmarshall** [comment]
Not sure if I need to do anything or not, now this was merged.
I created the change file fwiw - not sure where to put it. Here is the contents:

```json
{
  "changes": [
    {
      "packageName": "office-ui-fabric-react",
      "comment": "fix typo in commandbar example",
      "type": "patch"
    }
  ],
  "packageName": "office-ui-fabric-react",
  "email": "danmar@microsoft.com"
}
```

**Pull request merged**
