### PR TITLE
Beak Position Fix

### PR DESCRIPTION
**Pull request by andrewhwng**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes
This is a patch related to PR #7778, which caused beak displacements on dynamically sized Callouts.

_Previously:_ Position anchoring was only applied to the Callout box itself but not the beak. Dynamically sized Callouts would grow correctly, but the beak would be anchored to the incorrect edge, causing it to move away from the target.

_Now:_ This update re-anchors the beak to the correct edge so dynamically sized Callouts do not change the beak position.

#### Focus areas to test

General Callout & beak placement behavior should not change at all.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8370)

### CODE REVIEW

**Comment by joschect** [comment]
@andrewhwng Great fix! Thanks for putting this in! If possible could you add a test case for this as well so we can catch this if it regresses it? The positioning unit tests are probably the right place to put it.

**Comment by KevinTCoughlin** [comment]
Adding a test would be rad as it seems like we've already regressed this behavior

**Comment by andrewhwng** [comment]
@joschect @KevinTCoughlin Thanks for the feedback! I added a new case in case to test the finalized beak position, rather than the finalized position of the Callout.

**Comment by KevinTCoughlin** [comment]
> @joschect @KevinTCoughlin Thanks for the feedback! I added a new case in case to test the finalized beak position, rather than the finalized position of the Callout.

Great, thanks for following-up and your contribution :).

**Pull request merged**
