### PR TITLE
External documentation website: Searchbox feature for left nav

### PR DESCRIPTION
**Pull request by sopranopillow**
#### Description of changes

Added a searchbox to the left nav for the external website.

### CODE REVIEW

**Comment by cliffkoh** [comment]
It would be good to include before/after screenshots (or gifs) in your description!

@Jahnp - who is the right person to review website changes?

**Comment by cliffkoh** [comment]
@sopranopillow Could you please edit your PR title to more accurately describe your work? The title becomes the commit message during a squash and merge operation.

**Comment by Jahnp** [comment]
@cliffkoh , thanks for tagging me! For the website, it'd be good for @mikewheaton and @jordandrako to check this out as we're working with @sopranopillow offline. I also want to emphasize that we need to lock on the design of this implementation before we merge--I believe we have time later this week.

**Comment by sopranopillow** [comment]
The original look of the left nav is the following:

original look

After adding the searchbar, it would look like the following pictures:

searchbox look
filtering

**Pull request merged**
