### PR TITLE
Button: replace divs with spans to make W3 compliant

### LINKED ISSUE #10021: Button: Use spans instead of divs to fix validation issues
### Issue:
[HTML Validator](https://validator.w3.org/nu/about.html) for the button components are failing, for invalid nesting of **div** elements inside the **button**.

From the W3C specifications, **div** elements are not allowed as child of **button**. 

### Codepen:
https://codepen.io/anon/pen/WVExLK

image

#### Reproduce:
Go to button documentaion page, https://developer.microsoft.com/en-us/fabric#/controls/web/button, and validate the buttons with the Html validator (https://validator.w3.org/nu/about.html)

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #10021
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Button: replace divs with spans to make W3 compliant

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10188)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
haha.....167 files changed, and CI fails....hmmm....WHAT COULD IT BE!!

Change file....

**Comment by joschect** [comment]
Looks like a test is failing, I think it's because it's grabbing the element based on a div rather than span.

**Comment by kenotron** [comment]
> Looks like a test is failing, I think it's because it's grabbing the element based on a div rather than span.

This is indicative of a pretty big API change even if the visuals didn't change

**Comment by joschect** [comment]
@dzearing Ken makes a good point, should we consider this a breaking api change?

**Comment by jdhuntington** [comment]
This seems like a risky change for something that's not functionally broken. Can we fix this in the new button instead of upending the present one?

**Comment by micahgodbolt** [comment]
We should certainly communicate this broadly. There are only a few ways this could affect someone. 

1. If they are targeting 'divs' inside of the button with css/js rather than spans
2. If they are using unstyled base button and expecting the divs to be display block

I don't think either are that likely (maybe the 2nd one more than the 1st). Question is "will be compliant and setting a good example outweigh any possible side effects".

**Comment by khmakoto** [comment]
Regardless of the outcome here (I'm still a bit on the fence about this change), I'll make sure to change the new Button to use `spans` anywhere inside of the outermost container.

**Comment by micahgodbolt** [comment]
internal feedback so far has been good. It really comes down to the friction teams will get by compliance tests failing (not hearing much), vs the friction of edge case styles breaking (not hearing much there either).

**Comment by dzearing** [comment]
@joschect Can you please resolve conflicts and get this in a good state? :)

**Comment by dzearing** [comment]
Since @joschect will be unavailable this next week, i'll see if I can fix the branch.

**Pull request merged**
