### PR TITLE
Reserve red as a color in the personacoin color palette

### PR DESCRIPTION
**Pull request by mtennoe**
#### Pull request checklist

- [  ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

For several applications the color red is a reserved color, and is often used as a warning color. This change allows the consumer of PersonaCoin to still set Red as an override, but red will not be used in the default palette.

#### Focus areas to test
Nothing special. Non-risky change

### CODE REVIEW

**Comment by mtennoe** [comment]
@dzearing, @micahgodbolt:
This is related to the email thread we have ongoing about ensuring textboy colors across applications.

Longer term, it would be interesting to support a color palette override, or a way to exclude or include explicit colors from the palette (not just reserving Red like here). That is a bigger change that needs more thought on how to design it though, and is out of scope for this PR

**Comment by mtennoe** [comment]
Looking into fixing the broken test. Will push a fix soon

**Comment by mtennoe** [comment]
Screener complains about the color changes caused by this, which is an expected result. Who has the power to approve the new screenshots?

**Comment by betrue-final-final** [comment]
As a designer on the project, I can help you, and I have a couple of questions. 

1. Is this reserving ms-color-red for all cases unless you override manually?
2. It appears from the screener test that a magenta color is being prevented, is that intentional?
3. It also appears that black is being reserved.

Screener results:
image

Magenta color
image

**Comment by erichdev** [comment]
@betrue-final-final Regarding # 2 and 3 about black and magenta, it has to do with the function that determines the color. With red and black being removed the options, it affects the output.

https://github.com/OfficeDev/office-ui-fabric-react/blob/ef0f5b010fc8a8383c75470db3c64340b9a256cb/packages/office-ui-fabric-react/src/components/Persona/PersonaCoin.tsx#L151-L156

**Comment by betrue-final-final** [comment]
It sounds like there's a bug in the PR then. Magenta and black should not be excluded.

**Comment by erichdev** [comment]
They're not being excluded entirely, the determined colors have just changed. I left out a line in the snippet above, `color = COLOR_SWATCHES_LOOKUP[hashCode % COLOR_SWATCHES_NUM_ENTRIES];` - Because the num of colors have changed, now a different color is selected.

Here's a larger facepile generated with the changes from this PR - 
facepile-reserved

But maybe `_getColorFromName` should be updated anyhow with this PR? I don't fully understand the intent behind the way it's randomizing the colors. For example, why `8` in lines 153 and 155 in the above snippet.

**Comment by betrue-final-final** [comment]
I'm not an engineer, so I'm not sure how this works, but we need to have it only exclude ms-color-red.

However you choose to do it is up to you.

**Comment by mtennoe** [comment]
Hi

As @erichdev says, red is the only color being excluded. I do not remove red from the PersonaInitialColors enum, meaning consumers of the component can still override it to red, while removing it from the color-swatch array causes it to not be selected "randomly" any more (its not really random, as it is deterministic based on a hash of the name passed in as prop). Due to the length of the color-swatch array changing, the result of the modulo operation changes, meaning the selected color changes, which is why the colors in the screener snapshots change.

The function being used in _getColorFromName is a relatively common hashing function (as far as I know), which _should_ have a good enough mix of distribution, while maintaining acceptable perf, so I don't really want to change that

**Comment by betrue-final-final** [comment]
Alright, seems fair. What designer were you working with on this?

**Pull request merged**
