### PR TITLE
Calendar: change clickable spans to buttons

### LINKED ISSUE #1535: Calendar: use buttons rather than clickable spans for days/months
See @cschlechty's comment in #1476.

### PR DESCRIPTION
**Pull request by jordandrako**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1535 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Change all calendar spans with onClick to buttons. Add CSS properties to related classes to reset browser default button styles.

#### Focus areas to test

Be sure added CSS doesn't have ill effects on all supported browsers.

### CODE REVIEW

**Comment by jordandrako** [comment]
I'm concerned there may be scalability issues using `background: transparent;` and the likes. Should I try using an existing variable, or add a className instead?

**Comment by battletoilet** [comment]
All these changes look great, thank you! 👍 . @jordandrako let's track that discussion outside of GitHub and complete this pull request.

**Comment by battletoilet** [comment]
@jordandrako it looks like you have a breaking build because the jest test for Calendar is breaking. This is expected because you changed the spans to buttons and now the snapshots no longer match. Within `packages/office-ui-fabric-react/` you can run `npm run update-snapshots`, commit/push the update and the build _should_ pass.

**Comment by johannao76** [comment]
@John Lorenz<mailto:jolore@microsoft.com>, so he can review these change from my team.

________________________________

**Comment by lorejoh12** [comment]
confirmed that calendar still looks fine, thanks for making this change!

**Pull request merged**
