### PR TITLE
Button and Card: cursor token improvements

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Button: Removing `undefined` from `cursor` token definition.
Card: Adding `cursor` as a token and giving it the correct default styling.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8751)

### CODE REVIEW

**Comment by khmakoto** [comment]
@msft-github-bot require review from @dzearing or @JasonGore

**Comment by JasonGore** [comment]
@cliffkoh Why did bot merge this? It said it acknowledged requiring review from me or David...

**Comment by khmakoto** [comment]
@cliffkoh Yes, I plan to do that

**Comment by cliffkoh** [comment]
@jasongore I have to investigate. It is part of why I approve, to exercise this scenario.

**Comment by cliffkoh** [comment]
Sorry about that though

**Pull request merged**
