### PR TITLE
date picker: 3161: do not parse formatted dates

### LINKED ISSUE #3161: DatePicker must not try to parse the text value unless it was changed by the user
### Bug Report

- __Package version(s)__: 5.5.0
- __Browser and OS versions__: 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal 

Products/sites affected: Outlook (OWA)

#### Describe the issue:

When text input is enabled, DatePicker tries to parse the string returned by formatDate even if the formatted text of the selected date was not changed by the user.
The problem is that there is no guarantee that such string can be parsed, even if the application uses a custom parser.
The formatted string can be ambiguous, so attempting to parse it might yield an unexpected date.
The control should not attempt to parse the string, unless the user typed it.

#### Actual behavior:
Suppose in OWA the user might choose to display dates using 'd/M/yy' format.
With this, we will format Jan 1st 1950 as 1/1/50.
The same will happen with Jan 1st 2050.

Now suppose the user selects such a date using the control UI and then we format it with 'd/M/yy'.
The selected date in the control is correct, but as soon as you tab out of that control, it will try to parse the string and at that point all bets are off.
Even with a custom parser, how would it know if '1/1/50' is to be 1950 or 2050?
Similar with any other year: is '00' supposed to be 1900 or 2000? What about '99', is that 1999 or 2099?
Or 1899?

#### Expected behavior:
The control should not parse the formatted string of dates that were selected using the control's UI.
The control should parse text that was entered by the user.
In addition, if the user selects a date in the control's UI and then makes a change in the text but reverts it back to what the formatted text was, it should keep the same date as before.

### If applicable, please provide a codepen repro:
https://codepen.io/fpintos/pen/oGyrzR

#### Possible solution
Just before calling the parser, the control can format the current selected date and compare the resulting string with the string it is about to parse. If the strings match, don't call the parser and simply leave the selected date as-is.

### PR DESCRIPTION
**Pull request by fpintos**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #3161 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Updated DatePicker so that it will not parse the text input if the inputValue is the same as the formatted string of the selected date. In cases where the formatted string might be ambiguous, the parser might not be able to come up with the exact same date.

An example of the issue can be seen in this CodePen: https://codepen.io/fpintos/pen/oGyrzR, where entering and exiting the control by tabbing has the side-effect of changing the selected date.

With the fix, simply tabbing thru the control will not result in a date change.

#### Focus areas to test

A new example is added to the sample pages, showing DatePicker with custom formatting and parsing. This is basically a copy of DatePickerInputExample with callbacks for formatDate and parseDateFromString.

Tabbing thru the control should will not invoke the parser.
If the user enters the control and edits the text, but reverts it back to the same string produced by the selected date, the parser is not invoked and the selected date remains the same.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
@fpintos this is great. I love your explanation in the codepen.

**Comment by micahgodbolt** [comment]
My only thought is can we write a test for this?

**Comment by fpintos** [comment]
@micahgodbolt From what I can see, we need tests for DatePicker; not just for this, but for the whole control.
I'm looking for the DatePicker.test.tsx file and I don't see one.
Do we have tests for it somewhere else?

**Comment by johannao76** [comment]
@fpintos, @micahgodbolt : It does look like there are no tests for the datepicker itself right now, would be good to add the tests if you can at least just one case for this.

**Comment by micahgodbolt** [comment]
@johannao76 I was typing the exact same thing :) If you can at least add a test for this scenario, then we can increase test covered with future PRs.

**Pull request merged**
