### PR TITLE
Button type default to type='button' to avoid form submit action

### LINKED ISSUE #1783: PeoplePicker should use type="button" on remove button to prevent submits
### Bug Report

- __Package version(s)__: any
- __Browser and OS versions__: any

#### Describe the issue:

When using the PeoplePicker component with the default rendering template each item has a button, which removes the person from the list.
The remove button is a `<button>` without a type. Some browser are interpreting this as `type="submit"` which could trigger a form submit on click.

#### Actual behavior:

Remove button triggers a form submit (especially in ASP .NET Webform sites, in SharePoint, etc.) and the website reloads.

#### Expected behavior:

Button should have the attribute `type="button"` which doesn't submit a form.

_**Note:** This does only affect the PeoplePicker, other Pickers (like TagPicker) are not affected because they aren't using `<button>` elements for their remove button. Seems a bit inconsistent._

### PR DESCRIPTION
**Pull request by mdahamiwal**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1783, #1687 
- [x] Include a change request file if publishing 
- [x] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes
1. Defaulting button's to use type='button' to avoid unexpected form submit operation on consumer sites.

2. Remove Icon button's custom color for disabled state.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
What about situations where we want our button to be type='submit/reset/menu'. Can you confirm that native props will override the type?

**Comment by mdahamiwal** [comment]
@micahgodbolt, yes if you pass `type={submit/reset/menu}` to any specific button, it will be overridden.

**Comment by micahgodbolt** [comment]
@mdahamiwal oh, i noticed the change to high contrast mode as well. Can you explain why that is included?

**Comment by mdahamiwal** [comment]
@micahgodbolt, check the issues mentioned in description. The Icon button has different theme when disabled in high contrast mode. Seems like we were applying custom color which are not required.

**Pull request merged**
