### PR TITLE
Betrue wcag2.1 non text contrast

### PR DESCRIPTION
**Pull request by betrue-final-final**
These fixes addresses WCAG 2.1 non-text contrast guidelines https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast 

I've updated the focus and pressed states of these components:
- Textfield
- Combobox
- Dropdown
- Spinbutton

Before and after
image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10439)

### CODE REVIEW

**Comment by ecraig12345** [comment]
> Run `npm run change` at root to make a change file :)

That should be `yarn change` now, not `npm run change` (if this is your first time running a yarn command, you'll need to run `npm install -g yarn` first).

**Comment by betrue-final-final** [comment]
Doh! out of practice! Will do.

**Comment by betrue-final-final** [comment]
Had to use yarn to get this going :)

**Comment by dzearing** [comment]
Ah sorry for the friction, build is complaining about snapshots being out of date.

To update them:

```bash
cd packages\office-ui-fabric-react
yarn update-snapshots
```

**Comment by betrue-final-final** [comment]
Done! That was for screener?

**Comment by dzearing** [comment]
After you do that, you should have some changes in your changed files. Check those in. It's for the snapshot tests, which lock down the DOM shape for components in various scenarios. (Applies both to ux components and to utility components.)

**Comment by betrue-final-final** [comment]
I tried git push before and it said there were no changes, but the git commit worked.

**Comment by KevinTCoughlin** [comment]
@betrue-final-final, worked for me. Output below:

```shell
~\Work\office-ui-fabric-react [betrue-WCAG2.1-non-text-Contrast ≡]> yarn update-snapshots
yarn run v1.17.3
$ cd packages/office-ui-fabric-react && npm run update-snapshots

> office-ui-fabric-react@7.32.0 update-snapshots C:\Users\keco.REDMOND\Work\office-ui-fabric-react\packages\office-ui-fabric-react
> just-scripts jest -u

[3:09:45 PM] ■ started 'jest'
[3:09:45 PM] ■ Running Jest
[3:09:45 PM] ■ C:\Program Files\nodejs\node.exe "C:\Users\keco.REDMOND\Work\office-ui-fabric-react\node_modules\jest\bin\jest.js" --config "C:\Users\keco.REDMOND\Work\office-ui-fabric-react\packages\office-ui-fabric-react\jest.config.js" --passWithNoTests --colors --forceExit --updateSnapshot
 PASS  src/components/FocusTrapZone/FocusTrapZone.test.tsx (17.919s)
 PASS  src/components/FocusZone/FocusZone.test.tsx (20.227s)
 PASS  src/components/TextField/TextField.test.tsx (21.062s)
 PASS  src/components/Button/Button.test.tsx (24.272s)
 PASS  src/components/SpinButton/SpinButton.test.tsx
 PASS  src/components/ContextualMenu/ContextualMenu.test.tsx (25.495s)
 › 2 snapshots updated.
 PASS  src/components/ComboBox/ComboBox.test.tsx (25.948s)
 › 2 snapshots updated.
 PASS  src/components/Dropdown/Dropdown.test.tsx (26.972s)
 PASS  src/components/OverflowSet/OverflowSet.test.tsx (5.835s)
 PASS  src/components/ResizeGroup/ResizeGroup.test.tsx
 PASS  src/components/KeytipLayer/KeytipTree.test.tsx
 PASS  src/components/DetailsList/DetailsHeader.test.tsx (8.105s)
 PASS  src/utilities/dateMath/DateMath.test.ts
 PASS  src/components/Calendar/Calendar.test.tsx
 PASS  src/components/ColorPicker/ColorPicker.test.tsx
 PASS  src/utilities/color/colors.test.ts
 PASS  src/components/KeytipLayer/KeytipLayer.test.tsx
 PASS  src/utilities/selection/SelectionZone.test.tsx
 PASS  src/components/TextField/MaskedTextField/MaskedTextField.test.tsx
 PASS  src/utilities/positioning.test.ts
 PASS  src/components/ChoiceGroup/ChoiceGroup.test.tsx
 PASS  src/components/DetailsList/DetailsList.test.tsx
 PASS  src/components/ContextualMenu/ContextualMenu.deprecated.test.tsx
 PASS  src/components/DatePicker/DatePicker.test.tsx
 PASS  src/components/Stack/Stack.test.tsx
 PASS  src/components/GroupedList/GroupedList.test.tsx
 PASS  src/components/DetailsList/DetailsColumn.test.tsx
 PASS  src/components/Facepile/Facepile.test.tsx
 PASS  src/components/List/List.test.tsx
 PASS  src/components/pickers/BasePicker.test.tsx
 PASS  src/components/ExtendedPicker/BaseExtendedPicker.test.tsx (5.946s)
 PASS  src/components/Layer/Layer.test.tsx
 PASS  src/components/CommandBar/CommandBar.test.tsx
 PASS  src/components/TextField/MaskedTextField/inputMask.test.ts
 PASS  src/components/Toggle/Toggle.test.tsx
 PASS  src/components/HoverCard/HoverCard.test.tsx
 PASS  src/components/Checkbox/Checkbox.test.tsx
 PASS  src/components/Stack/StackUtils.test.ts
 PASS  src/components/SearchBox/SearchBox.test.tsx
 PASS  src/utilities/keytips/KeytipManager.test.tsx
 PASS  src/components/Callout/Callout.test.tsx
 PASS  src/components/Image/Image.test.tsx
 PASS  src/components/Slider/Slider.test.tsx
 PASS  src/components/Persona/Persona.deprecated.test.tsx
 PASS  src/components/CommandBar/CommandBar.deprecated.test.tsx
 PASS  src/components/Autofill/Autofill.test.tsx
 PASS  src/components/TeachingBubble/TeachingBubble.test.tsx
 PASS  src/components/pickers/TagPicker/TagPicker.test.tsx
 PASS  src/components/Link/Link.test.tsx
 PASS  src/components/SwatchColorPicker/SwatchColorPicker.test.tsx
 PASS  src/components/ContextualMenu/ContextualMenuItem.test.tsx
 PASS  src/components/ColorPicker/ColorRectangle/ColorRectangle.test.tsx
 PASS  src/components/Persona/Persona.test.tsx (18.009s)
 PASS  src/components/Breadcrumb/Breadcrumb.test.tsx
 PASS  src/components/Dialog/Dialog.test.tsx
 PASS  src/components/Persona/PersonaPresence/PersonaPresence.test.tsx
 PASS  src/components/DetailsList/DetailsRow.test.tsx
 PASS  src/components/ComponentConformance.test.tsx (23.678s)
 PASS  src/components/Tooltip/TooltipHost.test.tsx
 PASS  src/components/FloatingPicker/BaseFloatingPicker.test.tsx
 PASS  src/components/MessageBar/MessageBar.test.tsx
 PASS  src/utilities/keytips/KeytipConfig.test.ts
 PASS  src/utilities/keytips/KeytipUtils.test.ts
 PASS  src/components/pickers/PeoplePicker/PeoplePicker.test.tsx
 PASS  src/components/Nav/Nav.test.tsx
 PASS  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.test.tsx
 PASS  src/components/Pivot/Pivot.test.tsx
 PASS  src/components/Callout/CalloutContent.test.tsx
 PASS  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.test.tsx
 PASS  src/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.test.tsx
 PASS  src/utilities/grid/Grid.test.tsx
 PASS  src/utilities/keytips/IKeytipTransitionKey.test.ts
 PASS  src/components/Shimmer/Shimmer.test.tsx
 PASS  src/components/ActivityItem/ActivityItem.test.tsx
 PASS  src/components/Dropdown/utilities/DropdownSizePosCache.test.ts
 PASS  src/components/Tooltip/Tooltip.test.tsx
 PASS  src/components/Rating/Rating.test.tsx
 PASS  src/components/Panel/Panel.test.tsx
 PASS  src/components/MarqueeSelection/MarqueeSelection.test.tsx
 PASS  src/components/FloatingPicker/Suggestions/SuggestionStore.test.tsx
 PASS  src/components/pickers/Suggestions/Suggestions.test.tsx
 PASS  src/components/SelectedItemsList/BaseSelectedItemsList.test.tsx
 PASS  src/components/Persona/PersonaCoin/PersonaCoin.test.tsx (6.621s)
 PASS  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.test.tsx
 PASS  src/utilities/contextualMenu/contextualMenuUtility.test.ts
 PASS  src/components/Modal/Modal.test.tsx
 PASS  src/components/DocumentCard/DocumentCardImage.test.tsx
 PASS  src/components/Toggle/Toggle.deprecated.test.tsx
 PASS  src/components/Stack/StackItem/StackItem.test.tsx
 PASS  src/components/Persona/PersonaCoin/PersonaCoin.deprecated.test.tsx
 PASS  src/components/Button/Button.deprecated.test.tsx
 PASS  src/utilities/groupedList/GroupedListUtility.test.tsx
 PASS  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.deprecated.test.tsx
 PASS  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.deprecated.test.tsx
 PASS  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.deprecated.test.tsx
 PASS  src/components/ProgressIndicator/ProgressIndicator.test.tsx
 PASS  src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.test.tsx
 PASS  src/components/Spinner/Spinner.test.tsx
 PASS  src/components/Icon/Icon.test.tsx
 PASS  src/components/Keytip/KeytipContent.test.tsx
 PASS  src/components/Persona/PersonaInitialsColor.test.ts
 PASS  src/components/DetailsList/ShimmeredDetailsList.test.tsx
 PASS  src/components/FocusZone/FocusZone.deprecated.test.tsx
 PASS  src/utilities/decorators/withResponsiveMode.test.tsx
 PASS  src/components/Pivot/Pivot.deprecated.test.tsx
 PASS  src/components/Label/Label.test.tsx
 PASS  src/components/DocumentCard/DocumentCard.test.tsx
 PASS  src/components/ScrollablePane/ScrollablePane.test.tsx
 PASS  src/components/Fabric/Fabric.test.tsx
 PASS  src/components/Text/Text.test.tsx
 › 26 snapshots updated.
Force exiting Jest

Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
[3:11:19 PM] ■ finished 'jest' in 93.99s
Done in 97.24s.
```

I've pushed the updated snapshots in https://github.com/OfficeDev/office-ui-fabric-react/pull/10439/commits/13c2f93f147bb69a21a873d1989b31baa8b4c4e2.

**Comment by betrue-final-final** [comment]
Thanks @KevinTCoughlin ! I thought I had done it successfully but for some reason it didn't show up. Hey so why is the first check still failing?

**Comment by dzearing** [comment]
It looks like the same thing needs to be done in `packages/experiments`. Something in this change caused experiments to change.

**Comment by KevinTCoughlin** [comment]
> It looks like the same thing needs to be done in `packages/experiments`. Something in this change caused experiments to change.

Odd...

```shell
~\Work\office-ui-fabric-react\packages\experiments [betrue-WCAG2.1-non-text-Contrast ≡]> yarn update-snapshots
yarn run v1.17.3
$ just-scripts jest -u
[5:25:58 PM] ■ started 'jest'
[5:25:58 PM] ■ Running Jest
[5:25:58 PM] ■ C:\Program Files\nodejs\node.exe "C:\Users\keco.REDMOND\Work\office-ui-fabric-react\node_modules\jest\bin\jest.js" --config "C:\Users\keco.REDMOND\Work\office-ui-fabric-react\packages\experiments\jest.config.js" --passWithNoTests --colors --forceExit --updateSnapshot
 PASS  src/components/Chiclet/Chiclet.test.tsx
 PASS  src/components/Slider/Slider.test.tsx
 PASS  src/components/Sidebar/Sidebar.test.tsx
 PASS  src/components/Button/Button.test.tsx (5.051s)
 PASS  src/components/Button/SplitButton/SplitButton.test.tsx (5.107s)
 PASS  src/components/Button/ButtonVariants/ButtonVariants.test.tsx (5.175s)
 PASS  src/components/PersonaCoin/PersonaCoin.test.tsx (5.212s)
 PASS  src/components/Button/MenuButton/MenuButton.test.tsx
 PASS  src/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.test.tsx
 PASS  src/components/Pagination/Pagination.test.tsx
 PASS  src/components/Toggle/Toggle.view.test.tsx
 PASS  src/components/Toggle/Toggle.state.test.tsx
 PASS  src/components/MicroFeedback/MicroFeedback.test.tsx
 PASS  src/components/Persona/Vertical/VerticalPersona.test.tsx
 PASS  src/components/SelectedItemsList/SelectedItemsList.test.tsx
Force exiting Jest

Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
[5:26:10 PM] ■ finished 'jest' in 12.68s
Done in 14.16s.
```

**Comment by KevinTCoughlin** [comment]
FYI - I had to do a full repo build via `yarn build` (which could have been localized to `office-ui-fabric-react`. Then I had to run `yarn update-snapshots` in `packages/experiments` for those bits to pick-up the changes and regenerate snapshots. This was committed as https://github.com/OfficeDev/office-ui-fabric-react/pull/10439/commits/07d052338ab3207b61a76d313b2ca3cc80dfae92.

**Comment by KevinTCoughlin** [comment]
With https://github.com/OfficeDev/office-ui-fabric-react/pull/10439/commits/bc5d0b51b1dff3a94e1687a0637b6cf9eb674a53 this will now pass CI.

PR reviewers please take a look at the change-set.

**Comment by dzearing** [comment]
Thank you @KevinTCoughlin for weeding that out!

**Comment by dzearing** [comment]
Focusing into the ComboBox causes the icon to jump.

TextField text also jumps on focus.

SpinButton icons jump.

Dropdown looks good though.

**Comment by betrue-final-final** [comment]
Thanks David. I wonder if it's because of the extra pixel. I could change the positioning on focus. Investigating.

**Comment by KevinTCoughlin** [comment]
CI is complaining about missing change file for `office-ui-fabric-react`

```shell
Target branch is "origin/master"
Checking for changes against "origin/master"
fetching latest from remotes
Your local repository already has change files for these packages: office-ui-fabric-react
Found changes in the following packages: [@uifabric/experiments]
Run 'yarn change' to generate a change file
ERROR: Change files are needed!
```

**Comment by betrue-final-final** [comment]
Hey @KevinTCoughlin, @dzearing or @ecraig12345 , can you check out my PR again?

**Pull request closed without merging**
