### PR TITLE
Fixing high contrast for Link

### PR DESCRIPTION
**Pull request by antonlabunets**
After a discussion with designers, removing all the overrides to ensure the defaults are met AND the end user can customize as with the rest of the links.

I've played with all the high contrast settings and confirmed they match the expectations and pass WebAIM.

### CODE REVIEW

**Comment by mikewheaton** [comment]
Approved, thanks 😄

**Comment by atneik** [comment]
This is being addressed in MDL2 PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/123

**Comment by antonlabunets** [comment]
Feel free to abandon then.

**Comment by atneik** [comment]
Addressed in https://github.com/OfficeDev/office-ui-fabric-react/commit/b158fc4c196fc7c29563b8683e6e1aa7d0291693

**Pull request closed without merging**
