### PR TITLE
Use the `data-is-scrollable` attribute on the correct ScrollablePane div

### LINKED ISSUE #4601: Lists rendered inside a ScrollablePane fail to render pages as they are scrolled into view
### Bug Report

- __Package version(s)__: 5.82.4
- __Browser and OS versions__: macOS 10.13.4, Chrome 65

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: onedrive.live.com

#### Describe the issue:

A bug was introduced in #4055 which prevents a virtualized List rendered inside a ScrollablePane from rendering pages as they're scrolled into view.

#### Actual behavior:

Render a `List` or `DetailsList` inside a `ScrollablePane`, e.g.
```jsx
<ScrollablePane>
  <DetailsList
    items={ items }
    columns={ columns }
    setKey='set'
    selection={ this._selection }
  />
</ScrollablePane>
```

Observe that, when there is a large number of `items`, pages below the fold are not rendered as they are scrolled into view. e.g. run `npm start` and visit http://localhost:4322/#/examples/scrollablepane:

kapture 2018-04-18 at 13 34 50

#### Expected behavior:

Pages in the list should be rendered as they are scrolled into view.

### PR DESCRIPTION
**Pull request by elliottsj**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4601
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Move the `data-is-scrollable` attribute to the correct scrollable div: the one which has the `overflow-y: auto;` CSS property.

#### Focus areas to test

Run `npm start`, then visit
http://localhost:4322/#/examples/scrollablepane

The DetailsList example should behave like this:
kapture 2018-04-18 at 13 35 56

### CODE REVIEW

**Comment by elliottsj** [comment]
@MaxLustig can you take a look at this?

**Comment by aappddeevv** [comment]
I'm looking forward to this merge!

**Comment by jordandrako** [comment]
Might fix #4204

**Comment by elliottsj** [comment]
@ThomasMichon They are back inside the `data-is-scrollable` element because the `data-is-scrollable` attribute needs to be applied to the scrollable div in order for any child `List` to correctly identify the scrollable div.

I'm not clear on why `stickyAbove` and `stickyBelow` cannot be inside the `data-is-scrollable` element. I'm looking at #4055:

>This, however, unfurled a different bug in ScrollablePane which the infinite loop had masked: the top sticky header wouldn't properly be placed in `stickyAbove` on creation of the ScrollablePane, but the constant changing of `isStickyTop` and `isStickyBottom` eventually caused it to snap in place. By getting rid of `stickyContainer` and moving `stickyAbove` and `stickyBelow` to siblings of the children of the pane, this is fixed (it also removed the need for `resizeContainer`).

@MaxLustig Can you help clarify what this means? Is there a repro of this issue I can try?

**Comment by leddie24** [comment]
@elliottsj @ThomasMichon can you look at PR #4491 .  This sets data-is-scrollable on the correct element and keeps stickyAbove/Below as sibling children on the scrollable element.  #4491 fixes #4601 as well.

**Comment by dzearing** [comment]
@leddie24 @ThomasMichon Are there concerns here? Is `data-is-scrollable` on the wrong element? Seems reasonable to me.

**Comment by elliottsj** [comment]
@leddie24 Thanks; I'll take a deeper look at your PR when I get a chance. Given that your PR is much bigger (& potentially riskier) than this change, I'd like to get this merged first to at least fix the List scrolling issue.

@ThomasMichon is the stickyAbove / stickyBelow issue blocking here?

**Pull request merged**
