### PR TITLE
Add List scenarios to perf-test suite

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Adds `DetailsHeader` scenarios for "justified" and "fixed" layout modes to perf test scenarios.

I'm interested to see the results for a successful run.

Additional scenarios I'm looking to add without regressing build time, ideally to this PR:

- `StaticList`
- `FixedList`
- `DetailsList` (virtualized)
    - Currently hangs indefinitely when run (continuing to debug)
- `GroupedList`

#### Focus areas to test

- CI should pass.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9776)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
> One thing I've been thinking of having is a narrower list for CI.. if/when build time ends up being a problem. The CI list really should be gates for limiting regression (core scenarios) rather than exhaustive variants.

That makes sense.. these will add up. 

There are some cases where changes to components such as `StaticList` and `FixedList` would not regress the others. However, I'm not sure the tool can be that intelligent as to which tests to drop based on dependencies.

I'll recommend we hold off on merging this until I have a final run and can see how much overhead this change-set brings to CI time.

**Comment by JasonGore** [comment]
Each scenario is about 30 seconds. Before + After = 1 minute. 2 tests = 2 minutes total impact.

```
Starting test for DetailsHeaderFixed at http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/9776/merge/perf-test/index.html?scenario=DetailsHeaderFixed&iterations=5000
Ran perf test in: 29259.423ms
Starting test for DetailsHeaderJustified at http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/9776/merge/perf-test/index.html?scenario=DetailsHeaderJustified&iterations=5000
Ran perf test in: 24205.252ms
```

**Comment by KevinTCoughlin** [comment]
> I'll approve this for now and leave it up to you how to approach.

Thanks, I'm going to think about the trade-offs here. If I can get `DetailsList` rendering as a whole in a reasonable amount of time without requiring additional tests... that might be ideal. Same thing for `List`.

**Comment by KevinTCoughlin** [comment]
FYI - my plan for this PR is as follows:

1. Push additional scenarios to this branch today so CI runs and captures profiler snapshots.
1. Save the captures and timings
1. Close the PR
1. Evaluate which are worth keeping based on ongoing work, timings, and profiler output

**Comment by KevinTCoughlin** [comment]
Will re-visit.

**Pull request closed without merging**
