### PR TITLE
Fix SwatchColorPicker flicker issue on circle border hover. Fixes #8681

### LINKED ISSUE #8681: SwatchColorPicker hover issue for ColorPickerGridCell
In the current SwatchColorPicker, hovering over the exact border between the color and the background makes it flicker between selected/unselected states very fast.

I believe this might be due to the fact that each cell is a border-box with 50% border radius. Adding padding + border on hover makes it relayout itself and this causes the sudden flicker between the selected-unselected states.

Can be reproduced here: https://developer.microsoft.com/en-us/fabric#/components/swatchcolorpicker

demo

### PR DESCRIPTION
**Pull request by Dalimil**
#### Pull request checklist
- [x] Addresses an existing issue: Fixes #8681
- [x] Include a change request file using `$ npm run change`

Fix an issue in the current SwatchColorPicker where hovering over the exact border between the color and the background makes it flicker between selected/unselected states very fast.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8682)

### CODE REVIEW

**Comment by ecraig12345** [comment]
@Dalimil Looks like you need to run `npm run change` (and commit the result)

**Comment by ecraig12345** [comment]
Oops, ignore that last comment, seems I can't read today... What you actually need to do is run `npm run update-snapshots` and commit the result.

**Comment by Dalimil** [comment]
@ecraig12345 Ok, should be fixed now :)

**Comment by ecraig12345** [comment]
Talked with @phkuo about the flickering issue--he thinks it's a browser bug (it only happens in Chrome, not Firefox or IE) and wasn't able to find a simple workaround. There may be a workaround which doesn't break other cases, but it will be more complicated. 

Also just to clarify, the scenario that breaks with the `overflow: hidden` change is showing an outline around the tentatively-selected swatch when keyboarding between swatches. To repro this:
1. Click a swatch
2. Use the arrow keys to move to a different swatch

Without this change:
image

With this change (note the missing outline):
image

**Comment by phkuo** [comment]
This is a Chrome (webkit?) browser bug that seems to be caused by the border-radius combined with hover styles on the button. I'd suggest refactoring the styles such that the button itself doesn't change styles on hover, and instead only the child elements do. The button itself wouldn't have `overflow:hidden` or `border-radius` on it. Maybe if the button doesn't change styles, it will be a consistent hover target and so we won't get this flickering issue.

**Pull request closed without merging**
