### PR TITLE
Shimmer: resolve conflicts

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [X] Include a change request file using `$ npm run change`

#### Description of changes
Reverting the revert for [PR#4958](https://github.com/OfficeDev/office-ui-fabric-react/pull/4958).
Resolving the conflicts related to `getStyles` renamed to `styles` and `IStyleFunction` renamed to `IStyleFunctionOrObject`.

### CODE REVIEW

**Comment by Vitalius1** [comment]
@cliffkoh What is this message: 
screen shot 2018-05-30 at 12 04 46 pm

**Comment by cliffkoh** [comment]
@Vitalius1 master branch is locked for checkin atm. Please wait a bit before merging (until 6.0 is officially released).

**Comment by Vitalius1** [comment]
@cliffkoh Oh-oh ... I already pushed the button `Update branch`. What to expect now 😰? I think it updated the shrinkwrap 😬

**Comment by cliffkoh** [comment]
Update branch is fine :) Don't worry, just don't merge into master

**Pull request merged**
