### PR TITLE
darkened the placeholder text for dropdown to meet MAS color contrast requirements

### PR DESCRIPTION
**Pull request by petdun2519**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes https://github.com/OfficeDev/office-ui-fabric-react/issues/2572
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
You can avoid all of the empty change files in the future by running `rush change -b upstream` where upstream is the name of the office-ui-fabric-react git remote.

**Comment by micahgodbolt** [comment]
@petdun2519 for reference, can you describe the color contrast requirements and how this change got us aligned with those requirements? Want to make sure someone doesn't come along and simply decide to change the values back.

**Comment by petdun2519** [comment]
@micahgodbolt ok will do that in the future. Sure so basically the requirement stems from all meaningful text needing to have a color contrast ratio between it's color and the background color of 4.5 to 1 as described here https://www.1eswiki.com/wiki/Color_(contrast).

**Comment by micahgodbolt** [comment]
What was the original contrast ratio and what is the new one?

**Comment by petdun2519** [comment]
@micahgodbolt the old colors were Foreground: #a6a6a6 Background: #ffffff with a Contrast ratio: 2.4:1, the new contrast ratio is at least more than 4.5:1

**Comment by petdun2519** [comment]
it's 5.7:1 the new ratio

**Comment by Jahnp** [comment]
Thanks for doing this, @petdun2519. It'd be great if you could include some screenshots as well. @betrue-final-final for FYI.

**Comment by dzearing** [comment]
@Jahnp you can merge this if you're ok with it.

**Pull request merged**
