### PR TITLE
Panel: Enabling the addition of new buttons (or other components) to the Navigation region.

### PR DESCRIPTION
**Pull request by riosn-n**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

The Panel component currently allows a developer to replace the entire Navigation area, but that means that the close button (along with its handler) as well as the styles of the region are lost.

This PR adds a new render prop for the content of the Navigation region, making it easy to add new components as well as rendering the close button via the defaultRender.

This same pattern is in use today for the Footer (onRenderFooter, onRenderFooterContent).

panel-with-navigation-buttons

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/7956)

### CODE REVIEW

**Comment by kenotron** [comment]
Given that we're getting Slots soon, should we wait until we have this to proceed? @JasonGore

**Comment by JasonGore** [comment]
We *could* change the prop name to `navigation` similar to the other props objects changes we've been making, and then it would also be a backwards compatible API change. But I would also have to make some changes to Slots typings to align them with `IRenderFunction`.

**Comment by riosn-n** [comment]
@JasonGore do you want me to rename the prop to "navigation"? Notice that IRenderFunction is already being used in multiple places. For example, we already have "onRenderFooter" and "onRenderFooterContent" props. Wouldn't it make more sense to keep the current pattern (instead of checking-in a hybrid approach) and deprecate all these props at once (including this new one that I'm adding) when Slots are ready?

**Comment by JasonGore** [comment]
Yeah I can see that argument. Let's go for consistency now since we already have similar props to deprecate. Thanks!

**Comment by Vitalius1** [comment]
I like a lot the new feature. Would you mind also adding an example on its usage? You can either create a new example or modify slightly an existing one as there are plenty of them in there already. Thanks!

**Comment by riosn-n** [comment]
Thanks, @Vitalius1. I've added a new example as suggested.

panel-with-navigation-and-search

**Comment by Vitalius1** [comment]
You will need to run `npm run update-snapshots` and push the snapshots for the new example.

**Comment by riosn-n** [comment]
All green now 😃  Thank you for reviewing, @Vitalius1

**Pull request merged**
