### PR TITLE
Buttons: Remove borders for buttons that should not have borders

### PR DESCRIPTION
**Pull request by phkuo**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

See: https://github.com/OfficeDev/office-ui-fabric-react/pull/6101
Removes borders from buttons that should not have borders.

### CODE REVIEW

**Comment by phkuo** [comment]
@betrue-final-final Screener is failing because I removed an invisible 1px transparent border, so things are now slightly closer together. This is the technically correct fix... should we proceed with this? Otherwise, I can preserve the invisible border instead of removing it.

**Comment by betrue-final-final** [comment]
Hmmm let me look

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by phkuo** [comment]
@cliffkoh @bennettclark can one of you merge this please? I don't have authorization =)

**Comment by cliffkoh** [comment]
@phkuo FTFY :)

**Pull request merged**
