### PR TITLE
[Commandbar] Fixes the chevron to make it the same size as a menuIcon inside commandbar

### LINKED ISSUE #6018: Command bar split button not to spec
- __Package version(s)__: Current 
- __Browser and OS versions__: Not sure
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? NO
 
Requested priority: NORMAL
 
Products/sites affected: OWA
 
#### Describe the issue:
 
The command bar split button does not seem to spec. 
- the chevron is too large. 
- it looks like the interactive font colors may not be correct (usually the icon and text get darker on hover/press).

I did not design this but would consult with Ben or the Fabric Sketch Design file for the Design spec.

 
#### Actual behavior:
 
image
image
 
#### Expected behavior:
 
To look like the other command buttons

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6018
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Fixes the chevron to make it the same size as a menuIcon inside commandbar

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by suztocco** [comment]
@kenotron  @micahgodbolt - Is there any way to see this update visually? Or do I need to wait until it is pushed onto the official fabric site?

**Comment by kenotron** [comment]
Sure! For each pull request, we generate a "preview" of the demo site. In this case, we have:
http://fabricweb.z5.web.core.windows.net/pr/refs/pull/6098/merge/#/examples/button

**Comment by suztocco** [comment]
@kenotron  

the color of the chevrons are not the same.
image

**Comment by micahgodbolt** [comment]
tracking that color issue in #6128

**Pull request merged**
