### PR TITLE
Card: Porting latest Fabric-7 changes to master

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This PR ports the latest `Card` changes from the Fabric 7 branch to master for their availability to a broader audience. In doing this we also added some tokens to `Stack` that were already in fabric-7 but not in master and added `Card` stories to master as well.

We did had to change all references to `React.FunctionComponent` to `React.StatelessComponent`, but aside from that, all of these changes have already been reviewed and are checked in the Fabric 7 branch.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9139)

### CODE REVIEW

**Comment by JasonGore** [comment]
Adding @jdhuntington since this'll come back around to `fabric-7` again

**Comment by dzearing** [comment]
@khmakoto this pr is getting stale and has conflicts. Can you drive getting it merged or closed tomorrow?

**Comment by khmakoto** [comment]
@dzearing I spoke with @jdhuntington and because of all the movements that are happening today regarding Fabric 7 he said it is better if we wait until at least tomorrow to merge this in.

**Comment by jdhuntington** [comment]
Closing; will reopen a cherry-pick later this week.

**Pull request closed without merging**
