### PR TITLE
Drop hint's icon and position, for column drag-drop in DetailsList updated

### PR DESCRIPTION
**Pull request by svaibhav**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Changing the drop hint icon and it's position for list's column drag-drop

Old drop hint:
old_drop_hint

New drop hint:
new_drop_hint

#### Focus areas to test

Details list: drag drop a column to a new position. The drop hint will now appear above

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10086)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
@svaibhav, did caret position recently regress?

@Vitalius1, is the caret supposed to be positioned top or bottom aligned with the header cell?

**Comment by Vitalius1** [comment]
That is a very good question… will reach out to @betrue-final-final and get an opinion about that because I don’t see any redlines about it.

**Comment by KevinTCoughlin** [comment]
> That is a very good question… will reach out to @betrue-final-final and get an opinion about that because I don’t see any redlines about it.

Thanks @Vitalius1 cc: @arkogupta

**Comment by svaibhav** [comment]
@KevinTCoughlin No, this is not because of regression. A design decision was taken to move the caret icon above the column divider. This was made to make the 'Sticky Header' feature work smoothly with lists. Once the header is made sticky (post scrolling of the list), the caret icon at the bottom gets chopped off (overflow: hidden) because of the CSS changes.

Although I noticed that in the version 7 of fabric, the caret and the column divider are not properly placed (there is some gap between them, and caret seem to have moved few pixels upwards).

**Comment by arkogupta** [comment]
@KevinTCoughlin Yes, these changes are to not let the sticky header interfere with the drophint. @naveedahmed should have the redline for this.
Also, in Fabric 7, the screener tests are updated wrongly. There is a gap b/w the caret and the line. Not sure what caused the regression and why have those screener snapshots been approved :/

**Comment by marygans** [comment]
@betrue-final-final has agreed with these changes but would like to see it in context.

**Comment by Vitalius1** [comment]
@marygans don’t forget to bug Ben or anyone else in charge of lists design specs to include the drag and drop scenario in the toolkit so that we don’t need to constantly ask if this intended or not. It’s easy to just open the toolkit and look 😄

**Comment by svaibhav** [comment]
I was also a bit surprised after seeing so many change files, but without making them part of the PR the build was failing at "check change" step!
@kenotron @Vitalius1 please let me know if there is anything at my end which can be done.

**Comment by marygans** [comment]
@msft-github-bot please merge in 1 hour

**Comment by svaibhav** [comment]
@KevinTCoughlin Kindly have a look at the final changes and see if this PR can be merged. Your's review/approval is the only thing pending for this PR.

**Comment by svaibhav** [comment]
@KevinTCoughlin As @arkogupta pointed out in [his comment](https://github.com/OfficeDev/office-ui-fabric-react/pull/10086#issuecomment-519394024), the caret is not positioned properly if we see the example in the demo app on the master branch, so I can't really say if we can merge this directly into master or not.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin As @arkogupta pointed out in [his comment](https://github.com/OfficeDev/office-ui-fabric-react/pull/10086#issuecomment-519394024), the caret is not positioned properly if we see the example in the demo app on the master branch, so I can't really say if we can merge this directly into master or not.

We can't have divergent experiences else the behavior you're introducing in `DetailsList` for `6.0` will regress once partners onboard to Fabric >= 7.

Can you two work together to provide a patch for `master` i.e. `Fabric >= 7`? The gap is likely an incorrect pixel value, but you are more familiar having _just_ touched the area of code.

**Pull request merged**
