### PR TITLE
Refactored groupedList to its own component

### PR DESCRIPTION
**Pull request by magellantoo**

### CODE REVIEW

**Comment by wdo3650** [comment]
Approved.

**Comment by battletoilet** [comment]
Approved

**Comment by dzearing** [comment]
Not approved

**Comment by dzearing** [comment]
Rejected

**Comment by ericthompson** [comment]
Hey, @dzearing - what do you think needs to be fixed/reconsidered?

**Comment by magellantoo** [comment]
@ericthompson The PR was completed in VSO and copied over by David Zearing. The github PR is now redundant.

**Comment by dzearing** [comment]
Sorry, @ericthompson was on my phone and wanted to make sure this didn't go in redundantly. I should have just closed it (but i was also curious if pullapprove supported rejecting PRs that are already approved.) In the future if i see Approves and I also see blocking issues, I will mark Rejected as a way to halt commit train until issues are resolved.

**Comment by ericthompson** [comment]
Makes sense - thanks for the explanations!

On Jul 28, 2016, at 10:49 AM, David Zearing <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, @ericthompson<https://github.com/ericthompson> was on my phone and wanted to make sure this didn't go in redundantly. I should have just closed it (but i was also curious if pullapprove supported rejecting PRs that are already approved.) In the future if i see Approves and I also see blocking issues, I will mark Rejected as a way to halt commit train until issues are resolved.

-

**Pull request closed without merging**
