### PR TITLE
5.x- Group sibling count 5.0

### PR DESCRIPTION
**Pull request by tharshada**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Adding siblingCount prop to get a group's sibling count

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by mikewheaton** [comment]
Is this a change in 6.x that is being ported over to 5.x? Or functionality that is only valid for 5.x?

**Comment by tharshada** [comment]
> Is this a change in 6.x that is being ported over to 5.x? Or functionality that is only valid for 5.x?

This is a change which is ported over to 5.x.  I will be pushing an update here so that it has the same changes as that of [ 6.x](https://github.com/OfficeDev/office-ui-fabric-react/pull/6660).

**Comment by tharshada** [comment]
@mikewheaton, @KevinTCoughlin can you approve & merge this?

**Comment by mikewheaton** [comment]
(Ab)using my admin privileges to merge this as Aditi is out.

**Pull request merged**
