### PR TITLE
Calendar: adding year picking option

### LINKED ISSUE #4610: Feature Request: Provide loverly extended year selection for the Calendar component
Hi,

It'd be loverly (as a start) to replicate the extended year selection available in the non-React version of fabric (see attached images) to the React version of fabric.

calendar-year-selection
calendar-year-selection-open

If I get time I'll hack something into a fork myself (ugh).

Just wanted to say thanks for open saucing fabric and for the work you guys are doing.

Cheers.

### PR DESCRIPTION
**Pull request by gitfish**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4610
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Addition of year picker to Calendar

#### Focus areas to test

Anything Calendar related

### CODE REVIEW

**Comment by JasonGore** [comment]
It looks like you added a new component. Can you add some snapshot and unit tests for this new component showing the behavior you expect? This will help validate your implementation and prevent future regression.

**Comment by dzearing** [comment]
@lorejoh12 Can you make sure to take a look here?

**Comment by dzearing** [comment]
react/src/components/Calendar/Calendar.test.tsx:374:12
ERROR: 374:12  quotemark  " should be '
ERROR: 397:8   quotemark  " should be '
ERROR: 399:39  quotemark  " should be '
ERROR: 399:53  quotemark  " should be '
ERROR: 402:8   quotemark  " should be '
ERROR: 407:38  quotemark  " should be '
ERROR: 407:52  quotemark  " should be '
ERROR: 410:8   quotemark  " should be '
ERROR: 419:43  quotemark  " should be '
ERROR: 419:57  quotemark  " should be '
ERROR: 422:22  radix      Missing radix parameter
ERROR: 430:8   quotemark  " should be '

**Comment by dzearing** [comment]
Tried fixing for you :)

**Comment by lorejoh12** [comment]
any chance you can fix the merge conflicts before I try testing this? I added some code on May 15th, and it looks like you did this PR back on May 10th (sorry I missed it), but there's some significant conflicts between the two.

**Comment by gitfish** [comment]
Hi John,

Yep there were quite a few changes after I submitted this, and mostly it didn’t get to review because of my slackness around the code styling rules.

I’ll try and make some time for it in the next couple of days.

Cheers.

Sent from Mail for Windows 10

**Comment by dzearing** [comment]
Any update? This is a cool update, I'd love to get this working

**Comment by dzearing** [comment]
This has gone idle since June 5th. Please resubmit once you've cleaned up conflicts. It would be great to add this experience.

**Pull request closed without merging**
