### PR TITLE
 Bug Fix: FirstWeekOfYear - with FirstFourDayWeek setting enabled December 2020 has 2 weeks with number 52 #3119

### LINKED ISSUE #3119: FirstWeekOfYear - with FirstFourDayWeek setting enabled December 2020 has 2 weeks with number 52
### Bug Report

- __Package version(s)__: 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

Products/sites affected: OWA Calendar

#### Describe the issue:

microsoftteams-image 1

#### Actual behavior:

Week starting Dec 20 shows as number 52, Week starting Dec 27 also shows 52

#### Expected behavior:

Week starting Dec 20 shows as number 52, Week starting Dec 27 shows as number 53

### PR DESCRIPTION
**Pull request by manas-misra**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3119
- [x] Include a change request file using `$ npm run change`

#### Description of changes

 Week number computation logic was fixed by referring to last day of previous year correctly.
 Added unit tests.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by manas-misra** [comment]
Hi @lorejoh12, can you please review the changes?

**Comment by manas-misra** [comment]
Hi @johannao76 , @dzearing, can you please help to review the changes?

**Comment by johannao76** [comment]
@John Lorenz<mailto:jolore@microsoft.com>, Can you please help review these changes?
________________________________

**Comment by lorejoh12** [comment]
since this is in DateMath and not in the calendar component, Johanna and I don't have permission to actually sign off and check this in for you, I think we need someone from fabric- @dzearing ?

**Comment by johannao76** [comment]
John, we should own DateMath, if not, can you send a PR to update the codeowners file to add us? Also if there are other date related files that are used by the date picker/mini-month we should add us as code-owners for those as well.

Thanks!
-J

________________________________

**Comment by manas-misra** [comment]
@lorejoh12 I saw the code owner update for DateMath. Can you approve the changes now?

**Pull request merged**
