### PR TITLE
Experiments: Fluent styles for ChoiceGroup and more updates

### LINKED ISSUE #6707: ChoiceGroup: Fluent experiment
1. Updating fluent styles for ChoiceGroup in experiments package.
2. Addresses #6116

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6707, #6116
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Also includes some updates to Checkbox, Breadcrumb and Dropdown to address feedback on #6706, #6412, #6701

### CODE REVIEW

**Comment by Vitalius1** [comment]
@mikewheaton @betrue-final-final 
Notice how I changed previously used fluent colors with semanticColors or paletteColor if no semantic one exists. Would appreciate some feedback on any improper use of those... meaning if the semanticColor is not semantically correct used on a region and should be replaced by a paletteColor and vice versa.

**Comment by betrue-final-final** [comment]
It doesn't look like the experiments package has a conversion, so if you're going to use semantic slots, you're going to need to convert them or it won't work.

**Comment by Vitalius1** [comment]
@betrue-final-final 
semanticColors are defined [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/theme.ts#L167-L258) which are using whatever the palette colors you give to your theme. Consequently, in the experiments package, we have the fluent theme [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/experiments/src/components/fluent/FluentTheme.ts#L5-L27) mapping the current colors to the new fluent colors. So when I decide using a semanticColor I am actually making sure the entire chain matches to the fluent specs... the only thing I am still unsure if I am using the correct semanticColor slot for the appropriate situation (ex: when Dropdown is open for the items in the list should I use `menuItemText` or `listText` or `actionLink` and so on...). In the pursuit of matching the fluent specs colors, I feel like we are lacking semanticColor slots so I try to find the closest one semantically, so I need your feedback on their use.

**Comment by Vitalius1** [comment]
@betrue-final-final I will merge this PR so that you can start reviewing the changes and I could submit a folder reorganization PR for the fluent project as the styles file starts to increase gradually. But feel free to look through this PR or the master branch code already on the semanticColor usage.

**Pull request merged**
