### PR TITLE
#787 Fixes broken search bar border in HighContrast mode, add border on hover

### PR DESCRIPTION
**Pull request by aleksandrjPersonal**
#### Pull request checklist

- [ ] Addresses an existing issue: #0000
- [x] Include a change request file if publishing 
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by aleksandrjPersonal** [comment]
@dzearing Should I update the task then remove the search bar from the CommandBar?

**Comment by micahgodbolt** [comment]
@aleksandrjPersonal no...don't remove anything. We'll need to deprecate the props associated with the search field first. Can you close this and open up a new PR with those props deprecated? Happy to show you how that works if you need a hand.

**Comment by micahgodbolt** [comment]
Nevermind, I'll close this.

**Comment by aleksandrjPersonal** [comment]
Ok, I am going to remove this bug from my list. LMK if I need to reopen this for additional work.

**Pull request closed without merging**
