### PR TITLE
Nidurak/fix command bar button as

### PR DESCRIPTION
**Pull request by nickdurak**
#### Pull request checklist

- [x] Include a change request file using `$ npm run change`

#### Description of changes

Fixing the commit made here: https://github.com/OfficeDev/office-ui-fabric-react/commit/038724b414db80b123703a79304d12389e8f8599
such that the commandBarButtonAs is under the correct interface. The motivation for that commit was to sdd support of commandBarButtonAs from the following Commits:
55c0766#diff-06463e29cbbe1d7609db26feebbaabe2
and
c3f996a

#### Focus areas to test

CommandBar

### CODE REVIEW

**Comment by micahgodbolt** [comment]
I know this is the 5.x branch, kinda a breaking change. How difficult would it be to support both in this case, and note that this is not the official 6.x interface.

**Comment by nickdurak** [comment]
> I know this is the 5.x branch, kinda a breaking change. How difficult would it be to support both in this case, and note that this is not the official 6.x interface.

The property is currently only used by an object of type ICommandBarItemProps and is not used by any object of type ICommandBarProps. Given that this is an optional parameter and there is no reason anyone else would be using the property in the wrong interface I would lean toward just moving it completely. With that said, we could leave it in the ICommandBarProps interface with a comment saying no longer in use. Which would you prefer?

**Comment by micahgodbolt** [comment]
i'd feel better deprecating the old one (to denote it'll be gone in 6.x) and just supporting both. Should be able to say 

```
const buttonAs = item.commandBarButtonAs  || this.props.commandBarButtonAs || CommandBarButton;
```

Right?

**Comment by nickdurak** [comment]
> i'd feel better deprecating the old one (to denote it'll be gone in 6.x) and just supporting both. Should be able to say
> 
> ```
> const buttonAs = item.commandBarButtonAs  || this.props.commandBarButtonAs || CommandBarButton;
> ```
> Right?

Will do

**Comment by micahgodbolt** [comment]
@nickdurak hah! I totally forgot that this work was in experiments. I'm sorry nick, I made you make that change for no real reason :D

**Comment by nickdurak** [comment]
@micahgodbolt thanks for cleaning up those change files!

**Comment by nickdurak** [comment]
@micahgodbolt, can you approve the merge? I had to add another change file since Travis CI failed without it

**Pull request merged**
