### PR TITLE
 Website: Add more mobile docs

### PR DESCRIPTION
**Pull request by lynamemi**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

New pages for Android:
- Calendar
- Avatar (decoupled from Persona)
- PeoplePicker (decoupled from Chip)
- Snackbar

New pages for iOS:
- Avatar (decoupled from Persona)
- Popup Menu

Other:
- Added image for iOS ActivityIndicator

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9140)

### CODE REVIEW

**Comment by vladfilyakov** [comment]
It seems that Fabric React is using actual control names on the root page and in the control page headers. On Mobile we are using names in "human" language. In this case we don't need to "merge" words like  Popup Menu, People Picker, List Cells, etc.

**Comment by vladfilyakov** [comment]
"Related pages" section at the bottom of control page has a list of links to related controls.
1) One of them is always a link to "self" - can we remove that?
2) Can we move "web" link down for mobile since it's less relevant than other mobile platform?

**Comment by vladfilyakov** [comment]
Can you please update iOS Avatar View demo screenshots? They don't show square design that we talk about on the page. Also today demo was updated to align with Android demo :-)

**Comment by vladfilyakov** [comment]
iOS > Items & Lists > ListCells - Split into "List Cells" for now, until we have a better name

**Comment by vladfilyakov** [comment]
iOS > Items & Lists > Persona > Control names - Please add MSPersonaCell

**Comment by jordandrako** [comment]
> "Related pages" section at the bottom of control page has a list of links to related controls.
> 1. One of them is always a link to "self" - can we remove that?
> 2. Can we move "web" link down for mobile since it's less relevant than other mobile platform?
@lynamemi You can define a different `Related.md` for each platform, just place them within those platform folders and require them like the other markdown files.

**Comment by vladfilyakov** [comment]
iOS > Progress > Progress Indicator - Rename to "Spinner": I feel it makes more sense (and update references to appropriate controls on other platforms)

**Comment by vladfilyakov** [comment]
Android > Galleries & Pickers - Rename to just "Pickers" like on iOS, also we don't have any galleries yet.

**Comment by vladfilyakov** [comment]
Android > Galleries & Pickers - "Calendar" should be before "Date & Time Picker" - alphabetically (like on Web)

**Comment by vladfilyakov** [comment]
Android > Galleries & Pickers > Date & Time Picker > Implementation > Control name - change to DateTimePickerDialog (currently iOS name is shown there)

**Comment by vladfilyakov** [comment]
Android > Progress > Snackbar - I think this control should be in "Notification & Engagement" category (see Web)

**Comment by vladfilyakov** [comment]
Android > Items & Lists - Move above Progress like on iOS and Web

**Comment by vladfilyakov** [comment]
Android > Items & Lists > Avatar - Can we make screenshots 100% scale? They look too tiny.

**Comment by vladfilyakov** [comment]
Android > Surfaces > Tooltip > Control name - Add "Tooltip" class name

**Comment by vladfilyakov** [comment]
In some control descriptions we mention actual class names. Sometimes we style them to be shown as such, and sometimes they are just plain text. Can we style them in all cases?

**Comment by vladfilyakov** [comment]
Android > Items & Lists > Chip - I'd swap the order of screenshots: first show the actual control, then where it's used (it's done well for Persona).

**Comment by vladfilyakov** [comment]
iOS > Items & Lists > Chip:
1) "Chip States" screenshot should show MSBadgeView demo screen, right?
2) I'd swap the order of screenshots: first chip itself, then badge field where it's used
3) Screenshot and title used for "People Picker" is unrealistic: we don't have people picker yet for iOS - only Badge Field. Better use second screenshot, I think, or get one from demo.

**Comment by vladfilyakov** [comment]
Screenshot scales are not aligned - we use both 100% and what seems like 50%. Maybe make them the same? I'd prefer 100%, but open...

**Comment by lynamemi** [comment]
> "Related pages" section at the bottom of control page has a list of links to related controls.
> 
> 1. One of them is always a link to "self" - can we remove that?
> 2. Can we move "web" link down for mobile since it's less relevant than other mobile platform?

**Comment by lynamemi** [comment]
> "Related pages" section at the bottom of control page has a list of links to related controls.
> 
> 1. One of them is always a link to "self" - can we remove that?
> 2. Can we move "web" link down for mobile since it's less relevant than other mobile platform?

@vladfilyakov I'll do this in a separate PR as it will require a bit of refactoring and new files, and I'd rather keep it organized.

**Comment by lynamemi** [comment]
> Screenshot scales are not aligned - we use both 100% and what seems like 50%. Maybe make them the same? I'd prefer 100%, but open...

@vladfilyakov The pattern I see is that screenshots in tables are scaled at 50% because they're side by side, but single screenshots are at 100%. Maybe @jordandrako has more context for this.

**Comment by vladfilyakov** [comment]
> @vladfilyakov It's easier to respond to comments if they are inline with code where possible - Even if you can put it on file with an example of what you're talking about.

@lynamemi The thing is I was doing a website review, not code review :-) So some comments are not even related to this specific PR, but more to website in general. Besides, I wouldn't even know what file to use for each comment - there are billions of them! :-) I'm sure you know better how to go from piece on website to piece in code. I wish it would be easier to edit this website...

**Comment by ecraig12345** [comment]
> > "Related pages" section at the bottom of control page has a list of links to related controls.
> > 
> > 1. One of them is always a link to "self" - can we remove that?
> > 2. Can we move "web" link down for mobile since it's less relevant than other mobile platform?
> 
> I'll do this in a separate PR as it will require a bit of refactoring and new files, and I'd rather keep it organized.

This would actually be kind of challenging from a technical perspective. We should talk before you start working on it.

**Pull request merged**
