### PR TITLE
Fixing bug dialog content does not grow fully to take up all the space provided by parent

### LINKED ISSUE #4371: [Dialog] Content does not grow fully to take up all the space provided by parent
### Bug Report

- __Package version(s)__: 5.66.0
- __Browser and OS versions__: any browser/os

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low)  Normal

Products/sites affected: (if applicable) Visual Studio Team Services

#### Describe the issue:
Content does not grow fully to take up all the space provided by parent.

#### Actual behavior:
Dialog content takes up the space of its own content

#### Expected behavior:
Dialog content takes up the space provided by its parent

### If applicable, please provide a codepen repro:
https://codepen.io/anon/pen/pLdaQw

### PR DESCRIPTION
**Pull request by serkan-inci**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4371 
- [x] Include a change request file using `$ npm run change`

#### Description of changes
Added width:100% to the dialog content.

### CODE REVIEW

**Comment by dzearing** [comment]
I am nervous without seeing the impact of this change. Screener likes this though, so that's good.

@joschect, @Jahnp as an fyi. Is there someone in OneDrive using dialog that can make sure they are ok with this?

**Comment by MLoughry** [comment]
Should be fine. The parent <div> has a max-width of 340px.

https://github.com/OfficeDev/office-ui-fabric-react/blob/b410f6b9a328dd4ad24cbaa739156c23880e44e4/packages/office-ui-fabric-react/src/components/Dialog/Dialog.styles.ts#L30


-Michael

________________________________

**Comment by serkan-inci** [comment]
The issue is parent container specifies display: flex but content doesn't specify any flex value. I was initially thinking to have ```flex-grow: 1``` but ```width: 100%``` seems a more generic solution in case someone overrides parent display to something other than flex.

And as @MLoughry mentioned, parent also specifies a constant width.

@dzearing

**Comment by dzearing** [comment]
If we made it `display: block` rather than flex, it would also fix. I wonder what the reasoning for flex was.

**Comment by serkan-inci** [comment]
@jordandrako Can you suggest what should be the right fix here since you initially added ```display: flex``` to Dialog?

**Comment by jordandrako** [comment]
Dialog was already `display: flex` before I converted it to mergeStyles. It seems @micahgodbolt changed it to flex about a year ago. https://github.com/serkan-inci/office-ui-fabric-react/commit/26f605dfe92f82b11dec6bf9c46bbd9cb71f0d8c

**Comment by micahgodbolt** [comment]
flex has better support for vertical centering, which you can [see above](https://github.com/serkan-inci/office-ui-fabric-react/commit/26f605dfe92f82b11dec6bf9c46bbd9cb71f0d8c#diff-121c57c445f8aca464b41da74c7c4869R20) that flex change.

**Comment by serkan-inci** [comment]
Thanks Micah, done.

@micahgodbolt

**Comment by serkan-inci** [comment]
Can we get this merged if you're OK with the fix? We are about to move to a newer version and want this issue fixed. Thanks.

@dzearing @micahgodbolt

**Pull request merged**
