### PR TITLE
SearchBox: added the ariaLabel optional property

### LINKED ISSUE #1670: SearchBox: Allow setting aria-label
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: Chrome win10

Are you willing to submit a PR to fix? No

Requested priority: High 

Products/sites affected: Office ui fabric react components - SearchBox Component and all websites using this component.
Can be seen here: http://dev.office.com/fabric#/components/searchbox 

#### Describe the issue:
Go to [SearchBox Component](http://dev.office.com/fabric#/components/searchbox)
Use this tool: [Google Accessibility - Accessibility Developer tools](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb)
and run an audit from the Audits tab in the Developer tools in chrome.

#### Actual behavior:
There's a severe level error being thrown saying "Controls and media elements should have labels" for all references of SearchBox components in the page.
image
The link [AX TEXT 01](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_text_01)

#### Expected behavior:
All control and media elements should have labels.
I have tried the labeltext option for SearchBox component, but it only adds the placeholder text and not a label to the component whereas it's needed to use label/aria-label instead. (Ref: [Audit rules - AX -TEXT 01](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_text_01) as can be seen that it's recommended to not use only placeholder)

### If applicable, please provide a codepen repro:
Can be seen here: [SearchBox component](http://dev.office.com/fabric#/components/searchbox)

### PR DESCRIPTION
**Pull request by jakob101**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1670
- [x] Include a change request file if publishing 
- [x] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [x] Documentation update

#### Description of changes

Added an optional property ariaLabel for the SearchBox input component. It defaults to the value of the labelText property.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by jakob101** [comment]
I do need to do "rush change" for this, right?

**Comment by jakob101** [comment]
My first PR here!

**Comment by micahgodbolt** [comment]
@jakob101 congrats on your first PR! Yup. Just run `rush change` and fill out the form that pops up in the terminal. What you put in that file will show up in our release notes so put something just like your PR title 

SearchBox: added the ariaLabel optional property

Once that's in we should be able to merge this in pretty quick!

**Comment by dzearing** [comment]
@jakob101 nice :)

**Comment by jakob101** [comment]
Thx guys. I did the rush change, what's next?

**Comment by micahgodbolt** [comment]
Now we do the dance of joy

image

And merge

**Pull request merged**
