### PR TITLE
ComboBox: Optional getStyles prop for options 

### PR DESCRIPTION
**Pull request by kysedate**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x ] Include a change request file using `$ npm run change`

#### Description of changes

This change gives ComboBox options an optional getStyles prop which will allow for a full override of combobox option styles. Today, they are simpy merged with fabric styles, which is not ideal for teams that want to buffer themselves from potential style breaks. 

#### Focus areas to test

I have validated that with this change, ComboBox options can have their styles overridden completely. When the getStyles prop isn't present on a ComboBoxOption, there is no change to how styles are calculated today.

### CODE REVIEW

**Comment by cliffkoh** [comment]
I think this change might be controversial. We cannot have an opt-out switch randomly for just 1 component like this - and its coexistence with `styles` (and the fact it was previously called `getStyles` in Fabric 5) are all likely future sources of confusion and frustration. 


Assigning this PR to @dzearing and @micahgodbolt.

**Comment by micahgodbolt** [comment]
There is no issue that this PR addresses, so can you describe what you are having trouble doing without this update? I'm confident we can figure out a solution that's inline with how the rest of fabric works.

**Comment by micahgodbolt** [comment]
Oh, so you want to be able to provide ALL of the styling vs mixing in with our default styles? Sounds like we should give you access to a .base file, and let you supply your own styles function.

**Comment by cliffkoh** [comment]
@kysedate There are two better approaches:

1) Instead of using ComboBox, use `BaseComboBox` which comes completely unstyled and supply your own styling (you can make use of the `styled()` helper).

2) To help ensure your team is not vulnerable to visual regressions from Fabric, the best thing to do is to check in a Screener test (in `apps/vr-test`) for the specific scenario. If you're not familiar with Screener tests, it is actually quite easy/straightforward to write a test for it.

**Comment by cliffkoh** [comment]
Hmm.. I just realized we don't uniformly export the Base***** components. In fact, most of the times, we do not but there are some components for which we do.

This is something we should fix. I will open an issue for it.

**Comment by kysedate** [comment]
That's correct. I actually sent out a [PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/3868) for this in February, but I found issues with allowing a complete overwrite of base styles AND subcomponent styles with that model. I discussed with @dzearing and there wasn't a good solution at that time.

**Comment by kysedate** [comment]
If this isn't the right solution, I'll abandon the PR. But I'd like to have some more confidence in the component going forward.

**Comment by cliffkoh** [comment]
@kysedate The best way to ensure Fabric does not break scenarios important to downstream consumers is for downstream consumers to add tests into Fabric that assert their expectations w.r.t. the scenarios. I highly recommend adding a visual regression test here.

**Comment by kysedate** [comment]
@cliffkoh I don't believe there was a regression in the Fabric ComboBox in this scenario. Different classnames were targetted in the PR I mentioned, which seems to have worked fine for this component, but caused a regression in our implementation. To be a bit more specific: the getFocusStyle() styles from the combobox used to target '.ms-Fabric.is-focusVisible &:focus:after', but was changed to '.ms-Fabric.is-focusVisible &:after'. This caused the associated styles to apply to our 'focused' options, whereas before they never did. I don't think additional visual automation in fabric would have caught it. The only protection would have been either more extensive automation testing on our end, or the ability to supply all of the styles ourselves.

**Comment by micahgodbolt** [comment]
@kysedate looking at #5399 again, it seems the intention was to properly set a boreder style when the item was checked, which came from this bug #3472 stating that the checked state was missing styling.

This is an unfortunate problem where a 'fix' on our end is perceived as a bug downstream. Unfortunately, when it comes to components being to spec vs fearing that alignment might break someone, we have to move towards alignment. This is the same principle that lead us to change default directionHintFixed to false on dropdowns and comboboxes #5771 

So solutions going forward:

1. Invest in visual regression tests. We test our own components in this way, but when we saw a border added to combobox on checked, we saw that as a fix, not as a bug. Having your own tests would allow you to evaluate those visual changes and determine if they are correct for you, or breaking.
2. If you have custom styled components, and would rather not worry about upstream visual changes breaking your design, start using the base component and supplying your own set of styles.
3. Be sure to review release notes as you update Fabric.  I know that can be a bit of a firehose, but any mention of visual changes to Fabric component should be a good reason to review those in your application
4. We'll continue to try and be more transparent about visual/functional changes. When we know our change has the possibility to cause downstream regressions (even if it's a fix, or moving things more towards spec) we'll be more vocal about those changes.


Anyway, I'm going to close this up, but it's been great to dig into this and become aware of how our "fixes" can be perceived as "bugs" if not properly communicated.

**Pull request closed without merging**
