### PR TITLE
Adding props that take bolding for the content in each cell of gridlist

### PR DESCRIPTION
**Pull request by dezverev**
#### Description of changes

Adding props that take bolding for the content in each cell of gridlist

### CODE REVIEW

**Comment by samiyaakhtar** [comment]
Can you add a screenshot of the change to the PR?

**Comment by dezverev** [comment]
girdlistbold
 screenshot

**Comment by samiyaakhtar** [comment]
Hi @micahgodbolt would you know why the screener has been failing lately?

**Comment by KevinTCoughlin** [comment]
> 
> 
> Hi @micahgodbolt would you know why the screener has been failing lately?

Likely due to the break fixed with #6423. Can you merge master so the tests re-run?

**Comment by KevinTCoughlin** [comment]
@dezverev would you be able to merge `master` into your branch. I believe this PR build will succeed and we can get this merged.

**Pull request merged**
