### PR TITLE
Toggle: add inlineLabel prop to render label on a side.

### LINKED ISSUE #7547: textLeft option in Toggle component
The toggle component in Fabric-JS has a "textLeft" option, as demonstrated in the last example  [here](https://developer.microsoft.com/en-us/fabric-js/components/toggle/toggle).

This option does not however seem to have been ported to the corresponding React "Toggle" component (or if it supported, I cannot find a way to make it work).  

(This could either be a question or a feature request, depending on the situation. Thanks!)

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #7547 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Came as a feature request, but apparently, this variation was already included in the toolkit but never made the code implementation.

screen shot 2019-01-10 at 11 59 36 am

1. Adds `inlineLabel` prop to enable optional rendering with the label on the left (right in RTL) side.
2. Ads a styling prop `onOffMissing` to check whether the user provided `onText` and `offText` props. When used with the new `inlineLabel` prop it will render the label on the left side if on/off are provided and on the right side if none are given.
3. Made a minor adjustment to the already existing margin between the toggle and the on/off text as per designer request.

Also added some screener stories, examples and snapshots.
screen shot 2019-01-11 at 6 09 38 pm

## in RTL

screen shot 2019-01-11 at 6 08 51 pm

### CODE REVIEW

**Comment by ecraig12345** [comment]
I'd just been wanting this--nice! Question though, why is the label always on the left? I guess I can see why that would be needed if the toggle displays custom on/off state text, but without the custom text it seems more natural to have the label to the right of the toggle (like with checkboxes).

**Comment by betrue-final-final** [comment]
@ecraig12345, well, I guess you could have the label on the right, but you would then want the state (on/off) on the left then, or the label and value gets a bit confusing.

**Comment by Vitalius1** [comment]
@betrue-final-final to be fair, it does look nicer to have the label on the right of the `Toggle` like in the screenshot @ecraig12345 posted. There are a couple of scenarios to look into:
1. on/off present:
    * user specifies it wants the label on the left (OK)
    * user specifies it wants the label on the right (NOT OK) - should we flip the on/off on the other 
side automatically?
2. on/off not present:
   * we can render the label on both sides if the user wants.

**Comment by Vitalius1** [comment]
Actually I don't think we want to ever have the on/off on the left. In case the on/off text is different in length it will shift the entire right side of it:


So the question is should we do something like that:
In case the user wants the label inlined with the toggle he passes the prop. Then we check if he provided the on/off text then we leave the label on the left side. In case he did not provide one we can place it on the right. All this can be explained in the documentation of the `inlineLabel` prop.

**Comment by betrue-final-final** [comment]
Yes I see. We could have the option like you suggeat, but buyer beware that people may not be clear if it's off or on. Is blue "sunken" and off, or active and on?

**Comment by Vitalius1** [comment]
All this can be documented and make sure the consumer understands that not having on/off text may bring some confusion to app users. @ecraig12345 do you think this could satisfy both camps)))

**Comment by ecraig12345** [comment]
@Vitalius1 That sounds good to me, though I can also understand @betrue-final-final 's concern about it not being obvious which state is off.

**Comment by KevinTCoughlin** [comment]
Thanks for adding all of the test coverage @Vitalius1!

**Comment by Vitalius1** [comment]
Need to add something... reviews are welcome but no merge yet.

**Comment by dzearing** [comment]
@Vitalius1 are you good with this?

**Comment by Vitalius1** [comment]
Yeah I am. Let me solve the conflicts and push a fix.

**Comment by Vitalius1** [comment]
Hmmmm conflicts again 😭

**Pull request merged**
