### PR TITLE
Dropdown placeholder text

### LINKED ISSUE #1678: Dropdown: Add placeholder text
Users would like to be able to support placeholder text in our dropdown like this:
image

Unfortunately, the only current way to do this is to set the 1st item in the list as the placeholder text and default the dropdown to this item.
image

This is obviously not the preferred method as it makes the drop down choices a bit confusing, messes with alignment (margins are different when not an actual link), and the dropdown looks to be already selected, even though the user still needs to make a selection.

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1678

### CODE REVIEW

**Comment by micahgodbolt** [comment]
dropdown

**Comment by dzearing** [comment]
lint errors

**Comment by dzearing** [comment]
fixed them for you

**Comment by micahgodbolt** [comment]
Thanks @dzearing last minute PR at the end of my day with a dying battery :)

**Pull request merged**
