### PR TITLE
Design update to PR Deployed Sites

### PR DESCRIPTION
**Pull request by mikewheaton**
#### Pull request checklist

- [x] Addresses an existing issue: N/A
- [x] Include a change request file using `$ npm run change: N/A

#### Description of changes
The PR Deployed Sites page ([example](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/7978/merge/)), which is linked to in every pull request to make it easier to review the changes, was functional but very basic:

image

I've spruced it up a bit:
image

The page now has a title and brief summary to explain what it's for, and the links have been replaced with tiles with icons. This will make it easier to scan and find the package you're looking for. And there's a blob for fun. I ran it by a designer and got the thumbs up.

We have some ideas for improving the page, but this is at least a step forward for now.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/7980)

### CODE REVIEW

**Comment by kenotron** [comment]
A thousand times YES!

**Comment by Jahnp** [comment]
This looks really nice! Love the improvements and use of tiles + icons. 

I admit the blob feels a little odd somehow, though. I've usually seen those blobs as backdrops to more complex illustrations, where the shape itself kind of recedes. Here the blob contrasts REALLY strongly and feels like it grabs a lot of attention. Does that make sense? I wonder if it'd be more effective if it were a little more subtle.

**Comment by mikewheaton** [comment]
I was hoping to get an illustration from design but haven't had any luck there yet. A background element helps to anchor the tiles and adds some visual interest but I agree this is quite strong.

How about a lighter tint and a smaller blob?

image

**Comment by Jahnp** [comment]
Yeah it's just the contrast/strength of the blob that feels distracting in this context. Totally agree that layout needs some visual interest to tie it together.

The sketch you have is an improvement for sure! I'd be curious to see it even lighter/lower contrast--closer to a "background texture" than a solid element. Does that make sense? Thoughts?

**Comment by mikewheaton** [comment]
Here it is even lighter:
image

Or we could remove it entirely:
image

**Comment by Jahnp** [comment]
Thanks for humoring me and iterating on this, @mikewheaton . Now that I see it, I lean a little more towards 2 and a little less towards 3, but both over no blob at all. What do you think? Honestly any of these are great and I don't want to stop progress on a blob 😂

**Comment by mikewheaton** [comment]
Alright, let's go for the second one with the lighter tint!

It's hard to add personality without crossing the line to goofy or distracting. I'd love to get some sort of illustration we could just anchor to the bottom of the page. Anything to avoid another page that's just grey on grey on grey.

**Comment by kenotron** [comment]
I would have loved to see the blobs actually animate like lava lamps... but oh well :)

**Comment by Jahnp** [comment]
@kenotron we're saving that one for v2!

**Pull request merged**
