### PR TITLE
Add example of using CommandBarButtonAs with coachmarks and add IComponentAsProps

### PR DESCRIPTION
**Pull request by nickdurak**
#### Pull request checklist

- [x] Include a change request file using `$ npm run change`

#### Description of changes

Continuation of https://github.com/OfficeDev/office-ui-fabric-react/pull/6354

Add example of using CommandBarButtonAs with coachmarks and add IComponentAsProps

#### Focus areas to test

CommandBar and IComponentAs

### CODE REVIEW

**Comment by nickdurak** [comment]
commandbarbuttonasexample

**Comment by micahgodbolt** [comment]
Just wanted to note that this appears to be a change, right? 
image

**Comment by nickdurak** [comment]
@micahgodbolt can you elaborate on the comment above?  That is an intentional change on my part so consumers can use the IComponentAsProps type. Under the hood it is the same interface for IComponentAs<T>, just extracting the props into it's own type.

**Comment by micahgodbolt** [comment]
@nickdurak oh sorry...I didn't notice this mentioned in the title. Wanted to make sure this was an intentional change as I at first thought this was 100% docs

All good.

**Pull request merged**
