### PR TITLE
Theming: fix font variables passed to legacyLoadTheme

### PR DESCRIPTION
**Pull request by phkuo**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Fix font variables passed to legacyLoadTheme so that they actually work.
Backport of #10106

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10107)

### CODE REVIEW

**Comment by phkuo** [comment]
@msft-github-bot automerge after Natalie has reviewed.

**Comment by phkuo** [comment]
@msft-github-bot merge this change after Natalie Ethell has reviewed it.

**Comment by phkuo** [comment]
@msft-github-bot merge after @natalieethell has reviewed

**Comment by phkuo** [comment]
@msft-github-bot YES

**Comment by phkuo** [comment]
@cliffkoh 😭

**Comment by cliffkoh** [comment]
@msft-github-bot merge after @natalieethell has reviewed

**Comment by phkuo** [comment]
@cliffkoh 😂😂😂😂😂😂😂

**Comment by cliffkoh** [comment]
let's try again. merge after @natalieethell has reviewed

**Comment by cliffkoh** [comment]
@msft-github-bot  merge after @natalieethell has reviewed

**Comment by cliffkoh** [comment]
💪

**Pull request merged**
