### PR TITLE
DetailsList: export DetailsHeader

### PR DESCRIPTION
**Pull request by natalieethell**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Exports APIs from DetailsHeader, DetailsHeader.base, and DetailsHeader.types. This allows customization of the DetailsHeader and removes api-extractor warnings in the api.md file.

I also noticed that `IDetailsHeader` was duplicated, so I removed the declaration in DetailsHeader.base, and instead reference the one in DetailsHeader.types.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8849)

### CODE REVIEW

**Comment by natalieethell** [comment]
Going to fix some weirdness in the api.md file diff

**Comment by aftab-hassan** [comment]
Looks like we do not have baseline information for the baseline for this PR, and so size auditor reports the size bump as the entire size of the PR.

I can look at why the baseline commit https://github.com/OfficeDev/office-ui-fabric-react/commit/5c78f7e4c7a08715cdfde21981fd48c6d59c1e62 did not trigger a run on size auditor. In the meanwhile, if anyone has an idea, please let me know as well.

I can also have a PR soon to change size auditor behavior to report a message along the lines of `Insufficient baseline information` in such cases, for future PRs

https://github.com/OfficeDev/office-ui-fabric-react/pull/8861#issuecomment-487232510

**Comment by natalieethell** [comment]
Adding a Do Not Merge label while I figure out the weird api.md formatting

**Comment by KevinTCoughlin** [comment]
Worst case we can probably open a new PR to update baseline info (this time hopefully successfully).

**Pull request merged**
