### PR TITLE
Fix 404 with universal header "Skip to main content" tab stop

### LINKED ISSUE #9563: "Skip to content" link does not work on Fabric documentation page
## Reproduce

1. Open [a page of Fabric component documentation](https://developer.microsoft.com/en-us/fabric#/controls/web/focuszone)
1. On page load, tab once until you see the "skip to main content" section appear.
1. Press enter.

## Actual behavior:

1. Navigates to a 404 page.

## Expected behavior:

1. Page scrolls to (& focus starts at) content.

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9563
- [x] Include a change request file using `$ npm run change`

#### Description of changes

The universal header on the Fabric documentation site has a tab stop for jumping to main content as per [accessibility specs](https://www.w3.org/TR/WCAG20-TECHS/G1.html). The anchor points to `#mainContent` which is not currently handled by our site and therefore results in a 404.

See https://developer.microsoft.com/en-us/fabric#mainContent

The solution here is to add a redirect to our "Getting started" route for `#mainContent`.

The header's DOM:

image

This might need to be cherry-picked for previous releases of the website cc: @ecraig12345.

#### Focus areas to test

I replicated the scenario to the best of my ability locally since we lack the header in local dev.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9570)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
> `#mainContent` is meant to go to the main content of the current page, not to navigate. So unfortunately I think some more specialized handling will be required here.

@ecraig12345 @jordandrako, as area owners do you have a recommendation as to what element that would be site-wide. Perhaps this container:

image

Knowing the above would help me provide a fix. Thank you.

**Comment by ecraig12345** [comment]
Just fixing the element it points to won't solve the issue. Since we use hash routing, we'll have to add handling to stop hash change events with `#mainContent` and make our own corrected update to the hash instead. It might be easiest for me to just fix this because I have a better idea of where the code is.

**Comment by KevinTCoughlin** [comment]
> Just fixing the element it points to won't solve the issue. Since we use hash routing, we'll have to add handling to stop hash change events with `#mainContent` and make our own corrected update to the hash instead. It might be easiest for me to just fix this because I have a better idea of where the code is.

I'm aware of what would be required to navigate relative to a page and like to learn. But if you wish to fix, go ahead.

**Comment by ecraig12345** [comment]
The complicating factor in the website is that URLs can have two hashes: first for the route and second for the anchor within the page (and now that I think about it, although we have manual handling for scrolling to an anchor within the page, we don't currently update focus to match--should probably fix that). There are also multiple places within the website code that listen for hash changes, so we'd have to make sure the `#mainContent` hash change is detected and canceled at the appropriate spot.

**Comment by ecraig12345** [comment]
Sorry my response earlier wasn't more helpful. I *think* the place to fix this would be in `example-app-base/src/utilities/redirects.ts`--add a parameter for the [event](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange#The_hashchange_event) and if `event.newURL` includes `#mainContent`, cancel the event and/or redirect back to `event.oldURL`. Then in theory, scrolling to `#mainContent` should be handled by other code in the app. 

The most straightforward place to update the focus would probably be in `example-app-base/src/utilities/jumpToAnchor.ts`.

**Comment by KevinTCoughlin** [comment]
> Sorry my response earlier wasn't more helpful. I _think_ the place to fix this would be in `example-app-base/src/utilities/redirects.ts`--add a parameter for the [event](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange#The_hashchange_event) and if `event.newURL` includes `#mainContent`, cancel the event and/or redirect back to `event.oldURL`. Then in theory, scrolling to `#mainContent` should be handled by other code in the app.
> 
> The most straightforward place to update the focus would probably be in `example-app-base/src/utilities/jumpToAnchor.ts`.

Perfect, this is extremely helpful. I will take another pass at this as part of my current shield rotation.

**Pull request closed without merging**
