### PR TITLE
Use role="alert" instead of aria-live="assertive" on error message container when TextField error present

### LINKED ISSUE #3902: [TextField] Accessibility- Error message not announced in most browser/screen reader combos
### Bug Report

- __Package version(s)__: 5.40

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Planner

#### Describe the issue:

The error message has aria-live="assertive" set, but this does not result in an announcement in all browsers and screen readers.

#### Expected behavior:

Screen readers should announce the alert. I have found adding both role="alert" and aria-live="assertive" works fairly well.

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3902
- [x] Include a change request file using `$ npm run change`

#### Description of changes

The error message content for TextField input in error state aren't announced by most browser/screen reader combos as described in #3902. The suggested solution by @daweffe and [ARIA docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role) is to use `role="alert"` on the error message `<div/>`.

As per the documentation:

>The alert role is used to communicate an important and usually time-sensitive message to the user. When this role is added to an element, the browser will send out an accessible alert event to assistive technology products which can then notify the user about it. The alert role is most useful for information that requires the user's immediate attention, for example:
>- An invalid value was entered into a form field 

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role#Description

Also note that this `role="alert"` replaces `aria-live="assertive"` because:

> Using the alert role on an element implies that element has aria-live="assertive".

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role#Notes

#### Focus areas to test

Enter incorrect input to an example `TextField` with a screen reader on i.e. [Narrator Buddy](https://support.microsoft.com/en-us/help/17173/windows-10-hear-text-read-aloud). When the error message appears you should receive an alert notifying you of the error. The element does not need to have focus as described in the docs.

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
I used Narrator w/ Firefox and Chrome... Edge was being weird for me. Here's the Narrator Buddy output:

Input Used on local dev site:

image

### With Change

Firefox + Narrator:

```
TextField has both description and error message., editing text, capital <say-as interpret-as="spell">I</say-as>, 
end of line
<say-as interpret-as="spell">k</say-as>
<say-as interpret-as="spell">e</say-as>
<say-as interpret-as="spell">v</say-as>
TextField has both description and error message., editing text, kev, 
Alert ,  
The length of the input value should less than 3, actual is 3., editable text, 
```

Chrome + Narrator

```
capital <say-as interpret-as="spell">K</say-as>
<say-as interpret-as="spell">e</say-as>
<say-as interpret-as="spell">v</say-as>
<say-as interpret-as="spell">i</say-as>
<say-as interpret-as="spell">n</say-as>
```

### Without Change

Firefox + Narrator

```
capital <say-as interpret-as="spell">K</say-as>
<say-as interpret-as="spell">e</say-as>
<say-as interpret-as="spell">v</say-as>
TextField has both description and error message., editing text, Kev, 
<say-as interpret-as="spell">i</say-as>
<say-as interpret-as="spell">n</say-as>
TextField has both description and error message., editing text, Kevin, 
```

Chrome + Narrator

```
capital <say-as interpret-as="spell">K</say-as>
<say-as interpret-as="spell">e</say-as>
<say-as interpret-as="spell">v</say-as>
<say-as interpret-as="spell">i</say-as>
<say-as interpret-as="spell">n</say-as>
```

When I test this in Edge my alphanumeric keys jump me around the page rather than keying input 0_0... any luck on your end?

It looks like the change is beneficial given that it notifies the user with "alert" and reads the error message which it wasn't doing before in my testing.

**Comment by KevinTCoughlin** [comment]
I think the old test checks for `aria-live="assertive"` so the CI is failing -- let me fix now

**Comment by betrue-final-final** [comment]
Narrator should not work very well or predictably in Chrome or Firefox. I would try Edge still.

**Comment by KevinTCoughlin** [comment]
Yea.. I need to figure out why I can't key input in Edge when Narrator is on.

**Comment by KevinTCoughlin** [comment]
### With Change

Edge

```
capital <say-as interpret-as="spell">K</say-as>
<say-as interpret-as="spell">e</say-as>
<say-as interpret-as="spell">v</say-as>
<say-as interpret-as="spell">i</say-as>
<say-as interpret-as="spell">n</say-as>
alert, The length of the input value should less than 3, actual is 5.
```

### Without

Edge

```
capital <say-as interpret-as="spell">K</say-as>
<say-as interpret-as="spell">e</say-as>
<say-as interpret-as="spell">v</say-as>
<say-as interpret-as="spell">i</say-as>
<say-as interpret-as="spell">n</say-as>
The length of the input value should less than 3, actual is 5.,
```

**Pull request merged**
