### PR TITLE
adding string index sig to IButtonProps

### LINKED ISSUE #10896: IButtonProps should support string index sig
#### Describe the feature that you would like added

Be able to pass arbitrary props such as data- and aria- to a Button through an object spread onto it. Currently you can only do this in JSX.

#### What component or utility would this be added to
IButtonProps

#### Have you discussed this feature with our team, and if so, who

Not yet

### PR DESCRIPTION
**Pull request by brandonthomas**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #10896
- [x] Include a change request file using `$ yarn change`

#### Description of changes

- expose string index signature for IButtonProps.

#### Focus areas to test
That Buttons can take arbitrary props from objects being spread into them. Such examples include aria- and data-

const myObject = {
“data-test-id”: “anId”
}

<Button {...myObject}\>

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10897)

### CODE REVIEW

**Comment by brandonthomas** [comment]
I'm also hoping to backport to 6.x

**Comment by dzearing** [comment]
@khmakoto If I understand correctly, here's exactly the problem:

```tsx
// Sweet
<PrimaryButton data-foo="bar"/>

// Not sweet
const things = { ['data-foo']: 'bar' };
<PrimaryButton {...things } />
```

**Comment by brandonthomas** [comment]
@dzearing yup that’s exactly the issue. Not sure how else to solve. I talked to Jason about this issue and he forwarded me a typescript issue tracking how we can better type things like this. Currently it’s not possible.

**Comment by brandonthomas** [comment]
Updated the description to better reflect testing focus

**Comment by khmakoto** [comment]
@dzearing then, is this something we want to allow? Since like we can lose some of the benefits from typing if we do this but I'm not completely opposed to it.

**Comment by brandonthomas** [comment]
@khmakoto how else can we support things like data- props being spread in? If there's another way to spread in a data object I'm more than happy to do that instead. It is weird that you can do this within JSX but not on the object of the same type.

**Comment by dzearing** [comment]
We should ask the TypeScript team.

**Comment by brandonthomas** [comment]
The issue is we need it for a library we make on top of Fabric so our consumers may or may not know this. For now they can do what you mentioned or ts-ignore the next line which is also less than ideal. Currently this isn't possible to support any other way but there is a thread around this. For the data- and aria- issue specifically Ryan Cavanaugh said they would open an issue on it directly.

Sort of linked to the following: https://github.com/microsoft/TypeScript/issues/6579

**Comment by brandonthomas** [comment]
@dzearing I'm curious why this is not ok here but is ok in other parts of Fabric. Is there a specific reason for this or did the other examples just slip through?

**Comment by micahgodbolt** [comment]
Seeing that we aren't wanting to drop a wildcard into button, should we close this PR down and open an issue tracking this problem?

**Comment by brandonthomas** [comment]
> 
> 
> Seeing that we aren't wanting to drop a wildcard into button, should we close this PR down and open an issue tracking this problem?

As long as we address the underlying issue that we want to be able to pass valid props to components through an object. At the moment the only way to do this is the tsignore which is gross

**Comment by ecraig12345** [comment]
> As long as we address the underlying issue that we want to be able to pass valid props to components through an object. At the moment the only way to do this is the tsignore which is gross

In Fabric we typically use casts to `any` instead of outright tsignore. Still not great but slightly less nuclear.

**Comment by micahgodbolt** [comment]
yeah, casting to any on a per need basis is better than forcing the interface to basically be 'any' for everyone at all times.

**Pull request closed without merging**
