### PR TITLE
Change the way that people picker renders items.

### PR DESCRIPTION
**Pull request by joschect**
Allows parent components to specify how people picker items will be rendered.

### CODE REVIEW

**Comment by ericthompson** [comment]
@joschect - would you mind putting some screenshots up of the changes here?

**Comment by joschect** [comment]
@ericthompson Hey Eric. I will probably remove this pull request. I spoke with @dzearing about this and the change has increased in scope. You can find the branch that I'm working on [here](https://github.com/joschect/office-ui-fabric-react/tree/pickerUpdate). It is not ready to check in yet.

**Comment by ericthompson** [comment]
Sounds good!

**Comment by dzearing** [comment]
No longer necessary.

**Pull request closed without merging**
