### PR TITLE
Fabric icons update

### PR DESCRIPTION
**Pull request by srideshpande**
Updating fabric icons in **office-ui-fabric-react's**  `@uifabric/icons` package

### CODE REVIEW

**Comment by lynamemi** [comment]
not sure why the build isn't starting - closing and opening to prompt it

**Comment by lynamemi** [comment]
Oh darn, I'm seeing a build failure for the 6pointedstar and 12pointedstar - @Jahnp how do you want to handle that enum issue?

**Comment by srideshpande** [comment]
@lynamemi - can you paste here, the error you are seeing?

**Comment by srideshpande** [comment]
Yeah I see those errors in the build log now.

**Comment by lynamemi** [comment]
Yeah, it's weird, it looks like a build of your did go through, but it's not updating here

**Comment by Jahnp** [comment]
Ahh shoot, yes, it's tripping on the numerals. I forget how we handled this in Fabric Core, but I we had a similar problem there. @mikewheaton, do you know if we did any special work in Core to support those two values?

Sent on the go
________________________________

**Comment by Jahnp** [comment]
We may need to temporarily rename the enum values to SixPointStar and TwelvePointStar to get around the numerals issue.

Sent on the go
________________________________

**Comment by mikewheaton** [comment]
We haven't done anything special in Core to handle those icon names. Can enums not start with numbers?

**Comment by lynamemi** [comment]
Yep, that's the error, no enums starting with numbers.

**Comment by lynamemi** [comment]
To get us unblocked for now, can @srideshpande  implement what you recommended above, @Jahnp ?
```
SixPointStar = '6PointStar',
TwelvePointStar = '12PointStar',
```

**Comment by srideshpande** [comment]
If I implement that, hopefully no one will break.

**Comment by lynamemi** [comment]
Yeah, we would definitely need to come up with a longer term solution - same with the logos

**Comment by Jahnp** [comment]
I think that's the right thing to do, yes, since we likely don't want to remove them altogether. I can start a thread with the icons team about potentially renaming those symbols since I doubt we'd be the only team affected by this. Numerals in symbol names are [generally](https://stackoverflow.com/questions/342152/why-cant-variable-names-start-with-numbers) [a bit sketchy](https://www.quora.com/Can-a-variable-name-start-with-a-number).

**Comment by Jahnp** [comment]
It'd be a bit painful, but we could make some changes to the icon subsetting tool to make some of these corrections at build time. It would just separate Fabric's symbol name set from the icons team's source.

**Comment by lynamemi** [comment]
Icon changes are no longer breaking screener! Once we get a clean screener on master, we'll be able to get one here and close this.

**Comment by srideshpande** [comment]
Good to know. Thanks!

**Pull request merged**
