### PR TITLE
Copy over hasDynamicChildren and hasMenu for persisted keytips

### PR DESCRIPTION
**Pull request by kelseyyoung**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

When a persisted keytip triggers its execute function, it's expected that the "regular" keytip gets registered and set as the new current keytip in KeytipLayerBase.processInput. However, latency can mean that this registration comes slightly too late, just after the check to exit keytip mode.

This fix copies over the 'hasDynamicChildren' and 'hasMenu' properties for the persisted keytip, so that if latency is hit we don't exit keytip mode early since these properties will be checked. Functionality is the same for normal scenarios, this is just a backup check in case the default scenario wasn't properly hit

#### Focus areas to test

Tested in cases of low latency (where bug was originally found). Tested in "normal" environment where things are unchanged

### CODE REVIEW

**Comment by ecraig12345** [comment]
Build failed for reasons not related to this change. Closing the PR and reopening to trigger a new build.

**Comment by KevinTCoughlin** [comment]
@kelseyyoung, curious -- is it possible to simulate the latency you're describing so that this scenario can be unit tested? Seems like an edge-case scenario that could potentially regress in the future.

**Comment by ecraig12345** [comment]
Triggering new build...

**Comment by kelseyyoung** [comment]
@KevinTCoughlin good idea, I think I might be able to do it by adding a long timeout to a persisted keytip execute function...will give it a shot

**Comment by kelseyyoung** [comment]
Added a delayed test, and I actually needed to fix a few more unit tests as some delayed checking was incorrect...the code was functioning correctly but the tests were not correctly asserting. So it's a good thing I looked!

**Pull request merged**
