### PR TITLE
Adds 'justifySelf' to IRawStyleBase (Fixes #6069)

### LINKED ISSUE #6069: [merge-styles] justifySelf is missing in IRawStyleBase
### Bug Report 
 I am unable to use `justify-self` on styles processed by `merge-styles` as it is not defined in `IRawStyleBase`

See https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self for definitions.

 
- __Package version(s)__: 
@uifabric/merge-styles: 6.7.0
- __Browser and OS versions__:
n/a
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes.
 
Requested priority: High (Haven't identified a workaround).
 
Products/sites affected: n/a

### PR DESCRIPTION
**Pull request by redoz**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6069
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Adds `justifySelf` to `IRawStyleBase`

First attempt at PR for this project, my excuses in case I've missed something.

### CODE REVIEW

**Comment by redoz** [comment]
So that didn't work, how can I find the underlying error behind this:
`[@uifabric/merge-styles] [error] 'Returned error code: 1'`  ?

**Comment by micahgodbolt** [comment]
This is great stuff! Thanks for the contribution and documentation around those w3 css types.

**Comment by redoz** [comment]
@micahgodbolt Thanks, and you're welcome :) 

Could you maybe explain how `.\api\merge-styles.api.ts` is maintained and if I need to do something to add the property to that as well? Once I get this one rounded out I'll submit a PR for #6068 as well.

**Comment by micahgodbolt** [comment]
@dzearing is merge-styles.api.ts a generated file left over from some API extractor work? Doesn't seem updated in quite some time.

**Comment by micahgodbolt** [comment]
@redoz are you here at Microsoft? If so, make sure you hop into our teams channel and say hello. Microsoft UI Fabric

**Comment by redoz** [comment]
@micahgodbolt Afraid not, thanks for the invite though.

**Comment by micahgodbolt** [comment]
@redoz then even larger kudos for the contribution! Hope you're finding Fabric useful.

**Pull request merged**
