### PR TITLE
New button experimets with getStyles approach

### PR DESCRIPTION
**Pull request by micahgodbolt**
I started this work aiming at a 6.0 release, but there is WAY too much left to do, and I'd rather get more input on the effort as this is an opportunity to reinvision how our buttons work. 

Yes, this is pretty bare bones. There is still a bunch of styleing work to do, and I'm open to more API changes. But better to get it out in the open and start iterating.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
As I said, barebones. 
image

**Comment by christiango** [comment]
I love the direction this is going! Can you clarify what the 7.0 button refresh would be? Is it mostly this  change, where we are moving towards a dedicated MenuButton, BaseButton, and SplitButton to remove the complexity in BaseButton and only require ContextualMenu when you are using a button with a menu?

**Comment by micahgodbolt** [comment]
With the success I'm having, it might be better to shoot for 6.0, but we'll see. My concern is that we're looking to make a breaking change in Button in 6.0 (moving to getStyles), and making another breaking change in 7.0 might be too much.

**Comment by micahgodbolt** [comment]
Here's the current breakdown of what I have done.

Button.base
MenuButton.base
SplitButton.base

All 3 buttons are just Button.base with different things rendered in onRenderSuffix. This means that styling should be consistent regardless of the button used.

SplitButton.base already has the logic built in to choose the correct button render based on props. (So maybe could use a name change. I used SmartButton at once point).

**Comment by micahgodbolt** [comment]
Yup! Having some really good success. Found a nice trick to collapse the width of the divider, so that the background can be 100% on the buttons, and never on the wrapper.

image

**Comment by micahgodbolt** [comment]
closing this up. moving the code back into 6.0 feature branch

**Pull request closed without merging**
