### PR TITLE
fix: make export treeshakable in Fluent v0

### PR DESCRIPTION
**Pull request by layershifter**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes https://github.com/microsoft/fluent-ui-react/issues/2324
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

This change was introduced in https://github.com/microsoft/fluent-ui-react/pull/2121 and breaks treeshaking for themes, i.e. all themes will be loaded always.

image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/12224)

### CODE REVIEW

**Comment by layershifter** [comment]
[Rollup REPL](https://rollupjs.org/repl/?version=2.0.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHRoZW1lcyUyMCU3RCUyMGZyb20lMjAnLiUyRmZsdWVudCclNUNuJTVDbmNvbnNvbGUubG9nKHRoZW1lcy5mb28pJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZmx1ZW50LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHRoZW1lcyUyMGZyb20lMjAnLiUyRnRoZW1lcyclM0IlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMHRoZW1lcyUyMCU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ0aGVtZXMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAnZm9vJyU1Q25leHBvcnQlMjBjb25zdCUyMGJhciUyMCUzRCUyMCdiYXInJTVDbmV4cG9ydCUyMGNvbnN0JTIwYmF6JTIwJTNEJTIwJ2JheiclMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=
) that shows that it works 🚀

**Comment by ecraig12345** [comment]
Interesting, sorry about breaking that! This is a little unfortunate though if we do eventually end up wanting to use API Extractor on these packages, since it doesn't support `import * as foo from './foo'` currently.

Is there any way we can add automated validation for bundle issues like this?

**Comment by layershifter** [comment]
@ecraig12345 no worries ☺️ It was not obvious why it was broken 😯

> it doesn't support `import * as foo from './foo'; export { foo };` currently.

Can we create an issue for this?



> Is there any way we can add automated validation for bundle issues like this

As I know @miroslavstastny works on this for Fluent v0.

**Comment by ecraig12345** [comment]
There's a related open issue https://github.com/microsoft/rushstack/issues/1029 which I think covers this scenario.

**Comment by zerofront** [comment]
@layershifter 

[Rollup REPL](https://rollupjs.org/repl/?version=2.0.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHRoZW1lcyUyMCU3RCUyMGZyb20lMjAnLiUyRmZsdWVudCclNUNuJTVDbmNvbnNvbGUubG9nKHRoZW1lcy50ZWFtcy5MYWJlbCklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmbHVlbnQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwdGhlbWVzJTIwZnJvbSUyMCcuJTJGdGhlbWVzJyUzQiU1Q24lNUNuZXhwb3J0JTIwJTdCJTIwdGhlbWVzJTIwJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRoZW1lcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjB0ZWFtc1RoZW1lcyUyMGZyb20lMjAnLiUyRnRlYW1zLmpzJyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBmb28lMjAlM0QlMjAnZm9vJyU1Q25leHBvcnQlMjBjb25zdCUyMGJhciUyMCUzRCUyMCdiYXInJTVDbmV4cG9ydCUyMGNvbnN0JTIwYmF6JTIwJTNEJTIwJ2JheiclNUNuZXhwb3J0JTIwY29uc3QlMjB0ZWFtcyUyMCUzRCUyMHRlYW1zVGhlbWVzJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRlYW1zLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGNvbXBvbmVudFZhcmlhYmxlcyUyMGZyb20lMjAnLiUyRmNvbXBvbmVudFZhcmlhYmxlcyclM0IlNUNuJTVDbmNvbnN0JTIwdGVhbXNUaGVtZXMlMjAlM0QlMjAlN0IlNUNuJTVDdGNvbXBvbmVudFZhcmlhYmxlcyUyQyU1Q24lNUN0c2l0ZVZhcmlhYmxlcyUzQSUyMCdzaXRlJyU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjB0ZWFtc1RoZW1lcyUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb21wb25lbnRWYXJpYWJsZXMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwZGVmYXVsdCUyMGFzJTIwSW5wdXQlMjAlN0QlMjBmcm9tJTIwJy4lMkZjb21wb25lbnRBLmpzJyUzQiU1Q24lNUNuZXhwb3J0JTIwJTdCJTIwZGVmYXVsdCUyMGFzJTIwTGFiZWwlMjAlN0QlMjBmcm9tJTIwJy4lMkZjb21wb25lbnRCLmpzJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjb21wb25lbnRBLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwQSUyMCUzRCUyMCdpbnB1dHR0dHR0dHR0JyU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMEElMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY29tcG9uZW50Qi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJjb25zdCUyMEIlMjAlM0QlMjAnTGFiZWxsbGxsbGxsbCclNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) 
if I only need some component of Teams Themes, it import other components as well

**Comment by layershifter** [comment]
@zerofront yep, we should do more changes there, good catch 👍

**Pull request merged**
