### PR TITLE
DetailsList: add headerInfo prop to IColumn

### PR DESCRIPTION
**Pull request by shivasai09**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Added headerinfo prop in IColumn and consumed it in DetailColumn.tsx to show more information about column in an info icon within in the tool tip. below is the image for the same
headerinfo

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8619)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
Hey @shivasai09, thanks for your contribution.

I believe we already expose the ability to customize a column header tooltip, the API is just a bit confusing at the moment. I'll follow-up with a code sample to confirm shortly if so.

**Comment by KevinTCoughlin** [comment]
Hey @shivasai09, thanks for the pull-request.

This functionality should already be supported via `DetailsList`'s `onRenderDetailsHeader` prop when combined with `onRenderColumnHeaderTooltip`.

Here's an example diff:

```diff
diff --git a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
index 0365d2c11..4ad763733 100644
--- a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
@@ -4,6 +4,8 @@ import { DetailsList, DetailsListLayoutMode, Selection, IColumn } from 'office-u
 import { MarqueeSelection } from 'office-ui-fabric-react/lib/MarqueeSelection';
 import { Fabric } from 'office-ui-fabric-react/lib/Fabric';
 import { mergeStyles } from 'office-ui-fabric-react/lib/Styling';
+import { DetailsHeader, IDetailsHeaderProps } from '../DetailsHeader';
+import { TooltipHost, ITooltipHostProps } from '../../Tooltip';
 
 const exampleChildClass = mergeStyles({
   display: 'block',
@@ -44,8 +46,8 @@ export class DetailsListBasicExample extends React.Component<{}, IDetailsListBas
     }
 
     this._columns = [
-      { key: 'column1', name: 'Name', fieldName: 'name', minWidth: 100, maxWidth: 200, isResizable: true },
-      { key: 'column2', name: 'Value', fieldName: 'value', minWidth: 100, maxWidth: 200, isResizable: true }
+      { key: 'column1', name: 'Name', fieldName: 'name', ariaLabel: 'Name', minWidth: 100, maxWidth: 200, isResizable: true },
+      { key: 'column2', name: 'Value', fieldName: 'value', ariaLabel: 'Value', minWidth: 100, maxWidth: 200, isResizable: true }
     ];
 
     this.state = {
@@ -72,6 +74,14 @@ export class DetailsListBasicExample extends React.Component<{}, IDetailsListBas
             columns={this._columns}
             setKey="set"
             layoutMode={DetailsListLayoutMode.fixedColumns}
+            onRenderDetailsHeader={(props: IDetailsHeaderProps) => {
+              return (
+                <DetailsHeader
+                  {...props}
+                  onRenderColumnHeaderTooltip={(tooltipProps: ITooltipHostProps) => <TooltipHost {...tooltipProps} />}
+                />
+              );
+            }}
             selection={this._selection}
             selectionPreservedOnEmptyClick={true}
             ariaLabelForSelectionColumn="Toggle selection"
```

Can you try the above and see if it works for your use-case(s)? If not, I'd be interested to know how we can make it work for you.

This way we avoid modifying the public API and call flow for header tooltips. Its already quite difficult to reason about.

**Comment by shivasai09** [comment]
hey @KevinTCoughlin thanks for showing me this approach, but my use-case is little bit different, i don't want tooltip for the entire header, i just want Info icon inside the header and to that info icon i need the tooltip.

**Comment by KevinTCoughlin** [comment]
> hey @KevinTCoughlin thanks for showing me this approach, but my use-case is little bit different, i don't want tooltip for the entire header, i just want Info icon inside the header and to that info icon i need the tooltip.

Thanks for clarifying @shivasai09, I totally missed this (my fault). I dug a bit further and noticed that `DetailsColumn` already supports rendering an icon, here's the LoC:

https://github.com/OfficeDev/office-ui-fabric-react/blob/98347544dc0eabb461beea23bc50a1fec10be873/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx#L106

What do you think about localizing your changes to the above area of code to support what you need i.e. an icon aligned to the right of the header text?

Regarding the tool-tip support, I strongly recommend that the entire column be the target since the icon is too small of one. However, if you require that behavior perhaps we can also support it in that same area of code with minimal changes.

This way we are building off of a public API we already support rather than introducing another variant.

**Comment by shivasai09** [comment]
below is the snapshot from the **figma**!

tooltip

it's having a tooltip for the Icon, i also agree with you that icon is pretty small. i think adding extra icon with a tooltip would only be the solution for this design.

**Comment by KevinTCoughlin** [comment]
@Vitalius1, would you be able to provide guidance on the above scenario https://github.com/OfficeDev/office-ui-fabric-react/pull/8619#issuecomment-481714259. It looks like we currently support left-aligned icons and tooltips as mentioned in https://github.com/OfficeDev/office-ui-fabric-react/pull/8619#issuecomment-481487257. Perhaps we need to consider right-aligned as well?

**Comment by KevinTCoughlin** [comment]
@shivasai09, I chatted with folks offline and we think the most flexible approach would be to allow for developers to override the rendering of the contents of the column header cell. The corresponding DOM area being this span and everything within it:

https://github.com/OfficeDev/office-ui-fabric-react/blob/98347544dc0eabb461beea23bc50a1fec10be873/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx#L105

**Comment by shivasai09** [comment]
hey @KevinTCoughlin sorry for the late reply, i think that it  is a good idea, but i have some few doubts.

1)  if we had an ability to override the rendering content, what happens if someone  in the future decides to change the styles for the content in the header(within the span) in fabric? then one must use the same styles which have been used in fabric,because he might just override those style by using custom css.

2) and also i fear that someone might just abuse the ability, by passing `<div></div>`  tag inside  the rendering content. because our parent is a `span `

it would be great if you can explain me this dobuts.

and yes if the above two question are not a big concern than we can just go ahead with your idea and implement it. please let me know so that i can update my code.

**Comment by KevinTCoughlin** [comment]
> hey @KevinTCoughlin sorry for the late reply, i think that it is a good idea, but i have some few doubts.
> 
> 1. if we had an ability to override the rendering content, what happens if someone  in the future decides to change the styles for the content in the header(within the span) in fabric? then one must use the same styles which have been used in fabric,because he might just override those style by using custom css.

The styles selector `cellName` would be passed to the render function and used as the area to style via CSS-in-JS.

> 2. and also i fear that someone might just abuse the ability, by passing `<div></div>`  tag inside  the rendering content. because our parent is a `span `

The `<span>` would be the root that is extracted into its own render function. So if someone provided `<div></div>` in their custom render function that would replace the `<span/>`. So the above _shouldn't_ be an issue.

> it would be great if you can explain me this doubts.
> 
> and yes if the above two question are not a big concern than we can just go ahead with your idea and implement it. please let me know so that i can update my code.

So I _think_ this will work and be more flexible, but I haven't implemented it.

**Comment by shivasai09** [comment]
just an heads-up, i got my bug resolved as By design, so right now i might not need it, but it would be good if we apply this mechanism, we might need it in future. 
if we want to resolve it now,we had to implement your idea, right now i don't know the correct approach for that, if you could provide a diff file that would be amazing

**Comment by KevinTCoughlin** [comment]
> just an heads-up, i got my bug resolved as By design, so right now i might not need it, but it would be good if we apply this mechanism, we might need it in future.
> if we want to resolve it now,we had to implement your idea, right now i don't know the correct approach for that, if you could provide a diff file that would be amazing

Great! Meanwhile, I've added it as an ask to https://github.com/OfficeDev/office-ui-fabric-react/issues/8826. I would advocate that we gather more data points on what folks would like customization control over and then address it as a backlog item soon after.

**Pull request closed without merging**
