### PR TITLE
 Use UI fonts instead of non-UI fonts (CJK)

### LINKED ISSUE #3478: Fabric localized fonts should prefer UI fonts over regular fonts (Windows fonts)
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: All

#### Describe the issue:

Yu Gothic UI is an optimized font that displays Latin characters prettily alongside more condensed Japanese characters. Using Yu Gothic instead makes the UI look not like Microsoft.

These languages are not according to Microsoft UI preference guidelines:
* Japanese: "Yu Gothic UI" > "Yu Gothic" [major inconsistency]
* Chinese (S): "Microsoft Yahei UI" > "Microsoft Yahei" [minor inconsistency]
* Chinese (T): "Microsoft Jhenghei UI" > "Microsoft Jhenghei" [minor inconsistency]

image
image

### PR DESCRIPTION
**Pull request by philipzloh**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3478
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Changed font references of Yu Gothic, Microsoft Yahei, Microsoft Jhenghei --> Yu Gothic UI, Microsoft Yahei UI, Microsoft Jhenghei UI

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by philipzloh** [comment]
@MLoughry if you have a quick moment to look at this :) this bug became evident to me only after your awesome React Mail font-fixing improvements hit my regular mailbox, but it should have always plagued CJK (especially Japanese) users of Fabric UI.

**Comment by battletoilet** [comment]
My biggest concern is the change in space that the new font occupies. I dont know if that will break the visuals for any of the other components.

**Comment by mikewheaton** [comment]
It does seem like "UI" is part of the proper font name (see this [Microsoft Typography page](https://www.microsoft.com/typography/fonts/family.aspx?FID=408)), so I'd suspect that it was falling back to Segoe previously. Are we sure that it always contains "UI" and has been broken this whole time? I'm wondering if we should include both in the font stack, but it would be best to confirm that's actually necessary.

Could we add some visual regression tests for international fonts? John attached a GIF in Teams showing that there is a visual change here, but our tests aren't catching it.  It would be ideal to have visual regression tests for each language where we specify a custom font stack (with characters in that language, not just Latin characters), assuming that Screener has access to those system fonts.

**Comment by philipzloh** [comment]
I only noticed because Michael made a recent fix that actually pulls in localized Fabric fonts as opposed to forcing WestEuropean on all of React Mail. For extreme dogfooding, my mailbox is almost 100% set to Japanese. Previously, my latin charset used WestEuropean (via definition). Now, my latin charset uses Yu Gothic (via new definition). In both cases, it's **not really a fallback per se** that would allow it to use Segoe UI.

> Are we sure that it always contains "UI" and has been broken this whole time?

Pretty much...
https://en.wikipedia.org/wiki/List_of_typefaces_included_with_Microsoft_Windows

Typeface | Faces available | Target script | FirstWindowsversion
-- | -- | -- | --
Yu Gothic | Regular, Bold, Light, Medium | Japanese | 8.1
Yu Gothic UI | Regular, Bold, Light, Semilight, Semibold | Japanese | 8.1



Visual regression testing - Michael started a project on this for a previous hackathon.

**Comment by MLoughry** [comment]
@philipzloh, regarding the visual regression tests, my hack was based on what's [already implemented in Fabric](https://github.com/OfficeDev/office-ui-fabric-react/blob/c71d6b27f205b3685b758e9978e332bc4e992838/ghdocs/TESTING.md#visual-regression-testing).

**Pull request merged**
