### PR TITLE
Dropdown margin

### LINKED ISSUE #6082: Dropdown label has 8px extra bottom margin
The dropdown label has 8px extra margin at the bottom and it breaks the layouts, since the fields are not aligned vertically anymore.

Here is a codepen showing the extra margin: https://codepen.io/Intnovaction/pen/EePqGq

You can see that the label pushes down the dropdown and breaks the alignment between the Dropdown and the text filed, which should be vertically aligned.

Are you willing to submit a PR to fix? NO
 
Requested priority: Normal

Thanks!

### PR DESCRIPTION
**Pull request by SavannahBourgeois**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6082
- [x] Include a change request file using `$ npm run change`

#### Description of changes
There was an extra 8px margin between the dropdown label and container. This caused the dropdown container to be lower than a textfield with a label so they did not properly align. This change removes the bottom 8px from the dropdown and design has approved removing this.

#### Focus areas to test
Verify the dropdown examples look as expected.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/6133)

Below are some before and after screenshots of the dropdown and label. I added the codepen example included in the bug locally to verify the change which you can see at the bottom of each screenshot.
Before:
dropdownbottommarginbefore
After:
dropdownafter

### CODE REVIEW

**Comment by micahgodbolt** [comment]
yup...screener caught the changes, lots of labels getting moved closer to content below :)

Accepted and gtg!

**Comment by micahgodbolt** [comment]
@SavannahBourgeois just for completeness, can you add some before and after screenshots to your top message?

**Comment by SavannahBourgeois** [comment]
@micahgodbolt I added screenshots to the message at the top. Let me know if that works or if I needed to add them somewhere else. Thanks!

**Comment by micahgodbolt** [comment]
@SavannahBourgeois nice work! On to the next one.

**Pull request merged**
