### PR TITLE
Update inputBorder semantic color

### LINKED ISSUE #8910: Rest border colors do not meet WCAG 2.1 requirements - Textfield, Dropdown, Spinbutton, Combobox –
Current Fluent border colors for Textfield, Dropdown, Spinbutton and Combobox do not meet WCAG 2.1 requirement for non-text contrast. It is currently 2.15:1 (Gray 80)
image

Expected They must be 3:1 against background. Gray110 is the lightest color that will pass, but in our theming system we would need to use Gray130.

### PR DESCRIPTION
**Pull request by atneik**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8910
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Update the default `inputBorder` semantic color to `neutralSecondaryAlt`. Update `SearchBox` to use semantic color for input border.

#### Focus areas to test

Any components who were using the color non-semantically

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9064)

### CODE REVIEW

**Comment by phkuo** [comment]
`neutralSecondaryAlt` was deprecated quite a while back and only recently undeprecated. We will need to add it back to the oob themes in SharePoint before consuming Fabric 7, and add it to the theme generator tool.

**Comment by atneik** [comment]
> `neutralSecondaryAlt` was deprecated quite a while back and only recently undeprecated. We will need to add it back to the oob themes in SharePoint before consuming Fabric 7, and add it to the theme generator tool.

Glad you noticed. I was about to ask the process, when I saw this commit https://github.com/OfficeDev/office-ui-fabric-react/commit/7d3a64d4aa3c5b473bae8a3b817a7ef753d9fecd

**Comment by Vitalius1** [comment]
Wait... screener did not pick up the changes??? 😟

**Comment by Vitalius1** [comment]
These feels wrong and needs to be investigated before merge so that we don't mess the screener baselines.

**Comment by Vitalius1** [comment]
@atneik, do you know if the screener changes were accepted in some way by @betrue-final-final and it's not showing on screener page?

**Comment by atneik** [comment]
> @atneik, do you know if the screener changes were accepted in some way by @betrue-final-final and it's not showing on screener page?

No idea. He'd have to really fast :)

**Pull request merged**
