### PR TITLE
Stories: Testing that icons package loads all icons

### PR DESCRIPTION
**Pull request by lynamemi**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Making sure that the icons package initializes and renders all icons from the fabric cdn

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by Jahnp** [comment]
This is awesome, thanks for doing this. Any chance we can get a screen of what the test looks like?

**Comment by lynamemi** [comment]
I am hoping screener will show us what we need, but I did test this in the Icon.Basic.Example, too so can take a screen shot from that if you'd like.

**Comment by Jahnp** [comment]
Oh duh, hadn't even considered that Screener would account for this. Ya let's look to that for the preview. Thanks!

**Comment by lynamemi** [comment]
Finally made it through the build to the Screener test!

**Pull request merged**
