### PR TITLE
a11y-tests: Run a11y tests on all component examples

### PR DESCRIPTION
**Pull request by statm**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

This PR expands the scope of a11y tests from previous Button & TextField to all component examples (heavily borrowed mocks and routines from https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ComponentExamples.test.tsx).

Also resolves an issue where parallel jest execution can cause `fixWinEPERM` errors due to https://github.com/GoogleChrome/puppeteer/issues/298

#### Focus areas to test

As always, the stability of a11y snapshots has to be monitored after check in.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9479)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
shouldn't we be seeing tests here? 
image

**Comment by micahgodbolt** [comment]
is it filtering out errors...i only see green, and i'm sure we have SOME errors 
image

**Comment by statm** [comment]
@micahgodbolt Try `TextField.Basic.Example.sarif` or `Tooltip.Absolute.Position.Example.sarif` to see errors... but as a general point I think these 240-some sarif files will cause some info overload.

**Comment by micahgodbolt** [comment]
Yeah, and that UI is a bit painful when we have all of those files. 
image

Can we only generate errors, not passes?

**Comment by statm** [comment]
@micahgodbolt Sure. Just updated the file output logic. Now we should have 63 SARIF files - still a lot :-/

**Comment by micahgodbolt** [comment]
63 is at least a number we can start widdling down. I'm sure lots of them are low hanging fruit

**Comment by micahgodbolt** [comment]
Yeah, that's better. At least now we only get files generated for those with errors. the list is a LITTLE shorter: 
image

**Comment by micahgodbolt** [comment]
and it looks like the entire scan is 2 minutes. that's pretty solid:

image

**Pull request merged**
