### PR TITLE
If HoverCard has firstFocus set then setInitialFocus in ExpandingCard's Callout component

### LINKED ISSUE #4582: Hover card should set focus to it self after card is opened.
### Bug Report

- __Package version(s)__: recent
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? If I have time...

Requested priority: Normal

Products/sites affected: SharePoint onprem People web part

#### Expected behavior:

After hover card is opened by hover/click, I expect the focus should goes into the card

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4582 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

The `ExpandingCard`'s inner `Callout` component has a property to set focus on the card upon initial render called `setInitialFocus`

https://github.com/OfficeDev/office-ui-fabric-react/blob/5867a6982557d85227600af53420324734298285/packages/office-ui-fabric-react/src/components/Callout/Callout.types.ts#L176

which is not set to the value of `firstFocus?` declared here:

https://github.com/OfficeDev/office-ui-fabric-react/blob/5867a6982557d85227600af53420324734298285/packages/office-ui-fabric-react/src/components/HoverCard/ExpandingCard.types.ts#L105

This change sets `setInitialFocus` to the value of `firstFocus` so that developers can indicate that they want their HoverCard(s) to focus themselves on render to allow for keyboard navigation (for example).

It looks like there's a similar property `trapFocus?` and usage of `<FocusZone />` that may have been trying to accomplish the same? But they don't seem to work. Not sure of the history here.

#### Focus areas to test

You can test the following scenarios by running the solution locally and working with the `ExpandingCard` on http://localhost:4322/#/examples/hovercard. Simply hover over the rows in the example to test the below functionality:

##### HoverCards w/o `firstFocus` set:

1. Render a HoverCard
1. You should have to click the card for it to gain focus to then be able to keyboard nav within i.e. `TAB`.

##### HoverCards w/ `firstFocus` set:

1. Render a HoverCard
1. Upon render, the card should have the first element focused.
1. You should then be able to keyboard nav within w/o clicking first.

If this change is OK'ed, worth a test to avoid future regression?

### CODE REVIEW

**Comment by atneik** [comment]
@chaofeng2014 could you test this change and check why `trapFocus` and usage of `<FocusZone />` isn't working?

**Comment by chaofeng2014** [comment]
TrapFocus only works if user use keyboard to navigate into hover card.

**Comment by KevinTCoughlin** [comment]
@atneik any thoughts on this change given @chaofeng2014's reply? Is this the correct prop to use given that there's another similarly named last I checked.

**Comment by KevinTCoughlin** [comment]
I'm open to either the current change or conditionally wrapping in a `FocusTrapZone`. The current change sets focus to the first element and seemed to use existing code so from my UX with using the keyboard it seemed fine, but perhaps `FocusTrapZone` wrapper would be preferred. Looking for advice on that.

The issue this aims to solve is https://github.com/OfficeDev/office-ui-fabric-react/issues/4582 for additional context.

**Comment by atneik** [comment]
I don't think we should steal away focus if HoverCard is brought up using a light action such as a hover, but in case of a click or a keydown where the intent is clear we should totally set the focus in it. @benkaiser please correct me if this is wrong.

@KevinTCoughlin if you could update the PR so that we set `setInitialFocus` as true only when card is clicked or keydowned into, not hovered, that will be great! We could also look into removing `<FocusTrapZone/>` if its doing redundant work.

**Comment by KevinTCoughlin** [comment]
@atneik refactored and tested w.r.t your comment, works!

Thank you and @chaofeng2014 for the guidance & feedback 👍

**Comment by benkaiser** [comment]
@atneik did you mean to mention someone else?

**Comment by atneik** [comment]
@benkaiser Oh sorry, I mean @betrue-final-final

**Pull request merged**
