### PR TITLE
Fix for Issue7225 : Clicking outside a Panel when Panel and Dialog are both open

### LINKED ISSUE #7225: Panel: Panel & Dialog both are opened. Now click some where outside panel closes.
### Environment Information 
 
 
- __Package version(s)__: (latest) 
- __Browser and OS versions__: (Chrome and Windows 10)

#### Actual behavior:
* Click Open Panel button
* Panel opens.
* Click Open Confirm button.
* Click some where outside the Panel & Dialog area.
* Panel closes automatically.
* Dialog remains open.

 

 
#### Expected behavior:
* Click Open Panel button
* Panel opens.
* Click Open Confirm button.
* Click some where outside the Panel & Dialog area.
* Panel should not close automatically.
* Dialog remains open.
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable) Microsoft Workplace Analytics

### PR DESCRIPTION
**Pull request by aftab-hassan**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7225 
- [x] Include a change request file using `$ npm run change`

#### Description of changes
Modified the condition to disallow closing the panel if the click is outside and onOuterClick is not defined.

#### Focus areas to test

- Click Open Panel button
- Panel opens.
- Click Open Confirm button.
- Click some where outside the Panel & Dialog area.
- Panel should not close automatically.
- Dialog remains open.

[Here](https://drive.google.com/file/d/1BhJBp6bg9vzrOJ2bqjEqSpKi4h2u5PAi/view) is the original behavior prior to the fix

[Here](https://drive.google.com/file/d/1UxWWCVHCxIKJlzhyzVCSIPF_oiRQX-yD/view) is a screen recording of the fix.

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
It would be _great_ to have @tacambridge look at this as the removal was explicitly added as per https://github.com/OfficeDev/office-ui-fabric-react/pull/5422#issuecomment-402315777.

**Comment by aftab-hassan** [comment]
> It would be _great_ to have @tacambridge look at this as the removal was explicitly added as per [#5422 (comment)](https://github.com/OfficeDev/office-ui-fabric-react/pull/5422#issuecomment-402315777).

@ThomasMichon could you take a look at this PR. Looks like the current behavior was explicitly added by @tacambridge. Is this by design?

**Comment by aftab-hassan** [comment]
@ecraig12345 got a response from Siddarth (can't tag here) on Teams that this fix unblocked for the interim. +1 to get Thomas' inputs on the fix.

image

**Comment by ThomasMichon** [comment]
@aftab-hassan There are bunch of factors in play here, not the least of which is how the Panel and Dialog are rendered relative to each other. If you want it so clicking outside a blocking Dialog does not dismiss the Panel, then the Dialog needs to be rendered *inside* the Panel, and it needs to render a modal overlay:

```tsx
<Panel
  isOpen={ true }
  >
  <Button>Confirm</Button>
  <Dialog
    isOpen={ true }
  >
    <Button>Yes</Button><Button>No</Button>
  </Dialog>
</Panel>
```

In order to avoid dismissing the Panel, a click outside the Dialog needs to be seen as a click *inside* the Panel, which is what Panel's `elementContains` check is for. The way to ensure this happens is to ensure the Dialog renders as a child of the Panel and that it absorbs the click itself via a transparent overlay, rather than letting it propagate to Panel as an 'outside' click.

Can you share the CodePen that repro's the bug? I bet I can tweak it to behave how you intend.

**Comment by aftab-hassan** [comment]
> Can you share the CodePen that repro's the bug? I bet I can tweak it to behave how you intend.

@ThomasMichon thanks for taking a look at this.

[This](https://codepen.io/sidmanraj/pen/yQqRBx) is the original codepen with a repro of the bug submitted by the person who opened the issue.

[This](https://codepen.io/aftab-hassan/pen/PXbrwE) is the codepen with the fix we suggested which unblocked the issue.

**Comment by ThomasMichon** [comment]
Fixed the original CodePen by moving the `<Confirm>` to be a child of the `<Panel>`: https://codepen.io/ThomasMichon/pen/XopbyQ

**Comment by aftab-hassan** [comment]
> Fixed the original CodePen by moving the `<Confirm>` to be a child of the `<Panel>`: https://codepen.io/ThomasMichon/pen/XopbyQ

Thanks @ThomasMichon , I have got back with the person who opened this issue, and suggested this fix. 

Can we close this PR since the behavior seems to be by design ?

**Comment by KevinTCoughlin** [comment]
> 
> 
> > Fixed the original CodePen by moving the `<Confirm>` to be a child of the `<Panel>`: https://codepen.io/ThomasMichon/pen/XopbyQ
> 
> Thanks @ThomasMichon , I have got back with the person who opened this issue, and suggested this fix.
> 
> Can we close this PR since the behavior seems to be by design ?

@aftab-hassan let's mark this as "Needs Author Feedback" to invoke the bot since a possible solution has been provided. Thanks @ThomasMichon for assisting here 👏.

**Comment by ecraig12345** [comment]
I wouldn't have realized that the dialog needed to be rendered inside the panel. Maybe this is something we could document better, like in an example for panel and/or dialog?

**Comment by ThomasMichon** [comment]
All our components rely on 'real' React parentage in order to determine who owns what. For dismissal, we rely on a parent popup 'containing' a child popup to know that we shouldn't close the parent when the user clicks outside the child. Parent/child relationships are the only way we can reliably keep track of the modal 'back stack'.

**Comment by aftab-hassan** [comment]
> **Edit:** @aftab-hassan, sorry I see this is a PR. Since you are the author you can close. I would keep the Issue open and marked as "Needs Author Feedback" with the above solution proposed. Sorry about the comment churn here.

@KevinTCoughlin I believe we discussed about this offline. But I've re-opened the issue, marked as needing author feedback and pinged the person who posted this issue privately (MS employee), just to be sure our recommendations were helpful. I shall monitor the original issue [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/7225)

**Pull request closed without merging**
