### PR TITLE
Fix cell animations so they only trigger on valid cell key changes

### PR DESCRIPTION
**Pull request by ThomasMichon**
Fixed cell animations so they only trigger when the value of `getValueKey` from a column has actually changed since last render; this is done by using a 'ref' hook in `DetailsRowFields`.

Also, fixed the `key` value assigned to each cell `<div />` so it remains stable and never has duplicates.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9949)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
@ThomasMichon we need to update snapshots to unblock CI because https://github.com/OfficeDev/office-ui-fabric-react/pull/9432/files#diff-4e9df859b8dbf0839a68a78be6fae44b introduced a bunch of unnecessary newlines.

Let me see if I can push to your branch.

**Comment by cliffkoh** [comment]
@msft-github-bot merge this in 3 hours

**Comment by cliffkoh** [comment]
@msft-github-bot nevermind, ignore that.

**Comment by KevinTCoughlin** [comment]
@msft-github-bot please merge this PR in 5 minutes

**Comment by cliffkoh** [comment]
@msft-github-bot require approval from @KevinTCoughlin

**Pull request merged**
