### PR TITLE
Integrate markdown-to-jsx in example-app-base for use in documentation

### PR DESCRIPTION
**Pull request by jordandrako**
#### Pull request checklist

- [x] Include a change request file using `$ npm run change`

#### Description of changes

- Install [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx) in example-app-base.
- Use @dzearing's work from Fabric-Internal but fix imports for new location.
- Test use in ActivityItem

#### Desired changes

I'd prefer to configure webpack to load .md files with raw-loader by default instead of using:

```ts
const ComponentOverview = require<string>('raw-loader!./ComponentOverview.md');
```

### CODE REVIEW

**Comment by jordandrako** [comment]
Pinging @dzearing @lynamemi @mikewheaton for visibility on this. What are your thoughts?

**Comment by lynamemi** [comment]
Structure makes sense to me, and looks like it would be pretty easy to add markdown to a page! I pulled the branch locally, and the ActivityItem example looks spot on to the original.

**Comment by jordandrako** [comment]
Alright, the PR is ready for real review and possibly merge IMO.

**Comment by vernercs9** [comment]
We tried using this version of example-app-base and got errors about missing packages.  Do you need to add markdown-to-jsx and others to peerDependencies?

**Pull request merged**
