### PR TITLE
HoverCard dismissing with `sticky` prop true on mouse leave

### LINKED ISSUE #7848: HoverCard - Card still dismisses on mouse out when 'sticky' prop set to true
### Environment Information 
 
- __Package version(s)__: Whatever comes with SPFX 1.7.0
- __Browser and OS versions__: Chrome & Windows 10

CodePen: https://codepen.io/anon/pen/WPoXzo
 
#### Actual behavior:
 
HoverCard dismisses as usual
 
#### Expected behavior:
 
HoverCard remains open

Requested priority: Normal

### PR DESCRIPTION
**Pull request by SpencerLynn**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7848
- [x] Include a change request file using `$ npm run change`

#### Description of changes

In `HoverCard`, do not dismiss the card when the prop is true and the event prompting the dismissal is the `mouseleave` event from the card itself. Clicking outside, escape, etc will still dismiss the card.

#### Focus areas to test

I mostly want to verify that I am not missing an assumption with how `HoverCard` is meant to function.

Note: I am investigating adding a test for this now.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/7898)

### CODE REVIEW

**Comment by natalieethell** [comment]
Awesome, thanks for taking this on! I'm not super familiar with the HoverCard's functionality, so I'm interested to see what @Jahnp and @atneik think of this change.

**Comment by SpencerLynn** [comment]
> Bundle test	Size (minified)	Diff from master
> HoverCard	134.255 kB	ExceedsBaseline     123 bytes
> ExceedsTolerance  Exceeds Tolerance     ExceedsBaseline  Exceeds Baseline     BelowBaseline  Below Baseline     **1 kB** = 1000 bytes

@natalieethell, is this something I need to address with this PR? The bundledize check seems to have passed, but I saw this and wanted to confirm. I haven't found any way of updating this for this PR. Please let me know if this is something I need to handle! Thanks!

**Comment by atneik** [comment]
@SpencerLynn I see a similar function (i.e. `_cardDismiss`) to the one introduced. Can we fix the bug by using and updating it?

**Comment by SpencerLynn** [comment]
@atneik Nice catch! I'll take a look. The type of `ev` would be pretty complicated - `MouseEvent | React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>`. Probably not a huge deal, but would introduce more `instanceof` checks to check for the cases. I will start looking at that if you think this doesn't make the code significantly less readable.

**Comment by atneik** [comment]
That's right :/ But I'll choose an ugly type & checks over two similar functions. At least all the dismiss logic will be at the same spot. Thanks for your contribution and looking into this!

**Comment by SpencerLynn** [comment]
Ok. Sounds good. I think I can mitigate some of the other concerns, since the type in those cases will be `MouseEvent` instead of `React.MouseEvent` like the case I care about will have. I'll look into it! Thanks for the feedback!

**Comment by natalieethell** [comment]
Hey @SpencerLynn! Have you gotten a chance to look into the changes @atneik proposed?

**Comment by SpencerLynn** [comment]
Hey @natalieethell! I was able to look into it a little bit, but was running into issues with existing functionality merging the functions. I haven't been able to look any further since Monday. If anyone else wants to make edits, I'm open to it. Otherwise I'll try to come back around to this soon. Sorry for the delay!

**Comment by SpencerLynn** [comment]
I was able to spend a few minutes on it.

@natalieethell  @atneik  Basically I need to distinguish between the `_cardDismiss` being called from the native event listener and the card's `onLeave` prop. The event isn't enough to go (the `onLeave` prop event can actually be a `MouseEvent` also, it seems (when clicking outside the hover card). 

I can combine the function by adding an argument to the beginning of `_cardDismiss` to indicate whether the call is from a the event listener or the `onLeave` prop, but, to me, that doesn't seem like a cleaner solution than what I have currently in the PR. If everyone believes that keeping the entire logic into `_cardDismiss`, I'm happy to move it all there.

**Pull request merged**
