### PR TITLE
Rating: fix controlled behavior

### LINKED ISSUE #9799: Rating: Cannot set value as 0
## Bug Report: 

This issue primarily refers to the apparent bug where the state value is incorrectly updating. 

### Environment Information 
 
- __Package version(s)__: `office-ui-fabric-react` `7.7.0`

### Please provide a reproduction of the bug in a codepen:
 
Cannot clear value or set to 0: [CodePen](https://codepen.io/anon/pen/PrgXad)
note: click the rating value: 3 then use toggle.

#### Actual behavior:
 
Component updates too soon: Value refers to state before update.
 
#### Expected behavior:
 
Component render updates to state or allow controlled value input.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 

## Feature request:

When `allowZeroStars={true}`, clicking a star where the new value equals previous value sets the value to `0`. This avoids the requirement of a "clear" button. Note that there is no easy way to wrap this as a feature as `onChange` does not trigger unless the value changes.

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #9799 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

When using `Rating` in controlled manner updating the `rating` prop through the `onChange` callback was not working when `allowZeroStars` enabled. The `if` check will fail when the value is 0.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9805)

### CODE REVIEW

**Comment by joschect** [comment]
Also fixes #9807

**Comment by joschect** [comment]
@Vitalius1 could you confirm that the snap change is expected? It looks like it's clicking on the second star and that's not getting filled in. From what I can tell that is correct behavior and a bug fix since the rating of 0 is passed in making the rating a controlled component

**Comment by Vitalius1** [comment]
@joschect 
Yes, the screener change is expected because we don’t have a state update logic in `Rating` stories and now it looks with the fix it surfaced. Actually I think that I will remove that story as it’s not adding any valuable checks from the styles point of view and will work on adding a unit test to verify the controlled behavior.

**Comment by Vitalius1** [comment]
As for #9807 issue, I don’t think it’s the same thing as I am fixing in here. The author needed a fix of the controlled behavior or a suggested functionality that Rating is missing today. In the second part of [my comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/9799#issuecomment-511083651) you can see what that feature request is. Basically when `allowZeroStars` is enabled clicking on the same star in uncontrolled scenario will juts toggle between 0 value and the star you are clicking on.

**Pull request merged**
