### PR TITLE
Details Row now passes down the checkbox visible flag

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Details Row wasn't passing down the visible flag to the checkbox to render the style correctly (opacity)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by cliffkoh** [comment]
Looks like this change introduced other regressions...

**Comment by kenotron** [comment]
Screener is displaying something that actually isn't the same as what is showing up by real mouse hover... Have to investigate why this is.

**Comment by cliffkoh** [comment]
Can you also add a visibility: always test?

**Comment by dzearing** [comment]
I will approve, but assuming you 1. add a screener visibility test as requested above, and 2. screener passes :)

**Comment by kenotron** [comment]
Screener test added - will have to accept it when it comes out.

**Pull request merged**
