### PR TITLE
Lorejoh12/fix calendar year state overwriting

### LINKED ISSUE #8154: CalendarYear navigation arrows broken in React 16.8.3 (at least)
Due to #7379, the CalendarYear component was transitioned to use getDerivedStateFromProps(). There's a rather bad bug here that's detailed exactly in:
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-unconditionally-copying-props-to-state

For some reason this doesn't repro in the current version of React, 16.3.2, but it repros when you upgrade (tested on 16.6.3, which is what OWA Calendar is on, and it repros there, as well as the next Fabric version 16.8.3 which is coming).

The problem is that getDerivedStateFromProps runs on every rerender. And when we call setState(), we rerender. So in the CalendarYear component, when we hit the forward arrow, it calculates the next date range, calls setState, which goes into getDerivedStateFromProps... which overrides our setState call. End result is that we click the arrow buttons and nothing happens.

There are a couple of fixes for this detailed in the blog post linked, but they all require doing some work to fix the control itself, not a quick fix. The fix will have to be made for both date-time CalendarYear as well as current OUFR CalendarYear.

### PR DESCRIPTION
**Pull request by lorejoh12**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8154
- [x] Include a change request file using `$ npm run change`

#### Description of changes

CalendarYear component is no longer working in OWA. Investigation reveals that Fabric is on a slightly older version of React that hides an existing bug, but once the version bumps, the component will break. (OWA is already on an upgraded version). See linked Issue for more details.

#### Focus areas to test

Try using the year/decade picker functionality, should keep working even though React has been upgraded on the test. Will revert the React upgrade changes before committing the actual changes

### CODE REVIEW

**Comment by ecraig12345** [comment]
Also adding @jdhuntington since this is a derived state-related issue and he's working on derived state conversions.

**Comment by lorejoh12** [comment]
> I'm going to go ahead and block this until the React 16.8 change has been reverted--I know it's meant to be temporary for testing, but it would be really bad if it somehow slipped in.
> 
> Feel free to dismiss this review once the version change has been reverted.

reverted the test changes, dismissing review. Thanks!

**Comment by KevinTCoughlin** [comment]
> I'm going to go ahead and block this until the React 16.8 change has been reverted--I know it's meant to be temporary for testing, but it would be really bad if it somehow slipped in.
> 
> Feel free to dismiss this review once the version change has been reverted.

FYI @lorejoh12 @ecraig12345 we now have support for Draft PRs which is great to avoid the need for manual block

https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by JasonGore** [comment]
At least for awareness and correct me if I'm wrong but with Draft PRs don't you have to close them and reopen a new PR? At least it seemed that history was lost on your PR Kevin.. I'm assuming you had to close the draft PR and open a new PR.

**Comment by KevinTCoughlin** [comment]
> At least for awareness and correct me if I'm wrong but with Draft PRs don't you have to close them and reopen a new PR? At least it seemed that history was lost on your PR Kevin.. I'm assuming you had to close the draft PR and open a new PR.

History can be retained with draft PRs. See:

>Change the status to “Ready for review” near the bottom of your pull request to remove the draft state and allow merging according to your project’s settings.

**Pull request merged**
