### PR TITLE
Update documentation for Toggle vs Checkbox

### PR DESCRIPTION
**Pull request by philipzloh**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Toggle and Checkbox have awkward documentation that confused a coworker of mine so I'm updating them to be more readable and helpful.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by philipzloh** [comment]
@betrue-final-final You're saying I made changes that lost design aspects? Can you point it out?

**Comment by betrue-final-final** [comment]
Let me check with Tom or Matt. Yeah, so there is a nuance where one can use a checkbox as an option for another control that was removed, for example. It just raises flags when someone says they're confused and starts changing documentation without a writer or designer.

**Comment by philipzloh** [comment]
> It just raises flags when someone says they're confused and starts changing documentation without a writer or designer.

I'll take this in the most positive way possible.

> Yeah, so there is a nuance where one can use a checkbox as an option for another control that was removed, for example.

There must be some confusion. This is the previous text:

> Use a single Checkbox for a subordinate setting, such as with a "Remember me?" login scenario or with a terms of service agreement.
>
> ...
> 
> Use multiple Checkboxes for multi-select scenarios in which a user chooses one or more items from a group of choices that are not mutually exclusive.

This is the revised text:

> Nest a Checkbox under a control when that parent control will determine the applicability or availability of the child Checkbox.
>
> Use multiple Checkboxes within the same group when a user may choose one or more items from a group of choices that do not affect the other choices.

If we're talking about nuance, I believe my revision is the one that actually _contains_ nuance and doesn't create the wrong interpretation of there being a way to use a "single Checkbox" vs "multiple Checkboxes", where the former is only used for subordinate settings and the latter is used for multi-select scenarios.

The nuance is specifically about nesting Checkboxes. You nest the "Remember me?" under the password control because it determines what and whether the form asks to remember. You nest the "I have read" under the agreement text because it is the text that you are agreeing to. If we don't like the word "nesting" we could change that; perhaps all that really matters is placing it visually "under", but I fail to see how this revision removed nuance that was supposed to have been present before...

**Comment by betrue-final-final** [comment]
Yes please don't take it in a negative way. I'm just making sure we all have a team around us to make the best changes possible. Yeah it's really difficult to get the full gist of what is written in a change list, so I had to dig into it. I would just check out the review comments for specifics. I believe I didn't comment on the nesting section. I spoke with my writers and they had said there's a writer named Denise who may be willing to chip in here.

**Comment by micahgodbolt** [comment]
@betrue-final-final is there a plan for closing this PR up? Should this discussion be taking off Github until you've had a chance to fully flesh out these docs?

**Comment by micahgodbolt** [comment]
@betrue-final-final ping us when you've had a chance to chat with matt/tom/Denise regarding this documentation change. I'll close the PR down for now, but happy to open it back up as soon as there is a decision.

**Pull request closed without merging**
