### PR TITLE
Updated FileTypeIconMap.ts for 360-degree filetypes

### PR DESCRIPTION
**Pull request by bigbadcapers**
#### Pull request checklist

- [x] Added photo360 and video360 entries to the ramp of filetype icons

### CODE REVIEW

**Comment by Jahnp** [comment]
@bigbadcapers , are there any extensions for these file types you'd want to add? e.g. .mp4, cad

Also tagging @atneik as FYI

**Comment by Jahnp** [comment]
Also, you'll want to run `npm run change` and fill out the small form to get this included with the next release of `@uifabric/file-type-icons`. Let me know if you need help with that!

**Comment by bigbadcapers** [comment]
@atneik how do I change that? do I have to throw the whole PR away?
@Jahnp yes I will need help with that :-)

per the thread where Aniket asked, Wendy seems to own the integration work and detecting when a jpg or mp4 is actually a panorama. these files otherwise use the same file extension so some sort of extra code will be necessary in the app using the getFileTypeIcon (sp?) method.

**Comment by aneeshack4** [comment]
@bigbadcapers hello! did you still need help with "npm run change"? Let us know. Also, any follow up on the extra code that may be needed for this change?

**Comment by bigbadcapers** [comment]
abandoning this one in favor of the one that combines the 360 and the fluent changes

**Pull request closed without merging**
