### PR TITLE
cherry picked updates from PR 5993

### PR DESCRIPTION
**Pull request by bennettclark**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Cherry picked changes from https://github.com/OfficeDev/office-ui-fabric-react/pull/5993

### CODE REVIEW

**Comment by bennettclark** [comment]
I don't have write access to this repository, can someone please merge this pull request? @JasonGore ?

**Comment by phkuo** [comment]
@cliffkoh can you merge this?

**Comment by JasonGore** [comment]
It says it's out of date with 5.0 branch.. I think you should do a merge just to be safe.

**Comment by cliffkoh** [comment]
Done the merge. I believe it should be fine but we can let CI run if we want to be doubly safe.

**Pull request merged**
