### PR TITLE
Fabric 7.0: remove Shimmer from experiments package

### LINKED ISSUE #8020: Remove Shimmer from experiments package in Fabric 7.0
`Shimmer` from the `experiments` package needs to be removed with the next major version bump. I am working to make sure I replacing the imports of it from experiments package in the products I know I used it myself. For the rest of the consumers, they've been warned no to use in their production experimental components 😄 .
Tagging this in #7023 and #7402 for visibility. Will also label it accordingly.

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #8020 

#### Description of changes
 Removing any trace of `Shimmer` in `experiments` package for Fabric 7. Have been actively working with our partners we know of who were consuming the Shimmer from it and make sure all the imports have been replaced with pulling it from OUFR for a smoother upgrade.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8906)

### CODE REVIEW

**Comment by Vitalius1** [comment]
@cliffkoh I am cleaning up Shimmer for v7 of `experiments` package. Do we leave any sort of re-export from OUFR? The API is slightly different so I don't see any sense in doing it because it will break them anyway with or without the re-export.

**Comment by cliffkoh** [comment]
Hey @Vitalius1, I'm completely drowning here tonight and in a terrible place. Can you check with perhaps @jdhuntington or @aditima or @JasonGore?

**Comment by JasonGore** [comment]
If I understand correctly you are asking if there are experiments exports in OUFR? That's not possible since experiments depends on OUFR and any experiments exports would create a circular dependency.

**Comment by Vitalius1** [comment]
@JasonGore no, what I am asking is, do we leave re-export Shimmer in experiments package by pointing to the one in OUFR? So that anyone who used Shimmer from experiments doesn't get a module not found error... Now that I think better, I believe we are ok with a complete removal for 2 reasons: first, it's a major breaking change and second, it's in experiments package so people should know of possible breaking changes.

Can I get an approval on this one?

**Comment by Vitalius1** [comment]
Thanks Jason!

**Pull request merged**
