### PR TITLE
Dialog: title can now receive JSX content.

### LINKED ISSUE #8238: Adding icon support for Dialog title
**Describe the feature that you would like added**

For now the `Dialog`'s title can only be string. Can we support adding `Icon` to a title?

**What component or utility would this be added to**

`dialogContentProps.title` of `Dialog`

**Have you discussed this feature with our team, and if so, who**
Not yet

**Additional context/screenshots**

Like this:
image

### PR DESCRIPTION
**Pull request by dzearing**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #8238
- [X] Include a change request file using `$ npm run change`

#### Description of changes

You can now provide JSX as the title of a Dialog, which can enable scenarios like having glyphs/icons next to the content.

```tsx
        <Dialog
          dialogContentProps={{        
            title: <><Icon iconName="upload"/>Awesome</>
          }}
        >...
        </Dialog>
```

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8405)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
Needs `npm run update-api` I think

**Comment by dzearing** [comment]
@cliffkoh While I did have a local example modification, I actually reverted it, because im not sure we want to recommend this pattern in an example. Enabling the scenario is fine, but really it should be an edge case because it could possibly lead to non conformity.

**Comment by dzearing** [comment]
I can certainly add a snapshot tho

**Comment by cliffkoh** [comment]
@dzearing that is fine to not have an example but a unit test snapshot is a minimal alternative to make sure the actual app code handles this scenario (and continues to do so!) :)

**Comment by dzearing** [comment]
@cliffkoh snapshot added

**Pull request merged**
