### PR TITLE
fixed reload page by adding type='button'

### PR DESCRIPTION
**Pull request by mtringuyen**
This happen when I develop with SharePoint Add-in. All components are render in a form so the button element must specify with property **type='button'**

### CODE REVIEW

**Comment by cschlechty** [comment]
The button type should be an optional parameter that defaults to button.

**Comment by mikewheaton** [comment]
Agreed with @cschlechty, it's possible they might want it to be a `submit` or `reset` button, although it will be `button` in 99% of cases.

**Comment by cschlechty** [comment]
Your latest commit shows changes to 40 files. Can you clean this up so you're just submitting your changes?

**Comment by dzearing** [comment]
I'm going to close this pending PR. If you'd like to resubmit a separate change that has the resolves cleaned up, please re-open a new one. Thank you!

**Comment by mtringuyen** [comment]
Thanks @dzearing

**Pull request closed without merging**
