### PR TITLE
Dropdown: selectedIndices[0] Should not less than 0

### PR DESCRIPTION
**Pull request by luokuning**
When `selectedKey` is not in `options`, selectedIndices[0] would be `-1`, which then trigger a error in `!this.props.options[selectedIndices[0]].disabled`.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8712)

### CODE REVIEW

**Comment by ecraig12345** [comment]
@luokuning Thanks for this PR! Can you please run `npm run change` and commit the result?

**Comment by luokuning** [comment]
> It seems very strange to me that selectedIndices should ever contain -1 (and I think that's what ought to be fixed instead). Can you share a codepen demonstrating a scenario where this happens? You can use the "Export to CodePen" link on one of the [Dropdown examples](https://developer.microsoft.com/en-us/fabric#/components/dropdown) as a starting point.

Yeah sure, I have create a [CodePen example](https://codepen.io/luokuning/pen/bJrWaN?editors=0011) to demonstrate the scenario.

**Comment by luokuning** [comment]
> @luokuning Thanks for this PR! Can you please run `npm run change` and commit the result?

I have commit the `npm run change` result :-)

**Comment by luokuning** [comment]
@chieftn @ecraig12345 Yes, `selectedIndices` should not contain -1. Since we can't control the value of `selectedKey` or `selectedKeys` that user provide, so maybe we should ensure that index is not -1 before push to `selectedIndices`. I think it makes more sense than `selectedIndices[0] > -1`.

I have commit the changes, please take a review :)

**Comment by cliffkoh** [comment]
@luokuning your changes look good but could you also add a unit test that captures your scenario? There are a ton of unit tests already in Dropdown.test.tsx and it should be fairly straightforward to copy and modify one. This will really get your PR over the bar into mergable status :)

**Comment by luokuning** [comment]
@chieftn I have added the unit test for Dropdown that captures the scenario, please take a review.

**Comment by cliffkoh** [comment]
gentle ping @ecraig12345

**Comment by luokuning** [comment]
> Thank you! I appreciate that you added tests for both single select and multi-select scenario 👍
> 
> Approving as it looks good to me. Hopefully @ecraig12345 can help sanity check :)

I'm glad to help 😄

**Pull request merged**
