### PR TITLE
Webkit overflow scrolling bug in Panel

### LINKED ISSUE #4398: Panel not showing and blocking user interactions in IOS under "-webkit-overflow-scrolling: touch"
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: Safari, IOS, iPad or iPhone.

#### Priorities and help requested (not applicable if asking question):

Requested priority: Blocking

Products/sites affected: SharePoint mobile page, SharePoint mobile native apps.

#### Describe the issue:

1. Add this CSS style to body element: “-webkit-overflow-scrolling: touch”.
2. Open the page which can open <Panel /> in IOS devices with Safari.

#### Actual behavior:

Panel is not rendered.

#### Expected behavior:

Panel is rendered.

### If applicable, please provide a codepen repro:

I used this codepen example first: https://codepen.io/dzearing/pen/Rxxber
I can successfully open the panel at the right side.

Then I used this codepen that only changes one line of previous one (by addinng "-webkit-overflow-scrolling: touch;" to the body element) https://codepen.io/anon/pen/WzMyxm
I can no longer open the Panel.

### PR DESCRIPTION
**Pull request by natalieethell**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #4398 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Popup: overflow-y is now set to undefined when it does not need a scrollbar to fix the issue related to -webkit-overflow-scrolling: touch.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
snapshots need to be updated

**Comment by YusongLiu** [comment]
Hi @micahgodbolt , could we port this fix to fabric-react v5? We met this issue recently.

**Comment by micahgodbolt** [comment]
@YusongLiu #5462

**Comment by YusongLiu** [comment]
Thanks @micahgodbolt !

**Pull request merged**
