### PR TITLE
DetailsList: integrate Shimmer.

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist
- [X] Include a change request file using `$ npm run change`

#### Description of changes

- Integrates Shimmer as part of DetailsRow
- Removes previous implementation of Shimmer in DetailsRowFields.
- Adds `shimmerPlaceholderProps` to DetailsList to make available placeholder customization.
- Adds a condition to force update the DetailsList in order to pass the change of `compact` prop further down.
- Adds a fading out overlay over the first initial shimmer lines.
- Adjusts the example for using DetailsList with Shimmer.

### CODE REVIEW

**Comment by Vitalius1** [comment]
@aditima @ThomasMichon will appreciate if you could take a look... Thanks!

**Comment by dzearing** [comment]
@yiminwu

**Comment by dzearing** [comment]
@jijizz FYI this might increase bundle size

**Comment by Vitalius1** [comment]
@ThomasMichon I will close this PR and come back later with a different solution which will not affect the size of DetailsList and still easy to use. I talked to @dzearing  about it and he suggested to use test-bundle-button app we have in the repo to compare the size of DetailsList before and after my changes and the results were 48.34KB vs 50.69KB (gzipped size). So this being a 4.8% increase, it's clearly not the way to go.

**Pull request closed without merging**
