### PR TITLE
IconButton: add color to IconButton so it can be themed.

### LINKED ISSUE #5910: Icon button doesn't theme color
Are you willing to submit a PR to fix? Yes, but not anytime soon since I'm on call
 
Requested priority: High
 
Products/sites affected: SP
 
#### Describe the issue:
 
The IconButton does not declare a color. Because it is a `<button>` element, it doesn't inherit the font color automatically and uses the browser's default styles. In dark themes, this makes it nearly invisible since it's black on black.

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #5910 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Adding color to IconButton and change the color slot for hovered state as described in issue mentioned above.

Should also fix this [Issue](https://github.com/SharePoint/sp-dev-docs/issues/2350)

#### Focus areas to test
@phkuo @betrue-final-final  There are several other states for IconButton in this file... are they up for a change too?

### CODE REVIEW

**Comment by micahgodbolt** [comment]
appears to be a bunch of visual regressions where icon colors change. Would seem to be related.

**Comment by Vitalius1** [comment]
@betrue-final-final 🙏

**Comment by betrue-final-final** [comment]
Done.

**Comment by Vitalius1** [comment]
@micahgodbolt feel free to merge this one. It's awaiting the owner approval. Thanks!

**Pull request merged**
