### PR TITLE
Overlay: Adding onOverlayDidMount and onOverlayWillUnmount callbacks to IOverlayProps

### LINKED ISSUE #9631: Overlay component IOverlayProps interface add onOverlayDidMount and onOverlayWillUnmount properties
**Describe the feature that you would like added**
IOverlayProps interface add onOverlayDidMount and onOverlayWillUnmount properties

**What component or utility would this be added to**
Allow parent component setting whether to hide the scroll bar

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9631 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Overlay: Adding onOverlayDidMount and onOverlayWillUnmount callbacks to IOverlayProps.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9670)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
Is there a way to have a parent component wrap `Overlay` such that the parent component implements `componentDidMount` and `componentWillUnmount` with the assumption that they occur in the same tick as they do for its child components?

If so, that might be advisable so we avoid drilling holes for each callback devs want to use.

**Comment by khmakoto** [comment]
@KevinTCoughlin sounds good, let me know what you find.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin sounds good, let me know what you find.

It seems like composition will work here vs. adding new props: https://codepen.io/kevintcoughlin/pen/BgGYWw?editors=0010.

I could be misunderstanding the original issue tho.

**Comment by khmakoto** [comment]
@x73x63 Do you think Kevin's approach might work for you?

**Comment by x73x63** [comment]
> > @KevinTCoughlin sounds good, let me know what you find.
> 
> It seems like composition will work here vs. adding new props: https://codepen.io/kevintcoughlin/pen/BgGYWw?editors=0010.
> 
> I could be misunderstanding the original issue tho.


Thank you Kevin, this can't help me.
I need to allow the parent component to set whether to display the scroll bar

`export class OverlayBase extends BaseComponent<IOverlayProps, {}> {
  public componentDidMount(): void {
    disableBodyScroll();
  }

  public componentWillUnmount(): void {
    enableBodyScroll();
  }
  ...
}`

Or add bodyScroll props?
`  public componentDidMount(): void {
    if(this.props.bodyScroll){
        disableBodyScroll();
    }
  }`

**Comment by khmakoto** [comment]
@KevinTCoughlin do you think adding `bodyScroll` props is a better approach here?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin do you think adding `bodyScroll` props is a better approach here?

It seems like I don't fully understand what end result the user is trying to accomplish here. I defer to you both. A solution that minimizes API surface changes seems ideal to me.

**Comment by khmakoto** [comment]
Talked with @kkjeer offline and we came to the conclusion that these changes wouldn't fix this issue. However, we're wary about adding the proposed `bodyScroll` prop because of unintentional effects this might have on `Panel` and `Modal`. We'll try to test the change in these components before committing to a fix here.

In the meantime, I'll close this PR.

**Pull request closed without merging**
