### PR TITLE
Fluent: Update code via import (again)

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Running import script again, this time including a change that removes a stats file that should be gitignored in preparation for a stats PR I will make.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/12036)

### CODE REVIEW

**Comment by JasonGore** [comment]
This PR is just another import of Fluent code, but it's pulling in Miro's Fluent lint changes. This PR is highlighting a conflict between Fabric and Fluent lint rules, now that Fluent's lint rules are being activated during `yarn lint`. We've decided to converge on Fabric rules for now, which means the fluent import script will need to be modified to change Fluent's lint rules on import.

However, since the big prettier PRs (#12005, #12006) are still open, Fluent's new lint commands will still likely fail given the inconsistency in committed files. This PR will either need to remain open until those PRs are merged, or this PR will need to temporarily disable Fluent's lint commands in the import script.

All further Fluent code imports will also be blocked for the same reason. This lint conflict issue is a blocker for converging the repos.

**Comment by ecraig12345** [comment]
To speed up merging (eliminate requirement of manual lint rule fixes), I added a separate base fluent tslint config temporarily. Pretty easy to set up and at least to me doesn't seem like a hard blocker (though I agree we should converge rules ASAP after merge).

**Comment by ecraig12345** [comment]
Also updated it to run prettier separate from lint staged.

**Comment by ecraig12345** [comment]
Jest type issue currently failing build is b/c of missing matchers from [`@testing-library/jest-dom`](https://github.com/testing-library/jest-dom) I think.

**Pull request merged**
