### PR TITLE
Fix TeachingBubble focus outline

### LINKED ISSUE #6332: Coachmark/TeachingBubble: Undesirable outline on content
### Repro 
https://fabricweb.z5.web.core.windows.net/oufr/6.67.2/#/examples/teachingbubble

### Bug Report 
 
- __Package version(s)__: Latest (6.67.2)
- __Browser and OS versions__: Edge, Windows 10 1803
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes. See #6333 
 
Requested priority: Normal
  
#### Describe the issue:
TeachingBubble and Coachmark have an undesirable dotted outline as a result of `ms-TeachingBubble-content` being focusable, but not visually handling the focused state. 
 
#### Actual behavior:
 

Here are some examples of the outline in Edge.

On TeachingBubble:
image

On Coachmark:
image

 
#### Expected behavior:
 There should be no outline, like this:
image

### PR DESCRIPTION
**Pull request by Jahnp**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6332
- [x] Include a change request file using `$ npm run change`

#### Description of changes
Sets `ms-TeachingBubble-content`'s `outline` to `transparent` to prevent an undesirable outline that appears when the TeachingBubble or Coachmark has focus.

Before:
image

After:
image

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
That's odd.. the `ContextualMenuItem.deprecated` tests added in #6235 are the only snapshots failing on this PR.

**Comment by micahgodbolt** [comment]
snapshots still appear broken

**Comment by Jahnp** [comment]
@micahgodbolt they are, yeah. Not sure what's going on or why those tests would be tied to this change. I'll investigate.

**Comment by micahgodbolt** [comment]
Make sure you've pulled in latest master and done a fresh module install. Could be due to a shrinkwrap update or something.

**Comment by Jahnp** [comment]
Thanks! Yeah I did all that this morning on a fresh clone & update of this branch. Will give it another go.

**Pull request merged**
