### PR TITLE
Fabric to Fluent PR #2

### PR DESCRIPTION
**Pull request by micahgodbolt**
This is built off of #12286, so don't merge (or review) this until the first is done and merged in.

This PR is focused on replaced Fabric with Fluent UI in text. 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/12321)

### CODE REVIEW

**Comment by ecraig12345** [comment]
I'm not clear on the reasoning for splitting this out?

**Comment by micahgodbolt** [comment]
I wanted to make each PR a bit easier to parse. focus on a set of changes.

I can glob everything into one monster huge PR is that's prefered.

**Comment by ecraig12345** [comment]
I see the point in general, but it's really hard to tell right now what this PR actually does since it also includes everything from the other one. And it makes the other one a little harder to review (at least as the descriptions are right now) since I'm not clear on what you plan to address later.

**Comment by micahgodbolt** [comment]
Yeah, when I created the PR is forgot that the diff would include both steps. I'll close this one down until the first is finished, as I don't need eyes on this one yet.

**Comment by ecraig12345** [comment]
Sounds good. Maybe also update the other one with a list of things that it's intentionally NOT doing. :)

**Pull request closed without merging**
