### PR TITLE
Fix master build

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

It seems #8601 collided with another change resulting in snapshots being invalid on master.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8615)

### CODE REVIEW

**Comment by dzearing** [comment]
Thank you @JasonGore !

**Comment by dzearing** [comment]
@msft-github-bot merge in 1 hour

**Comment by JasonGore** [comment]
@aftab-hassan What is going on with size-auditor? This PR just has snapshot changes...

**Comment by JasonGore** [comment]
Oh that's weird, since master is in a broken state, it thinks the baseline for everything is 0 bytes? The size diffs all match the baseline sizes.

**Comment by aftab-hassan** [comment]
@JasonGore @KevinTCoughlin 

> Oh that's weird, since master is in a broken state, it thinks the baseline for everything is 0 bytes? The size diffs all match the baseline sizes.

That is correct. We first collect baseline stats by looking at the master's commit hash, in this case `0f51e419a3934462e5cc8773fd79fa7c1bd5eba4`

This happens to be empty
empty-data

And, since the backend code does not find a baseline, it assumes the size is 0. This is intentionally done because in case of a newly added component, we want to capture that the size of the bundle went up due to the newly added component.
`long baselineFileSize = (baselineDetails == null) ? 0 : baselineDetails.FileSize;`
empty-baseline

The LightRail service is run only upon successful build, so there is no way to capture if a build failed or succeeded. Had it failed, it wouldn't have made it thus far.

I am open to thoughts on fixing this edge case.

**Comment by cliffkoh** [comment]
@dzearing sorry that feature you were using is not deployed to Fabric yet :$

**Pull request merged**
