### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by yamatatsu**
Fix "the the " to "the " in comments and markdowns.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11223)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
i just did the search in our docs and we have 15 occurrences of 'the the '. How is this such a common typing mistake :)

**Comment by micahgodbolt** [comment]
@yamatatsu did you clone the repo to make this change? Can you run 'yarn change' to generate a change file?

**Comment by yamatatsu** [comment]
@micahgodbolt I have committed change files. Thank you 😃

**Comment by dzearing** [comment]
This PR made me laugh out loud

**Pull request merged**
