### PR TITLE
[ScrollablePane] DetailsList sticky header alignment bug fix

### LINKED ISSUE #7059: ScrollablePane Details List Header is not aligned with the List rows
### Environment Information 
 
 
- __Package version(s)__: 6.100.0 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
In ScrollablePane DetailsList example create a list with ~15-20 rows such that number of rows are just enough make the DetailsList Header sticky if we scroll down . Now -

- Scroll horizontally to some position .
- Then try to Scroll down slowly .

We will notice just when the header is becoming sticky , at that moment - it is not aligned with the rows . Also , If that is end of scrolling to the bottom then the Header will remain not aligned .

#### Actual behavior:
 
stickyissue

 
#### Expected behavior:
 
Details list Header row should always be aligned to the List rows

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by RupamSarkar**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7059
- [x] Include a change request file using `$ npm run change`

#### Description of changes
This issue is happening because scroll position of the content container is not synced with the sticky content till it has not become sticky yet . So in the example, at the moment it is becoming sticky , we can see the DetailsList header is not aligned with rows . 

Here , we are syncing the scroll position in componentDidUpdate of sticky component so that sticky content scroll position should always be in sync with the content container scroll position.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by natalieethell** [comment]
@leddie24 and @ThomasMichon could you take a look at this when you have a chance? Thanks!

**Comment by cliffkoh** [comment]
Ping @leddie24  and @ThomasMichon

**Comment by KevinTCoughlin** [comment]
Thanks for the fix @RupamSarkar! Worth adding a test to ensure we don't regress this behavior in the future?

**Comment by natalieethell** [comment]
Once @leddie24 merges this PR, we should have vr tests for ScrollablePane: https://github.com/OfficeDev/office-ui-fabric-react/pull/6937.

**Comment by leddie24** [comment]
I need to add a VR test for this scenario in the future. I don't really have bandwidth at the moment. I can add this next month sometime, unless Rupam would like to add it to the VR before merging.

**Comment by RupamSarkar** [comment]
I will try to raise a separate PR for VR test to test this particular scenario . Can someone please merge this one ?

**Pull request merged**
