### PR TITLE
Update Breadcrumb per toolkit - primarily involves adding size prop

### PR DESCRIPTION
**Pull request by lynamemi**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [X] Include a change request file using `$ npm run change`

#### Description of changes

- Added size prop for Breadcrumb, similar to the implementation in Persona, matching the design toolkit guidance
- Tweaked a couple state colors to also match the toolkit
- Cleaned up some spacing and clarified labeling

The size prop examples can be seen below:
image

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by lynamemi** [comment]
Thanks @kristoferbrown ! @dzearing , are you ok with this size implementation?

**Comment by dzearing** [comment]
I'm not really sure about the use case. Right now the breadcrumb scales given page width. Does that affect this still?

**Comment by micahgodbolt** [comment]
@lynamemi can you drop in some gifs of what happens to each breadcrumb at different screen sizes...it appears that they all drop down to small at the smallest breakpoint, right?

**Comment by lynamemi** [comment]
Great feedback, thank you, I will look into it.

**Comment by lynamemi** [comment]
@dzearing @micahgodbolt I talked to design, and the toolkit sizes are, indeed, referencing breakpoints and not a size prop! I will update this PR to revise sizing at different breakpoints instead of with a size prop. And include a more informative gif.

**Comment by lynamemi** [comment]
breadcrumb-responsiveness

**Pull request merged**
