### PR TITLE
Added shimmeredDetailList to top level index file

### PR DESCRIPTION
**Pull request by micahgodbolt**

### CODE REVIEW

**Comment by cliffkoh** [comment]
Could you please add a changefile? The template isn't there for nothing you know 😉

**Comment by micahgodbolt** [comment]
Ah drat. Made one, but never committed it before pushing :D

**Comment by KevinTCoughlin** [comment]
cc: @ThomasMichon

**Comment by micahgodbolt** [comment]
not sure if Thomas really needs to approve here. It's already exported at the lib/component level. This just supports root level export.

**Pull request merged**
