### PR TITLE
Add new icons from the Fabric icons tool (March 2019)

### PR DESCRIPTION
**Pull request by Jahnp**
#### Pull request checklist

- [ ] Addresses an existing issue: N/A
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This PR adds a number of new glyphs from the Fabric icons tool since the last update in November, #7135. Note that all of these icons are added to the defer-loaded subset chunks--it **does not** affect the default icon set that's loaded when you call `initializeIcons()`.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8272)

### CODE REVIEW

**Comment by Jahnp** [comment]
I've added the `PR: API Modified` label due to the new icon names added to the API surface.

**Comment by KevinTCoughlin** [comment]
> I've added the `PR: API Modified` label due to the new icon names added to the API surface.

@Jahnp, looks like the API file within OUFR was modified as part of this so you may need a change file for that package as well for CI to pass. Thanks to @natalieethell for debugging 👏.

**Comment by Jahnp** [comment]
@KevinTCoughlin yeah absolutely! Sorry to waste @natalieethell 's time, I was actually in the midst of adding the new changefile when I saw your comment :) Should be updated shortly.

**Comment by aftab-hassan** [comment]
@dzearing could you take a look at this one, with the change files added (Thanks @Jahnp)

**Comment by Jahnp** [comment]
Thanks @aftab-hassan ! Also note for those familiar with this space: I've already deployed the font files to the SharePoint CDN, so they should be available at the default location now.

**Pull request merged**
