### PR TITLE
Fix application of aria properties on BaseButton. #2270

### LINKED ISSUE #2270: Buttons redundantly specify aria-labelledby, which sometimes doesn't even exist
BaseButton.tsx creates a <button> element with aria-labelledby set to the id that is generated for the descendent <span> that acts as the button's label. This is redundant, since that element's text already serves as the button's label by default.

Furthermore, some buttons don't have a label (e.g. IconButton), so the aria-labelledby attribute refers to an element that doesn't even exist.

I plan to submit a fix tomorrow.

### PR DESCRIPTION
**Pull request by trevorsg**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2270
- [x] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by trevorsg** [comment]
@micahgodbolt Another aria fix :) Would you mind taking a look?

**Comment by micahgodbolt** [comment]
@trevorsg looks good. Might be worth writing a quick test to ensure that this continues to work properly, or at least demo it in an example so that we can see it working.

**Comment by trevorsg** [comment]
@micahgodbolt Thanks! I have added some tests for the various aria label/description combinations.

**Comment by micahgodbolt** [comment]
Awesome :) Looking forward to not having to come back and fix this later when we update the button code again.

**Pull request merged**
