### PR TITLE
Fix 6407

### LINKED ISSUE #6407: Column reordering wrong when DetailsList.checkboxVisibility === 2
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/goodoldneon/pen/pOQObe

### Bug Report 
 
 
- __Package version(s)__: 6.71.0
- __Browser and OS versions__: Chrome 69.0.3497.92 and macOS 10.13.6
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? I'll try
 
Requested priority: Normal
 
Products/sites affected: N/A
 
#### Describe the issue:
 
When setting the `DetailsList` prop `checkboxVisibility` to `2`, column reordering is wrong. The dragged column is not the column that is reordered. The `draggedIndex` argument passed into `handleColumnReorder()` is off by 1.
 
#### Actual behavior:
 
Dragged index is off by 1.
 
#### Expected behavior:
 
Dragged index should match the dragged column's index.

### PR DESCRIPTION
**Pull request by goodoldneon**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6407
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Change the `showCheckbox` conditional to always be `2`. To be honest, I don't know why this works; I'd think the conditional would be necessary. But it fixed the issue.

Running `npm run build` failed because the snapshot for `src/components/DetailsList/DetailsList.test.tsx` is no longer valid after this fix.

#### Focus areas to test

Reorder columns in `DetailsList` component when `checkboxVisibility` props is `2`.

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
What a fun 🐛 -- Nice find! Unfortunately this solution won't work because it causes the sequence of `aria-colindex` to start at `2` when the checkbox is hidden (report of failing test below).

It seems like the items array modification on drag & drop is not taking into consideration the presence of the checkbox as a column, relying on `aria-colindex` as the source of truth. Still thinking... 🤔 

```diff
●DetailsList › renders List with hidden checkboxes correctly
expect(value).toMatchSnapshot()
Received value does not matchstored snapshot "DetailsList renders List with hidden checkboxes correctly 1".
- Snapshot
+ Received
@@ -148,11 +148,11 @@
              >
                
              </i>
            </div>
            <div
-             aria-colindex={1}
+             aria-colindex={2}
              aria-sort="none"
              className=
                  ms-DetailsHeader-cell
                  is-actionable
                  {
 171 |    );
 172 |const tree= component.toJSON();
> 173 |    expect(tree).toMatchSnapshot();
     |^
 174 |  });
 175 |
 176 |  it('focuses row by index' ()=> {
```

**Comment by KevinTCoughlin** [comment]
Here's a potential fix:

```diff
diff --git a/packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx b/packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsxindex 7671be1aa..613efb14a 100644
--- a/packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx+++ b/packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx@@ -337,7 +337,7 @@ export class DetailsHeaderBase extends BaseComponent<IDetailsHeaderBaseProps, ID
   }
   private _onDrop(item?: any, event?: DragEvent): void {-    const draggedColumnIndex = this._draggedColumnIndex;
+    const draggedColumnIndex = this.props.selectionMode !== SelectionMode.none ? this._draggedColumnIndex : this._draggedColumnIndex + 1;^M
     const { columnReorderProps } = this.state;
```

**Comment by goodoldneon** [comment]
`DetailsColumn.props.columnIndex` has a conditional using `showCheckbox`, it might be a little clearer to do the same in your proposed changes. It wouldn't change anything functionally, but it might make the code a little easier to reason through. `DetailsList` (and its subcomponents) is an absolute beast to reason through already.

**Comment by KevinTCoughlin** [comment]
Closing this in favor of #6418 which I'll get merged tomorrow. Again thanks for finding this.

**Pull request closed without merging**
