### PR TITLE
adding a dropdown button option

### PR DESCRIPTION
**Pull request by kenotron**
There needs to be an option to have BOTH a button onClick and a dropdown for items below. The look is slightly different.

### CODE REVIEW

**Comment by cschlechty** [comment]
This change won't work with keyboarding alone or screen readers as-is. What's the scenario for this button?

**Comment by mikewheaton** [comment]
Could you provide a screenshot?

**Comment by kenotron** [comment]
owa
Here's the current OWA command bar with the New button

**Comment by kenotron** [comment]
@cschlechty The scenario is already in place for OWA's command bar. I'm adding parity to the Fabric one basically. You need to have a single click experience to create new mail OR drop down for more options for new meetings, etc. Junk button is the same, but "Move to" is a full drop down all the time.

We should have a way to do this with the JSON based on whether you have a onClick or items. Truly, I really wished that CommandBar is a composition of Components rather than with JSONs...

**Comment by atneik** [comment]
@kenotron We have plans to do that :) https://github.com/OfficeDev/office-ui-fabric-react/issues/94

**Comment by cschlechty** [comment]
I'm fine with the scenario but not the current implementation. We should consider creating a new button type, split button, where the user can either focus both portions of the button separately, or launch the menu via known key press (down arrow, alt_down, etc). I'm in favor of separate focus-able areas as its more user intuitive. Currently a screen reader user will tab to this button, hear it has a menu popup associated, try to launch the menu, but instead activate the onClick.

**Comment by dzearing** [comment]
I have support for this coming in a PR very soon

**Comment by dzearing** [comment]
I'm going to close this; we have some fixes coming for this but it will be a bit of time.

**Pull request closed without merging**
