### PR TITLE
Check: Reduced size of background so blue does not extend outside of border.

### LINKED ISSUE #2024: Detailslist selection check has blue artifacts around it
### Bug Report

Affects all browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

#### Describe the issue:
When selecting an item in DetailsList, there are blue (theme colored) artifacts around the edges.
This is likely due to the background being a different object, and the same size as the border, which results in half pixel artifacts around the outside of the border.

#### Expected behavior:
There should be no artifacts around the outside edge. See right side circle

selectionbug

### PR DESCRIPTION
**Pull request by betrue-final-final**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2024
- [x] Include a change request file using `$ npm run change`

#### Description of changes

I subtracted 2px from the selection background so the background does not show beyond the white borders and give it a blue tinge.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by betrue-final-final** [comment]
Doh! Forgot to add it. I saved it even.
selectioncheckfix

**Comment by micahgodbolt** [comment]
Rad :D

**Comment by betrue-final-final** [comment]
Alrighty, squashing da merge.

**Comment by betrue-final-final** [comment]
OH! You did it 👍

**Pull request merged**
