### PR TITLE
Use overflow-wrap: break-word instead of word-break: break-all in tooltips, labels and dropdowns

### LINKED ISSUE #1627: Tooltips break intra-word for wrapping
@gitjain @mikewheaton 

The PR #1402 makes tooltips break intra-word for the majority case, which is strings containing breaking characters.

See how the word "April" is broken:
image

I believe we want `overflow-wrap: break-word` instead. See: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Note:** this property is word-wrap in IE.

### PR DESCRIPTION
**Pull request by trevorsg**
Fix #1627

#### Pull request checklist

- [x] Addresses an existing issue: #1627 
- [x] Include a change request file if publishing 
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes

See #1627

### CODE REVIEW

**Comment by micahgodbolt** [comment]
I'm trying to see why we need overflow-wrap as well. seems word-wrap: break-word is sufficient.

**Comment by trevorsg** [comment]
@micahgodbolt overflow-wrap is the standard. word-wrap is IE/Edge nonsense. See http://caniuse.com/#search=overflow-wrap

**Comment by micahgodbolt** [comment]
Here's a codepen to play with https://codepen.io/micahgodbolt/pen/KmagqP

Seems overflow-wrap is only supported by some browsers, but word-wrap works just fine for all of them. What does overflow-wrap do that word-wrap doesn't?

**Comment by micahgodbolt** [comment]
ok, seems overflow-wrap has better support than I first thought

**Comment by micahgodbolt** [comment]
looks good to me then.

**Comment by micahgodbolt** [comment]
We probably want to make this change in dropdown and label too then. Pretty sure we copied over the implementation.

**Comment by trevorsg** [comment]
Oh, cool. I'll update the branch if that's the case.

**Comment by trevorsg** [comment]
@micahgodbolt Updated to make the same fix to Label and Dropdown. Can you have a look?

**Pull request merged**
