### PR TITLE
Stack: Renaming horizontalAlignment, verticalAlignment, fillHorizontal and fillVertical to horizontalAlign, verticalAlign, horizontalFill and verticalFill respectively

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Stack: Renaming `horizontalAlignment`, `verticalAlignment`, `fillHorizontal` and `fillVertical` to `horizontalAlign`, `verticalAlign`, `horizontalFill` and `verticalFill` respectively.

The reason for changing `horizontalAlignment` and `verticalAlignment` to `horizontalAlign` and `verticalAlign`, respectively, is twofold. The first reason is to shorten the properties for ease of use. The second reason is because `horizontalAlign` and `verticalAlign` were already the naming schemes exposed by `VerticalStack` and `HorizontalStack` before they were conflated into a singular `Stack` component. Since the separate components were the ones we were encouraging to use, it makes sense to update the singular `Stack` component's interface to reflect the separate components' api.

The reason for changing `fillHorizontal` and `fillVertical` to `horizontalFill` and `verticalFill`, respectively, are to achieve symmetry with the naming scheme of `horizontalAlign` and `verticalAlign`.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
@khmakoto while i'm 100% for this change, can you add a little background on the rationale for the name change?

**Comment by khmakoto** [comment]
@micahgodbolt The rationale for the name change came from some discussions with David. I've updated the PR description to add more context behind why we are doing this.

**Comment by dzearing** [comment]
@micahgodbolt yeah in usage, anything that isn't consistent or predictable makes for a messy api.

Without looking at docs, when I used it, i remember that `horizontalAlign` is how I'd align. Then when I used `wrap`, I remember that I may need to fill the given area, so I intuitively tried `horizontalFill`, referring to the align prop, but found it missing. So anything that applies to horizontal, we should just normalize the naming for maximum predictability and ease of memorization.

**Comment by micahgodbolt** [comment]
Yup, just wanted to make sure the rationale was captured in this PR.

And David....stop working!

**Pull request merged**
