### PR TITLE
SwatchColorPicker: Update scss to make colorpicker meet redlines.

### PR DESCRIPTION
**Pull request by montselozanod**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Before these changes, the SwatchColorPicker looked this way:

beforecolorpicker

In this gif we can see three problems:
1. There is a lot of spacing between the cells in the grid.
2. The redlines call for the circles to be 20px in an unselected state. In a selected state, circle should become 16px because inner border/padding trim circle by 2px. Before the change, the circles were being trimmed to 12px and the inner  border/padding was 4px.

After these changes, these is how the SwatchColorPicker looks like now:

aftercolorpickerkeyboard

Important Note: For visibility of styling changes the gifs are in a browser with a 400% zoom

### CODE REVIEW

**Comment by betrue-final-final** [comment]
It looks like you got rid of theme color for selected. We should have theme for selected vs. neutral for hover.

image

**Comment by betrue-final-final** [comment]
Also looks like the horizontal and vertical margins are different.

**Comment by montselozanod** [comment]
@betrue-final-final Yeah the margins are different, I'll check that. I am confused regarding your first comment. My change is only making circle's bigger when hovered/selected and changing height of cells. I don't see a change in the color in screener (though I may be a bit blind) The change should be the circle and border size

**Comment by christiango** [comment]
@montselozanod, this is probably going to conflict with #3318 and it might break some partners. @montselozanod, can you drive the conversion of the component to mergeStyles and then we can have both Outlook and and Office Online can customize them to meet their needs?

The merge styles PR should have exact visual parity with the current visuals and we could rely on the customization inside the various apps.

@dzearing is working on new guidelines for how styling should work as a part of #3180 , he's currently targeting this in the 6.0 branch, but hopefully we can actually move some of the shared utilities into 5.0 to avoid having to change the styling API later on.

**Comment by christiango** [comment]
Closing this PR since we are going to solve this by converting the component to mergeStyles

**Pull request closed without merging**
