### PR TITLE
Updated FileTypeIconMap.ts for Fluent FileType Icons update

### PR DESCRIPTION
**Pull request by bigbadcapers**
#### Description of changes
updated filetype icon mappings to include missing files (figma, powerpoint slide, etc) and entries for new supported non-file items (sp news, sway)

### CODE REVIEW

**Comment by betrue-final-final** [comment]
Designer in the repo!!!

**Comment by aneeshack4** [comment]
Travis's failing because there's no change file, do "rush change" in your command line and copy paste your description to create a change file and commit that.

**Comment by Vitalius1** [comment]
@bigbadcapers what about #7153? Are this PR's introducing different things? It looks like both target the same file... maybe first one needs to be closed?

**Comment by aneeshack4** [comment]
@bigbadcapers any update on this?

**Comment by Vitalius1** [comment]
@Jahnp can you unblock this PR if it looks right to you. I pushed a change log to help @bigbadcapers .

**Comment by Jahnp** [comment]
Thanks for adding the change file @Vitalius1 . I'm not the expert with the file type icons code, but this doesn't look objectionable to me. I'll go ahead and approve.

**Pull request merged**
