### PR TITLE
Add optional property to DetailsList to render with transparent background

### LINKED ISSUE #5635: DetailsList doesn't have a way to render with a transparent background
**Describe the feature that you would like added**
I would like to have a way to render DetailsList with a transparent background.

**What component or utility would this be added to**
DetailsList

**Have you discussed this feature with our team, and if so, who**
Discussed with Thomas Michon

**Additional context/screenshots**
Modern Sharepoint sites can have themes that set the background color of the page. Web parts do not have a way to access this background color. When web parts with a DetailsList component are rendered, the DetailsList doesn't look very good with the default white background. For an example of how this can be accomplished, I have already created a PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/5634

### PR DESCRIPTION
**Pull request by paul-otten**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5635
- [x] Include a change request file using `$ npm run change`

#### Description of changes

I added a new property to the DetailsList component: `enableTransparentBackground`.
This property causes DetailsList, DetailsHeader, and DetailsRow to render without a background color. This property does not seem to have an effect when shimmer is enabled and should likely not be used together with that feature.

#### Focus areas to test

Test DetailsList component and how it renders with the `enableTransparentBackground` property set/not set.

### CODE REVIEW

**Comment by kenotron** [comment]
Change a style should be done with the theme / style customizer mechanism. This will make sure it works with Shimmer, etc. 

I think what you're looking for is to create a theme with the `semanticColor.listbackground` set to "transparent".

**Comment by kenotron** [comment]
Also the styles file of interest is here:
`/Users/ken/workspace/fabric/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.styles.ts`
for your reference.

**Comment by dzearing** [comment]
@ThomasMichon Any idea why we'd ever have a white background? Shouldn't it be transparent by deffault?

**Comment by paul-otten** [comment]
@kenotron As suggested, I will go ahead and pass in a theme with a transparent listBackground in my consuming code in sp-client. I didn't realize that I could pass in a theme via the props.

I will go ahead and abandon this PR.

**Comment by kenotron** [comment]
Cool! Glad I helped you out! It's an elegant generalized solution that solves a nice category of problems all at once :)

**Pull request closed without merging**
