### PR TITLE
Added TeachingBanner Component

### PR DESCRIPTION
**Pull request by janjachacz**
#### Pull request checklist

- [x] Include a change request file using `$ yarn change`

#### Description of changes

Added a new TeachingBanner Component

https://www.figma.com/file/BAfsTrZ9ehIYZ0oYuyskUN2R/Web-Fluent?node-id=13858%3A47817

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10943)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
my concern with this control is that there is so much overlap with message bar. as an experiment, that's fine, but i'd want to better rationalize how this could simply be a message bar variant.

**Comment by v-jajach** [comment]
@micahgodbolt, I guess you're right.

At the time of scoping this, `messageBarIconProps` was not in `MessageBar`'s source code yet. My understanding was to create a new component to match the `TeachingBubble`'s and `Coachmark` _collection_. 

I'll discuss this with my team. 

Thanks for your return

**Comment by micahgodbolt** [comment]
@v-jajach any decision here?

**Comment by v-jajach** [comment]
@micahgodbolt, yes finally we'll leverage the MessageBar component. 
Just need to add the task in one of our sprints.

**Comment by micahgodbolt** [comment]
Thanks @v-jajach i'll close down this PR then.

**Pull request closed without merging**
