### PR TITLE
Allow consumers of onItemContextualMenu a way to stop ev.preventDefau…

### LINKED ISSUE #2835: DetailsList: No way to prevent onItemContextMenu based on target
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: VSTS

#### Describe the issue:

If a DetailsList is passed onItemContextMenu, there is no way to NOT prevent default based on the target that was selected. As an example, if the row contains a <a> element, and that is the element that the user invokes the context menu for, we want to show the default context menu to allow the user to open in a new tab, copy link, etc.

However, after calling the onItemContextMenu callback, the SelectionZone will always call ev.preventDefault(), so even in the case where the component decides that it doesn't want to do anything special for this event, there is no way to stop ev.preventDefault from being called.

### If applicable, please provide a codepen repro:

Reproducible on the 
Advanced DetailsList of 5000 items, variable row heights 
DetailsList Example (the 'key' column is a link).

### PR DESCRIPTION
**Pull request by dmarcey**
…lt from being called.

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2835 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

If onItemContextMenu returns false, don't call ev.preventDefault().

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by cschleiden** [comment]
@dzearing @micahgodbolt I think this is similar to the problem with `onEscape` we recently discussed. Did we find a pattern that works for all events?

**Comment by micahgodbolt** [comment]
Yup, just waiting for approval on this one.

https://github.com/OfficeDev/office-ui-fabric-react/pull/2730

```js
myFunc(ev) {
  this.props.onClear && this.props.onClear(ev); 
  if (!ev.defaultPrevented) { // do default bahavior }
}
```

```jsx
<Component onClear={(ev) => ev.preventDefault()} />
```

Not sure if this works for the current situation, but I think this is the model we should use when we can.

**Comment by cschleiden** [comment]
@micahgodbolt Here it's basically the other way around... we always prevented default and we need a way to not do that.

**Comment by joschect** [comment]
I believe that when an event handler returns false it is often the equivalent of saying preventDefault. It's not always the case but it's often enough that we should stick with that convent and have it return true if we don't want prevent default from being called.

**Comment by dmarcey** [comment]
Are we in agreeance that preventDefault() should still be called if undefined is returned, in order to keep back-compat? If so, I will go ahead and update such that preventDefault is called if onItemContextMenu returned undefined or false.

**Comment by dmarcey** [comment]
@joschect @cschleiden @micahgodbolt Any other thoughts on these changes or if there is a different way we should be doing this?

**Comment by cschleiden** [comment]
Yeah, I think back compat is important here, we probably don't want context menus suddenly showing up everywhere.

**Pull request merged**
