### PR TITLE
Drop trailing space in DetailsList header aria-labeledby

### PR DESCRIPTION
**Pull request by benabbon**
<Disclaimer: This is my first contribution to this project, please advise If I did something not respecting the process, thanks!>

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Fix the DetailsList header aria-labeledby having an extra space.

{
  "changes": [
    {
      "packageName": "office-ui-fabric-react",
      "comment": "Drop space from DetailsList header aria-labeledby",
      "type": "patch"
    }
  ],
  "packageName": "office-ui-fabric-react",
  "email": "b.nabil@live.fr"
}

Please let me know if the change file needs to be included in another way.
Also, let me know if I should create an issue for this bug.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8301)

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
@benabbon actually you need to commit the file output from `npm run change` which you've pasted in the description. That will cause CI to pass and this will merge :).

**Comment by aftab-hassan** [comment]
@benabbon thank you for your contribution. As @KevinTCoughlin  mention, please run the command `npm run change` which will help keep track of details of the fix.

@KevinTCoughlin can I remove the `Auto-merge` label until this is added? Looks like 6 hours to go for the auto merge.

**Comment by KevinTCoughlin** [comment]
FWIW I tried to push the change file to the remote branch but received permission denied :(. So we'll need @benabbon to do it when next available.

**Comment by benabbon** [comment]
Thank you  @KevinTCoughlin and @aftab-hassan , I pushed the update (sorry for the delay, different time zones ;))

**Pull request merged**
