### PR TITLE
Removing Fabric component from vr-tests

### LINKED ISSUE #6528: Always use fonts defined in the theme for components (remove Fabric component dependency)
Expected:

render any Fabric component, renders the correct fonts.

Resulted:

times new roman

### PR DESCRIPTION
**Pull request by aneeshack4**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6528
- [x] Include a change request file using `$ npm run change`

#### Description of changes

In https://github.com/OfficeDev/office-ui-fabric-react/pull/6647#, fonts were loaded from theme for all components that have a theme available. In this PR, I'm removing the Fabric component from the vr tests. There are more instances of <Fabric> wrappings in other parts of the code like Example files but none left under vr tests.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by aneeshack4** [comment]
I'm looking into the screener failures - it looks like it's a result of changes in width/height and padding.

**Comment by micahgodbolt** [comment]
The Fabric component had display flex on it

image

Just change <Fabric to <div and leave it there

**Comment by dzearing** [comment]
There are a lot of bugs here. Take a look at the screener issues, some themes are:

1. The component assumed the inherited text color. This might be ok, but to reduce the noise, you can assign the DIV wrapper this text color.

2. The component is now rendering in times new roman. These components did not mix in the theme font, and therefore need to be fixed. DocumentCard for example.

**Comment by aneeshack4** [comment]
@dzearing working on it! trying to finish the other PR i have on aria-modal first but I will get back to this asap

**Comment by dzearing** [comment]
Awesome, thank you!

**Comment by aneeshack4** [comment]
I'm going to come back to this PR after finishing my shield issues - closing for now but will reopen it!

**Pull request closed without merging**
