### PR TITLE
Nav: add data-link-key to items.

### LINKED ISSUE #1869: Nav: need a way to find items in Nav
### Bug Report

- __Package version(s)__: 2.34.0 (latest master as of 2017/5/26)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Blocking)

#### Describe the issue:

Interfaces `INavLink`, `INavLinkGroup` contains property `automationId` but it's not working.

#### Actual behavior:

`automationId` property does not work. As I checked, it is not used in `Nav.tsx` code.

#### Expected behavior:

Value of `automationId` should be present in HTML as value of `data-automation-id`. And user can use them for automation purpose, i.e., unit test.

### PR DESCRIPTION
**Pull request by warmsea**
This is to fix #1869 

Currently, there's no good way to find a particular item in a Nav.
This PR added `data-link-key` to each link in a Nav.
So, customers can find an item with queries like `[data-link-key='news']` in page.

### CODE REVIEW

**Comment by Jahnp** [comment]
@inateeg could you take a look when you have a chance? I believe you added this initially--would love your thoughts on this change. Seems righteous to me IMO.

**Comment by dzearing** [comment]
Hmmm. @micahgodbolt @Jahnp 

This is a very limited hack, which is simple and destabilizing, but also less robust. The root is that Nav needs love. The same problem will apply when someone wants to add `data-automation-id` attributes. We should allow data-* attributes to be mixed into the items here in general.

At a minimum we should just use `getNativeProperties` and mix them into the items like other components. That solves the data-automation-id issue.

A better design would be that the NavItems are just IButtonProps, which just mixes in native props into the root. 

An even better design would be to decompose Nav similar to maybe Dialog, where maybe it has "areas" and you can just host stuff in the areas. Maybe there is are Nav.Group and Nav.Item components which help to render content within.

**Comment by micahgodbolt** [comment]
@warmsea take a look at @dzearing's suggestions and see if that works for you.

**Comment by warmsea** [comment]
I agree with @dzearing's idea. But the better designs require seem require interface changes. Do you accept PR changes that much?

**Comment by micahgodbolt** [comment]
No problem with changing interfaces, as long as we aren't totally breaking them. We can support the old interface for now and deprecate the old prop.

**Comment by micahgodbolt** [comment]
So short term is mix in getNativeProperties, long term is refactor to be more like dialog.

**Comment by micahgodbolt** [comment]
I'm going to close this PR down. Let's approach it via mixing in getNativeProps like this https://github.com/OfficeDev/office-ui-fabric-react/blob/2047284a4e879d5a65131385f11204c87371b1c2/packages/office-ui-fabric-react/src/components/Overlay/Overlay.tsx#L27

This'll allow you to pass through any valid div prop needed for tracking nav items.

**Comment by warmsea** [comment]
OK.

**Pull request closed without merging**
