### PR TITLE
Panel: Add optional custom function to handle clicks outside the panel when isLightDismiss=true

### PR DESCRIPTION
**Pull request by amkronen**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ x] Include a change request file using `$ npm run change`

#### Description of changes

Added an optional callback in the props which handles the click. If the custom predicates are met, the Panel can be closed from the outside. If no custom function is set, we default to the current behavior. Also added an example which shows the usage of this: we display a dialog with an "are you sure..." text where the user can confirm that they want to close the panel.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by amkronen** [comment]
@micahgodbolt , @dzearing when can I expect this to be merged? I have other work pending on this change :) As a general question, is there a system for when pull requests are approved and merged, vs when they only are approved? Just trying to figure out if there is work left to do for me here :)

**Comment by micahgodbolt** [comment]
@amkronen do you see the 'squash and merge' button? Typically we sign off on a PR at allow the dev to merge it when they feel ready. I'll merge it in this time. It should go out in a release this afternoon.

**Comment by amkronen** [comment]
I did not get the squash and merge option, just a message at the bottom that only users with write access can merge the change and I guess I’m not supposed to have that?

Få Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by micahgodbolt** [comment]
That makes sense, no worries!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Pull request merged**
