### PR TITLE
Tooltip: Fixing 'persist on scroll' issues

### LINKED ISSUE #9694: Tooltip Persists After Scrolling
### Environment Information 
 
- __Package version(s)__: > 6.184.0
- __Browser and OS versions__: Chrome 75.0.3770.100, macOS 10.14.5

#### Actual behavior:
 
I'm seeing 2 variations of this issue.

**With Tab Focus**
1. With tab focus on a tooltip host, scroll the page.
2. Observe that the tooltip continues to show until focus changes.
tooltip_with_tab_focus

**Without Tab Focus**
1. Hover cursor over tooltip host and scroll the page.
2. Observe that the tooltip continues to show until scrolling stops.
tooltip_without_tab_focus

Tooltip continues to show after page scrolling starts, and appears disconnected from the tooltip host. 
 
#### Expected behavior:

Tooltip should disappear the instant that scrolling starts. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Maybe.  With strong guidance.
 
Requested priority: Normal
 
Products/sites affected: Yammer

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9694
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This PR fixes some issues that existed on the `Tooltip` component:
- The `Tooltip` was not dismissing on scroll when the focus was on the element
- The `Tooltip` was not dismissing on scroll until the scroll stopped
- You couldn't scroll the document when hovering over a `Tooltip`

The first two bugs was introduced in Fabric 5.77.0 as part of PR #4364.

#### Focus areas to test

- Hover over a component with a `Tooltip` in the `Tooltip` examples page and notice the difference between the live website and this PR when scrolling after the `Tooltip` appears.
- Move focus with your keyboard over a component with a `Tooltip` in the `Tooltip` examples page and notice the difference between the live website and this PR when scrolling after the `Tooltip` appears.
- Hover over a `Tooltip` in the `Tooltip` examples page (easiest to do this is the `Tooltip with delay closing`). Once you are hovering the `Tooltip`, start scrolling and notice the difference between the live website and this PR.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9749)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
few quick Qs. 
1. does this address tooltips with delays?
2. Can you figure out why scroll doesn't work when you hover over the tooltip (keeping focus)

**Comment by khmakoto** [comment]
@micahgodbolt:

1.- Yes, the example with tooltips with delays was still working when I tested this change.
2.- I'm kind of confused, what do you mean by this? Is this a separate bug from those filed in #9694?

**Comment by khmakoto** [comment]
@Vitalius1 it's PR #4364, the PR adds delayed functionality to the `Tooltip` component but seems to have added these bugs by mistake.

**Comment by khmakoto** [comment]
@micahgodbolt I think I know what you mean by your second question now. That seems to be the behavior since `Tooltip` uses `Callout`, which as another surface doesn't allow for scrolling when focus is inside. You can check this behavior in the `Callout` examples as well.

**Comment by micahgodbolt** [comment]
But since a tooltip can't have scrollable content is it possible to reenable scrolling?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by khmakoto** [comment]
@micahgodbolt let me investigate.

**Comment by khmakoto** [comment]
@micahgodbolt just pushed a commit to allow scrolling when hovering over a `Tooltip`.

**Comment by micahgodbolt** [comment]
now what's the chance that someone has a tooltip with so much content that it has to scroll :-\

If that comes up i guess we can simply check for overflow....but people really shouldn't have that much content in a tooltip.

**Comment by khmakoto** [comment]
@micahgodbolt yes, I feel like the `Tooltip` shouldn't be used like that in the first place so I think we should be ok with this change.

**Comment by micahgodbolt** [comment]
jon is on vacation. going to merge this in

**Pull request merged**
