### PR TITLE
Adds missing property values for 'alignSelf' (Fixes #6068)

### LINKED ISSUE #6068: [merge-styles] alignSelf definition in IRawStyleBase is not complete
### Please provide a reproduction of the bug in a codepen:

This is the current definition of alignSelf:
`alignSelf?: ICSSRule | 'auto' | 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch'; `

But per MDN several values are missing (`normal`, `start`, `end`, `self-start`, `self-end`, `first baseline`, `last baseline`, `safe center`, `unsafe center`):
https://developer.mozilla.org/en-US/docs/Web/CSS/align-self

### Bug Report 
 
 
- __Package version(s)__:
@uifabric/merge-styles:  6.7.0
- __Browser and OS versions__: 
n/a
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 Requested priority: High (I haven't found a work-around yet).
 
Products/sites affected: n/a

### PR DESCRIPTION
**Pull request by redoz**
Adds missing property values for "align-self" css property.

#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6068
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Adds missing property values to 'self-align' per https://www.w3.org/TR/css-align-3/#propdef-align-self

### CODE REVIEW

**Comment by redoz** [comment]
Last one for me for this week. If there are issues here I'll pick them up again Monday. 
Have a great weekend everyone!

**Comment by redoz** [comment]
I misread the CSS grammar for this and justify-self. Should I push the correct fix to this PR or close this and create a new one?

**Comment by redoz** [comment]
Well, I pushed the fixes anyway, as regardless this PR is incorrect without it. If you rather I close this and open a new PR let me know. 
I ended up with a second change file now as well, not entirely sure if I should've edited the one I already had, but I didn't want to clobber @cliffkoh edits with a squash. If that is preferred let me know and I'll squash this into a single commit with a single change file.

**Comment by micahgodbolt** [comment]
pushing was correct....just make this PR as correct as possible.

**Comment by micahgodbolt** [comment]
From taking a look at https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items , i'd say this looks good.

**Comment by micahgodbolt** [comment]
btw, i deleted the redundant changefile from master. Thanks again!

**Pull request merged**
