### PR TITLE
Dropdown, slider high contrast fixes

### LINKED ISSUE #1273: Dropdown: Focused element in dropdown list is not visible in high contrast
### Bug Report

- __Package version(s)__: office-ui-fabric-react 1.14.2
- __Browser and OS versions__: EDGE, Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
Normal
#### Describe the issue:

When in high contrast mode, Dropdown list focused item is black and not visible.

image

#### Actual behavior:

When in high contrast mode, Dropdown list focused item is black and not visible.

#### Expected behavior:

When in high contrast mode, Dropdown list focused item background color and font color should be such that they are visible.

### LINKED ISSUE #1640: [High Contrast] Slider is coming as a circle only in high contrast modes in IE/Edge
### Bug Report

- __Package version(s)__: (2.20.2)
- __Browser and OS versions__: (IE/Edge Win10)
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)
VSTS or any site using slider  ( and users using it high contrast modes )

#### Describe the issue:
Slider: https://dev.office.com/fabric#/components/slider

Slider in non-high contrast mode
image

In "High contrast Black" and "High contrast White" [ could be issue in other high contrast modes as well] Slider is not visually similar to what we see in non-high contrast mode, Only the silder knob(circle) is visible in this mode .

#### Actual behavior:
High Contrast Black
Slider: https://dev.office.com/fabric#/components/slider
image

High Contrast White
image

#### Expected behavior:
In high contrast mode we should get the slider visually similar to what we get in non-high contrast mode.

#### User Impact:
User with low vision who relay on screen reader will face difficulty to access the slider.

### PR DESCRIPTION
**Pull request by mdahamiwal**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1273, Fixes #1640 
- [x] Include a change request file if publishing 
- [x] bugfix
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes
In Edge and IE11, the browser adjusts the high contrast color. For components where we provide high contrast styling we need to disable the Edge/IE11 high contrast adjusting to avoid conflicts.
This PR fixes three HC issues:

**Before fix:**
- Dropdown option selection has back plate and caret clipped borders

image

- slider areas are not visible in HC
image

**After fix:**
- Dropdown selected options are visible and caret shows top-down border
image

- Slider has visible slider areas
image

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by betrue-final-final** [comment]
Thanks for the screen shots. Can we reverse those track colors on the sliders? The most visible part should be the "value" side.

As this is reversed color, that would mean what is usually darkest, becomes lightest.

**Comment by betrue-final-final** [comment]
Also lets make the disabled track disabled green.

**Comment by micahgodbolt** [comment]
Great work. Once you address Ben's requests we should be able to get this in.

**Comment by mdahamiwal** [comment]
@betrue-final-final, I see your point but in HC there is no option for lighter and darker colors. So I am making them white and black for now. @micahgodbolt, any idea if we can provide custom colors in HC for slider. I see only following ones for a dark theme:

`$ms-color-contrastWhite`
`$ms-color-contrastWhiteSelected`
`$ms-color-contrastBlackDisabled`

Applying these it looks like this:
image

Let me know if this looks good. I will update the PR.

**Comment by betrue-final-final** [comment]
Yes, the palette is limited, and I realize you were using a non-high contrast color with that blue. The best answer is to make the right side hollow.
image

**Comment by mdahamiwal** [comment]
float styling was breaking due to new borders. I converted the slider to flex layout

@betrue-final-final, @micahgodbolt, does this look good ?

slider

**Pull request merged**
