### PR TITLE
disable module concatenation

### PR DESCRIPTION
**Pull request by aftab-hassan**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes
This PR turns off module concatenation so the size auditor tool has more meaningful stats to report.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8617)

### CODE REVIEW

**Comment by aftab-hassan** [comment]
This works and generates a module name per module tested on my machine.

However, please suggest any changes you'd like to see. I am not very sure of the `isProduction` tags and if they would show a different result against a `prod` build, say.

**Comment by cliffkoh** [comment]
@aftab-hassan you can test by using `rush build --production`  :) 

To validate impact downstream, after you do that, copy and replace the files built in a downstream repo (such as in odsp-next). @aditima can guide you on how to do that.

**Comment by dzearing** [comment]
This is rather terrible because now we are no longer showing the exact size difference or which modules actually end up in the bundle.

**Comment by dzearing** [comment]
Somehow webpack-bundle-analyzer can show concatenated results, and has a way to unpack what's in the concatenation. I don't think it should be required to turn off concatenation to break down the content.

I am wondering if sourcemap explorer could be another way to understand bundle content.

https://alligator.io/angular/bundle-size/

**Comment by aftab-hassan** [comment]
thanks @cliffkoh. I ran the above command, and it generates modules without concatenating them, as we'd like to see. `rush build` and `rush build --production` both work

**Comment by aftab-hassan** [comment]
> This is rather terrible because now we are no longer showing the exact size difference or which modules actually end up in the bundle.

just seeing now.

**Comment by aftab-hassan** [comment]
> This is rather terrible because now we are no longer showing the exact size difference or which modules actually end up in the bundle.

@dzearing can you give me an example of why this is not a good idea, so I can understand better and look for an alternative approach? These are the module name I see in the `office-ui-fabric-react-ActivityItem.stats.json` after disabling module concatenation based on this PR. Also attaching the entire stats file [here](https://microsoft.sharepoint.com/teams/FabricTactical/Shared%20Documents/General/office-ui-fabric-react-ActivityItem.stats.json). Could you point out which entries here make it not a suitable approach?

1. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/Persona.types.js
2. D:/GitRepos/office-ui-fabric-react/common/temp/node_modules/.registry.npmjs.org/tslib/1.9.3/node_modules/tslib/tslib.es6.js
3. external "React"
4. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/index.js
5. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaConsts.js
6. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Image/Image.types.js
7. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/fonts.js
8. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/index.js
9. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/Stylesheet.js
10. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/keyframes.js
11. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/KeyCodes.js
12. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Utilities.js
13. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/styleToClassName.js
14. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/DefaultPalette.js
15. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/warn/warn.js
16. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/utilities/icons.js
17. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/DefaultFontStyles.js
18. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/customizations/Customizations.js
19. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/properties.js
20. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/theme.js
21. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/getWindow.js
22. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Styling.js
23. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/index.js
24. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/transforms/rtlifyRules.js
25. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/getDocument.js
26. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/index.js
27. D:/GitRepos/office-ui-fabric-react/common/temp/node_modules/.registry.npmjs.org/process/0.11.10/node_modules/process/browser.js
28. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/concatStyleSets.js
29. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/mergeStyles.js
30. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/utilities/index.js
31. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/utilities/buildClassMap.js
32. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/MergeStyles.js
33. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/CommonStyles.js
34. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/zIndexes.js
35. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/extractStyleParts.js
36. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/object.js
37. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/fontFace.js
38. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/setSSR.js
39. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/styled.js
40. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/classNamesFunction.js
41. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Icon/Icon.js
42. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/AnimationStyles.js
43. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/getFocusStyle.js
44. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/mergeStyleSets.js
45. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/GlobalSettings.js
46. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Image/Image.js
47. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/localStorage.js
48. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/initializeFocusRects.js
49. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Icon/Icon.types.js
50. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/sessionStorage.js
51. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/memoize.js
52. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/BaseComponent.js
53. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/ActivityItem/index.js
54. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/ActivityItem/ActivityItem.js
55. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/classNames/index.js
56. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/classNames/AnimationClassNames.js
57. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/utilities/getIconClassName.js
58. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/hiddenContentStyle.js
59. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/PulsingBeaconAnimationStyles.js
60. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/getGlobalClassNames.js
61. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/scheme.js
62. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/GeneralStyles.js
63. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/getFadedOverflowStyle.js
64. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/classNames/FontClassNames.js
65. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/classNames/ColorClassNames.js
66. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/customizations/CustomizerContext.js
67. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaCoin/PersonaCoin.base.js
68. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/transforms/kebabRules.js
69. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/transforms/provideUnits.js
70. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/transforms/prefixRules.js
71. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/getVendorSettings.js
72. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Image/Image.base.js
73. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Image/Image.styles.js
74. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/keyboard.js
75. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/DefaultSpacing.js
76. D:/GitRepos/office-ui-fabric-react/common/temp/node_modules/.registry.npmjs.org/@microsoft/load-themed-styles/1.8.39/node_modules/@microsoft/load-themed-styles/lib/index.js
77. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/styles/DefaultEffects.js
78. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Icon/Icon.base.js
79. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Icon/Icon.styles.js
80. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaInitialsColor.js
81. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaPresence/PersonaPresence.base.js
82. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/initializeDir.js
83. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/Async.js
84. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/EventGroup.js
85. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/warn/warnDeprecations.js
86. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/warn/warnMutuallyExclusive.js
87. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/warn/warnConditionallyRequiredProps.js
88. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaPresence/PersonaPresence.styles.js
89. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaCoin/PersonaCoin.styles.js
90. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/ActivityItem/ActivityItem.classNames.js
91. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/ActivityItem/ActivityItem.styles.js
92. D:/GitRepos/office-ui-fabric-react/packages/set-version/lib/setVersion.js
93. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/merge.js
94. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaPresence/PersonaPresence.js
95. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/ActivityItem.js
96. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Icon.js
97. D:/GitRepos/office-ui-fabric-react/packages/set-version/lib/index.js
98. D:/GitRepos/office-ui-fabric-react/packages/merge-styles/lib/version.js
99. (webpack)/buildin/global.js
100. D:/GitRepos/office-ui-fabric-react/packages/styling/lib/version.js
101. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaCoin/PersonaCoin.js
102. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/language.js
103. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/customizations/mergeSettings.js
104. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/rtl.js
105. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/initials.js
106. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Image.js
107. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Persona.js
108. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaPresence/index.js
109. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Callout.js
110. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Fabric.js
111. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/FocusTrapZone.js
112. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Layer.js
113. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Popup.js
114. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/Tooltip.js
115. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/common/DirectionalHint.js
116. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Callout/Callout.js
117. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Callout/CalloutContent.base.js
118. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Callout/CalloutContent.js
119. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Callout/CalloutContent.styles.js
120. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Callout/FocusTrapCallout.js
121. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Callout/index.js
122. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Fabric/Fabric.base.js
123. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Fabric/Fabric.js
124. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Fabric/Fabric.styles.js
125. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Fabric/index.js
126. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/FocusTrapZone/FocusTrapZone.js
127. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/FocusTrapZone/index.js
128. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Icon/index.js
129. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Image/index.js
130. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Layer/Layer.base.js
131. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Layer/Layer.js
132. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Layer/Layer.notification.js
133. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Layer/Layer.styles.js
134. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Layer/LayerHost.js
135. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Layer/index.js
136. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/Persona.base.js
137. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/Persona.js
138. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/Persona.styles.js
139. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/PersonaCoin/index.js
140. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Persona/index.js
141. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Popup/Popup.js
142. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Popup/index.js
143. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/Tooltip.base.js
144. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/Tooltip.js
145. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/Tooltip.styles.js
146. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/Tooltip.types.js
147. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/TooltipHost.base.js
148. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/TooltipHost.js
149. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/TooltipHost.styles.js
150. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/TooltipHost.types.js
151. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/components/Tooltip/index.js
152. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/utilities/positioning.js
153. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/utilities/positioning/index.js
154. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/utilities/positioning/positioning.js
155. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/utilities/positioning/positioning.types.js
156. D:/GitRepos/office-ui-fabric-react/packages/office-ui-fabric-react/lib/version.js
157. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/AutoScroll.js
158. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/Context.js
159. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/DelayedRender.js
160. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/FabricPerformance.js
161. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/Rectangle.js
162. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/appendFunction.js
163. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/aria.js
164. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/array.js
165. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/asAsync.js
166. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/assertNever.js
167. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/autobind.js
168. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/createRef.js
169. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/css.js
170. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/customizations/Customizer.js
171. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/customizations/customizable.js
172. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/customizations/mergeCustomizations.js
173. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom.js
174. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/elementContains.js
175. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/elementContainsAttribute.js
176. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/findElementRecursive.js
177. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/getChildren.js
178. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/getParent.js
179. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/getRect.js
180. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/getVirtualParent.js
181. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/isVirtualElement.js
182. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/on.js
183. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/portalContainsElement.js
184. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/raiseClick.js
185. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/setPortalAttribute.js
186. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/dom/setVirtualParent.js
187. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/extendComponent.js
188. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/focus.js
189. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/hoist.js
190. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/hoistStatics.js
191. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/initializeComponentRef.js
192. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/math.js
193. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/mobileDetector.js
194. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/osDetector.js
195. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/overflow.js
196. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/resources.js
197. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/scroll.js
198. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/string.js
199. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/version.js
200. D:/GitRepos/office-ui-fabric-react/packages/utilities/lib/warn.js
201. external "ReactDOM"

**Comment by dzearing** [comment]
If you bundle with concatenation, and without, you see different bundle size numbers. It should be possible, with concatenation on, to get the modules from within.

Notice that in the bundle-analyzer reports with concat on, there is this checkbox in options:

image

When it is clicked, it turns this:

image


into this:

image


which tells me that it is not required to disable concatenation just to get the modules within the concatenated section of the bundle. I think you just need to compare the stats files to understand what is happening here.

**Comment by dzearing** [comment]
Closing PR until we figure this out.

**Pull request closed without merging**
