### PR TITLE
DatePicker: Add option to not auto-open on focus

### PR DESCRIPTION
**Pull request by c-w**
#### Pull request checklist

- [x] Addresses an existing issue: #1266
- [x] Include a change request file if publishing
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes

When focus lands on the date picker, it currently immediately opens the date picker. This is confusing from an accessibility point of view. This pull request adds an option to disable the auto-open behavior so that the user can open the date picker manually, e.g. by hitting enter.

#### Focus areas to test

Test steps (verified manually on DatePicker.Input.Example: [screencast](https://www.screencast.com/t/yPgjYiT8W)):
1) Create a date-picker with the disableAutoFocus property set to true.
2) Tab through the page and onto the picker, it should not automatically open.
3) Hit enter, the picker should open.

### CODE REVIEW

**Comment by mikewheaton** [comment]
Does it ever make sense to open it immediately on keyboard focus? Maybe instead of this being an option we should just remove the functionality entirely.

**Comment by c-w** [comment]
@mikewheaton If you're happy to make that API change, we can go for it. @scriby: do you see a scenario where auto-opening the date-picker is the correct behavior?

**Comment by scriby** [comment]
From the standpoint of supporting screenreaders, I think it's much more understandable to require the user to take an explicit action to open the popup than to just launch them into it without context. So, I think it's a reasonable stance to take that we don't allow the date picker to open automatically on focus.

Whether or not a third party might want that behavior regardless some day is another story...

**Comment by mdahamiwal** [comment]
@c-w , @mikewheaton I think we should go through the accessible date pickers listed at http://www.webaxe.org/accessible-date-pickers/ and decide on the design. There are both types 1. ones that open the picker popup on focus and 2. others that provide a focusable picker button next to date text box.

**Comment by c-w** [comment]
While we have the conversation about the focus-open behavior, I split out #1477 for the tab-order changes as the fix is valuable on its own.

**Comment by c-w** [comment]
@mdahamiwal @mikewheaton: Did you take a decision on whether you want the always/never auto-open behavior or whether you'd prefer to make it configurable?

**Comment by mikewheaton** [comment]
Let's just make it an option for now, as both look like valid options :)

**Comment by c-w** [comment]
@mikewheaton: Thanks for the decision. This pull request adds the new option to disable auto-open on focus of the date picker. Could you please give it a review?

**Comment by c-w** [comment]
@mikewheaton: Thanks for the sign-off. Could you please merge this in before master advances again? I don't have merge-access.

**Pull request merged**
