### PR TITLE
SplitButton: Fix SPACE/ENTER so that it executes the primary button

### PR DESCRIPTION
**Pull request by jspurlin**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [X] Include a change request file using `$ npm run change`

#### Description of changes

When the whole splitButton has focus, ENTER/SPACE no longer executes the primary button as expected. This change makes that behavior work again.

#### Focus areas to test
Verified that SPACE and ENTER work as expected for all three pieces (the whole control, the primary button, and the secondary button) of a splitButton

There's another conversation about updating the splitButton to be one stabstop but is out of scope for this PR

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Ah, so this is a click on the entire button? How does the whole thing get focus? Focus method?

**Comment by jspurlin** [comment]
The whole control will get focus if the splitButton is in a FocusZone.

**Comment by micahgodbolt** [comment]
Oh I gotcha.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by micahgodbolt** [comment]
As long as that doesn't affect regular click events when not in a focus zone.

**Pull request merged**
