### PR TITLE
Fix experiment imports for FloatingPicker and ExtendedPicker

### PR DESCRIPTION
**Pull request by amyngu**
#### Pull request checklist

- [ ] Addresses an existing issue:
- [x] Include a change request file using `$ npm run change`

#### Description of changes

FloatingPicker and ExtendedPicker components import from other experiment components. Using experiments/lib/... worked inside of the repo, but not in the npm public package

### CODE REVIEW

**Comment by amyngu** [comment]
@dzearing  & @micahgodbolt I was having issues building after importing the experiments package in owa-mail. I kept getting `Error: node_modules/@uifabric/experiments/lib/components/ExtendedPicker/BaseExtendedPicker.Props.d.ts(4,42): error TS2307: Cannot find module 'experiments/lib/FloatingPicker'.` I think using "experiments/lib/..." is why. Please let me know if this doesn't look right!

**Comment by micahgodbolt** [comment]
yeah, this looks great.

**Comment by amyngu** [comment]
@micahgodbolt great! Thanks for the confirmation. Could I get this merged? :)

**Comment by micahgodbolt** [comment]
@amyngu I can never tell who has, and who does not have access to merge :) But there ya go!

**Pull request merged**
