### PR TITLE
Add "News" to FileIconType

### PR DESCRIPTION
**Pull request by hjonasson**
#### Description of changes

Gives access to news icon already existing on the CDN.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11611)

### CODE REVIEW

**Comment by joschect** [comment]
@hjonasson It looks like this new pr still has some conflicts. I think another icon got added.

**Comment by hjonasson** [comment]
Thanks for the attention everybody. I believe I pulled correctly from master and fixed the conflicts. I also closed the other PR as was recommended there.

**Comment by hjonasson** [comment]
Thanks for you help everybody. What is the etiquette for completing the PR?

**Comment by khmakoto** [comment]
@hjonasson if it's ready for merging I can do that, has everyone that should review taken a look at this already?

**Comment by hjonasson** [comment]
I believe it is ready yes.

**Comment by khmakoto** [comment]
@hjonasson done 😄

**Pull request merged**
