### PR TITLE
Split menu button styles

### PR DESCRIPTION
**Pull request by micahgodbolt**
Command bar button never had split styles set. would be nice to have them set up before 6.0 release.

### CODE REVIEW

**Comment by dzearing** [comment]
Confused why screener failed. resetting.

**Comment by micahgodbolt** [comment]
Yeah, i'm not able to repro that bug locally. Really odd

**Comment by micahgodbolt** [comment]
It's not a styling difference, it's a completely different DOM structure

image

**Comment by micahgodbolt** [comment]
I'm utterly annoyed. I was able to repro this bug locally. So I started backing out my changes....still the bug. So then I switched back to master...STILL THE BUG. 

Emailed loyal, considering creating a brand new branch. no clue why this one is cursed

**Comment by suztocco** [comment]
@micahgodbolt Is this control done now? If so can I visually check it out?

**Comment by micahgodbolt** [comment]
@suztocco there's a split button in the command bar button example https://developer.microsoft.com/en-us/fabric#/components/button

**Comment by micahgodbolt** [comment]
seems there are still a few style tweaks to make though, already noted here https://github.com/OfficeDev/office-ui-fabric-react/issues/4997

**Comment by suztocco** [comment]
Ok, Here is what I see in the Fabric 6.0 build
https://outlook-sdf.office.com/calendar/view/week?branch=rakesh01-fabric6<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Foutlook-sdf.office.com%2Fcalendar%2Fview%2Fweek%3Fbranch%3Drakesh01-fabric6&data=04%7C01%7CRakesh.Masabattula%40microsoft.com%7Cfa752aba481f4fb2ab1908d5cd9c1a16%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636640992699880607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=PgXJvNCyvv6hcu%2FkSl3InvjeUPbFlrZrHLmlRurQLq0%3D&reserved=0>


There are some spacing issues. I just didn’t know when/where to check for the final control as you had sent me a place to review the design a while back.
Please do let me know when it is ready (based on the Fabric sketch spec). Thanks.


[cid:image001.png@01D4016F.BAAAF270]
[cid:image002.png@01D4016F.BAAAF270]

**Comment by suztocco** [comment]
@micahgodbolt - Just checking on status here. I am getting confused between this issue and the split button on the "command" bar.

**Comment by micahgodbolt** [comment]
the split button in the command bar is the same component as our regular split button, just with a few different styles. The icon size is actually shared between the two, and is incorrect in both cases.

**Pull request merged**
